### ISSUE TITLE
What is CamelCase?

### ISSUE THREAD

**Issue by evgeni-nabokov** [dotnet/dotnet-api-docs#10016]
There is CamelCase option, but no definition what camel case is in .NET. Different people have different opinions.
https://docs.microsoft.com/en-us/dotnet/api/System.Text.Json.JsonNamingPolicy.CamelCase?view=net-8.0

**Comment by eiriktsarpalis** [comment]
There should be a remarks section both in this type and the other built-in naming policies describing how they work at a higher level. Perhaps something to tackle in conjunction with https://github.com/dotnet/runtime/issues/34114

**Comment by evgeni-nabokov** [comment]
Oh, missed the link to the page with the description of the policies:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/customize-properties#use-a-built-in-naming-policy. Now I see what it means.
