### ISSUE TITLE
Docs show some APIs added in .NET 9 preview as available in .NET 8

### ISSUE THREAD

**Issue by jozkee** [dotnet/dotnet-api-docs#10012]
![image](https://github.com/dotnet/dotnet-api-docs/assets/16040868/6c80622c-5cf3-4844-87a5-1183af3c9b5a)

This API is only available for 9. Same happens for `IndentCharacter` and `IndentSize`. Not sure if it's a bug in the xml content or in the rendering tool.

cc @gewarren 

---
[Associated WorkItem - 335641](https://dev.azure.com/msft-skilling/Content/_workitems/edit/335641)

**Comment by gewarren** [comment]
@Jozkee It shows that way because the package can be used on downlevel frameworks - https://www.nuget.org/packages/System.Text.Json/9.0.0-preview.5.24306.7#supportedframeworks-body-tab. Do you think this is too confusing? Eventually the applies to table will differentiate package-provided versions from built-in versions, which will help a bit.

**Comment by gewarren** [comment]
Related to #9919, #9868.

**Comment by Jozkee** [comment]
> Do you think this is too confusing?

I think is not obvious how the specified versions are supported. Looks like the preview package targets both current (9.0) and previous (8.0) versions, which I forgot. For 7.0, netstandard2.0 version is used.

> Eventually the applies to table will differentiate package-provided versions from built-in versions, which will help a bit.

That would be nice!

**Comment by gewarren** [comment]
The UUF triage app shows that many other customers are getting confused too, so we should consider *not* showing the downlevel-versions until https://dev.azure.com/ceapex/Engineering/_workitems/970004 is implemented. Examples:

- IHostApplicationBuilder interface: This is NOT available in NET6 (or am I crazy)?
- TextReader.ReadToEndAsync method: ReadToEndAsync with cancellation token is not available for .NET Standard 2.0. It should not be shown in the doc with this view.
- AppDomainSetup class: Assembly is mscorlib not System.Runtime.dll
- JsonSerializerOptions.IndentSize property: Not available in NET8
- IAsyncDisposable.DisposeAsync method: I'm viewing the .net standard version of this interface but it says it's in the v9.0 package which I don't think is correct.
- JsonNode.GetValueKind method: This only works in .NET 8. It does not work on 6 and 7, but the page says it does: Applies toProductVersions.NET6, 7, 8, 9 This is incorrect, it does not work on 6 & 7.
