### ISSUE TITLE
"Applies to" table incorrect for new feature(s)?

### ISSUE THREAD

**Issue by ianleeder** [dotnet/dotnet-api-docs#10058]
I'm looking at JsonSerialisation options, specifically the [`IndentSize` property](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.indentsize?view=net-8.0).

I have clearly selected .NET 8, the "Applies to" table specifies that it's applicable to .NET 8, however it is not.  The only hint in the documentation is the package version:
![image](https://github.com/dotnet/dotnet-api-docs/assets/8241300/01abdf55-23fe-4bb2-8581-846f18004fb6)

Checking the source code for this class, I can see that the `IndentSize` property is available in the branch [`release/9.0-preview5`](https://github.com/dotnet/runtime/blob/release/9.0-preview5/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L98) but it is not in [`release/8.0`](https://github.com/dotnet/runtime/blob/release/8.0/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L77).

I haven't checked the documentation for any other new properties added in 9.0-preview.

**Comment by gewarren** [comment]
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is they the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of #10012.
