### ISSUE TITLE
Cuenta en Riesgo

### ISSUE THREAD

**Issue by Valijsjsjsb** [dotnet/dotnet-api-docs#10109]
Brrrr

**Comment by Valijsjsjsb** [comment]
Hxhjdj

**Comment by tarekgh** [comment]
The translation of `Cuenta en Riesgo` is `Account at Risk`. 

@richlander any action should be taken here as it is clear it is spam?

**Comment by richlander** [comment]
Thanks for reporting @tarekgh!
