### ISSUE TITLE
How about an example?

### ISSUE THREAD

**Issue by mrmsbarnes** [dotnet/dotnet-api-docs#1012]
Nothing complex.  As basic as possible.  Something we can build on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88445c33-dfb0-294f-f895-4f79a491defd
* Version Independent ID: 13e4bff9-d969-7f8a-720b-fe105f70353c
* Content: [DependencyProperty Class (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.dependencyproperty?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Windows/DependencyProperty.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/DependencyProperty.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by oldnewthing** [comment]
The page says

> To learn more about dependency properties, see [Dependency Properties Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/dependency-properties-overview?view=netframework-4.7.2).

On the Dependency Properties Overview, there is an example:

> The following example defines the `IsSpinning` dependency property, and shows the relationship of the DependencyProperty identifier to the property that it backs.

**Comment by mrmsbarnes** [comment]
Very helpful.  Thank you so much.
