### ISSUE TITLE
developer

### ISSUE THREAD

**Issue by yegorisB** [dotnet/dotnet-api-docs#10170]
### Type of issue

Code doesn't work

### Description
System.Text.RegularExpressions.Regex.Count(dsDNAtemplateForModification, searchPattern); CS0117	'Regex' does not contain a definition for 'Count'	VS2022

using System.Text.RegularExpressions;
Regex.Count(string a, string b); 	CS0117	'Regex' does not contain a definition for 'Count'	VS2022

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.count?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Text.RegularExpressions/Regex.xml

### Document Version Independent Id

eaa53010-0ad3-5926-c750-8b29ef19a4e0

### Article author

@dotnet-bot

**Comment by tarekgh** [comment]
@yegorisB [Regex.Count](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.count?view=net-8.0#system-text-regularexpressions-regex-count(system-string-system-string)) exit but it is introduced in .NET 7.0. You need to be using .NET 8.0 to make the code compile.
