### ISSUE TITLE
Update System.Formats.Nrbf.NrbfDecoder(byte[]) to accept ReadOnlySpan<byte> instead

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/dotnet-api-docs#10177]
I've noticed while reviewing https://github.com/dotnet/dotnet-api-docs/pull/10168 that we need to reflect the changes from https://github.com/dotnet/runtime/pull/103636 in the docs

**Comment by gewarren** [comment]
This has been updated: https://learn.microsoft.com/en-us/dotnet/api/system.formats.nrbf.nrbfdecoder.startswithpayloadheader?view=net-8.0#system-formats-nrbf-nrbfdecoder-startswithpayloadheader(system-readonlyspan((system-byte)))
