### ISSUE TITLE
Dotnet Api Docs

### ISSUE THREAD

**Issue by sedwin928** [dotnet/dotnet-api-docs#10199]
### Type of issue

Other (describe below)

### Description

Hi if there's anything I can do to help please let me know Thank You.
[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.boolean?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Boolean.xml

### Document Version Independent Id

065b337b-cff3-d5b0-8061-c4fe8525b32d

### Article author

@dotnet-bot

**Comment by Jozkee** [comment]
Hi @sedwin928, if you are interested in helping out in this repository you can take a look at issues labeled with https://github.com/dotnet/dotnet-api-docs/labels/help%20wanted.

Here's the query: https://github.com/dotnet/dotnet-api-docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22.
