### ISSUE TITLE
CacheItemPolicy's AbsoluteExpiration - how to set it

### ISSUE THREAD

**Issue by DrGriff** [dotnet/dotnet-api-docs#10202]
### Type of issue

Missing information

### Description

It's somewhat unclear whether this should be a  UTC or a LOCAL time.  Or does it matter?

What's "best practice"?  And does this matter if the .NET is run on Windows or Linux?
```
CacheItemPolicy cachePolicy = new CacheItemPolicy
{
    AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(12345)
};
```
or

```
CacheItemPolicy cachePolicy = new CacheItemPolicy
{
    AbsoluteExpiration = DateTimeOffset.UtcNow.AddMinutes(12345)
};
```
So, "Now" _vs_ "UtcNow".

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.caching.cacheitempolicy.absoluteexpiration?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.Caching/CacheItemPolicy.xml

### Document Version Independent Id

8b655b1e-f8da-d8d2-87a5-3fbb89e38df5

### Article author

@dotnet-bot

**Comment by Jozkee** [comment]
In this case using `Now` or `UtcNow` should yield the same result, Now will have your local time's offset, while the other will have offset zero which doesn't have a practical impact on the cache item policy.

**Comment by Jozkee** [comment]
With regard to best practices, take a look at https://learn.microsoft.com/en-us/dotnet/core/extensions/caching, if you are writing new code and your .NET version is compatible with netstandard2.0, you should consider using `Microsoft.Extensions.Caching.*` instead of `System.Runtime.Caching`.

**Comment by DrGriff** [comment]
Hi David, thanks for the detailed responses.

The application is an Azure App Service (.NET 8) hosted on Linux.

Interestingly, when I use the Microsoft.Extensions.Caching.Memory NuGet package, it fails, but with the System.Runtime.Caching it works.  Azure Logging isn't telling me much, and I'm just getting a 500 error.  Not sure what I'm missing (followed the documentation, and it runs perfectly on local Windows machine).  Any insights?

Griff -- Dr Jonathan Griffiths
________________________________

**Comment by Jozkee** [comment]
With very few details is hard to tell. One option that occurs to me for you to try to duplicate is to run WSL2 on your Windows machine and see if your scenario with Microsoft.Extensions.Caching gives an error there. 

Another thing you can try is to look for the logs in {your-app-service}.scm.azurewebsites.net.
