### ISSUE TITLE
new FileInfo() docs ought to explicitly specify what happens if the path doesn't exist

### ISSUE THREAD

**Issue by JendaPerl** [dotnet/dotnet-api-docs#10204]
### Type of issue

Missing information

### Description

"Wrapper to file path" seems to kinda say it, but it's better to be explicit.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo.-ctor?view=netframework-4.8&devlangs=csharp&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(System.IO.FileInfo.%2523ctor)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.8)%3Bk(DevLang-csharp)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.IO/FileInfo.xml

### Document Version Independent Id

2203c7b4-8c91-d5fb-3d0d-180b67d25096

### Article author

@dotnet-bot

**Comment by Jozkee** [comment]
From your perspective, what happens when `new FileInfo(path)` receives a path to a non-existing file that isn't documented?

**Comment by JendaPerl** [comment]
I don't know.
The constructor throws an exception? I mean how can you have info about a file if the file doesn't exist?

What if the path references a drive that doesn't exist? What if the drive seems to exist, but is not ready (think CD/DVD drive)?

You are in general being way too minimalistic when it comes to documentation. I often have to decompile and review the code or run tests to find out what the corner cases do. Disk space ain't expensive anymore, you don't have to save characters!

**Comment by Jozkee** [comment]
> The constructor throws an exception?

That's not the case. 

> I mean how can you have info about a file if the file doesn't exist?

You may be misunderstanding the class. FileInfo is meant to represent a file, whether it exists or not, hence the `Exists` property and the `Create()` method.
