### ISSUE TITLE
The root ID, or null if the current instance has either a ParentId or an Id.

### ISSUE THREAD

**Issue by rodolfograve** [dotnet/dotnet-api-docs#10205]
### Type of issue

Code doesn't work

### Description

The description of the property is incorrect.

`The root ID, or null if the current instance has either a ParentId or an Id.`

According to the code and its documentation, the correct statement would be:

`The root ID may be null if Activity has neither ParentId nor Id.`

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.rootid?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics/Activity.xml

### Document Version Independent Id

9a9b40a6-748a-7073-ea42-b51e33a97b1d

### Article author

@dotnet-bot

**Comment by Jozkee** [comment]
For reference: https://github.com/dotnet/runtime/blob/fdb741523a090a1bc31f70e336cc7783912bd089/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L295-L299
