### ISSUE TITLE
Missing Parameter type

### ISSUE THREAD

**Issue by NilsHoyer** [dotnet/dotnet-api-docs#10224]
### Type of issue

Missing information

### Description

There is no hint, which data type the pcbWritten points to. Is this Int32?

I'm talking about the German description.

### Page URL

https://learn.microsoft.com/de-de/dotnet/api/system.runtime.interopservices.comtypes.istream.write?view=net-8.0#system-runtime-interopservices-comtypes-istream-write(system-byte()-system-int32-system-intptr)

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.InteropServices.ComTypes/IStream.xml

### Document Version Independent Id

d1fb46d2-8cbe-7979-11a6-3869450b5d76

### Article author

@dotnet-bot

**Comment by Jozkee** [comment]
It's [`IntPtr`](https://learn.microsoft.com/de-de/dotnet/api/system.intptr?view=net-8.0), the link to the IntPtr documentation is in the Parameter section.

**Comment by NilsHoyer** [comment]
IntPtr is a pointer to a memory. But which kind of memory?

I'm sorry, but you believe, I would stupid, but you are this.🤔

David Cantú ***@***.***> schrieb am Do., 8. Aug. 2024, 17:30:

**Comment by Jozkee** [comment]
As per Windows [documentation](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-isequentialstream-write) it is ULONG. The [IStream.Read](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comtypes.istream.read?view=net-8.0#system-runtime-interopservices-comtypes-istream-read(system-byte()-system-int32-system-intptr)) method does mention it, will reopen so owners can consider if IStream.Write should include it too.

**Comment by Jozkee** [comment]
@AaronRobinsonMSFT @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
I think this is rather obvious given the "Remarks" section clearly points out that for more details the official [ISequentialStream::Write](https://learn.microsoft.com/windows/win32/api/objidl/nf-objidl-isequentialstream-write) definition should be referenced. Making both versions clear seems fine to me though.

@NilsHoyer Are you willing to submit a PR to update the doc?

**Comment by NilsHoyer** [comment]
I tried to use ULONG with the [Windows Portable Device](https://learn.microsoft.com/en-us/windows/win32/api/portabledeviceapi/nf-portabledeviceapi-iportabledevicecontent-createobjectwithpropertiesanddata), but this results with senseless values. But if I call it with INT, I receive the expected values.

So I'm unsure, if there is a bug in the WPD, or if you are wrong, telling me using ULONG.

**Comment by AaronRobinsonMSFT** [comment]
@NilsHoyer Can you share the managed code you used? The `ULONG` in C/C++ is not the same as `ulong` in C#. See https://learn.microsoft.com/dotnet/standard/native-interop/best-practices#common-windows-data-types for more details.

**Comment by NilsHoyer** [comment]
@AaronRobinsonMSFT: You are right, it was my mistake to use ulong for ULONG in C#. By using uint, everything works like expected with `pcbWritten`.

For me, it's a lot of work to offer a pull request.

But I suggest the following text for `pcbWritten`:

A pointer to a ULONG variable that, on successful return, contains the actual number of bytes written to the stream object. If the caller sets this [Zero](https://learn.microsoft.com/en-us/dotnet/api/system.intptr.zero?view=net-8.0#system-intptr-zero), this method does not provide the actual number of bytes written.

Maybe there is somebody else, who can provide a pull request instead of me? 🙄

**Comment by AaronRobinsonMSFT** [comment]
Thanks @NilsHoyer. Glad you are unlocked. I will create a PR.

**Comment by Sencaid** [comment]
Hello
I want to ask, when the German Translation is ready to be implemented for Tooltips (Quickinfos)? I could help translate the Docs, if it is necasarry for that.

**Comment by NilsHoyer** [comment]
For me, the German translation will be shown and its correct translated:
https://learn.microsoft.com/de-de/dotnet/api/system.runtime.interopservices.comtypes.istream.write?view=net-8.0#system-runtime-interopservices-comtypes-istream-write(system-byte()-system-int32-system-intptr)

**Comment by Sencaid** [comment]
Hello
I want to ask, when the German Translation is ready to be implemented for Tooltips (Quickinfos) in Visual Studio? I could help translate the Docs, if it is necasarry for that.
@AaronRobinsonMSFT, @jozkee

**Comment by Sencaid** [comment]
> I'm not sure how this flows into Visual Studio. I assume it comes through some additional artifact during deployment. It will be there eventually, but will take time.
> 
> > I could help translate the Docs, if it is necasarry for that.
> 
> Thanks for the offer. We have a dedicated documentation team that translates into the appropriate languages.

thanks for your reply
