### ISSUE TITLE
No VB.net example provided.

### ISSUE THREAD

**Issue by jbstcyr** [dotnet/dotnet-api-docs#1022]
No example of any kind provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a585a7-1ba1-9d21-507f-74d152131348
* Version Independent ID: a2f1c5ce-82f8-d70b-9e90-50b9ee0d0221
* Content: [ComponentDesigner.ShadowProperties Property (System.ComponentModel.Design)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.design.componentdesigner.shadowproperties?view=netframework-4.7.2#System_ComponentModel_Design_ComponentDesigner_ShadowProperties)
* Content Source: [xml/System.ComponentModel.Design/ComponentDesigner.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.Design/ComponentDesigner.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @jbstcyr. We don't have the resources to add samples to every single API. This page has very little traffic so it wouldn't get prioritized.

But we welcome contributions if the community wants to add a sample. Thanks!
