### ISSUE TITLE
Equatable example may have an error

### ISSUE THREAD

**Issue by KenKor** [dotnet/dotnet-api-docs#10234]
### Type of issue

Typo

### Description

I guess the string comparison should be done differently. Instead:
        return this.Name == other.Name && this.Code == other.Code;
I would write:
        return this.Name.equals(other.Name) && this.Code == other.Code;

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.union?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Linq/Enumerable.xml

### Document Version Independent Id

17beb25a-a13f-e33b-c350-9378ffdc8edb

### Article author

@dotnet-bot

**Comment by rzikm** [comment]
in .NET, both string comparisons are implemented by the same code (== operator redirects to Equals()). choice between the two is only a stylistic choice.

https://github.com/dotnet/runtime/blob/94c356d55a9f9d902f61708ee01e99d480597427/src/libraries/System.Private.CoreLib/src/System/String.Comparison.cs#L746-L748
