### ISSUE TITLE
Understanding user accounts. Remember me with me, add user, edit, sign in and sign out

### ISSUE THREAD

**Issue by idmansourid** [dotnet/dotnet-api-docs#10237]
To add a user account for my app, I need the logic of the user account/authentication, how can it be done. I already prepared an example. Thanks for editing and completing this example.
![20240809_074517](https://github.com/user-attachments/assets/46559b7c-d5b8-4031-b852-abcda77853b7)

VS 2019 VB.NET Project Type Windows Forms App( .NET framework 4.7)
  And Add Form With Name 'VirtualMachine' with txt File [Designer.vb.txt](https://github.com/user-attachments/files/16577649/Designer.vb.txt)
And Paste On Class
`    

        Public Class VirtualMachine
            #Region "Initialization for data outside the program"
            Dim dtUsers As New DataTable
            Dim dtSetting As New DataTable
        Private Sub VirtualMachine_Load(sender As Object, e As EventArgs) Handles MyBase.Load
          dtSetting.Columns.Add("ID", GetType(Integer))
          dtSetting.Columns.Add("SettingName")
          dtSetting.Columns.Add("SettingValue")
         dtSetting.Rows.Add({0, "Users", "Admin,Admin"})
         dtSetting.Rows.Add({1, "RememberMe", ""})
         dtUsers.Columns.Add("ID", GetType(Integer))
        dtUsers.Columns.Add("UserName")
      dtUsers.Columns.Add("UserPassword")
        dtUsers.Columns.Add("UserType")
        dtUsers.Columns.Add("Hit")
        dtUsers.Rows.Add({0, "Admin", "Admin", "Admin", "Admin"}) 'is Default User
        dgvUsers.DataSource = dtUsers
        dgvSetting.DataSource = dtSetting
    End Sub
    Private Sub butExecute_Click(sender As Object, e As EventArgs) Handles butExecute.Click
        LoadApp()
    End Sub
    #End Region
    #Region "Bringing data from outside and initial settings"
    Dim dtGetUsers As New DataTable
    Dim dtGetSetting As New DataTable
    Dim DicCheckUsers As Dictionary(Of String, String)
    Sub LoadApp()
        dtGetUsers = dtUsers.Copy ' Get Data from outside
        dtGetSetting = dtSetting.Copy ' Get Data from outside
        txtPassword.Text = ""
        SyngUsers()
        butViewSettingIfIsAdmin.Enabled = False
        lblCurrentUser.Text = ""
        comUserName.Items.Clear()
        Dim GetCompute As Object = dtGetSetting.Compute("Min(SettingValue)", "[SettingName]='RememberMe'")
        If GetCompute.ToString = "" Then
            GetCompute = dtGetSetting.Compute("Min(SettingValue)", "[SettingName]='Users'")
            DicCheckUsers = Dict_StringToDic_OfStrStr(GetCompute)
            comUserName.Items.AddRange(DicCheckUsers.Keys.ToArray)
            grpLoginForm.Visible = True
        Else
        End If
    End Sub
    Function Dict_StringToDic_OfStrStr(inString As String, Optional separator1 As String = "|", Optional separator2 As String = ",") As Dictionary(Of String, String)
        Dim MyString As String = inString ' "Admin,Admin|Mansour,1394"
        ' Dim separators() As Char = '{"|"c}
        Dim Result = MyString.Split(separator1).
            Select(Function(x) x.Split(separator2)).
            ToDictionary(Function(x) x(0), Function(x) x(1))
        Return Result
    End Function
    #End Region
    Private Sub butLoginOk_Click(sender As Object, e As EventArgs) Handles butLoginOk.Click
        Dim row As DataRow()
        Dim GetCompute As Object
        If txtPassword.Text = DicCheckUsers(comUserName.Text) Then
            If chkRememberMe.Checked Then
                row = dtSetting.Select("[SettingName]='RememberMe'")
                row(0).Item("SettingValue") = txtPassword.Text
            End If
            row = dtUsers.Select("[UserName]='" & comUserName.Text & "'")
            GetCompute = dtUsers.Compute("Min(UserType)", "[UserName]='" & comUserName.Text & "'")
            grpSettingOnlyAdminType.Visible = False
            grpLoginForm.Visible = False
            lblCurrentUser.Text = comUserName.Text
            If GetCompute.ToString = "Admin" Then
                InitialSetupOfAdmins()
            End If
            grpMainForm.Visible = True
        Else

        End If
    End Sub
    Sub InitialSetupOfAdmins()
        butViewSettingIfIsAdmin.Enabled = True
        lstUser.Items.Clear()
        For Each row As DataRow In dtUsers.Rows
            lstUser.Items.Add(Join(row.ItemArray, ","))
        Next
    End Sub

    Private Sub butViewSettingIfIsAdmin_Click(sender As Object, e As EventArgs) Handles butViewSettingIfIsAdmin.Click
        grpSettingOnlyAdminType.Visible = Not grpSettingOnlyAdminType.Visible
    End Sub
    Private Sub butExit_Click(sender As Object, e As EventArgs) Handles butExit.Click
        grpLoginForm.Visible = False
        grpMainForm.Visible = False
    End Sub
    Private Sub butAddUser_Click(sender As Object, e As EventArgs) Handles butAddUser.Click
        Dim MaxId As Integer = dtUsers.Compute("Max([ID])", "") + 1
        Dim Prompt As String = "Please enter the data in this order." & vbNewLine & "ID,User Name,Password,Type,Hit" & vbNewLine & "Sample:1,Jiachen Li,1234,User,Rev4321"
        Dim sttGetRow As String = InputBox(Prompt, DefaultResponse:=MaxId & ",Jiachen Li,1234,User,Rev4321")
        lstUser.Items.Add(sttGetRow)
        dtUsers.Rows.Add(Split(sttGetRow, ","))
        SyngUsers()
    End Sub
    Private Sub butEditUser_Click(sender As Object, e As EventArgs) Handles butEditUser.Click
        If lstUser.SelectedIndex > -1 Then
            lstUser.SelectedItem = InputBox("Edit", DefaultResponse:=lstUser.SelectedItem)
        End If
    End Sub
    Private Sub butSingOut_Click(sender As Object, e As EventArgs) Handles butSingOut.Click

    End Sub
    Sub SyngUsers()
        Dim GetAllUserPasword As String = ""
        For Each row As DataRow In dtUsers.Rows
            GetAllUserPasword += IIf(GetAllUserPasword <> "", "|", "") & row.Item("UserName") & "," & row.Item("UserPassword")
        Next
        Dim rows As DataRow() = dtSetting.Select("[SettingName]='Users'")
        rows(0).Item("SettingValue") = GetAllUserPasword
    End Sub
    End Class
`

**Comment by Jozkee** [comment]
@idmansourid sorry but this isn't the right place to ask for help with your specific application. I suggest you try on stackoverflow.com
