### ISSUE TITLE
Missing Methods

### ISSUE THREAD

**Issue by MWolman1990** [dotnet/dotnet-api-docs#10233]
### Type of issue

Missing information

### Description

This property, Children, has many methods. One of them is Clear(). Panel.Children.Clear(). But there is no documentation on this. At least none that I could find.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.panel.children?view=windowsdesktop-8.0#system-windows-controls-panel-children

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Windows.Controls/Panel.xml

### Document Version Independent Id

e4d4a8e4-64a2-6429-979e-2dc69fb34014

### Article author

@dotnet-bot

**Comment by Jozkee** [comment]
I think you are looking for the Panel.Children's type's documentation:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.uielementcollection?view=windowsdesktop-8.0

let me know if I misunderstood.

**Comment by MWolman1990** [comment]
@Jozkee yes that is what I was looking for! Thank you so much. I see my error now :)
