### ISSUE TITLE
Update System.AttributeUsage info 

### ISSUE THREAD

**Issue by aman-shahid** [dotnet/dotnet-api-docs#10252]
### Type of issue

Outdated article

### Description

[Enter feedback here] The 'System.AttributeUsage' has outdated/misleading info - although the text mentions the correct attribute usage (i.e. Class or Struct) - but the highlighted code snippet contains 'System.AttributeTargets.Assembly' - which leads to people trying out using the attribute in AssemblyInfo.cs - to be disappointed and verifying usage by decompiling.

Screenshot below:

![image](https://github.com/user-attachments/assets/caa644dd-58a7-4256-a74e-3f97a7388888)

![image](https://github.com/user-attachments/assets/5dfcc19e-d9e8-4ddd-b170-44295e29df4c)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.excludefromcodecoverageattribute?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics.CodeAnalysis/ExcludeFromCodeCoverageAttribute.xml

### Document Version Independent Id

f0b38a40-e78b-e70f-9343-5bedb1e9931a

### Article author

@dotnet-bot

**Comment by rzikm** [comment]
The Attribute usage on entire assembly has been introduced in .NET Core (not sure which version) and can be used there without problems. It is not supported for the entire assembly annotations in .NET Framework. This fact is reflected in the documentation when you switch the version to .NET Framework.
