### ISSUE TITLE
Server error in application, runtime error 

### ISSUE THREAD

**Issue by Rajan786273** [dotnet/dotnet-api-docs#10277]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.web.configuration.customerror?view=netframework-4.8.1

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.Configuration/CustomError.xml

### Document Version Independent Id

493ea7d5-3385-f1ed-9a85-2569ef115c40

### Article author

@Rick-Anderson

**Comment by rzikm** [comment]
Can you, please be more specific where the typo is? I can't seem to find it.
