### ISSUE TITLE
Not Able To Leave Feedback Because of @dotnet-bot

### ISSUE THREAD

**Issue by MaxFun** [dotnet/dotnet-api-docs#10315]
### Describe the issue or suggestion

Tried to leave feedback on problem with TcpChannel Class (https://learn.microsoft.com/en-us/dotnet/api/system.runtime.remoting.channels.tcp.tcpchannel?view=netframework-4.8.1) but bot reject it because it could not "couldn't figure out the best area label "

**Comment by rzikm** [comment]
The dotnet-bot attempts to label incoming issues to automatically triage them to the appropriate developer team. If it cannot identify the correct team, the appropriate label will be added manually by a person on triage duty.
