### ISSUE TITLE
Mrs.

### ISSUE THREAD

**Issue by sorin1970** [dotnet/dotnet-api-docs#10332]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.io.ports?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/ns-System.IO.Ports.xml

### Document Version Independent Id

24dce530-c03d-0469-f9a5-58268fa97be9

### Article author

@dotnet-bot

**Comment by krwq** [comment]
@sorin1970 can you please clarify what kind of typo you've noticed?
