### ISSUE TITLE
x

### ISSUE THREAD

**Issue by simen68** [dotnet/dotnet-api-docs#10349]
### Type of issue

Typo

### Description

xvalue

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.datavisualization.charting.series.yvaluetype?view=netframework-4.8

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Windows.Forms.DataVisualization.Charting/Series.xml

### Document Version Independent Id

be678254-1de1-3eb4-e5a9-dfd94fb38780

### Article author

@dotnet-bot

**Comment by krwq** [comment]
@simen68 can you please clarify issue you've hit?
