### ISSUE TITLE
ProdigaL'BusniesS

### ISSUE THREAD

**Issue by PROGIDALjokersss** [dotnet/dotnet-api-docs#10347]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.net.security?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/ns-System.Net.Security.xml

### Document Version Independent Id

5fdcb586-4514-64da-b2ab-e17cf6f3e470

### Article author

@karelz

**Comment by rzikm** [comment]
Hi, can you be more specific as to where there is a typo on that website?

**Comment by krwq** [comment]
Closing this as non-actionable
