### ISSUE TITLE
c# Test

### ISSUE THREAD

**Issue by chcig** [dotnet/dotnet-api-docs#10352]
### Type of issue

Typo

### Description

[여기에 피드백 입력]

### Page URL

https://learn.microsoft.com/ko-kr/dotnet/api/microsoft.extensions.hosting.ihostbuilder?view=netframework-4.7.2&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DKO-KR%26k%3Dk(Microsoft.Extensions.Hosting.IHostBuilder)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.7.2)%3Bk(DevLang-csharp)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/Microsoft.Extensions.Hosting/IHostBuilder.xml

### Document Version Independent Id

220c5f05-f537-875e-caa5-bd4919567a7e

### Article author

@dotnet-bot

**Comment by krwq** [comment]
@chcig can you please clarify the error you've hit?
