### ISSUE TITLE
Tommy function complier 

### ISSUE THREAD

**Issue by Tommykl33** [dotnet/dotnet-api-docs#10354]
### Type of issue

Thank you

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.action-10?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Action`10.xml

### Document Version Independent Id

31d6edfc-f83b-c522-54d3-6dd0327dc375

### Article author

@dotnet-bot/TommyKLee

**Comment by Tommykl33** [comment]
Ok I'll do my best thank you

**Comment by krwq** [comment]
@Tommykl33 can you clarify what's this issue about?
