### ISSUE TITLE
Dot instead of comma

### ISSUE THREAD

**Issue by akurpukov** [dotnet/dotnet-api-docs#10364]
### Type of issue

Typo

### Description

In first sentence is dot typed, but should be a comma:
> Occurs when a character. space or backspace key...

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.keypress?view=windowsdesktop-8.0#system-windows-forms-control-keypress

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Windows.Forms/Control.xml

### Document Version Independent Id

3e634cb6-391d-87d3-8bdc-884864559543

### Article author

@dotnet-bot

**Comment by krwq** [comment]
@akurpukov would you like to send a patch?

**Comment by akurpukov** [comment]
No, because first need to figure out how to do it in right way. So you can do it.
