### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by daniela2000111** [dotnet/dotnet-api-docs#10409]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.object?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Object.xml

### Document Version Independent Id

33ab6e94-fc93-40f0-6710-a057935f2d02

### Article author

@dotnet-bot

**Comment by Harry5012** [comment]
report request
