### ISSUE TITLE
Algorithm used for encryption is not explained in document

### ISSUE THREAD

**Issue by nishanthw** [dotnet/dotnet-api-docs#10403]
### Type of issue

Missing information

### Description

In document only mentioned that "It provides protection using the user or machine credentials to encrypt or decrypt data." but there is no explanation about what algorithm is used to encrypt the data like ASE 256 etc..

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Security.Cryptography/ProtectedData.xml

### Document Version Independent Id

bde8d035-9be9-e5fe-48f1-08ff12e9e728

### Article author

@dotnet-bot

**Comment by bartonjs** [comment]
We don't know what it is.

The documentation says "This class provides access to the Data Protection API (DPAPI) available in Windows operating systems.", and that's all we know, it's Windows decision as to what the algorithm is (or, for decrypt "supported algorithms are", one supposes).

For details, you'd have to chase down into Win32 documentation, e.g. https://learn.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata; and I don't see a mention of the algorithm(s) used there.  But, for real data you'd have to find the answer from Windows, not .NET (sorry).
