### ISSUE TITLE
Some Methods are translated in tree view and they shouldn't

### ISSUE THREAD

**Issue by luca1010** [dotnet/dotnet-api-docs#10440]
in
https://learn.microsoft.com/it-it/dotnet/api/system.collections.frozen.frozenset-1.system-collections-generic-icollection-t--clear?view=net-8.0

**set to Italian** I see as title page
FrozenSet<T>.ICollection<T>.Clear Metodo
and it is correct

but on the left tree navigation I have this link (see attached picture)
[ICollection<T>. **Chiaro**]

actually, some methods (Clear, Remove, Add) are translated in Italian, all others are correctly presented in English in the treeview.
![TranslationOfMethods](https://github.com/user-attachments/assets/d667a935-733b-4cf0-a9d5-b1da4c1165c8)

I did not check other classes, so this issue might be present also elsewhere.

**Comment by bartonjs** [comment]
@gewarren do you know how to route this?
