### ISSUE TITLE
character ai

### ISSUE THREAD

**Issue by thecacahead** [dotnet/dotnet-api-docs#10499]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.net.webproxy.-ctor?view=net-8.0#system-net-webproxy-ctor(system-string-system-int32)

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Net/WebProxy.xml

### Document Version Independent Id

c4cb8cba-50ee-6250-2ab0-84e7a2534c97

### Article author

@karelz

**Comment by MihaZupan** [comment]
Can you please be more specific as to which typo you had in mind?
