### ISSUE TITLE
TechRaiz Inc/Microsoft Virtual STORES Technology USA Inc.

### ISSUE THREAD

**Issue by jjramon1699-ai** [dotnet/dotnet-api-docs#10491]
### Describe the issue or suggestion

public interface IBitwiseOperators<TSelf,TOther,TResult> where TSelf : IBitwiseOperators<TSelf,TOther,TResult>

**Comment by bartonjs** [comment]
There doesn't seem to be enough information here to understand what issue you're trying to report.  Can you provide more details?
