### ISSUE TITLE
lastword

### ISSUE THREAD

**Issue by lastwordapp** [dotnet/dotnet-api-docs#10497]
### Type of issue

Missing information

### Description

[Enter feedback here]
i cant access api my property

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.gc.suppressfinalize?view=net-8.0#system-gc-suppressfinalize(system-object)

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/GC.xml

### Document Version Independent Id

b2b985d0-da77-a8ed-87b0-712c6ebd68d7

### Article author

@dotnet-bot

**Comment by bartonjs** [comment]
What property can you not access, and what does "can't" mean?  There isn't currently enough information to be actionable.
