### ISSUE TITLE
ConnectionState is an enum, not a string

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/dotnet-api-docs#10503]
### Type of issue

Outdated article

### Description

The `State` property's description on this page says "Gets a string that describes the state of the connection." and down below, "The format of the string returned depends on the specific type of connection you are using."

But the property is not typed as `string` at all, but as [ConnectionState](https://learn.microsoft.com/en-us/dotnet/api/system.data.connectionstate?view=net-8.0), which is an enum.

The `State` property description on the [DbConnection class page](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection?view=net-8.0) likewise needs to be fixed.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.state?view=net-8.0#system-data-common-dbconnection-state

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbConnection.xml

### Document Version Independent Id

918743a2-34ae-6bb2-ca98-2988508799b4

### Article author

@dotnet-bot

**Comment by roji** [comment]
@masonwheeler thanks for flagging this - is #10509 sufficient or did you see another thing needing fixing?

**Comment by masonwheeler** [comment]
@roji It's not clear to me how the XML maps to the documentation, but I notice it's only changing one thing.  Will this fix both pages?

**Comment by roji** [comment]
Yeah, each XML is responsible for a type (e.g. DbConnection) and all the members contained within, that includes all pages generated for that type.

**Comment by roji** [comment]
The enum itself does have the `[Flags]` enum, but the values aren't exactly defined accordingly; for example, one would expect the Fetching/Executing to also be Open, but they aren't. This is a very old type, and there are probably a few design issues around it.
