### ISSUE TITLE
Warning Message does not stand out. 

### ISSUE THREAD

**Issue by EddyHaigh** [dotnet/dotnet-api-docs#1050]
The warning message currently uses a greyish/whitish background making it hard to know the class is obsolete due to it not standing out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3331b9f-b4df-b76e-fffd-8ff9d327faa2
* Version Independent ID: 74837a55-0389-7547-ee9d-8bd2a28e531d
* Content: [SmtpClient Class (System.Net.Mail)](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Net.Mail/SmtpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Mail/SmtpClient.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by BillWagner** [comment]
@dend Should this go to [MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback)

**Comment by mairaw** [comment]
It should go there but the obsolete message is bright yellow on top. The gray box is the syntax block.
I personally preferred the way we used to do on MSDN with a bold text instead right before summary. 

Also, there's a separate bug for docs to be able to version the attributes. SmtpClient is not obsolete. This is only for Xamarin.

**Comment by mairaw** [comment]
Issue moved to https://github.com/MicrosoftDocs/feedback/issues/904

**Comment by gaj85210** [comment]
Trying to verify that SmtpClient is not obsolete!  If it is what is replacing it.  I want a simple way for my C# app to send emails.  Thanks
