### ISSUE TITLE
Unclear what SslCertificateTrust is referring to

### ISSUE THREAD

**Issue by fh-yuxiao-zeng** [dotnet/dotnet-api-docs#10504]
### Type of issue

Typo

### Description

The document says "Gets or sets an optional customized policy for remote certificate validation. If not null, [CertificateRevocationCheckMode](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.certificaterevocationcheckmode?view=net-8.0#system-net-security-sslclientauthenticationoptions-certificaterevocationcheckmode) and [SslCertificateTrust](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslcertificatetrust?view=net-8.0) are ignored."

CertificateRevocationCheckMode is another property in the SslClientAuthenticationOptions class, so it makes a lot of sense. On the other hand, SslCertificateTrust is a class. It's not clear what it means by a class is ignored. I was expecting a property.

(Should it be [ClientCertificateContext](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.clientcertificatecontext?view=net-8.0)?)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.certificatechainpolicy?view=net-8.0#system-net-security-sslclientauthenticationoptions-certificatechainpolicy

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Net.Security/SslClientAuthenticationOptions.xml

### Document Version Independent Id

01385e9b-4f99-408d-1840-6a7f6f0103b5

### Article author

@karelz

**Comment by rzikm** [comment]
it refers to SslStreamCertificateContext 's (the (Client/Server)CertificateContext property) Trust property, the wording can definitely use some improvements.
