### ISSUE TITLE
PatternBuilder 

### ISSUE THREAD

**Issue by MustafaDemircioglu** [dotnet/dotnet-api-docs#10513]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing.internal.patterns.patternbuilder?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns/PatternBuilder.xml

### Document Version Independent Id

f4c46d1b-f3cd-d7ae-39e6-57ae7479a090

### Article author

@dotnet-bot

**Comment by bartonjs** [comment]
What typo are you reporting? I don't see an obvious one.
