### ISSUE TITLE
The API not clear on whether included in the framework reference or need a package reference

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/dotnet-api-docs#10637]
### Type of issue

Missing information

### Description

The API docs page is not clear whether this API has been included into framework reference or need additional package reference.

There's info on whether the API is included into the framework on apisof.net page, but also not clear which package should be used if not included in the framework reference

![Image](https://github.com/user-attachments/assets/25d4f445-7d09-4803-b5ff-f80cbf102aaa)

![Image](https://github.com/user-attachments/assets/364d7dd3-e915-4d01-836f-2c4686e73c2f)

Is it possible to show the info on both sites?

- https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.meter.creategauge
- https://apisof.net/catalog/23975a72291ad4ad6d74f6af60d861c7

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.meter.creategauge?view=net-8.0#system-diagnostics-metrics-meter-creategauge-1(system-string)

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics.Metrics/Meter.xml

### Document Version Independent Id

74a2176b-587a-70e1-f3df-c1ade74eba6a

### Article author

@dotnet-bot

**Comment by tommcdon** [comment]
@noahfalk @tarekgh

**Comment by tarekgh** [comment]
@gewarren @terrajobst you were looking at improving the docs to be clearer on which framework the API is introduced and which down-level it is supported. Do you have input about this report?

**Comment by gewarren** [comment]
Related to #10012. I have some improvements coming in https://github.com/dotnet/dotnet-api-docs/pull/10646.

For apisof.net, the package is shown (and hyperlinked) if you select one of the package-provided versions:

![Image](https://github.com/user-attachments/assets/8cb6d312-01e4-4fd7-a714-caf075e00377)

So I think this issue can be closed?

**Comment by WeihanLi** [comment]
Thanks very much
