### ISSUE TITLE
“Diposes” typo in DbConnection.DisposeAsync description

### ISSUE THREAD

**Issue by theaswanson** [dotnet/dotnet-api-docs#10643]
### Type of issue

Typo

### Description

The description of DbConnection.DisposeAsync reads “ Asynchronously diposes the connection object.”

It should be “Asynchronously disposes the connection object.”

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnection.DisposeAsync?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data.Common/DbConnection.xml

### Document Version Independent Id

89516602-8c17-47f1-aec1-e703ac2d9534

### Article author

@dotnet-bot

**Comment by roji** [comment]
Thanks, submitted #10665 to fix.
