### ISSUE TITLE
SoapHttpClientProtocol是否支持Zscaler

### ISSUE THREAD

**Issue by 15204092822** [dotnet/dotnet-api-docs#10672]
### Type of issue

Typo

### Description
It is known that the above method can support SoapHttpClientProtocol to access the server through a proxy.
Is the above method support using SoapHttpClientProtocol to access the server through Zscaler?
Or does the above method need to be changed when using SoapHttpClientProtocol to access the server through Zscaler?

[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://favoritemenu.auth.star.nri.co.jp", ResponseNamespace="http://favoritemenu.auth.star.nri.co.jp")]
[return: System.Xml.Serialization.SoapElementAttribute("getMenuReturn")]
public FavoriteMenuGetDnBean getMenu(FavoriteMenuGetUpBean fmgub) {
    object[] results = this.Invoke("getMenu", new object[] {
                fmgub});
    return ((FavoriteMenuGetDnBean)(results[0]));
}
已知上述写法可以支持SoapHttpClientProtocol通过代理访问服务器
请问上述写法是否支持用SoapHttpClientProtocol通过Zscaler访问服务器，
或者说用SoapHttpClientProtocol通过Zscaler访问服务器上述写法是否需要变更

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/api/system.web.services.protocols.soaphttpclientprotocol?view=netframework-4.8.1&redirectedfrom=MSDN

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Web.Services.Protocols/SoapHttpClientProtocol.xml

### Document Version Independent Id

2ca50377-ec4b-75c6-08bd-94c97161adec

### Article author

@Rick-Anderson

**Comment by 15204092822** [comment]
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Nov 12, 2024 12:12 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [dotnet/dotnet-api-docs] SoapHttpClientProtocol是否支持Zscaler (Issue #10672)

&nbsp;



 
Tagging subscribers to this area: @dotnet/ncl
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.

Message ID: ***@***.***&gt;




[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://favoritemenu.auth.star.nri.co.jp", ResponseNamespace="http://favoritemenu.auth.star.nri.co.jp")]
[return: System.Xml.Serialization.SoapElementAttribute("getMenuReturn")]
public FavoriteMenuGetDnBean getMenu(FavoriteMenuGetUpBean fmgub) {
object[] results = this.Invoke("getMenu", new object[] {
fmgub});
return ((FavoriteMenuGetDnBean)(results[0]));
}

It is known that the above writing method can support SoapHttpClient Protocol to access the server through a proxy
May I ask if the above writing method supports accessing servers through Zscaler using SoapHttpClient Protocol,
Or, do we need to change the above writing method to access the server through Zscaler using SoapHttpClient Protocol

**Comment by 15204092822** [comment]
[System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://favoritemenu.auth.star.nri.co.jp", ResponseNamespace="http://favoritemenu.auth.star.nri.co.jp")]
[return: System.Xml.Serialization.SoapElementAttribute("getMenuReturn")]
public FavoriteMenuGetDnBean getMenu(FavoriteMenuGetUpBean fmgub) {
    object[] results = this.Invoke("getMenu", new object[] {
                fmgub});
    return ((FavoriteMenuGetDnBean)(results[0]));
}
It is known that the above writing method can support SoapHttpClient Protocol to access the server through a proxy
May I ask if the above writing method supports accessing servers through Zscaler using SoapHttpClient Protocol,
Or, do we need to change the above writing method to access the server through Zscaler using SoapHttpClient Protocol

**Comment by ManickaP** [comment]
I'm super confused by this issue. Is your problem with modern .NET or .NET framework (this repo is about the former)? What exactly doesn't work and how does it that problem manifests (code here is mixed with text - use 3 backticks to separate and [format the code](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code))?

**Comment by gewarren** [comment]
This looks like spam.
