### ISSUE TITLE
Examples at beginning obfuscate and useful information about structure and how to reference missing.

### ISSUE THREAD

**Issue by ClarkFrazier** [dotnet/dotnet-api-docs#10699]
### Type of issue

Outdated article

### Description

In addition to useless examples, there are no references to LINQ. Where is detailed information. Edge will crash if too many pages are open at once. Lack of Microsoft documentation is almost as bad as numerous obsolete, inconclusive, and inaccurate references from other websites.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.data.datatable.columns?view=net-8.0#system-data-datatable-columns

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Data/DataTable.xml

### Document Version Independent Id

7755efde-e11b-8139-4efd-06208b050e3d

### Article author

@dotnet-bot

**Comment by roji** [comment]
@ClarkFrazier I'm not sure what exact references to LINQ you're expecting (DataTable doesn't have any specific relation to LINQ AFAIK), or what exact detailed information you're missing.

Note that this page is an API reference page - it is not a general conceptual documentation explaining how DataTable works. For that, [see this page](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-data-datatable) as well as some others in the conceptual docs. API reference documentation only documents a very specific API - the DataTable.Columns property in this case.

**Comment by roji** [comment]
I'm going to go ahead and close this as it's not clear what is being requested, and no answer was provided.
