### ISSUE TITLE
Enumerable.max method does not return null if source sequence is empty

### ISSUE THREAD

**Issue by racnicolau** [dotnet/dotnet-api-docs#10739]
### Type of issue

Other (describe below)

### Description

The documentation for Enumerable.max [Max<TSource>(IEnumerable<TSource>)] states the following:
"If TSource is a reference type and the source sequence is empty or contains only values that are null, this method returns null."
This is not true as with an empty source sequence I am get the following exception:
"System.InvalidOperationException: Sequence contains no elements"

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.max?view=net-8.0#system-linq-enumerable-max-2(system-collections-generic-ienumerable((-0))-system-func((-0-1)))

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Linq/Enumerable.xml

### Document Version Independent Id

422bf5c0-9b03-1bed-adbf-d4c3b375815d

### Article author

@dotnet-bot

**Comment by eiriktsarpalis** [comment]
The documentation states that an `InvalidOperationException` will be thrown if the sequence contains no elements, but the remarks section clarifies that this isn't the case when you're passing in reference types. Presumably then, you're seeing this behaviour when you're using a value type?

**Comment by racnicolau** [comment]
Apologies. I am actually passing in reference types but am also invoking with a transform function which I now see also throws the exception. I was looking at the wrong method documentation. I will close the issue.
