### ISSUE TITLE
Translation of Webpage wrongly includes Method & Property Names

### ISSUE THREAD

**Issue by patricsgamma** [dotnet/dotnet-api-docs#10737]
I checked documentation for the .NET Queue Class and found a translation 🐛 
In the Classes, Properties and Methods side menu list, English words are translated, which makes no sense.

Example of [this](https://learn.microsoft.com/de-de/dotnet/api/system.collections.queue.dequeue?view=net-8.0) is translating the Queue's `Dequeue` method name into German: `Entfernen aus der Warteschlange`. 
Since these are **names** they should not be translated, only their description should be localized but not the Method, Property, Class etc. name itself.

Please check screenshot.
![Image](https://github.com/user-attachments/assets/aa1f667c-fdfe-4218-8b52-a5969eb9d940)

It seams to partially work in French where the name is kept but the translation is put in brackets `Dequeue (Enlever de la file d’attente)`, though its also not consistent. The Method name Clear was translated again into Effacer.
![Image](https://github.com/user-attachments/assets/5a40c34d-21a1-45b4-ab25-f65af6865ccf)

**Comment by gewarren** [comment]
Thanks @patricsgamma. This is a [known issue](https://github.com/dotnet/dotnet-api-docs/issues/8814) and currently being worked on. We are locking all API names from being localized. Hope to release a fix soon! cc @Khairunj
