### ISSUE TITLE
Would be helpful to have a link to the package

### ISSUE THREAD

**Issue by HugoRoss** [dotnet/dotnet-api-docs#10735]
### Type of issue

Missing information

### Description

In the "Applies To" section, instead of "(package-provided)" it would be helpful to have a link to the according package i.e. ([package-provided](https://www.nuget.org/packages/System.Threading.Tasks.Extensions)).

Applies to all the types defined in that package, namely
- System.Diagnostics.StackTraceHiddenAttribute
- System.Runtime.CompilerServices.AsyncMethodBuilderAttribute
- System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder
- System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable
- System.Runtime.CompilerServices.ValueTaskAwaiter
- System.Threading.Tasks.ValueTask
- System.Threading.Tasks.Sources.ValueTaskSourceOnCompletedFlags
- System.Threading.Tasks.Sources.ValueTaskSourceStatus
- System.Threading.Tasks.Sources.IValueTaskSource
- System.Threading.Tasks.Sources.IValueTaskSource<TResult>

(not all of them have any "package-provided" information yet).

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.valuetaskawaiter-1?view=net-9.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.CompilerServices/ValueTaskAwaiter`1.xml

### Document Version Independent Id

9376443b-e7f0-365b-f5a4-9a3339c2ab04

### Article author

@dotnet-bot

**Comment by gewarren** [comment]
Thanks @HugoRoss. We have [an internal work item](https://dev.azure.com/ceapex/Engineering/_workitems/edit/1010913) tracking this request, but it's good to hear customer feedback about it too. I've added your feedback there.
