### ISSUE TITLE
Old link to "Validate All Inputs" page

### ISSUE THREAD

**Issue by RieBi** [dotnet/dotnet-api-docs#10765]
### Type of issue

Outdated article

### Description

[Enter feedback here]
At the end of the page, in the "Important" section, there's a "Validate All Inputs" link, which links to https://top10proactive.owasp.org/archive/2018/c5-validate-inputs/, which is an outdated article, which you can notice by the message on the website when you visit that page. It would be good to update it to be https://top10proactive.owasp.org/archive/2024/the-top-10/c3-validate-input-and-handle-exceptions/, which is the new version of the article.

![Image](https://github.com/user-attachments/assets/582415b6-a982-4e2d-8338-836932bfddea)
![Image](https://github.com/user-attachments/assets/f57e2955-dd7d-47b5-b63d-3a35c3294b7d)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=net-9.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics/ProcessStartInfo.xml

### Document Version Independent Id

5f19e4c7-6c66-1d09-93b1-6e8e7abfc192

### Article author

@dotnet-bot

**Comment by tommcdon** [comment]
This looks like System.Diagnostics.Process documentation.  Adding @jeffhandley @dotnet/area-system-diagnostics-process per https://github.com/dotnet/runtime/blob/main/docs/area-owners.md
