### ISSUE TITLE
Add documentation for new SuppressMessageAttribute scope

### ISSUE THREAD

**Issue by mavasani** [dotnet/dotnet-api-docs#1101]
https://github.com/dotnet/roslyn/pull/31092 adds a new SuppressMessageAttribute scope for very widely requested feature: https://github.com/dotnet/roslyn/issues/486. We should document it here (and also improve the documentation for current scopes) once the fix goes out - Dev16 Preview2.

Also note that the new scope is only valid for Roslyn analyzers, and is not going to be respected for legacy binary FxCop based static analysis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ead130f-1feb-2367-ef07-9f73ec63b96f
* Version Independent ID: 1900bccb-13aa-120d-81cb-91e43702a141
* Content: [SuppressMessageAttribute.Scope Property (System.Diagnostics.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute.scope?view=netframework-4.7.2)
* Content Source: [xml/System.Diagnostics.CodeAnalysis/SuppressMessageAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics.CodeAnalysis/SuppressMessageAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
PR is here: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/3344

**Comment by mairaw** [comment]
@mavasani can you please review the changes made by @gewarren? Thanks.

**Comment by mavasani** [comment]
@gewarren @mairaw The changes look good to me. However, note that we have decided to rename the new scope (https://github.com/dotnet/roslyn/pull/31940), so the doc PR needs to be updated accordingly. Thanks!

**Comment by mavasani** [comment]
FYI: The new scope has been renamed to `NamespaceAndDescendants` (https://github.com/dotnet/roslyn/pull/31940)

**Comment by gewarren** [comment]
I added the scope to the [documentation](https://review.docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2017&branch=release-16.0-p2#suppressmessage-attribute). It will be published with Dev16 preview 2 (please let me know if it should be published sooner).
