### ISSUE TITLE
Terminating carriage return and/or line feed

### ISSUE THREAD

**Issue by oleesch** [dotnet/dotnet-api-docs#1150]
Not sure if my understanding is wrong but according to the remarks the terminating line feed should not be returned:
"The resulting string does not contain the terminating carriage return and/or line feed."

But when using the method I do get the terminating line feed included in the string, here's an example in PowerShell:

```
PS C:\temp> "ThisIsSomeText" > C:\temp\testfile.txt
PS C:\temp> [System.IO.File]::ReadAllText('C:\temp\testfile.txt')
ThisIsSomeText

PS C:\temp> [System.IO.File]::ReadAllBytes('C:\temp\testfile.txt')
84
104
105
115
73
115
83
111
109
101
84
101
120
116
13
10
PS C:\temp> [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
.NET Core 4.6.26725.06
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896775e2-4f85-35f2-6de5-ce4c73157f77
* Version Independent ID: b97f3644-3681-9fd1-a7b5-52e994db2233
* Content: [File.ReadAllText Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalltext?view=netframework-4.6.2)
* Content Source: [xml/System.IO/File.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/File.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
I believe you are right. I think the whole paragraph doesn't make sense:

> This method opens a file, reads each line of the file, and then adds each line as an element of a string. It then closes the file. A line is defined as a sequence of characters followed by a carriage return ('\r'), a line feed ('\n'), or a carriage return immediately followed by a line feed. The resulting string does not contain the terminating carriage return and/or line feed.

But `ReadAllText` doesn't have anything to do with lines, carriage returns and line feeds are not relevant to it. My guess is that this description is a result of copying text from the documentation for [`ReadAllLines`](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalllines?view=netframework-4.6.2#System_IO_File_ReadAllLines_System_String_), with only minor modifications.

I have opened PR https://github.com/dotnet/dotnet-api-docs/pull/1259 to fix this.
