### ISSUE TITLE
Unnecessary slash

### ISSUE THREAD

**Issue by satr** [dotnet/dotnet-api-docs#1155]
`Span\&lt;T&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36ef14f5-5cfc-5d83-971f-18789cf45237
* Version Independent ID: 9aa52936-b378-8715-4b31-46a1c0974c43
* Content: [Span&lt;T&gt; Struct (System)](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-2.1)
* Content Source: [xml/System/Span`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Span`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @satr. I've opened PR #1188 to fix this.
