### ISSUE TITLE
missing results

### ISSUE THREAD

**Issue by DickBaker** [dotnet/dotnet-api-docs#1157]
This doc gives some sample code but does NOT give results. Every other sane example lists the results in a commented-out block below the sample code. Please add.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed3eb1a-9d0e-3c27-a3fd-e72eb61fb2b2
* Version Independent ID: 6802ae9c-b816-4ab6-61fc-1fceff525967
* Content: [Uri.LocalPath Property (System)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.localpath?view=netframework-4.7.2)
* Content Source: [xml/System/Uri.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Uri.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @DickBaker. We've opened dotnet/samples#476 to display the output with the C#, Visual Basic, and C++ examples.
