### ISSUE TITLE
Docs say System.DirectoryServices aren't available in .NET Core 2.1

### ISSUE THREAD

**Issue by JohnCOsborne** [dotnet/dotnet-api-docs#1161]
Docs say System.DirectoryServices isn't available in .NET Core 2.1 and then you're directed to .NET Framework 4.7.2 and told it is the latest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd43c5b1-2ae5-247d-6831-0ff500b07096
* Version Independent ID: c7aa119f-d0e4-ab57-7b4e-91b1369ecfbe
* Content: [System.DirectoryServices Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices?view=netcore-2.0)
* Content Source: [xml/ns-System.DirectoryServices.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.DirectoryServices.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Which class on this namespace were you expecting to be in .NET Core 2.1 @JohnCOsborne?

You can access this when you select .NET Platform Extensions 2.1 though:
https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices?view=dotnet-plat-ext-2.1

**Comment by JohnCOsborne** [comment]
The issue isn't valid anymore; it seems the docs were updated. Thanks for the link!

**Comment by mairaw** [comment]
Thanks for letting us know!
