### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by lv1il0s** [dotnet/dotnet-api-docs#1170]
Default WPF Themes link ( https://go.microsoft.com/fwlink/?LinkID=158252 ) not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b938ea6-70b7-f088-2dfb-b69011a235d6
* Version Independent ID: fd9442d4-5bb4-f70e-5148-aad8b7d37ed9
* Content: [ContentControl Class (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.contentcontrol?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls/ContentControl.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/ContentControl.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @lv1il0s. I'm closing this since we have already another issue tracking the same problem: #821
