### ISSUE TITLE
Missing .net core docs

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/dotnet-api-docs#1172]
This method is undocumented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce8e507-db84-c2cf-d8e2-56e2c11a50d8
* Version Independent ID: 3489b98b-3252-2f41-89b5-c82a15cd5967
* Content: [HttpClient.PatchAsync Method (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.patchasync?view=netcore-2.1)
* Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
@imba-tjd thanks for reminder. Are you interested to submit a PR? The desription should be very simple - similar to PUT/GET, etc.

**Comment by tranceboyjohny** [comment]
I cannot see this method in System.Net.Http. What am i missing? I'm on 2.2 core

**Comment by mairaw** [comment]
@tranceboyjohny not sure. I just created a .NET Core 2.2 app and I see the 4 overloads:
![image](https://user-images.githubusercontent.com/12971179/53278158-79febd00-36bc-11e9-85cc-1e7e72471b56.png)

You're saying you can use the HttpClient class but not access just this method?

**Comment by tranceboyjohny** [comment]
My apologies, I'm actually targeting net47 in that dotnetcore app because of a legacy app dependency... I was able to access PatchAsync in my other Core app running 2.1. 

Thanks!
