### ISSUE TITLE
Update StringBuilder.Equals for .Net Core 3.0

### ISSUE THREAD

**Issue by svick** [dotnet/dotnet-api-docs#1177]
The documentation for this method says:

> Returns: `true` if this instance and `sb` have equal string, `Capacity`, and `MaxCapacity` values; otherwise, `false`.

This has been correct until now, but because of https://github.com/dotnet/coreclr/pull/20567 (which implements https://github.com/dotnet/corefx/issues/32932), it won't be correct anymore in .Net Core 3.0, because the method ignores `Capacity`, and `MaxCapacity` there.

What would be the right way to explain that situation? Something like the following?

> Returns: On .Net Framework and .Net Core versions before 3.0, `true` if this instance and `sb` have equal string, `Capacity`, and `MaxCapacity` values; otherwise, `false`. Since .Net Core 3.0, `true` if the two instances have equal string; otherwise, `false`.

Also: when should the documentation be updated? Am I right to assume now is too soon and any mentions of .Net Core 3.0 should be included in the documentation only shortly before its release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a39bc654-8660-6502-2be7-1008e50f5b4e
* Version Independent ID: c7e78992-eaf2-dfb2-9b1f-2a2a76297c19
* Content: [StringBuilder.Equals Method (System.Text)](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.equals?view=netframework-4.7.2#System_Text_StringBuilder_Equals_System_Text_StringBuilder_)
* Content Source: [xml/System.Text/StringBuilder.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text/StringBuilder.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
It's a bit too early to document this, @svick. Thanks for pointing it out, though; this is a detail that we could easily have overlooked. I'll assign the issue to myself and document it as soon as we've finalized our plans for the documentation.
