### ISSUE TITLE
Minor typos in paragraph

### ISSUE THREAD

**Issue by RaulBastian** [dotnet/dotnet-api-docs#1182]
Should this paragraph be reviewed?

The BinaryMessageEncodingBindingElement is the binding element that specified the .NET Binary Format for XML should be used for encoding messages, and has options to specify the character encoding and the SOAP and WS-Addressing version to be used

Maybe something like:

The BinaryMessageEncodingBindingElement is the binding element that **specifies** the .NET Binary Format for XML **which** should be used for encoding messages, and has options to specify the character encoding and the SOAP and WS-Addressing version to be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a10fc2e3-86c8-be04-808d-d70b46276df5
* Version Independent ID: 9ba0e82a-362e-0073-5b17-03110981c195
* Content: [TextMessageEncodingBindingElement Class (System.ServiceModel.Channels)](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.textmessageencodingbindingelement?view=netframework-4.7.2)
* Content Source: [xml/System.ServiceModel.Channels/TextMessageEncodingBindingElement.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ServiceModel.Channels/TextMessageEncodingBindingElement.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
That's a great suggestion @RaulBastian. Would you like to submit a pull request?

The instructions on how to do this can be found at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
