### ISSUE TITLE
SafeBuffer is not obsolete

### ISSUE THREAD

**Issue by jkotas** [dotnet/dotnet-api-docs#1184]
SafeBuffer was marked as deprecated by mistake. This mistake was fixed in the product a long time ago, but the docs are still showing it as deprecated.

Related discussion: https://github.com/dotnet/corefx/issues/33279#issuecomment-440957248

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3a15c01-6690-b994-182f-289e27d657aa
* Version Independent ID: e2716037-c033-957d-4705-89a6345ce9cd
* Content: [SafeBuffer Class (System.Runtime.InteropServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safebuffer?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.InteropServices/SafeBuffer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices/SafeBuffer.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@dend I know this has come up before but I can't seem to find the tracking item for displaying the right attributes based on the selected moniker. I think this is going to be addressed when we move the new system, correct?

**Comment by AaronRobinsonMSFT** [comment]
This no longer indicates obsolete in the doc.
