### ISSUE TITLE
Help is only associated with C#

### ISSUE THREAD

**Issue by netconuk** [dotnet/dotnet-api-docs#1193]
I'm using VB.net. When I press F1 it takes me to the help pages but the examples are only on C# which isn't any help at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4aa5497-1ade-5fda-f454-f7a553820d1b
* Version Independent ID: 3ad758b9-81f5-c4af-55d0-66c85204ad3b
* Content: [Timer.Elapsed Event (System.Timers)](https://docs.microsoft.com/en-us/dotnet/api/system.timers.timer.elapsed?view=netframework-4.7.2)
* Content Source: [xml/System.Timers/Timer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Timers/Timer.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @netconuk. You can change the default language selected up on top:

But I've moved the bug to https://github.com/MicrosoftDocs/feedback/issues/1308 for our engineering team to take a look at this problem.
