### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by jv42** [dotnet/dotnet-api-docs#1194]
This method throws an IndexOutOfRangeException if pos is negative.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd836f8-73ca-79b4-f32b-eeddae26036d
* Version Independent ID: 716c80eb-d03f-cde2-4585-c59c2498601f
* Content: [DataRowCollection.InsertAt(DataRow, Int32) Method (System.Data)](https://docs.microsoft.com/en-us/dotnet/api/system.data.datarowcollection.insertat?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Data.DataRowCollection.InsertAt);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.2);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Data/DataRowCollection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data/DataRowCollection.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks @jv42. You're correct. Would you like to submit a PR for this?

The change would be something similar to this: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.SqlServer.Server/SqlDataRecord.xml#L178.

**Comment by jv42** [comment]
Ok, it's done: https://github.com/dotnet/dotnet-api-docs/pull/1225
