### ISSUE TITLE
Return value details of Directory.GetCurrentDirectory

### ISSUE THREAD

**Issue by dorfire** [dotnet/dotnet-api-docs#1203]
Page doesn't mention if the returned path is absolute or relative

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9ac029-d61c-90af-fadf-5d01c40ef2ef
* Version Independent ID: 4c01f755-9830-7fce-1ec0-28caa161819b
* Content: [Directory.GetCurrentDirectory Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getcurrentdirectory?view=netframework-4.7.2)
* Content Source: [xml/System.IO/Directory.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Directory.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JeremyKuhne** [comment]
It should always return a fully qualified path per the OS apis we use.

Windows prevents you from setting a relative path (it resolves the path). https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-setcurrentdirectory

Unix guarantees that you'll get an absolute path.  https://linux.die.net/man/3/getcwd

**Comment by dorfire** [comment]
Gotcha. Thanks! I'll make the PR.

**Comment by mairaw** [comment]
I'm reopening so we don't lose track of this work item.
