### ISSUE TITLE
Should API reference keep including permission information?

### ISSUE THREAD

**Issue by svick** [dotnet/dotnet-api-docs#1204]
Many API reference pages include section on "security", which explains which `SecurityAction` is required to use them. As far as I know, using `System.Security.Permissions` is discouraged on .Net Framework and they are not used on .Net Core at all.

Is there a reason why this information should still be included or can it be removed wholesale?

**Comment by jkotas** [comment]
I have run into this when looking when looking at unrelated issue. The documentation of the required code access security permissions adds a lot of legacy clutter to the documentation.

The code access security is officially deprecated for number if years. It is documented here: https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security . I believe it would be  perfectly fine to delete the required code access security permissions from the documentation.

@mairaw I will be happy to do a global find&replace to delete this if you are ok with it. Let me know.

**Comment by mairaw** [comment]
Yep. If it doesn't add any value, I'm completely fine removing it.
