### ISSUE TITLE
Example does not produce correct output

### ISSUE THREAD

**Issue by tommos23** [dotnet/dotnet-api-docs#1211]
In the 1st example using the ProductA type the result is not:
orange 4
lemon 12

It is:
apple 9
orange 4
lemon 12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5fb66fb-9a33-2550-2783-7ce2a4760219
* Version Independent ID: 2e80b927-7888-1fc8-7db9-d052b33ac87a
* Content: [Enumerable.Except Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?redirectedfrom=MSDN&view=netframework-4.7.2#System_Linq_Enumerable_Except__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___0__)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @tommos23. After some investigation, I found out that samples and remarks were wrong. I've opened two PRs to fix this:
- https://github.com/dotnet/samples/pull/484
- https://github.com/dotnet/dotnet-api-docs/pull/1217
