### ISSUE TITLE
Example missing

### ISSUE THREAD

**Issue by JeffAtWeldon** [dotnet/dotnet-api-docs#1212]
The first four paragraphs under "Examples" describe a code example that does not appear in this article.  These four paragraphs seem to be duplicated from the "Control.DoDragDrop" article (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.dodragdrop) but without the code example.

Either the code example should be included in this article after the four paragraphs, or the four paragraphs should be removed and replaced with a statement such as "See the DoDragDrop method for the complete code example."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6325616f-0c20-7d4a-ff62-d22e45a01140
* Version Independent ID: 8383e576-2a04-167d-0af3-8f790260b8b4
* Content: [Control.QueryContinueDrag Event (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.querycontinuedrag?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/Control.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/Control.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @JeffAtWeldon. This is probably a copy and paste error. The best solution here would be to simplify the description and point to the method for the complete sample. I'm adding this to our backlog and our community contribution project.
