### ISSUE TITLE
If first list contains two simillar elements and even though the second list doesnt contain it, 'except' returns only one element of the first list 

### ISSUE THREAD

**Issue by SathishRanjan** [dotnet/dotnet-api-docs#1215]
If first list contains two simillar elements and even though the second list doesnt contain it, 'except' returns only one element of the first list 

See https://dotnetfiddle.net/tAjsEe

edit by @mairaw: cleaned up the issue and added the docs info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5fb66fb-9a33-2550-2783-7ce2a4760219
* Version Independent ID: 2e80b927-7888-1fc8-7db9-d052b33ac87a
* Content: [Enumerable.Except Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?view=netframework-4.7.2#System_Linq_Enumerable_Except__1_System_Collections_Generic_IEnumerable___0__System_Collections_Generic_IEnumerable___0__)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @SathishRanjan. I've added some clarification that the method returns unique elements on the following PR #1217
