### ISSUE TITLE
Inheritance chain is wrong

### ISSUE THREAD

**Issue by alfredmyers** [dotnet/dotnet-api-docs#1224]
The Inheritance chain shown on  the web page is wrong:

> Inheritance:    Object -> Exception -> **SystemException** -> SqlException

when immediately above we can see that in fact, SqlException inherits from DbException.

```
[System.Serializable]
public sealed class SqlException : System.Data.Common.DbException
```

As I understand, the docs generator isn't interpreting the following line correclty:

https://github.com/dotnet/dotnet-api-docs/blob/4a33732f45493ce4d12840dc9c4b6f66256c38a0/xml/System.Data.SqlClient/SqlException.xml#L27

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be16acd7-936e-9833-f743-6a704b5f7a63
* Version Independent ID: 4a3fe442-1648-f625-b5b5-7b9b3c647243
* Content: [SqlException Class (System.Data.SqlClient)](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlexception?view=netframework-4.7.2)
* Content Source: [xml/System.Data.SqlClient/SqlException.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlException.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks @alfredmyers. This issue is already being tracked at https://github.com/MicrosoftDocs/feedback/issues/616.
