### ISSUE TITLE
What is this supposed to mean?

### ISSUE THREAD

**Issue by maryob77062** [dotnet/dotnet-api-docs#1250]
Remarks "To ensure the proper sort order, specify sort criteria with Select or Select." The 2 links just bring you back to the same page. Looks kind of stupid, Select or Select.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d35d94-de9f-198f-844c-ec87d004e185
* Version Independent ID: bc76d78d-39d5-02cd-283a-9625dae2dbad
* Content: [DataTable.Select Method (System.Data)](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.select?view=netframework-4.7.2)
* Content Source: [xml/System.Data/DataTable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data/DataTable.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@maryob77062 Thank you for bringing this to our attention. The original intent was to link directly to the 2 overloads that support a _sort_ parameter, but I think this stopped working as expected after a content migration. I will remove the useless links.

**Comment by douglaslMS** [comment]
@maryob77062 I spoke too soon. I have corrected the link syntax (in both locations) to point correctly to the 2 overloads that support the _sort_ parameter.

**Comment by douglaslMS** [comment]
@mairaw I thought I fixed this article in 2 locations by updating the xref link syntax to use the correct syntax for specific overloads - for example, `<xref:System.Data.DataTable.Select(System.String,System.String)>`. However the links are still not working in the published page. Can you please take a look?

**Comment by mairaw** [comment]
I held off the publishing last night because of the releases going live today. Kicked off a new merge to live PR now.
