### ISSUE TITLE
Need to go to the Czech Republic for Examples?

### ISSUE THREAD

**Issue by maryob77062** [dotnet/dotnet-api-docs#1251]
I didn't know you were using off site links now.
"The criteria to use to filter the rows. For examples on how to filter rows, see DataView RowFilter Syntax [C#]."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d35d94-de9f-198f-844c-ec87d004e185
* Version Independent ID: bc76d78d-39d5-02cd-283a-9625dae2dbad
* Content: [DataTable.Select Method (System.Data)](https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.select?view=netframework-4.7.2)
* Content Source: [xml/System.Data/DataTable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data/DataTable.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@maryob77062 It's not clear what doc bug you are reporting. That the samples aren't useful samples? That the samples aren't official Microsoft samples? It's not clear how the location of the web host affects the value of the samples.

**Comment by douglaslMS** [comment]
No doc issues to fix. Closing this issue.

**Comment by mairaw** [comment]
It was about the use of this link: https://www.csharp-examples.net/dataview-rowfilter/

I believe we already have a similar issue filed.

**Comment by mairaw** [comment]
Here's the duplicate: https://github.com/dotnet/docs/issues/3905 

I'll transfer that issue into this repo.

**Comment by douglaslMS** [comment]
@mairaw Do you avoid using links to third-party sites in the .NET repo? The examples in the linked page seemed useful. I use third-party links with discretion in the SQL repo - for example, to a connection strings reference page.
