### ISSUE TITLE
Should "See Also" wrap?

### ISSUE THREAD

**Issue by svick** [dotnet/dotnet-api-docs#1257]
At the end of the documentation for [the `File.ReadAllText(string)` method](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalltext?view=netframework-4.6.2#System_IO_File_ReadAllText_System_String_) is the See Also section, which looks like this to me:

![](https://user-images.githubusercontent.com/287848/49343924-ef845f80-f670-11e8-80ce-905582014214.png)

At first sight, it appears as if the first line of links had the header "See" and the second line "Also". Since "See Also" is so short, I think it would look better without a line break:

![](https://user-images.githubusercontent.com/287848/49343971-85b88580-f671-11e8-999a-adc0d812b16f.png)

**Comment by mairaw** [comment]
Thanks @svick. Since this is not a content issue but an engineering issue, I've moved it to https://github.com/MicrosoftDocs/feedback/issues/920.
