### ISSUE TITLE
Sample output

### ISSUE THREAD

**Issue by Efreeto** [dotnet/dotnet-api-docs#1265]
This would be more helpful with a sample output from the example!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 063a2350-dac9-a611-92fa-5cab9af5912e
* Version Independent ID: 4093a2eb-97af-9af7-cbed-eb12e0394422
* Content: [ThreadLocal&lt;T&gt; Class (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadlocal-1?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Threading/ThreadLocal`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadLocal`1.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Removing the interactive piece for now as we sort out issues with try.net. So we should just add the output as part of the example similar to what we do in other pages:
https://github.com/dotnet/samples/blob/master/snippets/csharp/System.DateTime/Parsing.cs#L63

**Comment by mairaw** [comment]
Closing this one since both PRs got merged. Thanks @TashasEv! ❤️

**Comment by Efreeto** [comment]
Wow, thank you everyone.
I was only half expecting I would be heard here, but you guys actually heard me and did this!
