### ISSUE TITLE
CopyToAsync return type?

### ISSUE THREAD

**Issue by DickInKent** [dotnet/dotnet-api-docs#1279]
[Enter feedback here]the docs variously state that return type is Task or Task<TResult> so please correct whichever is wrong. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84dcad3c-cb67-e84b-1039-534a5b1f3f9b
* Version Independent ID: 3e4a5da3-8252-8b3d-cd55-6531007093c3
* Content: [HttpContent.CopyToAsync Method (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent.copytoasync?view=netframework-4.7.2#System_Net_Http_HttpContent_CopyToAsync_System_IO_Stream_)
* Content Source: [xml/System.Net.Http/HttpContent.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpContent.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by DickInKent** [comment]
the docs variously state that return type is Task or Task&lt;TResult&gt; so please correct whichever is wrong. Thanks.

Some corrector mangled my previous input text, removing the generic argument so I have attempted here to re-enter with html alias instead

**Comment by mairaw** [comment]
Thanks for your feedback @DickInKent and thanks @svick for fixing this issue.
