### ISSUE TITLE
Don't be perniciously generic

### ISSUE THREAD

**Issue by DickBaker** [dotnet/dotnet-api-docs#1280]
Stating "The returned Task&lt;TResult&gt; object .." is unnecessarily generic (requiring more brain cycles to determine what TResult might be). Please make life easier for readers by stating Task&lt;Stream&gt; throughout the docs (twice here as 2 signatures) instead of being cultishly obscure. [readers can fight back with long words too 😉]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d631c3d1-c266-5828-015f-ab08ce377542
* Version Independent ID: a6438168-4ae4-33b3-bb89-b17f0e987d2e
* Content: [HttpClient.GetStreamAsync Method (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstreamasync?view=netframework-4.7.2#System_Net_Http_HttpClient_GetStreamAsync_System_String_)
* Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Thanks for your feedback @DickBaker. That's a good suggestion.

The link would have to be changed from `<xref:System.Threading.Tasks.Task%601>` to `[Task\<Stream>](xref:System.Threading.Tasks.Task%601)` on lines 1123 and 1170. Similar changes could be done to the other APIs too.

Would you like to submit a pull request to fix this? The instructions on how to do this can be found at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.

**Comment by samsp-msft** [comment]
This seems to be a prevalent problem in the networking documentation. We should try and do a global fix.
@BillWagner, @joelmartinez - is this something we can do with mdoc?

**Comment by Naidile-P-N** [comment]
Is it still available to work on ? I would like to contribute to this

**Comment by BillWagner** [comment]
@Naidile-P-N This is still available.  We'll watch for a PR, if you'd like to submit one.

**Comment by Naidile-P-N** [comment]
Raised PR - Update HttpClient.xml #6858 with changes for GetStreamAsync method,
