### ISSUE TITLE
Configuration element name is missing

### ISSUE THREAD

**Issue by Thieum** [dotnet/dotnet-api-docs#1282]
In the remarks part:
"For very large ConcurrentDictionary&lt;TKey,TValue&gt; objects, you can increase the maximum array size to 2 gigabytes (GB) on a 64-bit system by setting the configuration element to true in the run-time environment."

I'd assume it's gcAllowVeryLargeObjects, but it's not named explicitely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 806c6485-9396-e6bf-2f8e-f27866115626
* Version Independent ID: 3e499bf3-fa82-0b82-5d85-84a0b3fe0515
* Content: [ConcurrentDictionary&lt;TKey,TValue&gt; Class (System.Collections.Concurrent)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Concurrent/ConcurrentDictionary`2.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @Thieum. We've opened #1345 to restore the missing text.
