### ISSUE TITLE
No Examples?

### ISSUE THREAD

**Issue by Bungalow12** [dotnet/dotnet-api-docs#1284]
Not that I feel this is complicated but one thing I have always loved regarding .NET documentation was the inclusion of simple examples.

How about something as simple as:
```
string jsonString = @"{
	"key": "value",
	"num": 2
}";

var json = JsonObject.Parse(jsonString);

Console.WriteLine("Key: {0}", json["key"]);
Console.WriteLine("Num: {0}", json["num"]);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17103a78-f993-6757-93f8-8d933c55fa6c
* Version Independent ID: 149b2685-d6c4-8be2-5ec8-980c53af0692
* Content: [JsonObject Class (System.Json)](https://docs.microsoft.com/en-us/dotnet/api/system.json.jsonobject?view=dotnet-plat-ext-2.1#feedback)
* Content Source: [xml/System.Json/JsonObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Json/JsonObject.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
HI @Bungalow12!
This is a new API that we haven't even documented yet. So we'll consider your suggestion when we start working on that class.

**Comment by JVimes** [comment]
In lieu of docs, is the source code available?

**Comment by mairaw** [comment]
Yes @JVimes, you can find the source code here: https://source.dot.net/#System.Json/System/Json/JsonObject.cs

**Comment by carlossanlop** [comment]
The APIs in `System.Json` have been obsoleted, and we discourage their usage. We strongly suggest you use the APIs in `System.Text.Json` instead, which is a fast and efficient new set of APIs for handling Json data.
