### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by william-shuman** [dotnet/dotnet-api-docs#1292]
This method documentation needs more detail.  In what cases does it return true vs false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81498c77-e953-d79b-d758-09e63edc61fd
* Version Independent ID: 51907d96-b483-143d-0462-45d3b3cd2b30
* Content: [Dictionary&lt;TKey,TValue&gt;.TryAdd(TKey, TValue) Method (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=netcore-2.2)
* Content Source: [xml/System.Collections.Generic/Dictionary`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/Dictionary`2.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @william-shuman for your feedback. This API is still lacking documentation Closing this request since issue #939 is already tracking this work.
