### ISSUE TITLE
The remarks section doesn't make clear that DbNull.Value must be used to send a NULL value

### ISSUE THREAD

**Issue by pkanavos** [dotnet/dotnet-api-docs#1294]
In the remarks section, the phrase : 

>  Use [Value](https://docs.microsoft.com/en-us/dotnet/api/system.dbnull.value?view=netframework-4.7.2) to send a NULL value as the value of the parameter. 

Should be changed to :

>  Use [DbNull.Value](https://docs.microsoft.com/en-us/dotnet/api/system.dbnull.value?view=netframework-4.7.2) to send a NULL value as the value of the parameter. 

The current link text confuses people, as shown [in this SO question](https://stackoverflow.com/questions/53665011/sqlparameter-disappears-when-assigned-a-value-of-null)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed540b8c-3445-9e89-501e-65dc61f31bd6
* Version Independent ID: af7e893b-d28e-c5de-e44b-3ca8a2631dc0
* Content: [SqlParameter.Value Property (System.Data.SqlClient)](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlparameter.value?view=netframework-4.7.2#System_Data_SqlClient_SqlParameter_Value)
* Content Source: [xml/System.Data.SqlClient/SqlParameter.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlParameter.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by rpetrusha** [comment]
Thanks for providing this feedback, @pkanavos, as well as for providing a link to the StackOverflow question that indicates the confusion. We've opened #1309 to address this issue.
