### ISSUE TITLE
Remarks before Examples in Documentation

### ISSUE THREAD

**Issue by NetMage** [dotnet/dotnet-api-docs#1301]
In general, it seems to me that Remarks should precede Examples in the documentation, as without the Remarks explaining the background and purpose of classes, the Examples aren't always meaningful. Possibly after the members documentation as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b66ab1a-35aa-1bba-388c-30d698c1f50c
* Version Independent ID: d7dde1b9-fd16-dd30-6622-a15836579a9c
* Content: [HashSet&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/HashSet`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/HashSet`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback, Given this was a design decision with the new documentation site @NetMage, I've moved this to https://github.com/MicrosoftDocs/feedback/issues/937.
