### ISSUE TITLE
Produce reports on interactive API usage and candidate identification

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/dotnet-api-docs#1307]
## Produce reports on interactive API usage and candidate identification

Two reports are needed:

- A data-driven report that evaluates whether interactive examples are successful.

- A data-driven report that identifies APIs whose examples would benefit from interactivity

**Comment by mairaw** [comment]
Item 1 is already on my to-do list for @LadyNaggaga.

We need to work with the CGA team to create custom Kusto queries for us.

/cc @wadepickett

**Comment by mairaw** [comment]
Should we close this @rpetrusha given we produced a list of the APIs that we want to add interactive on a first round?

**Comment by mairaw** [comment]
Although we still don't have the data-driven report 😢

**Comment by rpetrusha** [comment]
Righjt, @mairaw, we still don't have the data-driven report. We should leave it open as part of the overall project.

**Comment by rpetrusha** [comment]
Since the try.dotnet interactive REPL is no longer experimental, I'm going to close this issue.
