### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mrmsbarnes** [dotnet/dotnet-api-docs#1319]
Between XAML and C# towards top of page at https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textblock
"The following example   shows how to shows how to   " ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a311f5-9b11-d4d6-0e7c-f3a59ddcb466
* Version Independent ID: 519366a4-ef79-f1e2-e75c-87595f416fef
* Content: [TextBlock Class (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textblock?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Controls.TextBlock);k(VS.Toolbox);k(System.Windows.Controls.Slider);k(VS.XamlDesigner);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.1)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls/TextBlock.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/TextBlock.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @mrmsbarnes. Would you like to submit a pull request to fix this?

We explain the process at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
