### ISSUE TITLE
Inheritance should be inverted and it should omit the final class

### ISSUE THREAD

**Issue by drowa** [dotnet/dotnet-api-docs#1337]
Instead of... Inheritance Object -&gt; SubClass1 -&gt;  ... -&gt; SubClassN -&gt; ClassOnThisDocPage
It should be... Inheritance SubClassN &lt;- ... &lt;- SubClass1 &lt;- Object

This would follow the structure of the code, focusing on the immediate parent which is usually more relevant than Object.

Also, omitting the final class would make the 'Inheritance' part of the doc somehow more "symmetric" with the 'Implements' part.

Note that when using this rule, the doc page of the Object class would naturally lack the 'Inheritance' part (because we are omitting the final class).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b66ab1a-35aa-1bba-388c-30d698c1f50c
* Version Independent ID: d7dde1b9-fd16-dd30-6622-a15836579a9c
* Content: [HashSet&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1?view=netframework-4.7.2#definition)
* Content Source: [xml/System.Collections.Generic/HashSet`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/HashSet`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @drowa. Moved this feedback to https://github.com/MicrosoftDocs/feedback/issues/945, for our engineering team to take a look.
