### ISSUE TITLE
Candidate for NetStandard

### ISSUE THREAD

**Issue by markusschaber** [dotnet/dotnet-api-docs#1340]
Is this a candiadate for NetStandard? If not, what's the recommended way for custom certificate verification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f04ddf8-2cc7-7893-425f-cd4bb418ee22
* Version Independent ID: fe53746f-3022-7fd7-5366-612f3d2945e0
* Content: [ClientWebSocketOptions.RemoteCertificateValidationCallback Property (System.Net.WebSockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocketoptions.remotecertificatevalidationcallback?view=netcore-2.2)
* Content Source: [xml/System.Net.WebSockets/ClientWebSocketOptions.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.WebSockets/ClientWebSocketOptions.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
The best place for this kind of question would be at https://github.com/dotnet/standard but adding @terrajobst here to see if he can comment on that.

**Comment by karelz** [comment]
Agreed, we should not track these questions/discussions in docs repo. Closing.
