### ISSUE TITLE
"Applies to" ambiguity

### ISSUE THREAD

**Issue by trustypie** [dotnet/dotnet-api-docs#1348]
HashSet&lt;T&gt;(Int32) is only available from 4.7.2, but reading this document makes it appear available from 3.5+. See https://stackoverflow.com/questions/6771917/why-cant-i-preallocate-a-hashsett for detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37998f57-5432-f9e7-28ab-433891d2208f
* Version Independent ID: 275d1cf1-b919-bd71-82dd-540e9e091eb6
* Content: [HashSet&lt;T&gt; Constructor (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.-ctor?view=netframework-4.7.2#System_Collections_Generic_HashSet_1__ctor_System_Int32_)
* Content Source: [xml/System.Collections.Generic/HashSet`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/HashSet`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @trustypie.

We're tracking this request at https://github.com/MicrosoftDocs/feedback/issues/314.
