### ISSUE TITLE
You must use Process.Refresh() when reading stats in a loop

### ISSUE THREAD

**Issue by jsuddsjr** [dotnet/dotnet-api-docs#1360]
If you do not refresh the values, they will be the same each time you print them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d7a01a9-54a3-aea3-ccd5-d55d9f2d85a6
* Version Independent ID: fc981e67-5134-1bbe-5a4f-b2cb4e40dd53
* Content: [Process.WorkingSet Property (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.workingset?view=netframework-4.7.2)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/Process.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Jozkee** [comment]
@jsuddsjr can you give a concrete suggestion of what we should do to make this more obvious?
