### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by beedjees** [dotnet/dotnet-api-docs#1369]
What does Clamp(...) method ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccc0a127-e852-6fee-e901-59361541cac7
* Version Independent ID: 8e48c3bd-8e68-e4c7-167c-07efd236a06f
* Content: [Math.Clamp Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.math.clamp?view=netcore-2.2)
* Content Source: [xml/System/Math.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Math.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @beedjees. The Math class has new APIs that we haven't been able to document it yet.

You can see some info about it at https://github.com/dotnet/corefx/issues/467. 

It basically guarantees that a value will always be between its min and max values.

I'm scheduling this for a future sprint.

**Comment by mairaw** [comment]
Moving to the backlog until I can actually pick this up to start working on it.

**Comment by mairaw** [comment]
The APIs have been documented but I think they can still use some work given their descriptions now are not very helpful.

/cc @carlossanlop not sure who owns this

**Comment by carlossanlop** [comment]
@tannergooding are you the owner of System.Math? If not, do you know who is?

**Comment by tannergooding** [comment]
Yes I am. I think this is also simple enough that it could be marked `up-for-grabs` initially, and I or @pgovind can get to it for 5.0 otherwise.

**Comment by tannergooding** [comment]
I'm not sure how much more the docs can be improved. The existing docs are effectively: 
```csharp
/// <summary>Returns <paramref name="value" /> clamped to the inclusive range of <paramref name="min" /> and <paramref name="max" />.</summary>
/// <param name="value">The value to be clamped.</param>
/// <param name="min">The lower bound of the result.</param>
/// <param name="max">The upper bound of the result.</param>
/// <returns>
///   <paramref name="value" /> if <paramref name="min" /> ≤ <paramref name="value" /> ≤ <paramref name="max" />.  
///     
///    -or-  
///     
///    <paramref name="min" /> if <paramref name="value" /> &lt; <paramref name="min" />.
///     
///    -or-  
///     
///    <paramref name="max" /> if <paramref name="max" /> &lt; <paramref name="value" />.
/// </returns>
```

This is a correct and short explanation defining the semantics.
