### ISSUE TITLE
Wrong return value

### ISSUE THREAD

**Issue by breyed** [dotnet/dotnet-api-docs#1371]
The Returns section says, "The Result property on the task object returns a Byte array containing the received data." That's incorrect. The Result property contains a WebSocketReceiveResult, which does not contain the received data.

Less obvious is exactly when the returned task completes successfully versus with an exception, especially regarding connection closure and network errors. The Returns section should document these details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e9d105-0964-0a00-068c-c4160e620ce5
* Version Independent ID: 492a8ab2-9f42-aedc-3349-bc5056316874
* Content: [WebSocket.ReceiveAsync Method (System.Net.WebSockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.receiveasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.WebSockets.WebSocket.ReceiveAsync);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=netframework-4.7.2)
* Content Source: [xml/System.Net.WebSockets/WebSocket.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.WebSockets/WebSocket.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
Looks like a bug. Are you interested in putting up a PR?

Regarding the exceptions - I would expect that it goes without saying that a catastrophic network error may cause an exception in every networking API. Do you think there is anything specific in this case that needs to be called out?

**Comment by breyed** [comment]
I'd rather leave the PR to someone who can document the semantics are for the returned task. An example of the detail required is in [Socket.Receive](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receive?view=netframework-4.7.2#System_Net_Sockets_Socket_Receive_System_Byte___), e.g., what happens if there is a timeout or if the remote side shuts down the connection.

**Comment by karelz** [comment]
We would appreciate if you can submit PR for fixing the bug in `Result` property description.

Regarding the exceptions, it will require some code analysis, or playing with the APIs to test out various scenarios. Likely in all 4 different implementations (.NET Framework, .NET Native / UWP, .NET Core 1.0-2.0 and .NET Core 2.1+).
It would make sens to track that request separately.
