### ISSUE TITLE
The system's ping utility could not be found

### ISSUE THREAD

**Issue by mc0re** [dotnet/dotnet-api-docs#1386]
Looks like this class relies on the actual executable, and if it cannot be found on the system, the SendPing fails with the exception above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96056416-fab7-2a90-9189-082b9ec7a577
* Version Independent ID: 9d9dec54-e2e5-243e-cfdd-e045dd1c1171
* Content: [Ping Class (System.Net.NetworkInformation)](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ping?view=netcore-2.1)
* Content Source: [xml/System.Net.NetworkInformation/Ping.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.NetworkInformation/Ping.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mc0re** [comment]
It falls with PingException. I'm not much into networking, but I find that strange that sending ICMP packages from code requires admin privileges.
It would be nice to have it documented, I can do that if you tell me how. But even nicer would be pointing to a workaround, and that one I don't know :-(

**Comment by wfurt** [comment]
It would be rare for any OS _not_ to have ping available. Unprivileged uses on Unix do not have rights to send ICMP messages.

**Comment by mc0re** [comment]
Rare, but that's apparently the current setup I have to work with. Thanks for info.
