### ISSUE TITLE
Incorrect formatting of escaped sequence

### ISSUE THREAD

**Issue by jozefizso** [dotnet/dotnet-api-docs#1389]
Paragraph about escape sequence is incorrectly formatted:

```
The escape character is "". Any XML name character that does not conform to the XML 1.0 spec (fourth edition) recommendation is escaped as _xHHHH\.
```

It should be:

```
The escape character is "_". Any XML name character that does not conform to the XML 1.0 spec (fourth edition) recommendation is escaped as _xHHHH_.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7564b8be-35ca-a57a-6ea3-31bef1a25bbd
* Version Independent ID: 2723f9ed-4ed4-72c2-e6e6-15f321fe40da
* Content: [XmlConvert.EncodeName(String) Method (System.Xml)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlconvert.encodename?view=netframework-4.7.2)
* Content Source: [xml/System.Xml/XmlConvert.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlConvert.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @jozefizso for your feedback. This was fixed as part of this PR: https://github.com/dotnet/dotnet-api-docs/pull/1729
