### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by ptoye** [dotnet/dotnet-api-docs#1398]
The TryPeek and TryPop appear in the sidebar but there's no text for them.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83292c87-15de-b468-3ace-8d127b828305
* Version Independent ID: 405792e7-ea6b-870e-c6d9-2afe41be8bfd
* Content: [Stack&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.stack-1?view=netframework-4.7.1)
* Content Source: [xml/System.Collections.Generic/Stack`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/Stack`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@ptoye I'll be closing this one since you already filed issues #1396 and #1397 for these two APIs.
