### ISSUE TITLE
Document remaining Memory<T>-related APIs

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/dotnet-api-docs#1411]
## Document remaining Memory\<T>-related APIs

We've documented a portion of the Span\<T> and Memory\<T>-related APIs in the following PRs:
- dotnet/docs#2256
- dotnet/dotnet-api-docs#136
- dotnet/dotnet-api-docs#228
- dotnet/dotnet-api-docs#358
- dotnet/dotnet-api-docs#548

The remaining APIs (in the [System.Buffers](https://docs.microsoft.com/dotnet/api/system.buffers?view=netcore-2.1) namespace, should also be documented. These include:

- [x] [ReadOnlyMemory\<T>](https://docs.microsoft.com/en-us/dotnet/api/system.readonlymemory-1?view=netcore-2.1)

- [x] [BuffersExtensions](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.buffersextensions?view=netcore-2.1)
- [x] [MemoryManager\<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorymanager-1?view=netcore-2.1)
- [x] [MemoryHandle](https://docs.microsoft.com/dotnet/api/system.buffers.memoryhandle?view=netcore-2.2) 
- [x] [MemoryPool\<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorypool-1?view=netcore-2.1)
- [x] [ReadOnlySequenceSegment\<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.readonlysequencesegment-1?view=netcore-2.1)
- [x] [ReadOnlySequence\<T>.Enumerator](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.readonlysequencesegment-1?view=netcore-2.1)
- [x] [ReadOnlySequence\<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.readonlysequence-1?view=netcore-2.1)
- [x] [StandardFormat](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.standardformat?view=netcore-2.1)
- [x] [IBufferWriter\<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.ibufferwriter-1?view=netcore-2.1)
- [x] [IPinnable](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.ipinnable?view=netcore-2.1)
- [x] [OperationStatus](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.operationstatus?view=netcore-2.1)
- [ ] [ReadOnlySpanAction\<T,TArg>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.readonlyspanaction-2?view=netcore-2.1)
- [ ] [SpanAction\<T,TArg>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.spanaction-2?view=netcore-2.1)

**Comment by carlossanlop** [comment]
Since we have been porting missing documentation from runtime to dotnet-api-d0cs, we already documented these APIs.
