### ISSUE TITLE
Document RuntimeReflectionExtensions exceptions

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/dotnet-api-docs#1414]
## Document RuntimeReflectionExtensions exceptions

See https://github.com/dotnet/docs/issues/7926 

The exceptions thrown by the [RuntimeReflectionExtensions](https://docs.microsoft.com/dotnet/api/system.reflection.runtimereflectionextensions) methods are generally not documented. The exceptions are generally the same as those thrown by the corresponding [System.Type](https://docs.microsoft.com/dotnet/api/system.type) method. To document them, we need to:

- Examine the documentation the corresponding [System.Type](https://docs.microsoft.com/dotnet/api/system.type) method.
- Examine the source for the RuntimeReflectionExtensions method.
- Document the exception.  

@StephaneDelacroix

**Comment by mairaw** [comment]
@IcecreamBurglar sorry for not responding earlier. We try to triage incoming issues on a regular basis. The ones we assign to someone in our team means we have that in our pipeline of work for the next few sprints. @rpetrusha can let you know if he'd like some help on this one. 

But if you see one not assigned to anyone yet, feel free to jump in. We do tag the ones as up-for-grabs where we feel the community can be successful in helping us. But you can also help with any other unassigned issue. Just comment on the bug so people know someone is already working on that. And for easy fixes, just go ahead and submit a PR.
