### ISSUE TITLE
Affect versus Effect

### ISSUE THREAD

**Issue by FierceLlama** [dotnet/dotnet-api-docs#1430]
Previous comment was unprofessional, my apologies.  The word 'affect' is incorrectly used when discussing the use of Flush on a Network Stream; it should be changed to 'effect.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5295d10-0599-07a6-2e11-6fbe48522b61
* Version Independent ID: ce5c734a-c109-d27f-9a97-b276894b48eb
* Content: [NetworkStream.Flush Method (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.flush?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/NetworkStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/NetworkStream.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Thanks for your feedback @FierceLlama. We try our best, but we do have grammar mistakes here and there. Would you like to submit a fix?
This article explains how: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by FierceLlama** [comment]
I do want to apologize for my earlier post.  Rough day at work and I let my emotions get the better of my judgement.  I will follow the article to make the changes.  Thank you for the swift response, and again, my apologies for being a troll regarding this issue.
Very Respectfully,Chris Sosa

    On Tuesday, December 18, 2018, 12:42:38 PM CST, Maira Wenzel <notifications@github.com> wrote:  
 
 
Thanks for your feedback @FierceLlama. We try our best, but we do have grammar mistakes here and there. Would you like to submit a fix?
This article explains how: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by mairaw** [comment]
No worries. We all have those days. Thanks for making the fix.
