### ISSUE TITLE
Recommendation of HttpClient might be misleading when synchronous requests are needed

### ISSUE THREAD

**Issue by mpwaldhorst** [dotnet/dotnet-api-docs#1436]
The recommendation to use HttpClient instead of WebRequest/HttpWebRequest assumes that it is always possible to use asynchronous methods. If the framework/application in which you are developing prevents you from using that functionality sometimes it is better to do synchronous requests.

Synchronous requests are not supported by HttpClient and using GetAwaiter().GetResult() can cause performance issues due to blocking threads etc.

Maybe the recommendation should be reworded to indicate this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e85a092-3365-14df-19d5-9d1cc3d4dfe0
* Version Independent ID: dad847ce-299a-8dbd-7175-ce1b6e25e846
* Content: [WebRequest Class (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest?view=netframework-4.7.2)
* Content Source: [xml/System.Net/WebRequest.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/WebRequest.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
This is an interesting topic - @stephentoub what is our official advice here?

Is the right answer to go and add sync APIs to `HttpClient` (apparently such guidance is making its way into general Framework guidelines)
cc @geoffkizer

**Comment by karelz** [comment]
Actually, looks like it was already answered here: https://github.com/dotnet/corefx/issues/13813#issuecomment-261716796
I wonder if anything changed recently @stephentoub (@bartonjs mentioned the new Framework guidelines due to "recent" lessons we learned in ASP.NET API surface).
