### ISSUE TITLE
The link to LINQ to XML links to a “previous version” of documentation

### ISSUE THREAD

**Issue by binki** [dotnet/dotnet-api-docs#1440]
There is a link to https://msdn.microsoft.com/library/f0fe21e9-ee43-4a55-b91a-0800e5782c13 in this document. See https://github.com/dotnet/docs/issues/9678

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc592a3-25d9-1338-adc3-f0b284067cac
* Version Independent ID: 56e0556d-8d60-534a-899a-ebd3d38d47bf
* Content: [XNode.ToString Method (System.Xml.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xnode.tostring?view=netframework-4.7.2#System_Xml_Linq_XNode_ToString_System_Xml_Linq_SaveOptions_)
* Content Source: [xml/System.Xml.Linq/XNode.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Linq/XNode.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback. We're fixing some issues related to that documentation but I have a PR open to address that.
