### ISSUE TITLE
Conver to decimal 

### ISSUE THREAD

**Issue by jedionmelbin** [dotnet/dotnet-api-docs#1442]
Convert to decimal  result 2.5 round to 3.. please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e79a4a-b836-1691-5777-dc4a44363b8e
* Version Independent ID: 545103d9-864c-c3d7-91a6-17203c4c7897
* Content: [OutOfMemoryException Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.outofmemoryexception?view=netframework-4.7.2)
* Content Source: [xml/System/OutOfMemoryException.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/OutOfMemoryException.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Are you talking about a sample on this page you commented? If not, do you want to paste the code you're using which you're not getting what you want?

Have you looked into https://docs.microsoft.com/en-us/dotnet/api/system.decimal.round?

**Comment by mairaw** [comment]
Closing due to the lack of response. If you can come to us with more information, we can reopen the issue.
