### ISSUE TITLE
.net standard

### ISSUE THREAD

**Issue by DekkersR** [dotnet/dotnet-api-docs#1443]
Seems that this property is removed from the new nuget package. Is there somewhere some information on how to switch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f78ad825-9a73-58af-bd86-897df7b62188
* Version Independent ID: 70c56392-4ce6-db7c-af6c-210bf20c6180
* Content: [ServiceDescription.Behaviors Property (System.ServiceModel.Description)](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.description.servicedescription.behaviors?view=netframework-4.7.2)
* Content Source: [xml/System.ServiceModel.Description/ServiceDescription.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ServiceModel.Description/ServiceDescription.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
To which NuGet package are you referring to @DekkersR? This is a .NET Framework API, so you need to add a reference to the System.ServiceModel.dll in your project.

**Comment by mairaw** [comment]
Closing due to the lack of information and also because I feel the question was answered. Please let us know if we missed anything.
