### ISSUE TITLE
A possible HttpListenerException exception not listed

### ISSUE THREAD

**Issue by immitev** [dotnet/dotnet-api-docs#1451]
Under some circumstances calling `EndGetContext` might also lead to an exception:
System.Net.HttpListenerException
HResult=0x80004005
Message=The I/O operation has been aborted because of either a thread exit or an application request

Got this under Windows Server 2016. Btw, I see others has also encountered such a problem https://community.qlik.com/t5/QlikView-Management/Management-Console-does-not-work/td-p/949856 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb31b52d-620b-86e5-d5db-9bcd4e000c7c
* Version Independent ID: 9aa88650-6387-f2da-9af9-66946aaae893
* Content: [HttpListener.EndGetContext(IAsyncResult) Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.endgetcontext?view=netframework-4.7.2)
* Content Source: [xml/System.Net/HttpListener.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/HttpListener.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
Good catch. We could copy the text from here: https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.getcontext?view=netframework-4.7.2#exceptions
Do you want to put up a PR?

**Comment by immitev** [comment]
Copying this text would probably be good enough for a start. Being more specific about what exact kinds of `HttpListenerException` can be expected here would probably require non-trivial analysis...

P.S. I'll pass on a PR, as I have limited experience with `HttpListener`. Please take it wherever you think it's best.

**Comment by karelz** [comment]
Documenting specific kinds of `HttpListenerException` is not the point of the docs. If something goes wrong, it will be thrown.
Capturing type of the exceptions that can be thrown is key.

We should just copy the text I linked. Any takers?
