### ISSUE TITLE
XSLT 2.0

### ISSUE THREAD

**Issue by echuck66** [dotnet/dotnet-api-docs#1453]
How old is this information and will MS ever support XSLT 2.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110eff9c-c6c4-088b-aeef-c3af6612351a
* Version Independent ID: fe0fa56a-2817-da58-3584-afc4e5eaadfb
* Content: [XslCompiledTransform Class (System.Xml.Xsl)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xsl.xslcompiledtransform?view=netframework-4.7.2)
* Content Source: [xml/System.Xml.Xsl/XslCompiledTransform.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Xsl/XslCompiledTransform.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by echuck66** [comment]
Until MS integrates XSLT 2.0 into .NET, I guess we'll have to continue depending on third-party products like Saxon.

**Comment by mairaw** [comment]
I believe this is still the current status. See here for a related discussion on this:
https://github.com/dotnet/corefx/issues/2295

Tagging @buyaa-n and @krwq in case they have anything to add about XSLT 2.0 support in .NET.
