### ISSUE TITLE
Originaltext nicht mehr erreichbar

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#1460]
@mwardermann commented on [Fri Dec 21 2018](https://github.com/dotnet/dotnet-api-docs.de-de/issues/11)

In der Dokumentation konnte ich keine Möglichkeit mehr finden,  zum englischen Originaltext zu gelangen.
Die deutsche Übersetzung ist meistens nicht adäquat.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 50675e29-d746-a726-838c-7db75d089995
* Version Independent ID: bfdbf4fc-f2df-f2dc-b4ab-f46d8008830c
* Content: [Thread.CurrentCulture Property (System.Threading)](https://docs.microsoft.com/de-de/dotnet/api/system.threading.thread.currentculture?view=netframework-4.7.2)
* Content Source: [xml/System.Threading/Thread.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Threading/Thread.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
the "Read in English" button is not working in German and other locales (like French)
![imagen](https://user-images.githubusercontent.com/26746247/50348426-73669480-0517-11e9-871b-a4ad7b3f4035.png)
![imagen](https://user-images.githubusercontent.com/26746247/50348458-8e390900-0517-11e9-9e7c-485706765b03.png)

**Comment by mairaw** [comment]
This is not something we can fix in our repo @CeciAc since this is a loc functionality. Adding @JasonCard.

**Comment by JasonCard** [comment]
@mairaw @CeciAc Opened [Loc Issue 57701](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/57701) to escalate this issue.

**Comment by JasonCard** [comment]
@CeciAc @mairaw This issue no longer repro, so please close this GitHub issue.
