### ISSUE TITLE
Recommended alternate to Environment.Version answers the wrong question.

### ISSUE THREAD

**Issue by JesseChisholm** [dotnet/dotnet-api-docs#1461]
`Environment.Version` answers the question of "What framework am I using at run-time?"
The recommendation of checking the Registry only answers this question if there is only ONE framework installed.

If you don't want us to use `Environment.Version` at run-time, then offer an alternative that answers the _same_ question, not a relatively unrelated question.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e0e3ad9-1156-9897-ba9a-f0d1524ecdbb
* Version Independent ID: 994b2fe0-e717-2af5-a650-d6a9e6bb22b9
* Content: [Environment.Version Property (System)](https://docs.microsoft.com/en-us/dotnet/api/system.environment.version?view=netframework-4.7.2)
* Content Source: [xml/System/Environment.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Environment.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@karelz who can help with this question about System.Environment.Version? Is there anything we should add since I see this is also supported on .NET Core.

**Comment by karelz** [comment]
Yeah, this is not ideal state, but sadly that is where we are. I would recommend to take the discussion to CoreFX repo -- e.g. https://github.com/dotnet/corefx/issues/31099
cc @terrajobst
