### ISSUE TITLE
Where's the documentation for Lazy<T>(T) constructor?

### ISSUE THREAD

**Issue by andre-ss6** [dotnet/dotnet-api-docs#1462]
What does that constructor do? I don't understand it, since, if I need to pass an instance to it, won't the value be eagerly initialized?

And by the way, why is .Net Core documentation so bad? A LOT of types and members are missing documentation entirely.

.Net Core is awesome, but cmon. Does getting better performance and modularity lead to worse documentation (and tooling) somehow and I didn't know?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da884373-c4d9-3bb8-121f-df2f9a31fe7d
* Version Independent ID: f9aaab98-a493-9ead-4c97-32c967d6879d
* Content: [Lazy&lt;T&gt; Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1?view=netcore-2.2#remarks)
* Content Source: [xml/System/Lazy`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Lazy`1.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
You mean this one right @andre-ss6?
https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1.-ctor?view=netcore-2.2#System_Lazy_1__ctor__0_

We've been adding docs for the new .NET Core APIs but we have to prioritize it along with new articles, doc bugs, etc.

Obrigada pelo feedback!

**Comment by andre-ss6** [comment]
Well, your link leads to a page with all the constructors. The one I'm talking about is the `Lazy<T>(T)` one. It's the only one missing documentation.

And no problem :)

**Comment by mairaw** [comment]
Yeah, I meant to link to https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1.-ctor?view=netcore-2.2#System_Lazy_1__ctor__0_ instead. Sorry about that!

**Comment by pkulikov** [comment]
@andre-ss6 somehow the last underscore in the link text provided by @mairaw was not included into the link. 

That is the link: <https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1.-ctor?view=netcore-2.2#System_Lazy_1__ctor__0_>

@mairaw I used the following way to insert the link:
```
<https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1.-ctor?view=netcore-2.2#System_Lazy_1__ctor__0_>
```

**Comment by mairaw** [comment]
Oh interesting! I haven't noticed that it was GitHub that was eating my underscore 😄

**Comment by andre-ss6** [comment]
Well, thanks for the updated documentation, but I still don't understand why this constructor even exists. Could be explained a little better in the remarks. How is it _lazy_ initialization if it's _pre_initialized?
