### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tdworshak** [dotnet/dotnet-api-docs#1463]
The documentation for the overload that takes seven arguments incorrectly states "Combines six values into a hash code.".  It should state "Combines seven values into a hash code."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38e24cd-3568-ee10-e18c-6262faeeb5bb
* Version Independent ID: 4b23ab47-87c7-32b1-a0ca-9c13d5ec93e5
* Content: [HashCode.Combine Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.hashcode.combine?view=netcore-2.2#System_HashCode_Combine__2___0___1_)
* Content Source: [xml/System/HashCode.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/HashCode.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by NextTurn** [comment]
Fixed in #1485

**Comment by mairaw** [comment]
Thanks for the fix @ErikHsu and for letting me know the issue was fixed @NextTurn. Closing this one then.
