### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#1484]
Related to dotnet/docs#9735 

https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.Design/ViewTechnology.xml Line 38, Line 48
http://windowsforms.net/articles/shapedesigner.aspx

**Comment by mairaw** [comment]
Thanks @NextTurn. Opened https://github.com/dotnet/dotnet-api-docs/pull/1564 to remove these.
