### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by yotwerde** [dotnet/dotnet-api-docs#1496]
In the function `static void Deserialize()` the catch statement reads:
`catch (SerializationException e)`
As it is deserializing, shouldn't it write `catch (DeserializationException e)`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b820352-5a1b-0626-33c7-2927d9371621
* Version Independent ID: f0e9fd70-9ef8-1f10-bb98-d52e66ef2930
* Content: [BinaryFormatter Class (System.Runtime.Serialization.Formatters.Binary)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.Serialization.Formatters.Binary/BinaryFormatter.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.Serialization.Formatters.Binary/BinaryFormatter.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **sethm**

**Comment by mairaw** [comment]
Hi @yotwerde. No, that's actually correct. The exception thrown by the Deserialize method is the SerializationException as you can see here:
https://referencesource.microsoft.com/#mscorlib/system/runtime/serialization/formatters/binary/binaryformatter.cs,127
