### ISSUE TITLE
Does it apply to private members as well?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/dotnet-api-docs#1502]
Hi,

Please state in the documentation whether this attribute can apply to members with a `private` access modifier as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 201b1530-0b96-73aa-1cc4-522228018974
* Version Independent ID: 2b6787c4-31d0-0fa4-6ea0-6db290964b27
* Content: [InternalsVisibleToAttribute Class (System.Runtime.CompilerServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.CompilerServices/InternalsVisibleToAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.CompilerServices/InternalsVisibleToAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
No, they're not visible, @weitzhandler. The `InternalsVisibleAttribute` makes types and members with an C# `internal` or VB `friend` access modifier, which ordinarily makes them visible throughout the assembly in which they are defined, visible to another assembly as well.
 
I think that the documentation is sufficiently clear, so I'll close this issue. If you feel that the documentation can be made clearer, we'd welcome your pull request. For details on submitting a PR, see the [Contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md#process-for-contributing).

**Comment by weitzhandler** [comment]
@rpetrusha See #1526.
