### ISSUE TITLE
Add default value

### ISSUE THREAD

**Issue by danpetitt** [dotnet/dotnet-api-docs#1512]
Would be good to have a link to the source code on GitHub; i specifically want to find out what the default buffer size is but a) this doc doesnt say, which it should do and b) its going to be fun to find the source to find out

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29d94a8d-341c-5f29-7640-704144f60b69
* Version Independent ID: bb63691f-ecc3-0e26-3297-32b6e329d06a
* Content: [File.Create Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.create?view=netcore-2.2)
* Content Source: [xml/System.IO/File.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/File.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
.NET Framework source can be found at <https://referencesource.microsoft.com>. .NET Core source can be found at <https://source.dot.net>. In both cases, the default buffer size is 4,096 bytes. 
Would you like to open a pull request to update the documentation, @danpetitt.
