### ISSUE TITLE
Typo into example code

### ISSUE THREAD

**Issue by chinmay-trivedi** [dotnet/dotnet-api-docs#1521]
There is a typo into below snippet for List<T>.Add(T) Method c# example. There is an extra parenthesis ')' added by mistake into line in bold.

   // Check the list for part #1734. This calls the IEquitable.Equals method
        // of the Part class, which checks the PartId for equality.
        Console.WriteLine("\nContains(\"1734\"): {0}",
        **parts.Contains(new Part {PartId=1734, PartName="" }));**

It should be  **parts.Contains(new Part {PartId=1734, PartName="" });**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c63e75d4-791e-bf8b-e285-3be0517072ea
* Version Independent ID: 71e0e163-80bb-df9a-d039-4d3d968a37a6
* Content: [List&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netframework-4.7.2#examples)
* Content Source: [xml/System.Collections.Generic/List`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/List`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
The code is correct, @chinmay-trivedi. The `parts.Contains` line is a continuation of the previous line, which calls a Console.WriteLine method call. So there's one closing paren for the parts.Contains method call, and the second for the Console.WriteLine method call. 
I'll close this issue.
