### ISSUE TITLE
"The first subitem in the ListViewItem.ListViewSubItemCollection is always the item that owns the subitems."

### ISSUE THREAD

**Issue by Protiguous** [dotnet/dotnet-api-docs#1522]
Who in the hell designed this behavior? It is horrible!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058770d7-7a56-15d6-4d8f-aead21a19de2
* Version Independent ID: 65054ea6-08fa-cf72-b5a3-8ccf1d54f621
* Content: [ListViewItem.SubItems Property (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listviewitem.subitems?redirectedfrom=MSDN&view=netframework-4.7.2#System_Windows_Forms_ListViewItem_SubItems)
* Content Source: [xml/System.Windows.Forms/ListViewItem.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ListViewItem.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This repo is for feedback about the documentation. You can use the product feedback button or head to the https://github.com/dotnet/winforms repo to provide product feedback. It helps if you provide more information on what you'd like to see different than the current behavior. For this reason, I'm closing this.
