### ISSUE TITLE
Default parameters undocumented

### ISSUE THREAD

**Issue by nxtn** [dotnet/dotnet-api-docs#1529]
Some methods have different overloads with extended parameters.

For example
```csharp
public Task<HttpResponseMessage> GetAsync(string requestUri);
public Task<HttpResponseMessage> GetAsync(string requestUri, HttpCompletionOption completionOption);
```

If `completionOption` is unspecified, I have to go to the source codes to find the default value.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L20

I hope the docs could cover these.

**Comment by NextTurn** [comment]
Could you provide a sample article with such "default parameter" documented?

**Comment by NextTurn** [comment]
@mairaw

**Comment by mairaw** [comment]
Thanks @NextTurn. I provided a few examples on issue #3360. I feel like this would be similar to the constructor example, where the parameter here is not passed to that overload, so that info would be added to the remarks.
