### ISSUE TITLE
two words merged

### ISSUE THREAD

**Issue by toddpmain** [dotnet/dotnet-api-docs#1532]
The sentence "Most Collection<T> **objectscan** be modified" should read "Most Collection<T> **objects can** be modified". (Bold added by me for emphasis).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b2b685-7092-61f6-ce5e-0c4abc2e78c2
* Version Independent ID: 85bb1ef6-d230-5a1c-e2a7-2f2b2f4a636f
* Content: [Collection&lt;T&gt; Class (System.Collections.ObjectModel)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.ObjectModel/Collection`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.ObjectModel/Collection`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for the feedback @toddpmain and @mikkelbu for creating a PR to fix this!

Whenever you find issues that you know how to fix it, you can also just suggest a change:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
