### ISSUE TITLE
Suggestion / correction of description

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/dotnet-api-docs#1536]
Suggestion, or maybe correction:
Replace "Gets a specified DataRow using the PrimaryKey index"
By "Gets a DataRow using the specified PrimaryKey index"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed930cf-5705-0c3f-d661-3fd46b74b1fb
* Version Independent ID: bdb63167-34d6-6c7f-d19b-080a02a5994c
* Content: [DataRowCollection.Find Method (System.Data)](https://docs.microsoft.com/en-us/dotnet/api/system.data.datarowcollection.find?view=netframework-4.7.2)
* Content Source: [xml/System.Data/DataRowCollection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data/DataRowCollection.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks @MarcioAB for your feedback. I agree with your suggestion. Would you like to submit a fix?

You can find instructions here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

Here's the line where you'd make the change:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data/DataRowCollection.xml#L485

**Comment by MarcioAB** [comment]
Fix submited, process understood & thank you.

Regards
Marcio

**Comment by mairaw** [comment]
I was not finding your PR, so I took the liberty of creating the PR (#1999) from the changes I saw on your fork. I saw you had other branches there too but I didn't create a PR for those.

You can easily submit those if you want by clicking on the New pull Request button for the desired branch:
![image](https://user-images.githubusercontent.com/12971179/53924415-d5bc3500-4030-11e9-8b1d-3a5f9b99b032.png)
