### ISSUE TITLE
Clear documentation of System.Json classes  is missing.

### ISSUE THREAD

**Issue by jovabel** [dotnet/dotnet-api-docs#1543]
The classes in System.Json need API documentation. No example code suplied. And methods lack complete disciption texts (e.g. JsonValue.Parse). Please add clear documentation with example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 184fa0e3-3494-818f-5dcb-15ff39b030d7
* Version Independent ID: 7cfe8069-ef9b-9ece-77a7-d9a6fc823c69
* Content: [JsonValue.Parse(String) Method (System.Json)](https://docs.microsoft.com/en-us/dotnet/api/system.json.jsonvalue.parse?view=dotnet-plat-ext-2.1)
* Content Source: [xml/System.Json/JsonValue.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Json/JsonValue.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @jovabel. We haven't finished documenting the new APIs for Core and the Platform extensions. @karelz @ahsonkhan who owns these APIs under system.json?

**Comment by karelz** [comment]
These are ancient APIs which we are slowly replacing with other. We do not have any specific experts on them for years AFAIK.
While I agree it would be great to have the APIs documented, I think this is lower priority than other doc gaps.

**Comment by mairaw** [comment]
I agree they're lower priority given it's not on .NET Core. But this API seems kind of new, no?

**Comment by ahsonkhan** [comment]
>  But this API seems kind of new, no?

No, this namespace is quite old (as part of Silverlight): https://apisof.net/catalog/System.Json

From the initial PR: https://github.com/dotnet/corefx/pull/9897

> System.Json.dll is part of Silverlight and doesn't ship in the .NET Framework, nor do we encourage its usage. But, it's available and used with Mono, and in order to enable compatibility between Mono and .NET Core, we're adding it as an available assembly.

cc @stephentoub

**Comment by karelz** [comment]
Yep, I got that info from @stephentoub but didn't get time to reply here in time :)

**Comment by mairaw** [comment]
Thank you @ahsonkhan and @karelz!

**Comment by jovabel** [comment]
If I understand correctly, System.Json will be deprecated? 

And for updates wait for .net core 3.0?
(see https://github.com/dotnet/announcements/issues/90)

**Comment by jovabel** [comment]
No new activity on the issue. Thanks for the feedback everybody.

**Comment by ahsonkhan** [comment]
> And for updates wait for .net core 3.0?

To clarify, the APIs coming in .net core 3.0 and what you are probably looking for are in the System.Text.Json namespace:
https://docs.microsoft.com/en-us/dotnet/api/system.text.json?view=netcore-3.0
