### ISSUE TITLE
Working with Entity Keys link is broken

### ISSUE THREAD

**Issue by MNF** [dotnet/dotnet-api-docs#1545]
Working with Entity Keys link https://msdn.microsoft.com/library/fe3f4206-d277-43a1-a72f-4e86fdf12b9f opens https://docs.microsoft.com/en-us/previous-versions/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9690b3e1-bcb0-7a3e-7bc6-54cb9144b886
* Version Independent ID: 96626540-8b76-27fe-c907-52a48a22d871
* Content: [MergeOption Enum (System.Data.Objects)](https://docs.microsoft.com/en-us/dotnet/api/system.data.objects.mergeoption?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Data.Objects/MergeOption.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Objects/MergeOption.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks for your feedback @MNF. I've created PR #1547 to make that link go to a better place.

**Comment by MNF** [comment]
Are all https://msdn.microsoft.com/library/ links broken and you have to manually re-map them?
There are millions of links on different sites referring to msdn library.
According to 
https://docs.microsoft.com/en-us/teamblog/dotnet-api-docs-migration

> we wanted to ensure that no links are broken - all those MSDN links that might be integrated in products, blog posts and other sites should work properly and point users to the new location

**Comment by mairaw** [comment]
@MNF no, not all links. But we're finding a couple where they decided to just redirect them to https://docs.microsoft.com/en-us/previous-versions/ and from there you could search for the topic you wanted. I've asked for a report where we could find out which ones are doing this in our content, so we can find better targets for those proactively.

**Comment by MNF** [comment]
@mairaw
From what I see starting from this year, all Msdn library links are broken. 

Fixing your content is good, but there are much more links from external content. Could you from redirect (iis) logs get a list of msdn library links that were redirected to https://docs.microsoft.com/en-us/previous-versions/ and map all of them. 

E.g. I was reading old, but detailed answer 
https://social.msdn.microsoft.com/Forums/en-US/fdc5c7ac-dcf8-45a8-ab11-2ffbc338b0e5/entity-framework-4-poco-without-selftracking-proxies-detect-changes-wcf-with-aspnet-web-forms?forum=adodotnetentityframework
 

> I would just follow this walkthrough: http://msdn.microsoft.com/en-us/library/ee789839.aspx.
> 
> Besides, it looks like I wouldn't be able to store the self-tracking entity it in Session or ViewState anyway. According to the following article, "serialization to ASP.NET state management objects is not supported" (at the bottom of the article): http://msdn.microsoft.com/en-us/library/ff407090.aspx

 I needed to view the actual articles and  redirecting  to https://docs.microsoft.com/en-us/previous-versions/ is confusing and disruptive. I don’t know which exactly topics to search, the author  specified  the topic by URL, not the name.

You mentioned “they decided”. Does it mean, that the issue should be fixed by the different Microsoft department?

**Comment by mairaw** [comment]
I'll take this to the engineering team again. I think they made a decision to drop some URLs when the content was no longer on the TOC (and that's the team I meant with "they decided"). However, in some cases, a better redirection would be to go to the previous version: e.g. http://msdn.microsoft.com/en-us/library/ee789839(vs.100).aspx has a better target.

Also, if you wanna raise this issue with them as well, file a new issue at https://github.com/microsoftdocs/feedback.

But for now, what I have total control over is to update our content to use better links when we encounter those.

**Comment by mairaw** [comment]
Just to follow up on this issue @MNF. I talked to our engineering team and we revisited a couple of the redirects that were going to the previous-versions homepage and now you should see this problem less at least. But please keep us posted if you find any other links like that and we'll continue to revisit.
