### ISSUE TITLE
SocketsHttpHandler class and its members need to be documented

### ISSUE THREAD

**Issue by mairaw** [dotnet/dotnet-api-docs#1551]
PR #1546 took care of one of the members of this class, but this entire class and its members need some basic descriptions.

/cc @davidsh @caesar1995 @dotnet/ncl 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42d1b2c9-0d2d-32f1-d507-d8b5ecd2e9a3
* Version Independent ID: 075a1ce0-0cdf-8084-52ef-30249a42f6c2
* Content: [SocketsHttpHandler Class (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-2.1)
* Content Source: [xml/System.Net.Http/SocketsHttpHandler.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by loic-sharma** [comment]
Also, should [the remarks on `HttpMessageHandler`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessagehandler?view=netcore-3.0) be updated to mention `SocketsHttpHandler`?

**Comment by davidsh** [comment]
>Also, should the remarks on HttpMessageHandler be updated to mention SocketsHttpHandler?

Yes. That could be part of implementing this issue.
