### ISSUE TITLE
Mismatch between property name and description

### ISSUE THREAD

**Issue by gris-martin** [dotnet/dotnet-api-docs#1556]
The property value description defines the property as:
&gt; true if the UdpClient allows datagram fragmentation; otherwise, false. The default is true.

but that doesn't make sense considering the name of the property (`DontFragment`). A `true` value should mean that you **don't** fragment, and a `false` that you do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d42785-ae0e-c52d-cfba-27a2f433290c
* Version Independent ID: 32567fb7-1eca-bbb9-3f04-e6e6de473949
* Content: [UdpClient.DontFragment Property (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.dontfragment?view=netframework-4.7.2#System_Net_Sockets_UdpClient_DontFragment)
* Content Source: [xml/System.Net.Sockets/UdpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/UdpClient.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by paul70078** [comment]
Same for the  [Socket.DontFragment Property](https://docs.microsoft.com/en-US/dotnet/api/system.net.sockets.socket.dontfragment?view=netframework-4.8)

**Comment by samsp-msft** [comment]
@davidsh & @stephentoub  - can you clarify? Winsock docs are also somewhat evasive. https://docs.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options

**Comment by stephentoub** [comment]
It looks wrong to me, but @davidsh should confirm.
