### ISSUE TITLE
Out of range Exception

### ISSUE THREAD

**Issue by kiranmahale7** [dotnet/dotnet-api-docs#1567]
I get out of range error for some addresses even though they are valid address point.

example: 
Longitude: -97.386000, Latitude: 37.707050
Address: 6 S.GILMORE CIRLCE, MARGATE, NJ, 08402

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f6bd85-e689-5a08-0a65-bb0016c2123d
* Version Independent ID: ef2d07af-a7b9-e4c6-f18d-066c2dd7af99
* Content: [GeoCoordinate.Latitude Property (System.Device.Location)](https://docs.microsoft.com/en-us/dotnet/api/system.device.location.geocoordinate.latitude?view=netframework-4.7.2#System_Device_Location_GeoCoordinate_Latitude)
* Content Source: [xml/System.Device.Location/GeoCoordinate.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Device.Location/GeoCoordinate.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Hi @kiranmahale7! This repository is for feedback about the content and this seems to be a product issue. On the content, you'll find a button for product feedback on the bottom where you can report this sort of issues.
