### ISSUE TITLE
Change Font

### ISSUE THREAD

**Issue by deisterhold** [dotnet/dotnet-api-docs#1573]
[Enter feedback here]
It would be helpful if the font used for documentation was different so that uppercase i and lowercase L do not look the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bcb08bd-323a-cd5e-0d38-5485bd0f0a1a
* Version Independent ID: 9c0c4aec-a30b-c381-d096-9d9c613ec227
* Content: [UriIdnScope Enum (System)](https://docs.microsoft.com/en-us/dotnet/api/system.uriidnscope?view=netframework-4.7.2)
* Content Source: [xml/System/UriIdnScope.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/UriIdnScope.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @deisterhold. Given this comment is about the site UX and not the content itself, I moved it https://github.com/MicrosoftDocs/feedback/issues/1037. Thanks!

**Comment by deisterhold** [comment]
@mairaw Ok, thanks.
