### ISSUE TITLE
Typo - 'rest' should be 'test'

### ISSUE THREAD

**Issue by nickproud** [dotnet/dotnet-api-docs#1600]
In the remarks section you have a sentence that reads:
'As a result, your rest for null is never evaluated.'
I believe you meant to say:
'As a result, your test for null is never evaluated.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e18484b3-7dbb-28f1-4196-2985acc5586b
* Version Independent ID: eac8f147-92d6-658d-0680-995343aa0129
* Content: [NullReferenceException Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.nullreferenceexception?view=netframework-4.7.2)
* Content Source: [xml/System/NullReferenceException.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/NullReferenceException.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing out the typo, @nickproud. We've opened #1609 to fix it.
