### ISSUE TITLE
Typo in method description

### ISSUE THREAD

**Issue by tsahi** [dotnet/dotnet-api-docs#1630]
should be:

"Returns an instance of the [Authorization](https://docs.microsoft.com/en-us/dotnet/api/system.net.authorization?view=netframework-4.7.2) class in respo**n**se to an authentication challenge from a server."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f9ceeb-fcf3-a0c8-22ed-b67786a1d226
* Version Independent ID: 754643b6-fb35-c360-1bc6-fa4acb65a519
* Content: [IAuthenticationModule.Authenticate(String, WebRequest, ICredentials) Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.iauthenticationmodule.authenticate?redirectedfrom=MSDN&view=netframework-4.7.2#System_Net_IAuthenticationModule_Authenticate_System_String_System_Net_WebRequest_System_Net_ICredentials_)
* Content Source: [xml/System.Net/IAuthenticationModule.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/IAuthenticationModule.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by tsahi** [comment]
i.e. there is a missing "n" in "response".

**Comment by karelz** [comment]
@tsahi do you want to submit a PR? Should be fairly simple IMO ;)

**Comment by tsahi** [comment]
When I submitted PRs on API documentation like this in the past, they were rejected, because the XML is extracted from code comments. Is this different?

**Comment by karelz** [comment]
Correct, all CoreFX was one-time imported and lies in MD files only now - just hit the Edit button and you can make the change easily :).
If it was in source code, we would ask you to change it there ;)
