### ISSUE TITLE
Better than the info in VS

### ISSUE THREAD

**Issue by LambertWM** [dotnet/dotnet-api-docs#1646]
Not sure if this is the right place for this feedback: the above documentation ("IsCompleted will return true when the task is in one of the three final states: RanToCompletion, Faulted, or Canceled.") is MUCH better than the info ('from metadata') which you get when you press F12 in Visual Studio on the IsCompleted property, which reads "true if the task has completed; otherwise false."  (which is unclear about Cancellation)
So the feedback is: can you improve the info which you get when you press F12 in Visual Studio on the IsCompleted property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3ce93db-d764-6a30-f10e-2c915b21f91b
* Version Independent ID: 31b93ed4-2574-06fc-72c1-b4bcf9a8e2c1
* Content: [Task.IsCompleted Property (System.Threading.Tasks)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.iscompleted?view=netframework-4.7.2)
* Content Source: [xml/System.Threading.Tasks/Task.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading.Tasks/Task.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @LambertWM. Typically, I believe Visual Studio doesn't have the remarks information that we have in the online docs. But we could move that info from the remarks into the property value.
