### ISSUE TITLE
This page needs a link to the definition of DataGridSortingEventHandler

### ISSUE THREAD

**Issue by Jazzman123** [dotnet/dotnet-api-docs#1647]
This page needs a link to the definition of DataGridSortingEventHandler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182f16eb-767e-b8f5-c021-8ebc9ee22dc7
* Version Independent ID: 396acd8e-0d11-3cdb-cdc3-6b8a4083f2d5
* Content: [DataGrid.Sorting Event (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datagrid.sorting?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls/DataGrid.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/DataGrid.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @Jazzman123. I've moved this to https://github.com/MicrosoftDocs/feedback/issues/1071, to see if our engineering team can automatically display that information for all event api docs.
