### ISSUE TITLE
This example doesn't work.

### ISSUE THREAD

**Issue by LJ9999** [dotnet/dotnet-api-docs#1650]
In the example below, modified for prototyping usage in the real world, t will be null.

			Assembly assem = typeof(Test).Assembly;

			Assembly asm = Assembly.ReflectionOnlyLoad(assem.GetName().Name);
			Type t = asm.GetType("Test");
			MethodInfo m = t.GetMethod("TestMethod");
			ParameterInfo[] p = m.GetParameters();

The modification was made because I have no clue EXACTLY what the hell "Source" is and had to guess.

If the guess is wrong, the example is still horsesh!t because, once again, the crappy teachers writing this crap assume we know what they know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b1241ee-69a1-3bdb-2d1c-28c68a358f23
* Version Independent ID: 91067e2f-bedb-54f1-0db6-b67e0cd33025
* Content: [CustomAttributeData Class (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.customattributedata?view=netframework-4.7.2)
* Content Source: [xml/System.Reflection/CustomAttributeData.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/CustomAttributeData.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LJ9999** [comment]
I didn't know there was a code of conduct. I've been fighting Microsoft technologies for 30 years and this is the first time I was aware of such a thing. I guess people are reading the feedback. When did that start?

All I wanted was a moment of hopeless catharsis in a futile last gasp of dying effort to get something to work that is explained so poorly. If you wrote this doc then for sure you have every right to tell me to go to hell. I'm okay with that. I'm a fair man.

Now that I have read the code of conduct combined with the realization that someone reads the feedback (I'm still in shock) I will endeavor to express all future angst with a greater degree of measure.

**Comment by mikkelbu** [comment]
Hi @LJ9999. The [Assembly.GetType method](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.gettype?view=netframework-4.7.2#System_Reflection_Assembly_GetType_System_String_) expects the "full name of the type" meaning namespace and name, so your example will only work if the class `Test` is not inside a namespace. Otherwise, you should also supply the namespace. The following should work.

```csharp
using System;
using System.Reflection;

namespace TestReflection
{
    class Program
    {
        static void Main(string[] args)
        {
            Assembly assem = typeof(Program).Assembly;

            Assembly asm = Assembly.ReflectionOnlyLoad(assem.GetName().Name);
            Type t = asm.GetType("TestReflection.Program");
            MethodInfo m = t.GetMethod("TestMethod");
            ParameterInfo[] p = m.GetParameters();
...
        }

        public void TestMethod(string input) { }
    }
}
```

**Comment by bluecurveteam** [comment]
@LJ9999 in fact you don't know what you do...

**Comment by mairaw** [comment]
Thanks @mikkelbu for jumping in to help. @LJ9999 please let us know if that solves your issue. For now, I'm closing this.
