### ISSUE TITLE
A templated inherited class sample would be nice...

### ISSUE THREAD

**Issue by LJ9999** [dotnet/dotnet-api-docs#1654]
...really, really nice.

Otherwise, this doc is worthless. Like so many thousands of others without examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb5bcada-a4a4-c65b-5737-42a24199a6ab
* Version Independent ID: ca92a74a-498e-92b9-1894-25359aa179ee
* Content: [Stream Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?view=netframework-4.7.2)
* Content Source: [xml/System.IO/Stream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Stream.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by REscobar** [comment]
This one has examples, you should phrase your comments with a question, indicating exacly what are your expectations, that way your first response could probably be exactly what you are looking for.

What exactly are you looking for?
Is it about reading a binary file?
Is it about reading a text file?
Is it about reading an xml file?
Is it about reading from a network stream or named pipe?
Is it about reading a compressed stream from an ecrypted stream from a network stream?

Ask something specefic that you are looking for.

Like "I want to read a text file, but this doc doesn't explain how"

**Comment by mairaw** [comment]
I agree with @REscobar that we would need some info on what exactly you're looking for. I don't think we could show a templated inherited class either. But you could use the list of types under the derived list and see how they're actually implemented either at https://referencesource.microsoft.com or https://github.com/dotnet/corefx. 

Examples:
- System.IO.FileStream: https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,e23a38af5d11ddd3
- System.IO.MemoryStream: https://referencesource.microsoft.com/#mscorlib/system/io/memorystream.cs,1a4dcb744a23ba6f
- System.IO.Compression.GZipStream:
https://github.com/dotnet/corefx/blob/master/src/System.IO.Compression/src/System/IO/Compression/GZipStream.cs
