### ISSUE TITLE
Is this really completely correct? What is a ConsoleEment?

### ISSUE THREAD

**Issue by olastrom** [dotnet/dotnet-api-docs#1671]
// Access a configuration file using mapping.
// This function uses the OpenMappedExeConfiguration 
// method to access a new configuration file.   
// It also gets the custom ConsoleSection and 
// sets its ConsoleEment BackgroundColor and
// ForegroundColor properties to green and red
// respectively. Then it uses these properties to
// set the console colors.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fad210cc-b265-3203-cac5-1f0ebd9cff5d
* Version Independent ID: 43382992-6e73-b637-4faf-231cced3c6d8
* Content: [ConfigurationManager.OpenMappedExeConfiguration Method (System.Configuration)](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationmanager.openmappedexeconfiguration?view=netframework-4.7.2)
* Content Source: [xml/System.Configuration/ConfigurationManager.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Configuration/ConfigurationManager.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @olastrom. @MSDN-WhiteKnight has fixed that today.
