### ISSUE TITLE
The ConvertTimeToUtc(DateTime) example contains a typo

### ISSUE THREAD

**Issue by COwusuYianoma** [dotnet/dotnet-api-docs#1693]
The sample output shown for the third conversion in the ConvertTimeToUtc(DateTime) example should show the year 2006, not 2007.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35567f59-828d-8be6-d4aa-6071fdbafdf2
* Version Independent ID: ac48a392-9451-8677-d833-5ff1c735f7f6
* Content: [TimeZoneInfo.ConvertTimeToUtc Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.converttimetoutc?view=netframework-4.7.2#System_TimeZoneInfo_ConvertTimeToUtc_System_DateTime_)
* Content Source: [xml/System/TimeZoneInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/TimeZoneInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @COwusuYianoma. It seems that the example was meant to use 2007 by checking the VB version as well.

Would you like to submit a fix for this? The code is located here:
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR_System/system.TimeZone2.Conversions/cs/System.TimeZone2.Conversions.cs
