### ISSUE TITLE
Why modes named publication and execution?

### ISSUE THREAD

**Issue by MNF** [dotnet/dotnet-api-docs#1696]
Please clarify in the article Why modes named publication and execution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0066a0-ae56-5847-3672-afd64f863a98
* Version Independent ID: 9066bcd1-49dc-8a8e-7f0e-a52d22b0455b
* Content: [LazyThreadSafetyMode Enum (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.lazythreadsafetymode?view=netframework-4.7.2)
* Content Source: [xml/System.Threading/LazyThreadSafetyMode.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/LazyThreadSafetyMode.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by kouvel** [comment]
Clarified in https://github.com/dotnet/dotnet-api-docs/pull/7137
