### ISSUE TITLE
Where is this mysterious namespace?

### ISSUE THREAD

**Issue by LJ9999** [dotnet/dotnet-api-docs#1706]
It is not listed in the Reference Manager. Why is this a mystery?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147c0168-adf5-a021-af33-263b865b6285
* Version Independent ID: 42e8e4b9-2fa8-9e5d-a21a-28e56ca0930c
* Content: [System.Data.Objects Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.data.objects?view=netframework-4.7.2)
* Content Source: [xml/ns-System.Data.Objects.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.Data.Objects.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
@LJ9999 we don't list the assembly name for namespaces bur for any API under it such as classes, methods, and properties. 

If you navigate down to the classes level, you'll see that you need to add a reference to System.Data.Entity.dll, which then contains this namespace.
