### ISSUE TITLE
Could not be found

### ISSUE THREAD

**Issue by TentoesTom** [dotnet/dotnet-api-docs#1715]
How 'bout on these how to docs, you let us know what "using" you have to add?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 199dedf0-bee2-c9f2-aea4-731717c51b7c
* Version Independent ID: 295d53e0-2780-12d1-7ebb-e4ab1b8d9b99
* Content: [InstalledFontCollection Class (System.Drawing.Text)](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.text.installedfontcollection?view=netframework-4.7.2)
* Content Source: [xml/System.Drawing.Text/InstalledFontCollection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Drawing.Text/InstalledFontCollection.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by TentoesTom** [comment]
Um.. I see it right there at the top where any normal person would expect to find it.

**Comment by mairaw** [comment]
Yes, the namespace information is up there at the top. For this reason, I'm closing this. If you're still having issues, make sure you're referencing the right assemblies as well. Let us know if this solves your problem.
