### ISSUE TITLE
System.​Runtime.​Loader.AssemblyLoadContext unloadability extensions

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/dotnet-api-docs#1717]
`AssemblyLoadContext` was extended with new APIs for .NET Core 3.0.  This shipped in preview1.  This included a new protected constructor and a new `Unload()` method to support unloadability.

**Comment by sdmaclea** [comment]
@mairaw @rpetrusha How do we start to document 3.0 APIs.  Is there a 3.0 branch?  Will the XML be automatically updated for 3.0?  When?

/cc @janvorli

**Comment by rpetrusha** [comment]
@sdmaclea, there is no 3.0 branch; when 3.0 APIs are added, it will be to the master branch. Right now, there are some issues with the reflection and integration of new APIs into the doc set. We're hoping those will be resolved within the next week so that the 3.0 APIs can be added.

**Comment by mairaw** [comment]
@sdmaclea @rpetrusha the content for 3.0 is finally merged to master. I'll work on pushing it live either today or tomorrow. You can add content to it already though: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.Loader/AssemblyLoadContext.xml. 

If you have /// comments to new 3.0 APIs, send me the xml file and I can load it to our docs.
