### ISSUE TITLE
Mono.Cecil.CustomAttributeArgument is shown as ConfigurationPropertyAttribute.DefaultValue

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/dotnet-api-docs#1725]
<https://docs.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.maxrequestlength?view=netframework-4.8> and many other reference topics are showing `Mono.Cecil.CustomAttributeArgument` instead of the actual value of `ConfigurationPropertyAttribute.DefaultValue`:

```C#
[System.Configuration.ConfigurationProperty("maxRequestLength", DefaultValue=Mono.Cecil.CustomAttributeArgument)]
[System.Configuration.IntegerValidator(MinValue=0)]
public int MaxRequestLength { get; set; }
```

It should be:

```C#
[System.Configuration.ConfigurationProperty("maxRequestLength", DefaultValue=4096)]
[System.Configuration.IntegerValidator(MinValue=0)]
public int MaxRequestLength { get; set; }
```

The error is in [HttpRuntimeSection.xml](https://github.com/dotnet/dotnet-api-docs/blob/cfccd1eea93e3a25975ba7c4d3c5508c43516a33/xml/System.Web.Configuration/HttpRuntimeSection.xml#L663), too.

However, `IntegerValidatorAttribute.MinValue` appears to be OK. Perhaps the difference is that the type of `ConfigurationPropertyAttribute.DefaultValue` is `object`.

**Comment by eiriktsarpalis** [comment]
@gewarren Presumably these are auto-generated, so is this a probable tooling bug?

**Comment by gewarren** [comment]
Thanks. I logged an internal issue here: https://dev.azure.com/ceapex/Engineering/_workitems/edit/382683

**Comment by gewarren** [comment]
This is fixed now.
