### ISSUE TITLE
IBufferWriter<T> documentation is missing 

### ISSUE THREAD

**Issue by JamesNK** [dotnet/dotnet-api-docs#1730]
There is no API documentation - https://docs.microsoft.com/en-us/dotnet/api/system.buffers.ibufferwriter-1

Many other APIs in System.Buffers are missing API documentation - https://docs.microsoft.com/en-us/dotnet/api/system.buffers

**Comment by mairaw** [comment]
Thanks @JamesNK. I've transferred the issue to the API docs repo. We're aware of this issue.

@ahsonkhan sent me the xml file containing the /// comments for System.Memory.xml and I'm planning to load that either this week or next week depending on how well our CI runs go loading other platforms we need to load like uwp, 3.0, etc.
