### ISSUE TITLE
The description for the System.Numerics namespace on the MS documentation is incorrect/displays incorrectly.

### ISSUE THREAD

**Issue by vreniose95** [dotnet/dotnet-api-docs#1753]
Hello - 

Minor issue, i noticed when look at the MS Documentation for the namespaces and their associated descriptions. The examples appear to not show up, or have yet to be added. I've attached a screenshot for reference.
Thanks!

![image](https://user-images.githubusercontent.com/31714540/52096270-f0137680-258b-11e9-93c9-0720decfd5a0.png)

**Comment by vreniose95** [comment]
@tannergooding - are you aware of a fix for this? Thanks in advance, man.

**Comment by mairaw** [comment]
Thank you for your feedback @vreniose95. This is a known issue with the API browser:
https://github.com/MicrosoftDocs/feedback/issues/637

The workaround for now is to click on the API to see the text that is being dropped.

/cc @dendeli-msft
