### ISSUE TITLE
OnWriterCompleted is incorrectly documented.

### ISSUE THREAD

**Issue by corytodd** [dotnet/dotnet-api-docs#1754]
This page states that OnWriterCompleted cancels a pending ReadAsync operation. That doesn't sound right and the source says we're just setting a callback. Is there more to this?

Implementation doesn't cancel anything:
https://github.com/dotnet/corefx/blob/d6678e9653defe3cdfff26b2ff62135b6b22c77f/src/System.IO.Pipelines/src/System/IO/Pipelines/Pipe.cs#L522

Add callback doesn't seem to have a "cancel" side effect:
https://github.com/dotnet/corefx/blob/d6678e9653defe3cdfff26b2ff62135b6b22c77f/src/System.IO.Pipelines/src/System/IO/Pipelines/PipeCompletion.cs#L43

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60f39cbb-1a9a-33e8-76ad-5b6f7a9923bf
* Version Independent ID: fa25d060-e3fa-56bb-94db-ea746090d551
* Content: [PipeReader.OnWriterCompleted(Action&lt;Exception,Object&gt;, Object) Method (System.IO.Pipelines)](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.onwritercompleted?view=dotnet-plat-ext-2.1)
* Content Source: [xml/System.IO.Pipelines/PipeReader.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Pipelines/PipeReader.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by carlossanlop** [comment]
@davidfowl @halter73 @jkotalik

**Comment by halter73** [comment]
> This page states that OnWriterCompleted cancels a pending ReadAsync operation. 

Are we talking about the [same page](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.onwritercompleted?view=dotnet-plat-ext-2.1)?  I'm not seeing that. That looks like the description of CancelPendingRead which [looks accurate.](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.cancelpendingread?view=dotnet-plat-ext-2.1)

**Comment by corytodd** [comment]
The docs have since been fixed. The issue was referencing the documentation [when it was in this state](https://github.com/dotnet/dotnet-api-docs/blob/a5d251bd2680a48e4bf8ae027e267602e4c6d139/xml/System.IO.Pipelines/PipeReader.xml#L163). The fixed version we now see was introduced [in this PR](https://github.com/dotnet/dotnet-api-docs/pull/2842/files).

The method is now obsolete but the docs are correct. So, we're all set.
