### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by redfireemeraldice2188** [dotnet/dotnet-api-docs#1766]
Husband had my gram work rewrote help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf196230-3596-fe89-b9fd-81793a94d597
* Version Independent ID: aafe2ef3-20b7-929a-699a-9e9e57819078
* Content: [MemberInfo._MemberInfo.GetIDsOfNames(Guid, IntPtr, UInt32, UInt32, IntPtr) Method (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.system-runtime-interopservices-_memberinfo-getidsofnames?view=netframework-4.7.2#System_Reflection_MemberInfo_System_Runtime_InteropServices__MemberInfo_GetIDsOfNames_System_Guid__System_IntPtr_System_UInt32_System_UInt32_System_IntPtr_)
* Content Source: [xml/System.Reflection/MemberInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/MemberInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by carlossanlop** [comment]
The request is not clear. Closing.
