### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Enngage** [dotnet/dotnet-api-docs#1769]
The link 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/locality' is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1d461a1-4d28-76a4-9faf-af0d051406d9
* Version Independent ID: ca7bc136-ea0d-2c46-dcf2-749ad47cd931
* Content: [ClaimTypes.Locality Property (System.IdentityModel.Claims)](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.claims.claimtypes.locality?view=netframework-4.7.2&viewFallbackFrom=netcore-2.2)
* Content Source: [xml/System.IdentityModel.Claims/ClaimTypes.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Claims/ClaimTypes.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @Enngage for your feedback. I'm locking that value to not be displayed as a link in that and some other topics.

See PR here: #2026
