### ISSUE TITLE
Switched descriptions

### ISSUE THREAD

**Issue by telmer6** [dotnet/dotnet-api-docs#1773]
Under the heading "SendAsync(String, Int32, Byte[], PingOptions, Object)", the descriptions for timeout and buffer are switched.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447faa70-263c-3542-5968-27c9a29e6f1f
* Version Independent ID: 753c3580-8a96-70c8-3fdc-6c203f8a6ef6
* Content: [Ping.SendAsync Method (System.Net.NetworkInformation)](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ping.sendasync?view=netframework-4.7.2#applies-to)
* Content Source: [xml/System.Net.NetworkInformation/Ping.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.NetworkInformation/Ping.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by samsp-msft** [comment]
Appears to be fixed. @BillWagner can you close?

**Comment by BillWagner** [comment]
closed based on @samsp-msft 's recommendation.
