### ISSUE TITLE
How to differentiate static methods from instance methods

### ISSUE THREAD

**Issue by slear** [dotnet/dotnet-api-docs#1787]
It seems that we have lost this information in the new docs. Process.Start(StartInfo) is static but it is really hard to understand this fact from the current documentation. In the previous msdn we had that "nice" icon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f838bcf-d93c-65a7-b629-e6027d267dbb
* Version Independent ID: 25676ecc-5687-b317-e275-4b79e96c69c1
* Content: [Process.Start Method (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.0#System_Diagnostics_Process_Start_System_Diagnostics_ProcessStartInfo_)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/Process.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @slear. I've transferred this issue to our engineering team to look at:
https://github.com/MicrosoftDocs/feedback/issues/1121
