### ISSUE TITLE
example is CanConvertFrom

### ISSUE THREAD

**Issue by jeubank12** [dotnet/dotnet-api-docs#1794]
should be CanConvertTo -- this makes it very unclear the correct logic to apply (i.e. should it really be typeof(TimeSpan)?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85fe470c-55d0-616e-71b4-bed363b6d23c
* Version Independent ID: 66cbdeee-3ca9-7f7c-9317-a0490ffa0eb9
* Content: [ConfigurationConverterBase.CanConvertTo(ITypeDescriptorContext, Type) Method (System.Configuration)](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configurationconverterbase.canconvertto?view=netframework-4.7.2)
* Content Source: [xml/System.Configuration/ConfigurationConverterBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Configuration/ConfigurationConverterBase.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @jeubank12. The example is actually using CanConvertTo but the descriptions on this page are all referring to CanConvertFrom. I'm adding this to our backlog to address this on a future sprint.
