### ISSUE TITLE
Add link to Documentation

### ISSUE THREAD

**Issue by codan-prices** [dotnet/dotnet-api-docs#1798]
Note references a different set of documentation to look up the error code. 
Would be useful to link to the Windows Sockets version 2 API error code documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 182691a1-f791-3730-8563-203fa84e18bf
* Version Independent ID: da89f69b-ae3d-f57a-36ee-82a5585f2d06
* Content: [Socket.Blocking Property (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.blocking?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/Socket.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/Socket.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Thanks for your feedback @codan-prices. I've opened PR #1956 to fix this.
