### ISSUE TITLE
Code sample does not show the expected value

### ISSUE THREAD

**Issue by RickyRoeslerMS** [dotnet/dotnet-api-docs#1815]
The code on this page sets up an example to test whether two Uri objects would be equal, but doesn't actual provide the expected result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1851606b-5699-1c0f-868d-e5381ee611c0
* Version Independent ID: 9f365b21-56b3-b1bd-a5e8-a3c7f05f37c6
* Content: [Uri.Equals(Object) Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.equals?view=netframework-4.7.2)
* Content Source: [xml/System/Uri.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Uri.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @RickyRoeslerMS. That would be a nice addition to the sample.

I'm adding this to our backlog and community contributor project.

Here's where you can find the snippet files, if you'd like to contribute to our docs:
https://github.com/dotnet/samples/blob/master/snippets/cpp/VS_Snippets_Remoting/NCLUriExamples/CPP/uriexamples.cpp#L70
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Remoting/NCLUriExamples/CS/uriexamples.cs#L68
https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_Remoting/NCLUriExamples/VB/uriexamples.vb#L65

**Comment by SeanKilleen** [comment]
I added these comments in dotnet/samples#794.
