### ISSUE TITLE
Uri is not derived from MarshalByRefObject

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/dotnet-api-docs#1831]
Uri is not derived from MarshalByRefObject as indicated by the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97955623-57f5-f557-7c5a-b5075b17f56e
* Version Independent ID: bd87f79c-646b-41ed-1345-57d2ae7d7ba1
* Content: [Uri Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=netframework-4.7.2)
* Content Source: [xml/System/Uri.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Uri.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @MarcioAB. I've moved this issue to https://github.com/MicrosoftDocs/feedback/issues/1159 for our engineering team to take a look.
