### ISSUE TITLE
Tradução para o inglês

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#1834]
@lucasnobredev commented on [Sat Feb 09 2019](https://github.com/dotnet/dotnet-api-docs.pt-br/issues/7)

Quando eu clico para ler o artigo em inglês, alguns títulos ainda estão em português.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 201b1530-0b96-73aa-1cc4-522228018974
* Version Independent ID: 2b6787c4-31d0-0fa4-6ea0-6db290964b27
* Content: [InternalsVisibleToAttribute Class (System.Runtime.CompilerServices)](https://docs.microsoft.com/pt-br/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.CompilerServices/InternalsVisibleToAttribute.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.Runtime.CompilerServices/InternalsVisibleToAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is reporting a technical error on this page with replicates in al localized versions.
When clicking on the "read in English" switch, some titles remain translated.

![imagen](https://user-images.githubusercontent.com/26746247/52582898-0b447880-2e0d-11e9-9a51-a19ac89bf6e7.png)

**Comment by mairaw** [comment]
@CeciAc @JasonCard this should go to the engineering team to look at https://github.com/microsoftdocs/feedback/issues. This is not something our team can fix with content. 

For this reason, I'm closing the issue here.

**Comment by JasonCard** [comment]
@CeciAc @mairaw We have opened [Bug 66249](https://ceapex.visualstudio.com/Engineering/_workitems/edit/66249) to follow up on this issue.
cc @bodhigautam
