### ISSUE TITLE
Just confusing document!

### ISSUE THREAD

**Issue by syazdian** [dotnet/dotnet-api-docs#1848]
Only one line was enough for me:
IPAddress myIP = IPAddress.Parse("192.168.1.2");
but I did not find anything about letting me know where can I type my IP address!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0b61d8-e78b-cce2-73cd-663e47233b5e
* Version Independent ID: b0c811b7-6458-d239-1176-b87366dd013d
* Content: [IPAddress Class (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Net/IPAddress.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/IPAddress.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by syazdian** [comment]
I complained about this document around 3 years ago.  The document was very poorly explained, but now it is very well explained. Thanks

**Comment by rzikm** [comment]
Thanks for getting back to us, I will close this now.
