### ISSUE TITLE
Confusing example

### ISSUE THREAD

**Issue by syazdian** [dotnet/dotnet-api-docs#1849]
Only one line was enough for me:
IPAddress myIP = IPAddress.Parse("192.168.1.2");
but I did not find anything about letting me know where can I set my IP address!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05621ce1-cd87-7e28-a0f1-c8843c093705
* Version Independent ID: 436cf640-62f6-ddb7-2e40-a96d0b5912fd
* Content: [IPAddress.Parse Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.parse?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Net/IPAddress.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/IPAddress.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
@syazdian I am not sure I understand your question - the API creates `IPAddress` object from `string`. How else would you like it to be set?

**Comment by mairaw** [comment]
Closing due to the lack of information. Please get back to us if you can answer our question and we can reopen this issue @syazdian.
