### ISSUE TITLE
IReadOnlyCollection integration in MS Help Viewer 2.3

### ISSUE THREAD

**Issue by Harry-von-Borstel** [dotnet/dotnet-api-docs#1859]
Hi,
The IReadOnlyCollection Interface is missing from the index of MS Help Viewer 2.3. Only the Count property can be found there, but in a bad form ("IReadOnlyCollection\u003cT\u003e.Count..."). The same problem exists with other interfaces.
  Cheers, Harry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58df67be-8ede-26c9-3c88-b8c6610bdf28
* Version Independent ID: f3eca3d3-dbb3-520b-9980-bda035bc6644
* Content: [IReadOnlyCollection&lt;T&gt; Interface (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlycollection-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/IReadOnlyCollection`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/IReadOnlyCollection`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @Harry-von-Borstel,

Can you make sure you're using the following book for .NET API reference?
![image](https://user-images.githubusercontent.com/12971179/52843406-d9eed580-30b6-11e9-8a34-a7a25074d6fe.png)

I just updated all my books and I can see that interface (with a few duplicate properties nodes but not the issue being reported here):
![image](https://user-images.githubusercontent.com/12971179/52843452-03a7fc80-30b7-11e9-8675-58bfbc00704b.png)

Thanks!

**Comment by mairaw** [comment]
Closing due to the lack of information.
