### ISSUE TITLE
Needs to be documented. 

### ISSUE THREAD

**Issue by arstorey** [dotnet/dotnet-api-docs#1868]
Telling me that a property is exactly what its name states tells me absolutely nothing useful.  What *IS* an "Inner Duplex Channel", and how does it differ from a plain old "Inner Channel"?  When should one be used or referenced instead of the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c694d795-5530-6a41-a1b3-bb9b693ab0f4
* Version Independent ID: e827aa51-fb86-ed35-3b32-ce8c5ffc16c4
* Content: [DuplexClientBase&lt;TChannel&gt;.InnerDuplexChannel Property (System.ServiceModel)](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.duplexclientbase-1.innerduplexchannel?view=netframework-4.7.2#System_ServiceModel_DuplexClientBase_1_InnerDuplexChannel)
* Content Source: [xml/System.ServiceModel/DuplexClientBase`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ServiceModel/DuplexClientBase`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@Lxiamail @zhenlan can you help with this feedback?

**Comment by Lxiamail** [comment]
@arstorey The InnerDuplexChannel Property (System.ServiceModel) actually returns the InnerChannel by simply cast it to IDuplexContextChannel.
