### ISSUE TITLE
List.Sort() example should have "Jody" Duplicated in the string[] array.

### ISSUE THREAD

**Issue by MightyPen** [dotnet/dotnet-api-docs#1875]
The duplication of "Jody" would add an informative aspect to the code example, showing that this .Sort() successfully handles duplicates.
On StackOverflow, lots of .NET programmers ask about options for something roughly like a SortedList that retains duplicates.
Issue #1874 also concerns this request for two "Jody" values.  Thanks.  (2019/02/17)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36bdb60d-fa8f-84c1-6d7d-e17b06096112
* Version Independent ID: 1dc86b79-6cc3-b1ed-dd07-99559381a82c
* Content: [List&lt;T&gt;.Sort Method (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.sort?view=netframework-4.7.2#System_Collections_Generic_List_1_Sort)
* Content Source: [xml/System.Collections.Generic/List`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/List`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Do we really need two issues? They seem similar @MightyPen.

**Comment by MightyPen** [comment]
We do not need two. Closing the other one immediately, as a duplicate, would be better than closing this one.
This Issue 1875 was the kind I meant to open, but I created the first Issue in the wrong way.
Thanks. GeneMi

**Comment by mairaw** [comment]
Ok, closed the other one. Adding this one to our backlog and community project.

The source files for the samples for those wanting to contribute are:
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR_System/system.collections.generic.list.sort/cs/Sort1.cs
https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_CLR_System/system.collections.generic.list.sort/vb/Sort1.vb

**Comment by mairaw** [comment]
Reopening until https://github.com/dotnet/samples/pull/802 gets merged
