### ISSUE TITLE
TextWriter API page has title with no content

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/dotnet-api-docs#1884]
This page has the title "Explicit Interface Implementations", and then no content underneath it.

https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter?view=netframework-4.7.2#explicit-interface-implementations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16535b85-e8ab-d4dd-ee48-899a95b9f916
* Version Independent ID: 59385b2d-0c2e-a39a-34bd-28ce28bd238a
* Content: [TextWriter Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter?view=netframework-4.7.2#explicit-interface-implementations)
* Content Source: [xml/System.IO/TextWriter.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/TextWriter.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
That's odd @ChrisMaddock. I usually see that behavior when one of the versions has APIs under (which is still a bug), but in this case I don't see any version that has an EII.

Would you mind opening an issue at https://github.com/MicrosoftDocs/feedback/issues instead? This issue needs to go to the engineering team.

**Comment by ChrisMaddock** [comment]
Done, thanks @mairaw :+1:
