### ISSUE TITLE
This example doesn't work

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#1885]
@Panchich commented on [Mon Feb 18 2019](https://github.com/dotnet/dotnet-api-docs.ru-ru/issues/12)

Something wrong with using, anytime I try to synthesize a speech, I get errors:

Error	CS0234	The type or namespace name 'Speech' does not exist in the namespace 'System' (are you missing an assembly reference?)	ConsoleApp1	
 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 64a3dcf5-80df-e999-4725-8b6c1a894dde
* Version Independent ID: 9b549a9a-9954-eed4-de64-581f629069fa
* Content: [SpeechSynthesizer Class (System.Speech.Synthesis)](https://docs.microsoft.com/ru-ru/dotnet/api/system.speech.synthesis.speechsynthesizer?view=netframework-4.8)
* Content Source: [xml/System.Speech.Synthesis/SpeechSynthesizer.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.Speech.Synthesis/SpeechSynthesizer.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
I'm moving this here since the user is reporting an error with the example
best

**Comment by Panchich** [comment]
Now I found out the decision - added reference to System.Speech into my project.

**Comment by mairaw** [comment]
I'm glad you sorted out the issue @Panchich. Closing this then.
