### ISSUE TITLE
.Net verions is not correct here.

### ISSUE THREAD

**Issue by cdytoby** [dotnet/dotnet-api-docs#1886]
[Enter feedback here]
It seems that in .net 3.5 or 2.0, there is only string.Join() with array, the other 2 version with Generic T doesn't exist in .net 3.5 or 2.0. Please make it clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed5c8a58-14e3-5eb0-3ea7-d93fb835e06d
* Version Independent ID: 468a7581-ffa1-018b-5cfe-0c9dbff87f21
* Content: [String.Join Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netframework-4.7.2#System_String_Join_System_String_System_Collections_Generic_IEnumerable_System_String__)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @cdytoby. We already have an issue tracking this request at https://github.com/MicrosoftDocs/feedback/issues/314.

For now, the best way to find out which ones are supported by a specific version is to change the version in the version selector. For example:
https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netframework-3.5#overloads
https://docs.microsoft.com/en-us/dotnet/api/system.string.join?view=netframework-4.0#overloads
