### ISSUE TITLE
Parameter "PropertyName" can be null

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/dotnet-api-docs#1888]
The code below works fine.

ListBox1.ItemsSource = new int[] { 1, 2, 3, 4 };
ListBox1.Items.SortDescriptions.Add(new SortDescription(null, ListSortDirection.Descending));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3edc7541-a9ba-9c6d-018b-aabefa22012c
* Version Independent ID: d5bcf907-6866-cffb-1c87-af37bd6ef468
* Content: [SortDescription(String, ListSortDirection) Constructor (System.ComponentModel)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.sortdescription.-ctor?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.ComponentModel.SortDescription.%2523ctor);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.2);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.ComponentModel/SortDescription.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel/SortDescription.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @MarcioAB. The documentation notes that the method throws an ArgumentNullException if `propertyName` is null and ArgumentException if `propertyName` is String.Empty. Neither is true. The only exception thrown by the method is the InvalidenumArgumentException.
Would you like to submit a PR to remove the two exceptions? Instructions are in the [contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).

**Comment by MarcioAB** [comment]
@rpetrusha just to clarify: From my side I identified this issue at the Documentation level. My initial idea was just to fix the Documentation, removing the information about that limitation and improving the Documentation about the usage of a null parameter. You went further and identified the issue at the API (or product) level. I'm not prepared to sustaim the issue at the API level or in other words submit a PR about API issue, but I can fix only the Documentation part. On the other side, fixing only the Documentation may hidden the API issue even more. But fix the Documentation is just a 10 minutes task and may have some value for other users. How do you like I proceed ?

**Comment by rpetrusha** [comment]
Thanks, @MarcioAB. @Potapy4 opened PR #1918 to correct the documentation.  This issue was auto-closed when I merged his PR.
