### ISSUE TITLE
Mention gcAllowVeryLargeObjects setting

### ISSUE THREAD

**Issue by MgSam** [dotnet/dotnet-api-docs#1889]
For .NET Framework applications, even if they are 64 bit you can get `OutOfMemoryException`s if a collection holds more than 2GB worth of data. A fix for this was made in .NET 4.5, which is turned on by setting the [gcAllowVeryLargeObjects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcallowverylargeobjects-element) config element. Mentioning this in the OutOfMemoryException documentation for .NET Framework is essential (it's turned on by default for .NET Core) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e79a4a-b836-1691-5777-dc4a44363b8e
* Version Independent ID: 545103d9-864c-c3d7-91a6-17203c4c7897
* Content: [OutOfMemoryException Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.outofmemoryexception?view=netframework-4.7.2)
* Content Source: [xml/System/OutOfMemoryException.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/OutOfMemoryException.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @MgSam. That's a very important detail to add to the exception documentation. We'll do it during the current sprint.
