### ISSUE TITLE
Minor spelling

### ISSUE THREAD

**Issue by john-hollander** [dotnet/dotnet-api-docs#1891]
"You can also pass the objects to be formatted as an array rather than a an argument list."

should be:

"You can also pass the objects to be formatted as an array rather than as an argument list."

i.e. with "as an" instead of "a an"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e3beef-53d2-b35c-e183-08a1650d1dab
* Version Independent ID: 04976819-623e-2674-93b2-536395fd2732
* Content: [String.Format Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netframework-4.7.2#System_String_Format_System_String_System_Object___)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @john-hollander for your feedback. Would you like to submit a fix for this?
Here are the instructions on how to do this: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

The exact line is found here:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml#L5515
