### ISSUE TITLE
Don't dispose HttpClient

### ISSUE THREAD

**Issue by nycdotnet** [dotnet/dotnet-api-docs#1910]
The code example at the top of this article will cause disasterous performance problems on .NET Core 2.1 and higher.  Instances of HttpClient should not be disposed nor used in using blocks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbd5007c-82e5-a0c1-2156-7df4bbbcc2da
* Version Independent ID: eba98e03-3cc2-bebe-3dcd-45eda9c9c378
* Content: [HttpClient Class (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
I don't follow - in the context of Main, it makes sense to dispose of `HttpClient`.
It should just not be done per request ...
Maybe adding a comment there to clarify would help?

**Comment by nycdotnet** [comment]
Main is a bad example then (and honestly there is no reason to dispose in Main since the process ending is the ultimate garbage collection).  Using HttpClient with this pattern in a real app not in Main will result in really bad perf problems, and people are just going to copy and pase this sample and not read the article.

**Comment by force-net** [comment]
Agree. Main example is incorrect, remark about static usage:

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.

is placed very low, so, main example looks like to be standard usage of this class. But it will cause slow performance and socket leak.

I think, main example should be rewrited to example in remark.

**Comment by qinezh** [comment]
It's truly a problem as many people may just follow the sample code in Examples Section and ignore the content in Remarks Section which is more important...

**Comment by chrisfcarroll** [comment]
I've created Pr#987 for this.
The problem is, the Example is supposed to set an example. Especially for people who are learning. The example as it exists is setting a bad example. It is confusing because it directly conflicts with the guidance in Remarks.
