### ISSUE TITLE
Example provided fails on... System.Data.DataRowView drv = (System.Data.DataRowView)value;

### ISSUE THREAD

**Issue by Ray-Wynn** [dotnet/dotnet-api-docs#1911]
Example provided fails on... System.Data.DataRowView drv = (System.Data.DataRowView)value;
System.NotImplementedException: 'Unable to cast object of type 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e7271e-65e1-6484-aa46-37b3e44828d0
* Version Independent ID: 07f27f2e-e1a9-e536-1c5d-b9c3c9798a0a
* Content: [DataGrid.RowHeaderStyle Property (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datagrid.rowheaderstyle?redirectedfrom=MSDN&view=netframework-4.7.2#System_Windows_Controls_DataGrid_RowHeaderStyle)
* Content Source: [xml/System.Windows.Controls/DataGrid.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/DataGrid.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by MSDN-WhiteKnight** [comment]
The example assumes that DataGrid is bound to DataView, but it is not stated anywhere. If we bind DataGrid like this:

    public MainWindow()
    {
            InitializeComponent();
            DataTable dt = new DataTable();
            //...
            this.DataContext = dt.DefaultView;
    }

everything works properly. If we bind DataGrid to any other collection, the error is reproduced.

I think, there's no need to cast source item into DataRowView for purposes of this example, so it can be fixed by rewriting Convert method like this:

    public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
    {
        try
        {                
            //Get the CollectionView from the DataGrid that is using the converter
            DataGrid dg = (DataGrid)Application.Current.MainWindow.FindName("DG1");
            CollectionView cv = (CollectionView)dg.Items;
            //Get the index of the item from the CollectionView
            int rowindex = cv.IndexOf(value) + 1;

            return rowindex.ToString();
        }
        catch (Exception e)
        {
            throw new NotImplementedException(e.Message);
        }
    }

It should work with any collection.

**Comment by Ray-Wynn** [comment]
Thanks for the response.

It is somewhat confusing whilst learning C# when Microsoft examples fail. I don’t know if this occurs because C# is evolving or the examples provided are not tested (as in downloaded in isolation from original composition) or lack the documented conditions required.

But given the scale of C# possibilities, and the effort required to document every possibility! I have little to complain about. Again, thankyou for your response.

Cheers,

                Ray

________________________________
