### ISSUE TITLE
Not for CF 3.5

### ISSUE THREAD

**Issue by Heroenimus** [dotnet/dotnet-api-docs#1920]
This page says it applies to Framework 3.5, though this functionality is not available in my CF3.5 environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc74c710-7fc1-bb9b-1b67-b1ed1f0eaa11
* Version Independent ID: e5d7f2dc-961a-0f1b-def8-c62f3040c8f1
* Content: [Aes Constructor (System.Security.Cryptography)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes.-ctor?view=netframework-3.5)
* Content Source: [xml/System.Security.Cryptography/Aes.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/Aes.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
.NET Compact Framework 3.5 has a different surface area than .NET Framework 3.5, @Heroenimus. 

Closing as By Design.
