### ISSUE TITLE
Code example is encouraging socket resource leaks

### ISSUE THREAD

**Issue by iolazarc** [dotnet/dotnet-api-docs#1923]
Calling Socket.Shutdown without exception handling code will prevent Socket.Close from being called, causing the socket to potentially remain in a bound state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb95fde4-f6ad-f094-0800-76738233ef53
* Version Independent ID: 846c39ca-c7fc-4404-7868-16a762b32ca7
* Content: [Socket.Close Method (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.close?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/Socket.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/Socket.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
That's a good point. Do you want to submit a PR?
