### ISSUE TITLE
How do you set Write and Read Timouts on NetworkStream When Using Asynchronous methods WriteAsync, ReadAsync

### ISSUE THREAD

**Issue by dinobu** [dotnet/dotnet-api-docs#1924]
I have following method code in my Xamarin.Forms application 

```
    using (TcpClient client = new TcpClient(ip, port))
    using (NetworkStream stream = client.GetStream())
    {
    	byte[] messageBytes = PrepareMessageBytes();
    
        //
        // Setting these seam to have no effect
        //
    	stream.WriteTimeout = (int)TimeSpan.FromSeconds(10).TotalMilliseconds;
    	stream.ReadTimeout = (int)TimeSpan.FromSeconds(10).TotalMilliseconds;
    
        //
        // I have set read and write timeouts above but when 
        // hitting this line, app hangs indefinitely?  
        // I would expect that after 10 seconds, a IOException
        // will be thrown
    	await stream.WriteAsync(messageBytes, 0, messageBytes.Length);
    	stream.Flush();
    
    	byte[] buffer = new byte[1024];
    	StringBuilder builder = new StringBuilder();
    	int bytesRead = 0;
    
    	while (stream.DataAvailable)
    	{
    		bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length);
    		builder.AppendFormat("{0}", Encoding.ASCII.GetString(buffer, 0, bytesRead));
    	}
    
    	string msg = receivedMessage.ToString();
    } 
```

Above, I have set both Write and Read timeouts to 10 seconds.  I know my code hangs on call to:

await stream.WriteAsync(...) 

, but I would expect that after 10 seconds, an IOException will be thrown.  Based on your documentation that is what we use to set up write/read timeouts on NetworkStream.  But, at the very bottom of this page [(https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.writetimeout?view=netframework-4.7.2#System_Net_Sockets_NetworkStream_WriteTimeout),](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.writetimeout?view=netframework-4.7.2#System_Net_Sockets_NetworkStream_WriteTimeout) you "kind-of" state that the timeouts do not apply for async writes and reads.  This part of documentation is also very unclear as it does not talk about Task Parallel Library (WriteAsync, ReadAsync)  but only about Async Programming Model (WriteBegin, WriteEnd, ReadBegin, ReadEnd)

How do I set timeout for calls to WriteAsync / ReadAsync methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9791d7d-8f80-99d2-ab04-45f065e3a72f
* Version Independent ID: e88442cf-8ac7-4e6e-e872-e6f2dfe1f52c
* Content: [NetworkStream.WriteTimeout Property (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.writetimeout?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/NetworkStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/NetworkStream.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by rzikm** [comment]
All async methods can have timeout set using the `CancellationToken` parameter (obtained e.g. by creating new `CancellationTokenSource(timeout)`).

(Read/Write)Async should be mentioned in the notes. I will put up a PR for that.
