### ISSUE TITLE
StreamReader.Close documentation falsely claims it overrides TextWriter.Close

### ISSUE THREAD

**Issue by elgonzo** [dotnet/dotnet-api-docs#1925]
I doubt StreamReader.Close overrides **TextWriter**.Close ;-)
(and, unsurprisingly, proceeds to talk about flushing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f2e490-1e7e-16a5-4213-864aefa9109a
* Version Independent ID: 13833ca7-82b3-2f44-9527-193074669b13
* Content: [StreamReader.Close Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.close?view=netframework-4.7.2)
* Content Source: [xml/System.IO/StreamReader.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/StreamReader.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for noticing and reporting these errors, @elgonzo. We've opened #2310 to correct them.
