### ISSUE TITLE
StringReader.Close documentation falsely claims it overrides Stream.Close

### ISSUE THREAD

**Issue by elgonzo** [dotnet/dotnet-api-docs#1926]
As the title says
(and, it also talks about flushing)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5382d5-75ce-94f0-5e12-dea87c99a2ac
* Version Independent ID: c0c575a7-2d3d-6fd9-b3d7-a8ea48cd710e
* Content: [StringReader.Close Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.stringreader.close?view=netframework-4.7.2#System_IO_StringReader_Close)
* Content Source: [xml/System.IO/StringReader.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/StringReader.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for noticing and reporting these errors, @elgonzo. We've opened #2310 to correct them.
