### ISSUE TITLE
Third time's the charm: TextReader.Close documentation claims it calls StringReader.Dispose... let's have a party! ;-)

### ISSUE THREAD

**Issue by elgonzo** [dotnet/dotnet-api-docs#1928]
And also talks about flushing and StreamWriter.AutoFlush specifically. o_O?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30e1fb9-deeb-d281-c919-ba7ed44a02b4
* Version Independent ID: 8a7d079d-cec2-e127-3bac-21c4de01186c
* Content: [TextReader.Close Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.textreader.close?view=netstandard-2.0#System_IO_TextReader_Close)
* Content Source: [xml/System.IO/TextReader.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/TextReader.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out this copy-and-paste error, @elgonzo. We've opened #2263 to address the issue.
