### ISSUE TITLE
Undocumented overload

### ISSUE THREAD

**Issue by john-cullen** [dotnet/dotnet-api-docs#1935]
The overload `Path.GetFullPath(string, string)` does not appear to be documented, but is referenced in this page and visible in .Net Core 2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6bcce3-8ba6-fed5-b1ad-da7442288f6d
* Version Independent ID: eb2ecc15-c9fe-7fa9-d8d5-43dd0a431995
* Content: [Path.GetFullPath Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netframework-4.7.2#System_IO_Path_GetFullPath_System_String_System_String_)
* Content Source: [xml/System.IO/Path.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Path.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by john-cullen** [comment]
I see a commit fixing this was merged two days ago, I guess it just hasn't made it onto the website so I'll close this for now.

**Comment by mairaw** [comment]
Yes, this was fixed in PR #563. When a commit gets merged, we need to push the changes to the live branch to start the publishing process, which happens once a day.
