### ISSUE TITLE
broken URL

### ISSUE THREAD

**Issue by keithAtGerber** [dotnet/dotnet-api-docs#1937]
URL in doc, "http://www.contoso.com/index.html", is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55bdb40e-c781-331f-c357-757cfc51df06
* Version Independent ID: 8b868f58-1083-17b7-8d0c-76f9234eccbf
* Content: [UriKind Enum (System)](https://docs.microsoft.com/en-us/dotnet/api/system.urikind?view=netframework-4.7.2)
* Content Source: [xml/System/UriKind.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/UriKind.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @keithAtGerber. I've opened the following PR to fix this: https://github.com/dotnet/dotnet-api-docs/pull/2025
