### ISSUE TITLE
FileStream.Read() Code is Incorrect

### ISSUE THREAD

**Issue by CharcoalUchiha** [dotnet/dotnet-api-docs#1941]
The lines "inFs.Read(data, 0, blockSizeBytes);" in EncryptFile() and DecryptFile() are incorrect.  Those lines will cause applications to fall into an infinite loop.  The "0" should be replaced with "offset" for both methods.  This was probably a typo due to force of habit.  We've all done this at one point or another, but remember to be careful when sharing untested code ;) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d79da2-23c7-034a-6edd-5968af41c7fc
* Version Independent ID: 4ad593fd-ef7c-bea2-bd50-7b569554e66d
* Content: [X509Certificate2 Class (System.Security.Cryptography.X509Certificates)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2?redirectedfrom=MSDN&view=netframework-4.7.2#applies-to)
* Content Source: [xml/System.Security.Cryptography.X509Certificates/X509Certificate2.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.X509Certificates/X509Certificate2.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing out the errors in the examples, @CharcoalUchiha. We've opened dotnet/samples#818 to address this issue.
