### ISSUE TITLE
clarification “(For in Visual Basic)” is redundant.

### ISSUE THREAD

**Issue by MNF** [dotnet/dotnet-api-docs#1944]
clarification “(For in Visual Basic)” is redundant

“Executes a for (For in Visual Basic) loop”

As VB is case-insensitive, clarification “(For in Visual Basic)” is redundant.
If you want to refer to operator, not to concept, more precise wording will be  
“Executes a loop similar to for operator in a language like C#(For in Visual Basic)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2bf2007-a78a-e961-c318-d80b18be7df3
* Version Independent ID: 3a387aa2-ec90-e003-6968-13c4828e8208
* Content: [Parallel.For Method (System.Threading.Tasks)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.for?view=netframework-4.7.2)
* Content Source: [xml/System.Threading.Tasks/Parallel.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading.Tasks/Parallel.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @MNF. This was resolved in PR #2070.
