### ISSUE TITLE
Describe circumstances in which this function will return null

### ISSUE THREAD

**Issue by jazzdelightsme** [dotnet/dotnet-api-docs#1950]
For instance, it can return null if you pass 0 for the hresult. Are there any other cases?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7979e2b7-2226-efdd-456f-4300b222d898
* Version Independent ID: 8cb33d7f-a658-45ee-a2fc-013519feeb88
* Content: [Marshal.GetExceptionForHR Method (System.Runtime.InteropServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getexceptionforhr?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.InteropServices/Marshal.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices/Marshal.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @jazzdelightsme. We've addressed it in #2305.
