### ISSUE TITLE
CreateSafeFileHandle not documented

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/dotnet-api-docs#1962]
[`System.IO.WindowsRuntimeStorageExtensions`](https://msdn.microsoft.com/en-us/library/system.io.windowsruntimestorageextensions.aspx) (from the `System.Runtime.WindowsRuntime` library) had APIs added for converting from `Windows.Storage.IStorageFile` and `Windows.Storage.IStorageFolder` to `Microsoft.Win32.SafeHandles.SafeFileHandle`. These don't appear to be documented anywhere.

The key usage scenario is taking a WinRT IStorageFile and constructing a `System.IO.FileStream` around it. This allows synchronous access to IStorageFile/IStorageFolder objects.

The reference definitions:
[/runtime/src/libraries/System.Runtime.WindowsRuntime/ref/System.Runtime.WindowsRuntime.cs#L41-L46](https://github.com/dotnet/runtime/blob/4e72737a8ec246297bce916ad747e4a2fb1265ac/src/libraries/System.Runtime.WindowsRuntime/ref/System.Runtime.WindowsRuntime.cs#L41-L46) [_edited to point to dotnet/runtime_]:

``` C#
        public static SafeFileHandle CreateSafeFileHandle(
            this IStorageFile windowsRuntimeFile,
            FileAccess access = FileAccess.ReadWrite,
            FileShare share = FileShare.Read,
            FileOptions options = FileOptions.None)

        public static SafeFileHandle CreateSafeFileHandle(
            this IStorageFolder rootDirectory,
            string relativePath,
            FileMode mode)

        public static SafeFileHandle CreateSafeFileHandle(
            this IStorageFolder rootDirectory,
            string relativePath,
            FileMode mode,
            FileAccess access,
            FileShare share = FileShare.Read,
            FileOptions options = FileOptions.None)
```

Arguments work the same as FileStream constructor arguments, with the obvious exception that you can provide a root directory and a relative path.

The API is present in 2.0 releases of System.IO.WindowsRuntime` for .NET 4.6.1, .NET Core 2.0, and Universal Windows Platform 10.0.16299.

**Comment by mairaw** [comment]
I've transferred the issue from dotnet/docs to this repo.

Status update on this one:
- With the onboarding of UWP and .NET Platform extensions, we can now see the APIs available on docs:
https://docs.microsoft.com/en-us/dotnet/api/system.io.windowsruntimestorageextensions?view=dotnet-uwp-10.0
- I've requested the engineering team to turn the flag live for the .NET Platform Extensions 3.0 Preview 2, which is where the CreateSafeFileHandle methods show up (https://docs.microsoft.com/en-us/dotnet/api/system.io.windowsruntimestorageextensions.createsafefilehandle)
- I've requested our vendor team to bring the rest of the content from MSDN for WindowsRuntimeStorageExtensions and WindowsRuntimeStreamExtensions 
- I've asked @sudeepku to fix the redirection from MSDN to go to correct APIs

Next step is to document the CreateSafeFileHandle methods.

**Comment by mairaw** [comment]
Redirection request fix still hasn't been completed, so moving this to the August milestone. Other than that, all tasks were completed.

**Comment by carlossanlop** [comment]
I documented these APIs back in August: https://github.com/dotnet/dotnet-api-docs/pull/2846

We can close the issue.
