### ISSUE TITLE
 DirectoryVirtualListView constructor overloads beforeCount has same description as afterCount

### ISSUE THREAD

**Issue by shoe788** [dotnet/dotnet-api-docs#1969]
For example on [DirectoryVirtualListView(Int32, Int32, Int32)](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.directoryvirtuallistview.-ctor?view=netframework-4.7.2#System_DirectoryServices_DirectoryVirtualListView__ctor_System_Int32_System_Int32_System_Int32_) but present in other overloads

beforeCount
A Int32 data type objects that gets or sets a value to indicate the number of entries after the target entry that the client is requesting from the server.

afterCount
A Int32 data type object that gets or sets a value to indicate the number of entries after the target entry that the client is requesting from the server.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @shoe788. We've opened #2015 to address the issue you've raised.
