### ISSUE TITLE
FileStream(String, FileMode) docs doesn't mention UnauthorizedAccessException for readonly files.

### ISSUE THREAD

**Issue by Jalalx** [dotnet/dotnet-api-docs#1985]
Documentations for `FileStream(String, FileMode)` constructor doesn't mention `UnauthorizedAccessException` for `readonly` files.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

**Comment by mairaw** [comment]
@Jalalx maybe something similar to this one?
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/File.xml#L172
