### ISSUE TITLE
C50186: Code inside the ``` breaking loc pages

### ISSUE THREAD

**Issue by v-makoud** [dotnet/dotnet-api-docs#1990]
Hello @yishengjin1413, @TianqiZhang, @mairaw,
Localization team has reported possible source content issue.
Link to Github file: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Xsl/XslCompiledTransform.xml
Row where the issue is located: 589-607
Comment: Please consider using the same solution as in this commit
902ada3#diff-3961535003f568e38255b5826d494c5a

This problematic content has to be put into an include in order not to break loc pages.

Can you please review the comment and provide answer/explanation? Also, if source fix is needed please provide link to the PR that will include the fix, so we can confirm and close this Issue.
Many thanks in advance.

**Comment by mairaw** [comment]
Yes, I intend to do a similar fix @v-makoud. I just couldn't get to that yet.

**Comment by v-makoud** [comment]
@mairaw great, please let me know here when you do.
