### ISSUE TITLE
Wrong property description for NoCache

### ISSUE THREAD

**Issue by boskjoett** [dotnet/dotnet-api-docs#2000]
On this page:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.cachecontrolheadervalue.nocache?view=netcore-2.2
the description of the NoCache property is wrong.
It says:
"true if the HTTP client is willing to accept a cached response; otherwise, false."
should be:
"false if the HTTP client is willing to accept a cached response; otherwise, true."

**Comment by mairaw** [comment]
Thanks for your feedback. Would you like to submit a PR to fix this?

The instructions on how to do this are described here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

I'd also change the description of that property to follow our guidelines like this:
"Gets or sets a value that indicates whether an HTTP client is willing to accept a cached response."

**Comment by boskjoett** [comment]
Yes, I made a PR
