### ISSUE TITLE
Unsafe.Unbox API needs warning about intended usage

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/dotnet-api-docs#2020]
Doc link: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.unbox
For full context, see conversation at https://github.com/dotnet/corefx/issues/34258.

The `Unsafe.Unbox<T>(object)` method is special because there are additional usage constraints developers must be aware of when calling this method, and the compiler won't necessarily inform the developer if they're about to violate these extra constraints. We instead need to make sure these are called out in this API's documentation.

In particular, the `unbox` IL instruction is intended to return a controlled-mutability managed pointer. Since we cannot represent this constraint via our API surface, the `Unsafe.Unbox<T>(object)` instruction instead returns a normal mutable `ref T`. However, developers __must not__ mutate the returned reference unless they are certain that `T` is a mutable struct type.

__Disallowed example:__

```cs
// 'int' is not a mutable struct type, so the below code is illegal
Unsafe.Unbox<int>(obj) = 30;
```

__Allowed example:__

```cs
// 'System.Drawing.Point' is a mutable struct type with public property setters, so the below code is legal
Unsafe.Unbox<System.Drawing.Point>(obj).X = 50;
```

For more information regarding allowed and disallowed operations on the return value of `Unsafe.Unbox<T>(object)`, see [ECMA-335 (PDF)](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf), specifically § III.4.32 and III.1.8.1.2.2.

**Comment by GSPP** [comment]
@GrabYourPitchforks in what cases is the returned pointer usable for mutation? § III.4.32 seems to say that the pointer is always of controlled mutability.

**Comment by GrabYourPitchforks** [comment]
@GSPP Per a strict reading of ECMA-335, never; since a `stind` instruction is invalid on a controlled-mutability managed pointer (see specific wording in § III.1.8.1.2.2.) The only "legal" way to mutate it is to pass it as the byref _this_ parameter in an instance method on the struct type. That's what is implicitly taking place in the property setter example I provided above: it's being supplied as _this_ in the `Point::set_X(ref Point @this, int value) : void` method.

_In practice_, there shouldn't be a problem with mutating the entire reference itself as long as the struct itself was mutable. So the line below - though illegal per the strict reading of ECMA-335 - should work.

```cs
Unsafe.Unbox<System.Drawing.Point>(obj) = new System.Drawing.Point(40, 50);
```

**Comment by GrabYourPitchforks** [comment]
Note to doc writers: the important point here is that the documentation should say something like "The `Unsafe.Unbox<T>` method corresponds to the `unbox` IL instruction. Anybody who calls this method should be intimately familiar with these two specific sections from ECMA-335. You might see unexpected behaviors if you use this API in a manner other than as prescribed there."

**Comment by GSPP** [comment]
It seems dangerous to encourage code that contradicts ECMA. It seems that this would only work because of the way the JIT currently works. In other words it works by coincidence. It's an uncomfortable situation. It seems that there is a lot of this lately and I wonder if we are going down a good path.

Essentially, we are doing what the C community did 30 years ago. They used lots of Undefined Behavior because it worked at the time. This caused tremendous problems over the long run.

**Comment by GrabYourPitchforks** [comment]
@GSPP That was my original concern also. We had a debate about the API, good arguments were made all around, and ultimately the argument was not strong enough to persuade the larger whole. Such is life. :)

And TBH there are legitimate use cases. What we can do is give developers the knowledge to recognize if a particular use case is guaranteed stable by the runtime or whether it works by coincidence, as you point out. Consider the example I provided earlier.

```cs
Unsafe.Unbox<System.Drawing.Point>(obj).X = 50;
```

This is totally, 100% legal per ECMA-335. Guaranteed to work properly across every runtime, not relying on any implementation details. 👍 That's why I thought it might be a good candidate for inclusion in this method's official documentation.
