### ISSUE TITLE
ValueTuple<T1,T2,T3>.ToString() description refers to ValueTuple<T1,T2>

### ISSUE THREAD

**Issue by DoktorDemento** [dotnet/dotnet-api-docs#2046]
Line 766 of dotnet-api-docs/xml/System/ValueTuple`3.xml is:
```xml
<returns>The string representation of this <see cref="T:System.ValueTuple`2" /> instance.</returns>
```

Should be:
```xml
<returns>The string representation of this <see cref="T:System.ValueTuple`3" /> instance.</returns>
```

**Comment by mairaw** [comment]
Thanks for your feedback @DoktorDemento. I've opened https://github.com/dotnet/dotnet-api-docs/pull/2255 to fix this.

You can also click the edit button if you know how to fix the problem and submit a PR.
For more information, see https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
