### ISSUE TITLE
Type.GetProperties doc need to fixes 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/dotnet-api-docs#2052]
The doc 

https://docs.microsoft.com/en-us/dotnet/api/system.type.getproperties?view=netframework-4.7.2#System_Type_GetProperties_System_Reflection_BindingFlags_

need some fixes to address the suggestions mentioned in the community report  https://developercommunity.visualstudio.com/content/problem/463525/cannot-see-public-property-in-reflection.html?childToView=498831#reply-form

here is the suggestion text from that report 

```
Thank you for your reply. May I suggest that you consider rewriting the help for this?

The sentence in the comment "You must specify either BindingFlags.Instance or BindingFlags.Static in order to get a return." that you quoted uses the term "or", which I instinctively interpreted in its Boolean sense (being an article written for programmers). May I suggest that you add the phrase "but not both" to eliminate the confusion?

Also, I would like to point you to the following block of text which occurs more than once on that page:

A property is considered public to reflection if it has at least one accessor that is public. Otherwise the property is considered private, and you must use BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static (in Visual Basic, combine the values using Or) to get it.  
You may notice that it uses ```Instance``` and Static bindings in the same request, implying that this is a normal thing to do. If it is only legal to use Static and Instance together when also used with NonPublic, then you need to state this explicitly, to avoid confusing this reader.

```

**Comment by mairaw** [comment]
What do you think @rpetrusha? Grammatically either...or represents a choice, but adding (but not both) wouldn't hurt.

However, I need some additional clarification about the second part of the comment @tarekgh . That is exactly what the code does:
https://referencesource.microsoft.com/#mscorlib/system/type.cs,747b1a12f39d3a0d

So do we need to change the sentence "You must specify either BindingFlags.Instance or BindingFlags.Static in order to get a return." to cover the allowed usage of those flags together along with NonPublic only?

**Comment by rpetrusha** [comment]
Both either/or and the suggested either/or/but-not-both are incorrect. You can indeed specify both, as the source for the default `GetProperties` method shows. What the documentation should note is that you need at least one of BindingFlags.Public and BindingFlags.Instance, along with at least one of BindingFlags.Public and BindingFlags.Nonpublic. That's a consistent issue that affects not only the GetProperties(BindingFlags) method, but all of the Get... methods that include a BindingFlags parameter.

In terms of the second comment, the duplication of content is a result of our previous managed reference page design, which had separate pages for each method overload. Common material can be consolidated in the remarks section for the overload as a whole, which in this case is easy to do if we're modifying the content anyway.

This is a significant issue that developers commonly encounter. Until you figure out how BindingFlags work, method calls tend to be hit or miss. I'll schedule some time in the May sprint to work on this issue.
