### ISSUE TITLE
Make a pass to remove references to Windows 95/98/me

### ISSUE THREAD

**Issue by danmoseley** [dotnet/dotnet-api-docs#2053]
There are still mentions of Windows 9x eg in [Process.BasePriority](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.basepriority?view=netframework-4.7.2#System_Diagnostics_Process_BasePriority):

> The platform is Windows 98 or Windows Millennium Edition (Windows Me); set the UseShellExecute property to false to access this property on Windows 98 and Windows Me.

Windows 9x has not been supported since .NET Framework 2.0, 13 years ago, all docs for subsequent releases can remove all mention of it (unless possibly it refers to some remote machine)

**Comment by mairaw** [comment]
We have a broad issue covering this here: https://github.com/dotnet/docs/issues/5199

@rpetrusha should we close this as a duplicate or do you prefer to keep one in each repo?

**Comment by rpetrusha** [comment]
I thought it would be useful to have the issue in this repo -- it gives it somewhat more visibility, so that hopefully it can be addressed sooner.

**Comment by carlossanlop** [comment]
@gewarren is this something that needs to be addressed in batch in all the xml files mentioning unsupported Windows versions?

**Comment by gewarren** [comment]
@danmoseley Do we need to keep exception documentation such as this?

`<exception cref="T:System.NotSupportedException">Not supported for Windows 98 or Windows Millennium Edition.</exception>`

**Comment by danmoseley** [comment]
@gewarren no, we do not need to document that unless our document is intended for users of .NET Framework 2.0 or earlier, which I believe is out of support.

**Comment by gewarren** [comment]
Yes, .NET Framework 2.0 is 10 years out of support - https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework.
