### ISSUE TITLE
Add VB sample to AuthenticatedStream class

### ISSUE THREAD

**Issue by mairaw** [dotnet/dotnet-api-docs#2069]
This is the topic: https://docs.microsoft.com/en-us/dotnet/api/system.net.security.authenticatedstream?view=netframework-4.7.2

**Comment by obelink** [comment]
I will do this class, methods & properties.

**Comment by obelink** [comment]
Hi Maira.. can you assign this task on my name?

**Comment by mairaw** [comment]
Done @obelink

**Comment by mairaw** [comment]
@rpetrusha finished this task with https://github.com/dotnet/dotnet-api-docs/pull/2448. Closing.
