### ISSUE TITLE
Dubious information

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2198]
@TaWulf commented on [Wed Mar 27 2019](https://github.com/dotnet/dotnet-api-docs.de-de/issues/21)

This,,:

'Initializes a new instance of the AnnotationPathPoint class with the specified legend name.'

,,seems a misplaced piece of information.  It is obviously just a Legend not an AnnotationPathPoint  that gets created. This mistake is also visible in Intellisense and in the ASP version.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 76410ceb-3469-32f2-a52f-0b31628dbaa8
* Version Independent ID: 7b38058a-589b-ed37-8b10-ff4e8c96b0f0
* Content: [Legend Constructor (System.Windows.Forms.DataVisualization.Charting)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.datavisualization.charting.legend.-ctor?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Windows.Forms.DataVisualization.Charting/Legend.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Forms.DataVisualization.Charting/Legend.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team,
the contributor is reporting an issue in the original documentation
best

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @TaWulf. We've opened #2223 to correct the documentation.
