### ISSUE TITLE
code layout issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/dotnet-api-docs#2205]
There is a code layout issue in docs "[MessageBox Class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messagebox?view=netframework-4.7.2)"

		string message = "You did not enter a server name. Cancel this operation?";
                       string caption = "Error Detected in Input";
		MessageBoxButtons buttons = MessageBoxButtons.YesNo;
		DialogResult result;

should be like this:

		string message = "You did not enter a server name. Cancel this operation?";
            string caption = "Error Detected in Input";
		MessageBoxButtons buttons = MessageBoxButtons.YesNo;
		DialogResult result;

**Comment by rpetrusha** [comment]
Thanks for pointing out the badly formatted code, @kyle0418. We've opened dotnet/samples#773 to address this issue.
