### ISSUE TITLE
Documentation incomplete for System.Diagnostics.DiagnosticSource and friends

### ISSUE THREAD

**Issue by SwooshyCueb** [dotnet/dotnet-api-docs#2209]
**Issue description**

Documentation for the classes in the `System.Diagnostics.DiagnosticSource` assembly is scant. Only bare-bones "these classes exist with these members" is present. However, XML documentation comments exists within [the source](https://github.com/dotnet/corefx/blob/v2.2.3/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSource.cs).

Assuming I can motivate myself, I'd be willing to copy all the in-source documentation to this repo. Are there any tools to assist with this or is it all done more or less manually?

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
    - All versions
- [ ] .NET Framework
    - NuGet package exists for 4.5 and 4.6, but I assume that doesn't count.
- [ ] .NET Standard
    - NuGet package exits for 1.1, 1.3, and 2.0, but I assume that doesn't count.

**Comment by mairaw** [comment]
Thanks for pointing this out @SwooshyCueb.  
@karelz can you help me get a doc build from this namespace? I can then load the existing comments into our docs.

**Comment by karelz** [comment]
@mairaw how can I help? Is there some magical tool I don't know about?

**Comment by mairaw** [comment]
@ahsonkhan maybe can help as well. Also, can I get a new version of the xml files for pipelines @davidfowl? I've noticed when I updated the extensions that we got some new APIs.

**Comment by mairaw** [comment]
You need to run the build with the flag to generate the XML documentation file. I'll make some time to get corefx working on my machine as well.

**Comment by ahsonkhan** [comment]
> can you help me get a doc build from this namespace? 

The attached zip has both xml files (System.Diagnostics.DiagnosticSource.xml / System.IO.Pipelines.xml).

>Also, can I get a new version of the xml files for pipelines @davidfowl? I've noticed when I updated the extensions that we got some new APIs.

You probably want to cherry-pick only the new API docs from this xml since the docs and source comments are not in sync.

[xml-from-source-preview4-master.zip](https://github.com/dotnet/dotnet-api-docs/files/3020992/xml-from-source-preview4-master.zip)

**Comment by mairaw** [comment]
Yes, that’s usually what I do. Thanks @ahsonkhan! I also need to finish the json Par.

**Comment by mairaw** [comment]
I believe this was resolved by @carlossanlop with PR #2671
