### ISSUE TITLE
code formatting issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/dotnet-api-docs#2228]
There is a code formatting issue in docs "[ListView Class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview?view=netframework-4.7.2)"

	//Add the items to the ListView.
          		listView1.Items.AddRange(new ListViewItem[]{item1,item2,item3});

should be like this:

	//Add the items to the ListView.
    listView1.Items.AddRange(new ListViewItem[]{item1,item2,item3});

**Comment by mairaw** [comment]
Thank you @kyle0418. We'd love contributions to get this fix!

The source code for that is here: https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_Winforms/ListViewExample/CS/form1.cs
