### ISSUE TITLE
VB help page with C # example code

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2244]
@DBEKrause commented on [Wed Apr 03 2019](https://github.com/dotnet/dotnet-api-docs.de-de/issues/22)

[Hier Feedback eingeben]
Die reinen Erklärungen auf der Seite sind sicherlich hilfreich.
Nun habe ich die F1-Taste aus einer Visual-Basic-Applikation heraus gedrückt, die Beispiel-Codes sind jedoch in C# geschrieben, das ist definitiv nicht hilfreich, nicht einmal dann, wenn man erweiterte Grundkenntnisse darin hat; ich erwarte an dieser Stelle einen VB-Beispiel-Code, alles andere ist kontra-produktiv.
MfG Erwin Krause 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b506a9fe-8a9e-4ea4-705e-95896479d155
* Version Independent ID: 12a50eb1-1012-49b3-fad8-5c965e4534ce
* Content: [WebBrowser.Navigated Event (System.Windows.Forms)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.webbrowser.navigated?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(System.Windows.Forms.WebBrowser.Navigated);k(System.Windows.Forms.WebBrowser);k(VS.Properties);k(System.Windows.Forms.WebBrowser);k(Designer_System.Windows.Forms.Design.FormDocumentDesigner);k(VisualSelection);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/WebBrowser.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Forms/WebBrowser.xml)
* Product: **dotnet-api**
* Technology: **system.windows**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is making a suggestion on the example code:
Rough translation

> The pure explanations on the page are certainly helpful.
> Now I've pressed the F1 key out of a Visual Basic application, but the example codes are written in C #, which is definitely not helpful, even if you have advanced basic knowledge in it; I expect a VB example code at this point, everything else is counterproductive.

**Comment by rpetrusha** [comment]
I can't reproduce this: the example is available in both Visual Basic and C# versions. The following shows a portion of the page with the Visual Basic example when VB is the selected language:
![image](https://user-images.githubusercontent.com/10886961/55499859-d7f7bc00-55fb-11e9-98a6-cabadea2ab19.png)

I'm closing this as Not Repro.
