### ISSUE TITLE
Add VB samples to HttpListener

### ISSUE THREAD

**Issue by mairaw** [dotnet/dotnet-api-docs#2246]
This is the topic: https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener

**Comment by dsychin** [comment]
I would like to work on this.
Am I correct to think that I have to create a VB version of [this file](https://github.com/dotnet/samples/blob/staging/snippets/csharp/VS_Snippets_Remoting/Net_Listener_Basic/CS/test.cs) and also add the links to it to [this xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/HttpListener.xml)?
