### ISSUE TITLE
Assembly.Load(String) doesn't need full name

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#2270]
https://github.com/dotnet/dotnet-api-docs/blob/3417fadcec76fa01f6b262ea7bcd999ae6b74a50/xml/System.Reflection/Assembly.xml#L3552

I successfully called `Assembly.Load(String)` with the [simple name](https://docs.microsoft.com/dotnet/api/system.reflection.assemblyname.name) of an assembly, in .NET Framework 4.7.2 and .NET Core 2.2.

**Comment by rpetrusha** [comment]
You appear to be correct, @NextTurn; I can reproduce this as well. @GrabYourPitchforks, can you comment on this issue?

**Comment by NextTurn** [comment]
ping?

**Comment by jkotas** [comment]
Correct, the full name is not strictly required for `Assembly.Load`. It is recommended to call `Assembly.Load` with full name to make sure that the caller gets what it wants (e.g. that it does not get lower version of the assembly than it expects).

**Comment by NextTurn** [comment]
Thanks @jkotas. Is the behavior consistent for all assemblies (loaded or not, CoreLib or others)?

**Comment by jkotas** [comment]
What I have said above applies to all assemblies. 

The actual loader behavior varies. For example, you won't be able to load assemblies from GAC in .NET Framework without a full name; or if your custom assembly resolve event insist on a full name.
