### ISSUE TITLE
Span constructor has incorrect documentation

### ISSUE THREAD

**Issue by mikernet** [dotnet/dotnet-api-docs#2271]
`Span<T>(void* pointer, int length)` [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.-ctor?view=netstandard-2.1#System_Span_1__ctor_System_Void__System_Int32_) incorrectly indicates that the length is in bytes as opposed to the number of `T` elements.

**Comment by gfoidl** [comment]
See also https://github.com/dotnet/dotnet-api-docs/issues/2045
