### ISSUE TITLE
There is an error on BlockingCollection sample in documentation 

### ISSUE THREAD

**Issue by arslanmurat06** [dotnet/dotnet-api-docs#2289]
In the documentation examples , **https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1?view=netframework-4.7.2**

**await** before **ConsumingEnumerableDemo.BC_GetConsumingEnumerable()** gives error.

```
_class BlockingCollectionDemo
{
    static async Task Main()
    {
        await AddTakeDemo.BC_AddTakeCompleteAdding();
        TryTakeDemo.BC_TryTake();
        FromToAnyDemo.BC_FromToAny();
        await ConsumingEnumerableDemo.BC_GetConsumingEnumerable();
        Console.WriteLine("Press any key to exit.");
        Console.ReadKey();
    }
}_
```

**Comment by rpetrusha** [comment]
Thanks for reporting the compiler error, @arslanmurat06. We've opened dotnet/samples#813 to address this issue.
