### ISSUE TITLE
code layout issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/dotnet-api-docs#2326]
There is a code layout issue in docs "[GroupBox Class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.groupbox?view=netframework-4.7.2)"

    // Create and initialize a GroupBox and a Button control.
                GroupBox groupBox1 = new GroupBox();
                Button button1 = new Button();
                button1.Location = new Point(20,10);

should be like this:

    // Create and initialize a GroupBox and a Button control.
    GroupBox groupBox1 = new GroupBox();
    Button button1 = new Button();
    button1.Location = new Point(20,10);

**Comment by mairaw** [comment]
Thanks for your feedback @kyle0418. This has been fixed with https://github.com/dotnet/samples/pull/855 but the change will be live next week.
