### ISSUE TITLE
Contradicting information between ScrollableControl HScroll and class remarks

### ISSUE THREAD

**Issue by ite-klass** [dotnet/dotnet-api-docs#2329]
The remarks section of `ScrollableControl.HScroll` says:

> Note AutoScroll maintains the visibility of the scrollbars automatically. Therefore, setting the HScroll or VScroll properties to true have no effect when AutoScroll is enabled.

whereas the remarks section of the class `ScrollableControl` says:

> To manually override which scroll bars are visible, set the VScroll and HScroll properties. If either property is set to false, the corresponding scroll bar is not visible, even if the AutoScroll property is set to true.

These directly contradict each other.

**Comment by ite-klass** [comment]
Even with `AutoScroll` set to `false`, setting a `AutoScrollMinSize` seems to automatically set `AutoScroll` as well as `HScroll`/`VScroll` to true.

**Comment by mairaw** [comment]
@RussKie @Tanya-Solyanik can you help with this feedback about ScrollableControl.HScroll and confirm what the fix should be?

**Comment by RussKie** [comment]
I'll have a look

**Comment by RussKie** [comment]
I have created a simple test app, and values of `HScroll` and `VScroll` appear ignored if `AutoScroll` is set.

@Tanya-Solyanik would you have any further insights?

**Comment by Tanya-Solyanik** [comment]
I looked at the sources and i think that H/VScroll properties indicate whether the scrollbars are displayed, scroll bars are not forced into existence by these properties. Layout pass determines if scrollbars are displayed and sets these properties accordingly. Notice that they are not displayed in the property grid and are protected, they are designed for use by control developers. Values that are set by the application developers, are overwritten on the layout pass, based on the value AutoScroll property among other things.

**Comment by Tanya-Solyanik** [comment]
@mairaw  - I can really use some help with wording here - https://github.com/dotnet/dotnet-api-docs/pull/3702

**Comment by Tanya-Solyanik** [comment]
@mairaw  - could you please review https://github.com/dotnet/dotnet-api-docs/pull/3702

**Comment by mairaw** [comment]
Will do. Still catching up with the backlog of PRs after the holidays.
