### ISSUE TITLE
Invisible enum field remarks

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#2341]
https://github.com/dotnet/dotnet-api-docs/blob/bdc5c7e71a5092239783affe5074137cb0eeeba3/xml/System.Runtime.InteropServices/UnmanagedType.xml#L314-L321

https://github.com/dotnet/dotnet-api-docs/blob/bdc5c7e71a5092239783affe5074137cb0eeeba3/xml/System.Runtime.InteropServices/UnmanagedType.xml#L1064-L1071

I can't see these remarks anywhere.

**Comment by rpetrusha** [comment]
This is because remarks for enumeration members aren't published, @NextTurn; see #1306. I'll open a PR to move the two member remarks to the member summary.
