### ISSUE TITLE
Code formatting issue

### ISSUE THREAD

**Issue by jack147527** [dotnet/dotnet-api-docs#2346]
There are four formatting issues in docs [CheckedListBox](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.checkedlistbox?view=netframework-4.7.2)

      private System.Windows.Forms.Button button3;
        private System.ComponentModel.Container components;
      
      public Form1()
      {
            InitializeComponent();

         // Sets up the initial objects in the CheckedListBox.
            string[] myFruit = {"Apples", "Oranges","Tomato"};
         checkedListBox1.Items.AddRange(myFruit);

            // Changes the selection mode from double-click to single click.
         checkedListBox1.CheckOnClick = true;
      }

should be like this

      private System.Windows.Forms.Button button3;
      private System.ComponentModel.Container components;
      
      public Form1()
      {
         InitializeComponent();

         // Sets up the initial objects in the CheckedListBox.
         string[] myFruit = {"Apples", "Oranges","Tomato"};
         checkedListBox1.Items.AddRange(myFruit);

         // Changes the selection mode from double-click to single click.
         checkedListBox1.CheckOnClick = true;
      }

**Comment by mairaw** [comment]
Thanks for your feedback @jack147527. This was fixed in https://github.com/dotnet/samples/pull/846.
