### ISSUE TITLE
Code Layout Issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/dotnet-api-docs#2347]
There is a layout issue in the document "[BindingManagerDataErrorEventArgs Class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.bindingmanagerdataerroreventargs?view=netframework-4.7.2)"

    private void BindingManagerBase1_DataError(Object sender, BindingManagerDataErrorEventArgs e) {
    System.Text.StringBuilder messageBoxCS = new System.Text.StringBuilder();
    messageBoxCS.AppendFormat("{0} = {1}", "Exception", e.Exception );
    messageBoxCS.AppendLine();
    MessageBox.Show(messageBoxCS.ToString(), "DataError Event" );
    }

It should be:

    private void BindingManagerBase1_DataError(Object sender, BindingManagerDataErrorEventArgs e) {    
        System.Text.StringBuilder messageBoxCS = new System.Text.StringBuilder();
        messageBoxCS.AppendFormat("{0} = {1}", "Exception", e.Exception );
        messageBoxCS.AppendLine();
        MessageBox.Show(messageBoxCS.ToString(), "DataError Event" );
    }

**Comment by mairaw** [comment]
Thanks for your feedback @kyle0418. This was fixed in https://github.com/dotnet/samples/pull/845.
