### ISSUE TITLE
Make editorial updates to WebSocketReceiveResult Constructors

### ISSUE THREAD

**Issue by mairaw** [dotnet/dotnet-api-docs#2370]
URL:
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocketreceiveresult.-ctor

Similar to what was done in https://github.com/dotnet/dotnet-api-docs/pull/2319 for the ValueWebSocketReceiveResult struct

**Comment by carlossanlop** [comment]
@mairaw what does "Make editorial updates" mean? Does it mean "adding missing documentation? Did my [autoporting issue](https://github.com/dotnet/dotnet-api-docs/pull/2319) solve the problem?

**Comment by mairaw** [comment]
I think we can close this. Looking at a commit from back in the day, this class was mostly empty and that's not the case anymore.
