### ISSUE TITLE
Does the default value of the DataflowBlockOptions.EnsureOrdered property is true?

### ISSUE THREAD

**Issue by moyanming** [dotnet/dotnet-api-docs#2373]
Hi,
Does the default value of the [DataflowBlockOptions.EnsureOrdered property](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.dataflowblockoptions.ensureordered?view=netcore-2.2) is true?

**Comment by svick** [comment]
Yes, the default is `true`, you can see it in [the XML documentation in the source code](https://github.com/dotnet/corefx/blob/4ff66e5/src/System.Threading.Tasks.Dataflow/src/Base/DataflowBlockOptions.cs#L182-L192):

> Gets or sets whether ordered processing should be enforced on a block's handling of messages.
>
> By default, dataflow blocks enforce ordering on the processing of messages. This means that a
> block like `TransformBlock<TInput, TOutput>` will ensure that messages are output in the same
> order they were input, even if parallelism is employed by the block and the processing of a message N finishes 
> after the processing of a subsequent message N+1 (the block will reorder the results to maintain the input
> ordering prior to making those results available to a consumer).  Some blocks may allow this to be relaxed,
> however.  Setting `EnsureOrdered` to false tells a block that it may relax this ordering if
> it's able to do so.  This can be beneficial if the immediacy of a processed result being made available
> is more important than the input-to-output ordering being maintained.

I have also created a Pull Request that copies this information to the docs: https://github.com/dotnet/dotnet-api-docs/pull/2374.
