### ISSUE TITLE
What is the encryption standard underlying ProtectedData Class

### ISSUE THREAD

**Issue by sudeepku** [dotnet/dotnet-api-docs#2376]
@dsfwb asked this question in https://github.com/MicrosoftDocs/feedback/issues/1443
about Topic https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?view=netframework-4.8

**Comment by mairaw** [comment]
@bartonjs can you help with this question?

**Comment by bartonjs** [comment]
It uses [CryptProtectData](https://docs.microsoft.com/en-us/windows/desktop/api/dpapi/nf-dpapi-cryptprotectdata), part of Windows DPAPI.  I did a couple of minutes digging and couldn't find a clear answer beyond that point.

**Comment by mairaw** [comment]
Thanks @bartonjs. Does that help @dsfwb?

**Comment by GrabYourPitchforks** [comment]
The particular container format used by `CryptProtectData` is undocumented as it's an internal Windows implementation detail, and it has changed in previous releases of the operating system. The actual algorithms used under the covers are configurable, but if no override is specified in the registry the encryption algorithm is AES last I checked.

**Comment by mairaw** [comment]
Thanks @GrabYourPitchforks. Closing then.
