### ISSUE TITLE
[Question] How the `xml` files were generated in this format

### ISSUE THREAD

**Issue by colderlord** [dotnet/dotnet-api-docs#2397]
Hello!
Mb i ask something stupid, but how the `xml` files were generated in this format with you unique tags?
Where can i read about this or, where can i find tool that you use?
Regards

**Comment by mairaw** [comment]
Hi @colderlord,

It's not a stupid question at all.
We use a couple of tools in our pipeline including a couple of open-sources ones like [DocFX](https://dotnet.github.io/docfx/) and [mdoc](https://github.com/mono/api-doc-tools/).
The latter is the one that reflects over our assemblies and generates the XML files.

I hope this helps! Feel free to open issues on their repo with more questions.

**Comment by Des-Nerger** [comment]
@mairaw, could you clarify / add instructions how to build it locally? I tried to do simple `$ docfx docfx.json --serve`, but that wasn't enough: the site directory didn't even contain any `.html`'s after that.

[I don't think I'm the only one](https://www.reddit.com/r/dotnetcore/comments/e7g0hj/how_to_build_documentation/) who finds C# / .NET uncomfortable to learn and use without a convenient offline stdlib reference readable without any specialized GUI software (like an IDE). This GitHub repo feels like the only up-to-date and maintainable way out for satisfying the demand. But how do we build it?
