### ISSUE TITLE
DbConnection.Close - exception information

### ISSUE THREAD

**Issue by dmytro-gokun** [dotnet/dotnet-api-docs#2408]
Here: https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.close?view=netframework-4.8 (and for other .NET versions) we can read:

> Exceptions
> DbException
> The connection-level error that occurred while opening the connection.

Looks like a wrong sentence to me, copy-pasted from somewhere else. The truth, most probably, is that "Close" never throws. Thoughts?

**Comment by rpetrusha** [comment]
Thank you, @dmytro-gokun, for pointing this out. This evidently was a copy-and-paste error. I've removed the exception information.

**Comment by dmytro-gokun** [comment]
Thanks a lot, @rpetrusha, for fixing it. May be this is a stupid question, but plz bear with me :) What is the normal release cadence for fixes like this one? I mean, when it will be reflected in the official docs?

**Comment by rpetrusha** [comment]
Its not a stupid question at all, @dmytro-gokun. We merge PRs to the master branch, but publish from the live branch. Typically, we update the live branch from master once a day. So an update may appear anywhere from the same day to two business days after the PR is merged. 
This change is now live at  <https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.close>.
