### ISSUE TITLE
timeout or no timeout?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2409]
@mbrenn commented on [Fri May 03 2019](https://github.com/dotnet/dotnet-api-docs.de-de/issues/25)

Invoke(Action, DispatcherPriority, CancellationToken, TimeSpan) defines timeout variable as 'minimum time before start' while other overloads define timeout variable 'as maximum time until end'. 
Seems to be wrong or confusing.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8adbf2d5-66d0-15ab-743a-21ec03b05295
* Version Independent ID: 5269116e-7645-b2ba-839a-1aca693431f8
* Content: [Dispatcher.Invoke Method (System.Windows.Threading)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.threading.dispatcher.invoke?view=netframework-4.8#feedback)
* Content Source: [xml/System.Windows.Threading/Dispatcher.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Threading/Dispatcher.xml)
* Product: **dotnet-api**
* Technology: **system.windows**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is reporting a error in the documentation
best

**Comment by mairaw** [comment]
Thanks @mbrenn for your feedback. From what I can see [in the source](https://referencesource.microsoft.com/#WindowsBase/Base/System/Windows/Threading/Dispatcher.cs), they should all say "The minimum amount of time to wait for the operation to start. Once the operation has started, it will complete before this method returns."
