### ISSUE TITLE
Path.GetFullPath implementation/documentation discrepancy

### ISSUE THREAD

**Issue by KennethWhite** [dotnet/dotnet-api-docs#2411]
I encountered an issue this morning with a unit test revolving around `Path.GetFullPath`. I was upgrading unit tests from a .NET Framework 4.6.2 project to a .NET Core 2.2 project, which caused this test to go from passing to failing. I am unsure if this is an implementation discrepancy or a document discrepancy.

According to the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=netframework-4.6.2) which is labelled for both Framework 4.6.2 and Core 2.2, a call to `Path.GetFullPath` will throw an `NotSupportedException` if the path contains an extra `:` beyond the one used to specify the volume identifier. However, in Core 2.2 this exception does not throw for the unit test in question. 

I attempted to find the source of this issue in the [source code](https://referencesource.microsoft.com/#mscorlib/system/io/path.cs,9d69b1f37ab42ca1,references) for Framework 4.8 and found a possibly pertinent comment stating `:` could be a valid character in an object. In either case I have attached an XUnit snippet with a unit test demonstrating this issue. It passes when run on a 4.6.2 project and fails on a Core 2.2 project since no exception is thrown. 

```cs
public class PathHelperTests
    {
[Theory]
        [InlineData(@"file:\\NetworkShare\NetworkFolder\NetworkFile.avi", @"C:\MyFolder\MyProject.project")]
        public void WhenRelativePathContainsAbsolutePathThrowsNotSupportedException(string relativePath, string relativeTo)
        {

            Exception ex = Assert.Throws<NotSupportedException>(() =>
                Path.GetFullPath(Path.Combine(Path.GetDirectoryName(relativeTo) ?? "", relativePath)));
            Assert.Equal("The given path's format is not supported.", ex.Message);
        }
    }
``` #

**Comment by rpetrusha** [comment]
@JeremyKuhne, can you comment on this issue?

**Comment by carlossanlop** [comment]
This is an intentional breaking change from .NET Framework. I'll update the documentation to reflect this.
As it was mentioned in the [more recent runtime thread reporting this same behavior](https://github.com/dotnet/runtime/issues/33477), @JeremyKuhne discuss the reasoning in detail in [his blog post](https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek).

**Comment by plade** [comment]
Looks like this issue has been neglected. The documentation is still wrong as of today https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=net-6.0
```
[NotSupportedException](https://docs.microsoft.com/en-us/dotnet/api/system.notsupportedexception?view=net-6.0)
path contains a colon (":") that is not part of a volume identifier (for example, "c:\").
```

**Comment by carlossanlop** [comment]
Apologies for not being able to address it. @plade or @KennethWhite, would one of you be interested in submitting a PR to fix those docs? The file is https://github.com/dotnet/dotnet-api-docs/blob/e83c33bc0977a83d77396768f852bae5c07af231/xml/System.IO/Path.xml

**Comment by plade** [comment]
PR created https://github.com/dotnet/dotnet-api-docs/pull/8387 thank you @carlossanlop. I am not sure how the documentation would change retroactively. Could you help with that please?
