### ISSUE TITLE
default value of Serial.NewLine is vbLf and not Environment.NewLine

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2412]
@zoomx commented on [Mon May 06 2019](https://github.com/dotnet/dotnet-api-docs.it-it/issues/2)

in SerialPort.ReadLine Method is written

> The contents of the input buffer up to the first occurrence of a NewLine value.

The link in NewLine goes to SerialPort.NewLine Property where it's written

> A value that represents the end of a line. The default is a line feed, NewLine.

The link in NewLine goes to Environment.NewLine Property where it's written

> A string containing "\r\n" for non-Unix platforms, or a string containing "\n" for Unix platforms.

So it is expected that, using ReadLine, the NewLine, that is vbCrLf (\r\n), is removed.

Instead it is removed only vbLf so you have a string that is one character longer, ending with vbCR.
If I set NewLine Property to Environment.NewLine vbCrLf is removed.
So it seems that the default value is only vbLF and not Environment.NewLine

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 82605cc6-77d0-97a2-9fe4-1128d2f5c2e6
* Version Independent ID: a542f8d3-bfc3-a280-d8e9-c0b791519f94
* Content: [SerialPort.ReadLine Method (System.IO.Ports)](https://docs.microsoft.com/it-it/dotnet/api/system.io.ports.serialport.readline?view=netframework-4.8)
* Content Source: [xml/System.IO.Ports/SerialPort.xml](https://github.com/dotnet/dotnet-api-docs.it-it/blob/live/xml/System.IO.Ports/SerialPort.xml)
* Product: **dotnet-api**
* Technology: **system.io**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is reporting an error in the original documentation
best

**Comment by rpetrusha** [comment]
Thanks for reporting this, @zoomx, and for moving the issue to the dotnet/docs repo, @CeciAc. You are correct, @zoomx, that the value of the NewLine property is "\n" or vbLF. We'll update the documentation accordingly; see #2413.

**Comment by zoomx** [comment]
@CeciAc ,
thanks for moving in the right place. I opened the original issue using the links I found in the documentation page at the bottom (but I don't remember if the page was in Italian or in English), maybe they are wrong too?
