### ISSUE TITLE
Roslyn APIs should specify actual version instead of "Latest"

### ISSUE THREAD

**Issue by svick** [dotnet/dotnet-api-docs#2431]
As far as I can tell, the version of Roslyn shown in API reference is outdated. For example, the version 3.0.0 of the package Microsoft.CodeAnalysis.CSharp, which has been released for a month, contains the type `Microsoft.CodeAnalysis.CSharp.Syntax.RecursivePatternSyntax`, but that type is not included in the API reference. (I'm assuming that type can be considered to be released, even though it's related to a language feature that's still in preview.)

I understand that it can take some time before the API reference is updated. But in such cases, I think it's important to be clear about which version is being documented. Because of that, I think the version of Roslyn should be specified as e.g. "2.10.0", not "Latest".

On the other hand, I don't think it's necessary to have documentation of older versions, having just the latest available should be enough.

**Comment by BillWagner** [comment]
Thanks for raising this @svick 

I'm working to get the latest SDK uploaded

**Comment by BillWagner** [comment]
@mikadumont @jinujoseph Which version should we upload for the latest roslyn SDK APIs?
