### ISSUE TITLE
PemEncodeSigningRequest example is not properly formatted

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2438]
@jeremyVignelles commented on [Mon May 13 2019](https://github.com/dotnet/dotnet-api-docs.fr-fr/issues/6)

On the english page, the markdown code fences are shown, and the language is not detected as C#.

Could you please fix that?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6492c5e5-e154-6ead-e9f4-ea11a87fb29d
* Version Independent ID: 504f60e9-45e5-70ad-0bb6-d25da199efb6
* Content: [CertificateRequest.CreateSigningRequest Method (System.Security.Cryptography.X509Certificates)](https://docs.microsoft.com/fr-fr/dotnet/api/system.security.cryptography.x509certificates.certificaterequest.createsigningrequest?view=netframework-4.8)
* Content Source: [xml/System.Security.Cryptography.X509Certificates/CertificateRequest.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System.Security.Cryptography.X509Certificates/CertificateRequest.xml)
* Product: **dotnet-api**
* Technology: **system.security**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
the user is reporting a formating error present in the en-us page which replicates in the localized versions on the page

**Comment by mairaw** [comment]
Thanks @CeciAc and @jeremyVignelles. I've opened https://github.com/dotnet/dotnet-api-docs/pull/2439 to fix this. Merci!
