### ISSUE TITLE
Does not work at all!

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2497]
@dreamy-s commented on [Fri May 24 2019](https://github.com/dotnet/dotnet-api-docs.de-de/issues/26)

Hello, This example does not work. You will always get a ValidationException while reading thorugh the xsd Example. 
And if you use own things and even let visual studio create your xsd, everythin is going to be valide. There are no exceptions thrown. The only Ecxeptions that you can get is from the XmlReader when you add a opening tag but do not close it. Thats it! It doesn't matter what you are doing, this page and function is useless. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0f2f25ce-a5fc-e17e-6418-38a35784f990
* Version Independent ID: 19a31cc9-1d20-1aa0-7792-e56385d5f5fe
* Content: [XmlSchemaSet Class (System.Xml.Schema)](https://docs.microsoft.com/de-de/dotnet/api/system.xml.schema.xmlschemaset?view=netframework-4.8#feedback)
* Content Source: [xml/System.Xml.Schema/XmlSchemaSet.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Xml.Schema/XmlSchemaSet.xml)
* Product: **dotnet-api**
* Technology: **system.xml**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is reporting the example is not working
can you pleae check it?

**Comment by rpetrusha** [comment]
@dreamy-s, the example works as expected. Two of the three items in *booksSchemaFail.xml* violate the schema. The first book contains an author, but no title or price. The last contains an author, but uses an unknown name element instead of a first-name and last-name element.
We will modify the example to explain that the example is expected to produce validation errors.
