### ISSUE TITLE
Doesn't have examples

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2507]
@cassio-vo commented on [Thu May 23 2019](https://github.com/dotnet/dotnet-api-docs.pt-br/issues/10)

Doesn't have examples

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a4484428-7a0b-e18b-85f9-f91dd552fd35
* Version Independent ID: c4a4a71c-780c-fa16-5a57-8a6826f947c9
* Content: [EndpointDispatcher.ChannelDispatcher Property (System.ServiceModel.Dispatcher)](https://docs.microsoft.com/pt-br/dotnet/api/system.servicemodel.dispatcher.endpointdispatcher.channeldispatcher?view=netframework-4.8)
* Content Source: [xml/System.ServiceModel.Dispatcher/EndpointDispatcher.xml](https://github.com/dotnet/dotnet-api-docs.pt-br/blob/live/xml/System.ServiceModel.Dispatcher/EndpointDispatcher.xml)
* Product: **dotnet-api**
* Technology: **system.servicemodel**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@CeciAc commented on [Thu May 23 2019](https://github.com/dotnet/dotnet-api-docs.pt-br/issues/10#issuecomment-495368527)

Hello, @cassio-vo 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

---

@CeciAc commented on [Mon May 27 2019](https://github.com/dotnet/dotnet-api-docs.pt-br/issues/10#issuecomment-496279892)

Hello, @cassio-vo 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

---

@cassio-vo commented on [Mon May 27 2019](https://github.com/dotnet/dotnet-api-docs.pt-br/issues/10#issuecomment-496280247)

 An code example, with method and import.
This wioll be great.
    Em segunda-feira, 27 de maio de 2019 15:19:38 BRT, Cecilia Acevedo <notifications@github.com> escreveu:  
 
 
Closed #10.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is requesting examples to be added to the documentation
best

**Comment by mairaw** [comment]
Oi @cassio-vo, thanks for contacting us! We don’t have the resources to add examples to every single API page, so we use some metrics such as number of visits to decide whether a certain API meets the criteria for us to spend cycles adding examples. This page has very little visits every month, so for this reason, we're closing this issue. Let us know if there's anything special about this property that we should reconsider. Also, should your request generate enough 👍 responses, we’ll reconsider.
