### ISSUE TITLE
System.DirectoryServices.DirectorySearcher.AttributeScopeQuery example is malformed

### ISSUE THREAD

**Issue by mmascolino** [dotnet/dotnet-api-docs#2520]
The example code listed here:
https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.directorysearcher.attributescopequery?view=netframework-4.8#System_DirectoryServices_DirectorySearcher_AttributeScopeQuery

namely the line:
`DirectorySearcher src = new DirectorySearcher(group "(&(objectClass=user)(objectCategory=Person))");  
`
is not properly formed C# code.

**Comment by rpetrusha** [comment]
Thank you for reporting this issue, @mmascolino. We've opened #2524 to address it.
