### ISSUE TITLE
SurrogateSelector documentation has return null instead of object

### ISSUE THREAD

**Issue by yasuf** [dotnet/dotnet-api-docs#2548]
I was using the following docs https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.surrogateselector?view=netframework-4.8 and spend some time trying to figure out why the deserialization wasn't working, I found it weird that it has a `return null` at the end of `SetObjectData` but thought the documentation must be right, turns out when I changed that `return null` to `return emp` in a very similar scenario my code started working.

I can't make a PR for the change to that script since it's hosted in `(~/samples/snippets/csharp/VS_Snippets_Remoting/SurrogateSelector/CS/SurrogateSelector.cs#1`, it would be great if we can fix this slip in the docs!

**Comment by rpetrusha** [comment]
Thank you for reporting this issue, @yasuf. On the one hand, I can't reproduce it. On the other hand, the documentation indicates that `SetObjectData` should return the populated deserialized object. I've opened dotnet/samples#952 to modify the method's return value.

@bartonjs and @joperezr, is the change correct? It's not clear to me why the example should work when `SetObjectData` returns null.

**Comment by yasuf** [comment]
Thank you @rpetrusha !! Appreciate the quick response, didn't see that samples repo before
