### ISSUE TITLE
Fix formatting of ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/dotnet-api-docs#2560]
The ArgumentOutofRangeException documentation displays causes of the exception by category, and then lists subcategories of that main category. The formatting of the page, however, doesn't reflect this. For example:
![image](https://user-images.githubusercontent.com/10886961/59049599-367c2900-883d-11e9-93b1-0148d2c63f53.png)

Here, "You are retrireving" should be indented one level, and "The collection has no members" should be indented two. This is a consistent problem in the topic which makes the exception troubleshooting advice extremely difficult to follow or understand.
 
Related to #2552, which includes some formatting fixes for this topic.

**Comment by mairaw** [comment]
PR #2552 was merged.
