### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2577]
@eskivor commented on [Sun Jun 09 2019](https://github.com/dotnet/dotnet-api-docs.fr-fr/issues/8)

Il manque beaucoup d'informations, notamment quel est le résultat attendu

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 48e1abb6-6602-9ed2-2d6f-ae4e43d43f14
* Version Independent ID: a0696694-2c26-e625-1bef-e0d2240ddf86
* Content: [Math.MaxMagnitude(Double, Double) Method (System)](https://docs.microsoft.com/fr-fr/dotnet/api/system.math.maxmagnitude?view=netcore-3.0&viewFallbackFrom=netframework-4.8#feedback)
* Content Source: [xml/System/Math.xml](https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/live/xml/System/Math.xml)
* Product: **dotnet-api**
* Technology: **system**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
I moved this here since the contributor is requesting additional examples
Translation: _A lot of information is missing, including what is the expected result_

**Comment by mairaw** [comment]
This has been fixed in PR https://github.com/dotnet/dotnet-api-docs/pull/2519. It should be available in French in a few days/weeks.
