### ISSUE TITLE
Indentation  issue

### ISSUE THREAD

**Issue by kyle0418** [dotnet/dotnet-api-docs#2581]
There is the same indentation problem in the following document.
[Control.ControlAccessibleObject Class](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.controlaccessibleobject?view=netframework-4.8);
[Control.ControlAccessibleObject(Control) Constructor](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.controlaccessibleobject.-ctor?view=netframework-4.8).

         this.TextAlign = ContentAlignment.MiddleCenter;
	 // Set the AccessibleDescription text.
         this.AccessibleDescription = "A toggle style button.";

Should be,

         this.TextAlign = ContentAlignment.MiddleCenter;
	     // Set the AccessibleDescription text.
         this.AccessibleDescription = "A toggle style button.";

**Comment by mairaw** [comment]
Thanks @kyle0418 for your feedback. PR https://github.com/dotnet/samples/pull/982 was opened to fix this. We welcome fixes to the sample code as well!
