### ISSUE TITLE
typo: ProcessStartInfo.Arguments and ArgumentList

### ISSUE THREAD

**Issue by ryanmajidi** [dotnet/dotnet-api-docs#2585]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1601) by @ygoe**

Link to the documentation page:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.arguments?view=netstandard-2.1

The following text probably has a typo:

In include quotation marks in the final parsed argument, triple-escape each mark.

Did you mean "To include quotation marks..."? Or is this a rare aspect of the English language I don't know about?

Link to the documentation page:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=netstandard-2.1

There isn't much of an explanation why I would use ArgumentList over Arguments. Is there a platform-specific difference? The Arguments text only explains the situation on Windows. Is it different in Linux? Where does the string splitting happen? Or the list combination? (Whatever is used on the OS level.)

BTW: The content feedback box on the docs page is still missing.

**Comment by ryanmajidi** [comment]
Looks to already be addressed in original thread.

**Comment by mairaw** [comment]
The issue hasn't been addressed yet @ryanmajidi, so reopening.

**Comment by rpetrusha** [comment]
Thanks both for point out the typo, @ryanmajidi, and for asking about the difference between the `ArgumentList` and `Arguments` properties. We've opened #2611 to address both issues.
