### ISSUE TITLE
WindowsBase intellisense XML missing in _intellisense\netcore-3.0 folder

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/dotnet-api-docs#2602]
When I look inside an intellisense build output from https://ops.microsoft.com/#/sites/Docs/docsets/dotnet-api-docs?tabName=builds, and look through `_intellisense\netcore-3.0` folder contents, I can't find `WindowsBase.xml`. 

In addition, I can't find `PresentationBuildTasks.xml` either. 

/cc @mairaw, @ahsonkhan, @AdamYoblick, @rladuca

**Comment by mairaw** [comment]
If I look at the assemblies we used to generate the docs, I can see `WindowsBase.dll` there, but not `PresentationBuildTasks.dll`:
https://apidrop.visualstudio.com/_git/binaries?path=%2Fdotnet%2Fnetcore-3.0&version=GBnetcore30

I only see `PresentationBuildTasks.dll` for .NET Framework.

Re. WindowsBase, I don't see any APIs under that DLL for .NET Core in ildasm:

![image](https://user-images.githubusercontent.com/12971179/59541749-94e97d00-8eb7-11e9-9a19-06a8b8b5495d.png)

So this would probably explain why a file is not generated for that DLL.

**Comment by vatsan-madhavan** [comment]
`WindowsBase.dll` is _special_. It exists in both `Microsoft.NetCore.App` and `Microsoft.WindowsDesktop.App`. 

The one in `Microsoft.NetCore.App` is a shim - just forwarders. 
The one in `Microsoft.WindowsDesktop.App` is a full implementation. This one has a corresponding assembly in the ref-pack, and exports a lot of important API's.

**Comment by vatsan-madhavan** [comment]
`PresentationBuildTasks` is also interesting. It used to be included in the .NET Framework runtime, but now it is only part of the SDK - and not the runtime. 

It exposes public API's. 
How should we deal with it? 

I'm less worried about `PresentationBuildTasks` than I'm about `WindowsBase`. We should probably treat this as a separate/distinct issue.

**Comment by mairaw** [comment]
Thanks @vatsan-madhavan. Are there other assemblies that have this behavior?

And does `PresentationBuildTasks` also ships with Microsoft.WindowsDesktop.App?

@safern can you look at this? Is this something that we need to change how we obtain the assemblies for the docs?

**Comment by vatsan-madhavan** [comment]
As far as I know, only `WindowBase` is duplicated like this. 
`PresentationBuildTasks` ships as part of `Microsoft.NET.Sdk.WindowsDesktop` (and not in `Microsoft.WindowsDesktop.App`).

**Comment by vatsan-madhavan** [comment]
cc @ericstj

**Comment by vatsan-madhavan** [comment]
Has this been solved yet? API's that are part of WindowsBase.dll are not generating documentation - this is not just an intellisense XML problem. See #1496 for example. An e.g. is the lack of documentation for `System.Windows.Point`, which shows this banner: 

![image](https://user-images.githubusercontent.com/20246435/62842793-980baa00-bc69-11e9-95b4-f73828178530.png)

 /cc @carlossanlop 
/ cc @grubioe, can we please open a tracking issue for this in dotnet/wpf ?

**Comment by mairaw** [comment]
@safern now that we're going to separate the assemblies for Desktop and .NET Core shared framework, I think we could solve this issue, correct?

**Comment by safern** [comment]
Yes the issue should be solved with the new Preview8 I just generated. Indeed both the one coming from `Microsoft.NETCore.App` and `Microsoft.WindowsDesktop.App` were overlapping and the one from `Microsoft.NETCore.App` was winning when I was creating the drop.

**Comment by mairaw** [comment]
We can close this issue now, correct?

**Comment by vatsan-madhavan** [comment]
This can be closed - I see WindowsBase.xml in the builds now!
