### ISSUE TITLE
for-each-in

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2614]
@TheRealCountVonCount commented on [Tue Jun 18 2019](https://github.com/dotnet/dotnet-api-docs.de-de/issues/28)
(translation)
The for-each-in construct, as implemented in the code, works for C #, but not for C ++
Here the C ++ version should be commented or changed accordingly.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fa765d00-19f8-74e4-4be1-1d7f1e7dc6ce
* Version Independent ID: 260749e3-69c6-a370-89b0-4f90d944fac7
* Content: [SerialPort Class (System.IO.Ports)](https://docs.microsoft.com/de-de/dotnet/api/system.io.ports.serialport?view=netframework-4.8#feedback)
* Content Source: [xml/System.IO.Ports/SerialPort.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.IO.Ports/SerialPort.xml)
* Product: **dotnet-api**
* Technology: **system.io**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
The code compiles successfully, and for each...in is supported in Visual C++, although it is not a standard C++ feature. See [for each, in](https://docs.microsoft.com/cpp/dotnet/for-each-in). Closing as Not Repo.
