### ISSUE TITLE
The behaviour of  `ArraySegment<T>.GetEnumerator()` throwing when the underlying array is null is undocumented

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/dotnet-api-docs#2621]
https://docs.microsoft.com/en-us/dotnet/api/system.arraysegment-1.system-collections-ienumerable-getenumerator?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.arraysegment-1.system-collections-generic-ienumerable-t--getenumerator?view=netframework-4.8

Both the generic and non-generic explicit interface implementations throw `InvalidOperationException` if the underlying array is null, however such behaviour is not documented.

**Comment by mairaw** [comment]
Thank you for your feedback @Gnbrkm41. I've opened PR #2622 to address these and other issues I saw with this class.

**Comment by Gnbrkm41** [comment]
That was pretty quick, thank you very much.
