### ISSUE TITLE
No Example in example block of CommittableTransaction

### ISSUE THREAD

**Issue by scegg** [dotnet/dotnet-api-docs#2630]
https://docs.microsoft.com/en-us/dotnet/api/system.transactions.committabletransaction?view=netcore-2.2

There is an example block but no code included.

Related: xml/System.Transactions/CommittableTransaction.xml

**Comment by rpetrusha** [comment]
Thank you for pointing out that the documentation refers to an example without presenting any source code. A search of the dotnet/samples repository suggests that the example is no longer available. We've opened #2631 to remove mention of the example.
