### ISSUE TITLE
AssemblyBuilder docs for .NET Core are outdated

### ISSUE THREAD

**Issue by cablooshe** [dotnet/dotnet-api-docs#2645]
Currently the [`System.Reflection.AssemblyBuilder`](https://docs.microsoft.com/dotnet/api/system.reflection.emit.assemblybuilder?view=netcore-3.0 ) docs for .NET Core are currently giving examples and remarks based around saving an assembly using the `AssemblyBuilderAccess.RunAndSave` property. However, this property, as well as `AssemblyBuilderAccess.Save`, don't exist in .NET Core, as right now there is no way to set an access modifier that allows for saving. Furthermore, there also is a new property added to .NET Core: `AssemblyBuilderAccess.RunAndCollect`. 

Most of the information on the `AssemblyBuilder` page discusses working with saved assemblies, which isn't possible in Core. The docs should be updated to reference only running the dynamic assembly, instead of running and saving. There also could be additions to the examples showing the use of a collectible dynamic assembly.

**Comment by mairaw** [comment]
@steveharter, @GrabYourPitchforks is this something you can help out to make sure we call out explicitly the .NET Framework behavior vs. .NET Core?

**Comment by buyaa-n** [comment]
Fixed by https://github.com/dotnet/dotnet-api-docs/pull/5491, thanks @MSDN-WhiteKnight
