### ISSUE TITLE
[question] Ping.PingPingAsync DNS resolution-safe?

### ISSUE THREAD

**Issue by jzabroski** [dotnet/dotnet-api-docs#2651]
xml/System.Net.NetworkInformation/Ping.xml mentions in SendAsync that passing in a host name is not safe, but the TPL version of this command, SendPingAsync, does not have the same note.

Is there some reason why?  Is SendPingAsync safer than Ping.SendAsync?

**Comment by eiriktsarpalis** [comment]
Tagging @dotnet/ncl for triage.

**Comment by wfurt** [comment]
SendAsync uses internal state stored in the object to process the async state. SendPingAsync simply returns the task and it is api to the caller to deal with it.
