### ISSUE TITLE
[MS Docs/Question] Feedback section disappeared for English versions of MS Docs

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/dotnet-api-docs#2654]
Consider the documents for `System.IO.FileInfo`:
US: https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo?view=netframework-4.8
UK: https://docs.microsoft.com/en-gb/dotnet/api/system.io.fileinfo?view=netframework-4.8
AU: https://docs.microsoft.com/en-au/dotnet/api/system.io.fileinfo?view=netframework-4.8
NZ: https://docs.microsoft.com/en-nz/dotnet/api/system.io.fileinfo?view=netframework-4.8

KR: https://docs.microsoft.com/ko-kr/dotnet/api/system.io.fileinfo?view=netframework-4.8
JP: https://docs.microsoft.com/ja-jp/dotnet/api/system.io.fileinfo?view=netframework-4.8
ES: https://docs.microsoft.com/es-es/dotnet/api/system.io.fileinfo?view=netframework-4.8
DE: https://docs.microsoft.com/de-de/dotnet/api/system.io.fileinfo?view=netframework-4.8

English versions of MS docs do not have the `Feedbacks` section:
![image](https://user-images.githubusercontent.com/42944058/60303519-81fe9000-992e-11e9-992d-6fd6fb7aeb40.png)

On the other hand, any other non-English versions of MS docs do have feedbacks section, which you can submit issues directly to relevant `dotnet/dotnet-api-docs.[locale identifier] repo:`
![image](https://user-images.githubusercontent.com/42944058/60303530-8aef6180-992e-11e9-9674-67c7d2977596.png)

I do remember English versions of the docs having these feedback sections as well; Is there a reason it has been removed? It is quite an inconvenience since I would have to come to this repo, and open an issue with all the details filled in manually, whereas if you have the feedback section all the details are filled in automatically.

**Comment by imba-tjd** [comment]
Now all of them are disabled.
https://github.com/dotnet/dotnet-api-docs.zh-cn/commit/2418a491ab189267ab0d0ac4cc22d132837f5b42

**Comment by mairaw** [comment]
That was by design. You can still provide anonymous feedback using the voting control here:
![image](https://user-images.githubusercontent.com/12971179/69268105-5dc47980-0b83-11ea-9e36-9f32b9b63e20.png)

-Or-

File an issue directly here on the repo.

-Or-

Use the site feedback link on the bottom.
