### ISSUE TITLE
System.IO.CreateDirectory

### ISSUE THREAD

**Issue by EbrahimMajdey** [dotnet/dotnet-api-docs#2656]
The documentation of System.IO.CreateDirectory doesn't say that the Directory might be created and the Function returns null which happened the System.IO.Exists should be called to ensure whether the directory is created or not

**Comment by rpetrusha** [comment]
@JeremyKuhne, are there conditions under which the directory is not created and the Directory.CreateDirectory method returns null rather than throwing an exception?

**Comment by JeremyKuhne** [comment]
`System.IO.Directory.CreateDirectory" never returns null. I've double checked the code on Core and Framework.

**Comment by rpetrusha** [comment]
Thanks, @JeremyKuhne. In that case, I'll close this issue. If you have source that reproduces the issue, @EbrahimMajdey, we'd be happy to look at it and decide the best course of action.

**Comment by EbrahimMajdey** [comment]
@rpetrusha @JeremyKuhne I am sure it does return a null .. can be a driver issue or so but it did return a null windows 2012 R2 .. noting that the directory string can be a path of directories .. this is a piece of code I used .. please note it wasn't async but I added the delay .. 
`
private async Task<bool> CreateDateDirectoryAsync(string directory)
        {
            if (!Directory.Exists(directory))
            {
                var directInfo = Directory.CreateDirectory(directory); //For weird reason not documented it can return null although it is creating the directory
                if (directInfo == null)
                {
                    _logger.LogDebug(GetType().Name, $"CreateDirectory returned null");
                    await Task.Delay(DirectoryCreationTimeoutMs);
                }
                return Directory.Exists(directory);
            }
            return true;
        }`
