### ISSUE TITLE
API docs for WindowsRuntimeBufferExtensions missing

### ISSUE THREAD

**Issue by juliushardt** [dotnet/dotnet-api-docs#2661]
**Issue description**
The API docs for [`System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeBufferExtensions`](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.WindowsRuntime/src/System/Runtime/InteropServices/WindowsRuntime/WindowsRuntimeBufferExtensions.cs) could previously be found on MSDN, but I'm unable to find them on docs.microsoft.com. The  [old link](https://msdn.microsoft.com/en-gb/library/windows/apps/system.runtime.interopservices.windowsruntime.windowsruntimebufferextensions.aspx) from [this page (Docs home > Windows > UWP apps > .NET for UWP apps > System.Runtime.InteropServices.WindowsRuntime)](https://msdn.microsoft.com/en-gb/library/windows/apps/mt185505.aspx) redirects to [the new docs for the System.Runtime.InteropServices namespace](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.windowsruntime?redirectedfrom=MSDN&view=netframework-4.7.2), which don't contain an entry for `WindowsRuntimeBufferExtensions`. Unfortunately, selecting ".NET Core" instead of ".NET Framework 4.7.2" in the dropdown above the search box doesn't make it show up either and an option for "UWP" is not available.

It looks like the online docs for this class are currently unreachable.

**Comment by mairaw** [comment]
We're making progress towards this issue.

- UWP target was onboarded to the API browser and API now exists on docs
- PR #2662 was open to migrate the content from MSDN
- Next, I need to work with the engineering team to fix the redirections

**Comment by mairaw** [comment]
Links like this https://msdn.microsoft.com/en-gb/library/windows/apps/system.runtime.interopservices.windowsruntime.windowsruntimebufferextensions.aspx now redirect to the appropriate place. 
We don't have the same page on docs as https://msdn.microsoft.com/en-gb/library/windows/apps/mt185505.aspx, The best close match would be to redirect to the API browser search, as https://docs.microsoft.com/en-us/dotnet/api/?view=dotnet-uwp-10.0&term=system.runtime. Do you think that would that be better @juliushardt?

**Comment by mairaw** [comment]
Closing as this has been fixed.
