### ISSUE TITLE
Utf8JsonWriter: stale documentation

### ISSUE THREAD

**Issue by qbit86** [dotnet/dotnet-api-docs#2707]
> Since this type is a ref struct...
> — https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter?view=netcore-3.0

`Utf8JsonWriter` [is not](https://github.com/dotnet/corefx/pull/36961) a ref struct [anymore](https://github.com/dotnet/corefx/commit/1f9b84a0804e868c7e0f37a3c10fbaf7c735ae14).

**Comment by mairaw** [comment]
Thank you for your feedback @qbit86. I've opened PR #2863 to fix this.
