### ISSUE TITLE
Code formatting issue 

### ISSUE THREAD

**Issue by mairaw** [dotnet/dotnet-api-docs#2728]
Indentation for the C# code on this page looks funky:
https://docs.microsoft.com/en-us/dotnet/api/system.io.unmanagedmemorystream.write?view=netcore-3.0

Sample code can be found here:
https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR_System/system.IO.UnmanagedMemoryStream/cs/sample.cs

**Comment by ivanbuha** [comment]
Pull request #1087 was created under dotnet/samples.
