### ISSUE TITLE
DataMemberAttribute On Collection Properties

### ISSUE THREAD

**Issue by TheXenocide** [dotnet/dotnet-api-docs#2735]
A note in the documentation indicates that when `DataMemberAttribute` is applied to a property, it must have both get and set accessors, which lead me to wondering why some code I stumbled on in our existing codebase was working at all. It turns out properties that expose collections are allowed to be get only (or, at least I can confirm it works fine with a `Dictionary<TKey,TValue>`). Get-only collection properties are a common pattern (and recommended, in most cases) so it makes enough sense, but thought I'd mention that I noticed the documentation might lead people to think their data contracts need to have setters in conditions which they would otherwise not want. There are unique conditions applied which might be better documented as well. For instance, serializing the following class works fine but deserializing it throws a `SerializationException` with the message "The get-only collection of type 'System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' returned a null value.  The input stream contains collection items which cannot be added if the instance is null.  Consider initializing the collection in the getter."

```csharp
[DataContract]
public class TestObject {
	private Dictionary<string, string> names = new Dictionary<string, string>();
	
	[DataMember]
	public Dictionary<string, string> Names => names;
}
```
So, in order to write this class in a way that allows deserialization, it must be adjusted to:
```csharp
[DataContract]
public class TestObject {
	private Dictionary<string, string> names;

	[DataMember]
	public Dictionary<string, string> Names
	{
		get
		{
			if (names == null) names = new Dictionary<string, string>();
			return names;
		}
	}
}
```

**Comment by Thraka** [comment]
This is a slightly tricky subject. The reason a get-only **collection** would work is because you can still modify the collection through the get-only accessor, unlike a primitive type variable. For example:

```csharp
public int Age { get; } = 0;

// code below doesn't work
instance.Age = 1;
```
You can't change `Age` at all. But a collection you can change easily

```csharp
private Dictionary<string, string> _names = new Dictionary<string, string>();
public Dictionary<string, string> Names => _names;

// code below DOES work
instance.Names.Clear();
```

You've just modified the collection even though it's provided in a get-only accessor. This is why serialization would work. It just inserts all of the objects into the collection.

But really, more appropriate thing to do in your case is to just to serialize the field directly and not worry about the property:

```csharp
[DataMember(Name = "Names")]
private Dictionary<string, string> _names = new Dictionary<string, string>();

public Dictionary<string, string> Names => _names;
```

**Comment by TheXenocide** [comment]
Indeed, I'm familiar with the implications and such, but my main point of note is that it might be worth making the documentation more accurate to avoid people accidentally creating collection properties with setters simply because the documentation says that it's required on all properties. I'd also agree that serializing the field instead of the property is probably a better recommendation than my example, for those coming across this later. As for the rest of the discourse on serialization and collections (though it's not really the point I'm making I'd also be curious if there is (and I suspect there would be) an exception when using inline initialization:

```csharp
[DataMember]
public Dictionary<string, string> Names { get; } = new Dictionary<string, string>();
```

I'd say this is probably the most current/advisable way of defining a collection property for most simple classes, so the scenario is probably not uncommon.

**Comment by Thraka** [comment]
_Trying to think as a user who just runs into this_

I do think what you ran into though is an exception and workaround to the limitation of get and set being required. I'm not sure I think it's worth calling out. The error you got with deserializing gave you an idea of how to work around it. But your design did violate the documentation guidance, which if you had known in advance, you would have designed around (for example serializing the private field instead) the problem.

I'm not sure it's worth mentioning that collections can work around this. I do see your point about trying to prevent someone blindly implementing a `set` for their collection to satisfy this requirement. But in the light, but what prevents them from just doing that on anything else that isn't a collection that they want to serialize but keep get-only?

I would almost say that the suggestion to workaround via the `get` with setting the instance in `get` is a bad pattern (except for something like a singleton) but I'm not super-super-super familiar with what is popular in patterns these days.

Thoughts on that?

I do want to say I appreciate you bringing up this discussion though.

**Comment by TheXenocide** [comment]
I think you make a fair point (and the lazy initialization inside the accessor does seem less ideal than serializing the field); I've been using C# for long enough that the alternatives were already apparent to me and I just went to the documentation to see what the official line of support advised. I was simply surprised when I came across the documentation, since it's _technically_ inaccurate, though in an understandable way. The note in question is listed as follows:

> Properties to which the DataMemberAttribute attribute has been applied must have both get and set fields; they cannot be get-only or set-only.

I'm thinking it might at least be worth pointing a beginner in the right direction? Maybe something more like

> Properties to which the DataMemberAttribute attribute has been applied must have both get and set fields; they cannot be get-only or set-only. To serialize a property that should remain get-only by design (e.g. a property that returns a collection) consider applying the `DataMemberAttribute` to the backing field instead.

Maybe it isn't necessary, but just a thought worth considering (and one that doesn't get too deep in the implementation details of collection deserialization or being too explicit about how).

**Comment by TheXenocide** [comment]
I'm not sold on my wording, and it may be more than a sidenote calls for, but I'm interested to see what you (or others) think about it

**Comment by Thraka** [comment]
I actually like your description 😄 Would you want to submit a PR with your suggestion? There is an edit button at the top right of the page which takes you to an XML file of the whole class, which you'll have to sift through to find the note and edit it.

Otherwise, I'll add this to the backlog but I have no idea when we'll get to it 😄

**Comment by TheXenocide** [comment]
Took me a bit to get back to it, but PR submitted :)
Sidenote: my first time making a PR using only the GitHub editor. For a single file very simple change it was actually a bearable experience.
