### ISSUE TITLE
Clarify the direction of the relative path in MakeRelativeUri

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/dotnet-api-docs#2755]
It is unclear from [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.uri.makerelativeuri) as to the direction of the relative path. I think possibly it is from the *base* instance *to* the argument, but this is not clear, except possibly from the [*remarks* table](https://docs.microsoft.com/en-us/dotnet/api/system.uri.makerelativeuri#remarks). Also, this works for file-system based relative paths, correct? Would be helpful to provide a couple of those illustrations.

**Comment by Thraka** [comment]
I think in the **Returns** description is clear:

>If the hostname and scheme of this URI instance and uri are the same, then this method returns a relative Uri that, when appended to **the current URI instance**, yields uri.

The **the current URI instance** being the object you're working with. Additionally, at the start it says **hostname and scheme of this URI instance** and then mentions the **uri** parameter name. This would indicate that **this URI instance** is referring to the object instance that has the `MakeRelativeUri` method on it.

The **Remarks** section then gives some demonstrations that make it clear which way it goes. However, it does not have a file-system path example. Please feel free to open a PR and add one.

I'm going to close this as I think the descriptions are clear. Thanks.
