### ISSUE TITLE
CloseReason Enum bad description

### ISSUE THREAD

**Issue by ryanmajidi** [dotnet/dotnet-api-docs#2844]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1471) by @AlexYurkin **

Link to article:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.closereason?redirectedfrom=MSDN&view=netframework-4.8

Problem:
When you describe the fields of this Enumeration you state that the 'UserClosing' happens when: "The user is closing the form through the user interface (UI)". But this also happens when you use 'Close' method for a form in your code.
It would be great to distinguish the UI Closing from the code closing.

**Comment by mairaw** [comment]
@OliaG @merriemcgaw can you comment on this issue? Should we add this to the description or should this be consider a feature request to have a different field? Thanks!

**Comment by merriemcgaw** [comment]
It appears to me that the article already makes that clarification:

> The FormClosing and FormClosed events are raised when a Form is closed, either through user action or programmatically. 

Or is that not what the customer was looking for.

**Comment by merriemcgaw** [comment]
I see his confusion. I think we can add clarification in the UserClosing also includes programmatic closing.

**Comment by AlexYurkin** [comment]
> I see his confusion. I think we can add clarification in the UserClosing also includes programmatic closing.

But how can we distinguish either the form was closed by user or by code? 
In my code I needed to perform different actions depending on how the form was closed (programmatically or GUI). And I wasn't able to distinguish them in my code. Maybe there is a need to add another field?

**Comment by merriemcgaw** [comment]
We're happy to take feature requests, including API changes to .NET Core. Please file an issue over in the WinForms https://github.com/dotnet/winforms
