### ISSUE TITLE
Documentation of TextFormatFlags enum is incorrect

### ISSUE THREAD

**Issue by david-c14** [dotnet/dotnet-api-docs#2903]
The entries for PrefixOnly and for HidePrefix state that these are described as `a legacy value which has no effect.`

But they do still have an effect. When used as flags to TextRenderer.DrawText they change the rendered text. This is certainly still true in .NET Framework 4.7.1

The entry for ModifyString says `Has no effect on the drawn text.`  While this is strictly true, it glosses over the fact that using this flag has the potential to do exactly what it says and modify the string, despite the fact that the string should be immutable. Surely it should be more explicit about not using the flag, rather than simply saying it has no effect on the drawn text.

**Comment by mairaw** [comment]
Thanks for your feedback. @merriemcgaw @RussKie can one of you help with this issue about https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textformatflags?

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik do you have thoughts?

**Comment by Tanya-Solyanik** [comment]
Thank you, @david-c14, for raising very good points. These values only expose the underlying windows options for DrawTextEx: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-drawtextexa

**Comment by RussKie** [comment]
> These values only expose the underlying windows options for DrawTextEx

Then do we need to update our docs, as the Win32 docs don't mention "legacy"?

**Comment by Tanya-Solyanik** [comment]
> Then do we need to update our docs, as the Win32 docs don't mention "legacy"?

yes
