### ISSUE TITLE
System.Net.Sockets ReceiveFromAsync Remarks Incorrect

### ISSUE THREAD

**Issue by ryanmajidi** [dotnet/dotnet-api-docs#2922]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1790) by @chipperatkins  **

Link to article:
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receivefromasync?view=netcore-2.2#remarks

Problem:
What's wrong with the article?
The remarks sections states

"The caller must set the SocketAsyncEventArgs.RemoteEndPoint property to the IPEndPoint of the remote host from which the data is to be received."

This statement makes it sound like the caller is specifying the "remote host from which the data is to be received" when in reality, the caller is providing a reference to preserve the remote host's endpoint in the SocketAsyncEvent args.

The caller may set the SocketAsyncEventArgs.RemoteEndPoint property to any endpoint and still recieve data. In this way the documentation is misleading and should be reworded.

**Comment by mairaw** [comment]
Thanks for your feedback @chipperatkins.
@davidsh @wfurt @scalablecory @eiriktsarpalis @karelz can you please take a look?
