### ISSUE TITLE
VB samples for Lazy(Of T) class contain C# code.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/dotnet-api-docs#2944]
Hi @mairaw or @rpetrusha the docs for [Lazy(Of T)](https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1?view=netstandard-2.0) have VB samples with C# code that is commented out:

![vs_lazy_t](https://user-images.githubusercontent.com/20465797/62571905-3202d980-b89b-11e9-9b06-0fd38a997b0c.png)

I tried to do a PR to edit the docs but it seems to use code samples located in other files and I don't know how to find those files and edit them. Could you (or anyone else) point me in the right direction towards that end so I make the fixes?

**Comment by rpetrusha** [comment]
Samples are found in the [dotnet/samples](https://github.com/dotnet/samples) repo on GitHub, @ericmutta. The path in the code reference indicates the path and filename of the sample, and any string value following `#`, if it is present, indicates a snippet name.

**Comment by rpetrusha** [comment]
Shall I assign this issue to you, @ericmutta?

**Comment by ericmutta** [comment]
@rpetrusha please do, and thanks for the pointer, I will take a stab at tomorrow :+1:

**Comment by ericmutta** [comment]
Hi @rpetrusha, I've submitted a PR for this issue. I am assuming by changing the snippet, it will update **both** the snippet and the full example as they appear in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1?view=netstandard-2.0)?

**Comment by rpetrusha** [comment]
Yes, @ericmutta, it will update both the snippet and the example in the docs.
