### ISSUE TITLE
Opcode description error

### ISSUE THREAD

**Issue by wwh1004** [dotnet/dotnet-api-docs#2948]
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.bge
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.bge_s
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.bge_un
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.bge_un_s

>  The effect is identical to performing a clt instruction followed by a brfalse branch to the specific target instruction.

it is not the "clt". it should be "clt.un"

![Snipaste_2019-08-07_13-18-30](https://user-images.githubusercontent.com/27536652/62596800-56e86280-b916-11e9-8dcc-b1cecd2bd580.png)
![Snipaste_2019-08-07_13-18-43](https://user-images.githubusercontent.com/27536652/62596803-58198f80-b916-11e9-8234-3f585c422615.png)

**Comment by mairaw** [comment]
Thanks for your feedback @wwh1004. I've opened PR #2955 to fix this. I'll wait for one of the SMEs to confirm the behavior.

You can also submit fixes to our docs when you encounter issues like that. For more information, see https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.

**Comment by wwh1004** [comment]
Since other opcode documents (bge, bge_s, bge_un, bge_un_s) have the same problem, and for integer it is "clt.un" and for floats it is "clt", can I send a PR again to fix them?

**Comment by mairaw** [comment]
Sure. I'll close mine.

**Comment by mairaw** [comment]
Also take a look at the comment from my coworker here - https://github.com/dotnet/dotnet-api-docs/pull/2955#issuecomment-519321070
