### ISSUE TITLE
Bug in the IOrderedDictionary Sample Code

### ISSUE THREAD

**Issue by mvetom** [dotnet/dotnet-api-docs#2952]
Look at the setter in the    public object this[int index] property in the sample C# code implementation of IOrderedDictionary at https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.iordereddictionary?view=netframework-4.8
:

            object key = ((DictionaryEntry)_people[index]).Key;
            _people[index] = new DictionaryEntry(Keys, value);

Shouldn't the second line have "key"  (meaning the same key that was just retrieved)  rather than Keys (which would be the entire collection of Keys for this dictionary)  as a parameter?

**Comment by rpetrusha** [comment]
Thanks for your feedback, @mvetom. Yes, the second line should use `key` rather than `Keys`. This is an issue only in the C# and C++ code; the Visual Basic code is correct. We've opened dotnet/samples#1161 to correct the code.
