### ISSUE TITLE
SecurityRulesAttribute.SkipVerificationInFullTrust documentation: transparent option in the what?

### ISSUE THREAD

**Issue by SwooshyCueb** [dotnet/dotnet-api-docs#2961]
The documentation for `SecurityRulesAttribute.SkipVerificationInFullTrust` contains the [line](https://github.com/dotnet/dotnet-api-docs/blob/f0e2c291a8c88675b981776b95c99041e7f13faf/xml/System.Security/SecurityRulesAttribute.xml#L153): 
``If you use this property to skip MSIL verification for an assembly, use the `transparent` option in the  to statically verify that the assembly's transparent code meets type safety requirements.``

It would seem some fairly important information has been omitted, namely were I should be setting the `transparent` option.

**Comment by rpetrusha** [comment]
Thanks for reporting this issue, @SwooshyCueb. You use the transparent option in with the [Peverify tool](https://docs.microsoft.com/en-us/dotnet/framework/tools/peverify-exe-peverify-tool), We've opened #2992 to restore the lost link text and link.
