### ISSUE TITLE
[VERY minor Edit]  ICollection<T> implementation spell check

### ISSUE THREAD

**Issue by mvetom** [dotnet/dotnet-api-docs#2962]
On page: ICollection<T> Interface:  https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1?view=netframework-4.8

In sample code,  in the BoxCollection class, in the Contains method,
in  the comments - IEquitable should be IEquatable

**Comment by mairaw** [comment]
Thank you for your feedback @mvetom. I've opened https://github.com/dotnet/samples/pull/1150 to fix this.
