### ISSUE TITLE
System.Net.Mail.SmtpClient is marked as obsolete in docs, but not in the source code

### ISSUE THREAD

**Issue by PashaPash** [dotnet/dotnet-api-docs#2986]
[System.Net.Mail.SmtpClient class page](https://docs.microsoft.com/en-us/dotnet/api/System.Net.Mail.SmtpClient?view=netframework-4.7) is currently states that class is obsolete, and offers https://github.com/jstedfast/MailKit as a replacement.

```
[System.Obsolete("SmtpClient and its network of types are poorly designed, we strongly recommend you use https://github.com/jstedfast/MailKit and https://github.com/jstedfast/MimeKit instead")]
public class SmtpClient : IDisposable
```

That class has no `Obsolete` attribute in both [Reference Source for 4.7](https://referencesource.microsoft.com/#System/net/System/Net/mail/SmtpClient.cs,ebaa2d61cfed8051) and [corefx source](https://github.com/dotnet/corefx/blob/9ebea3c459a094487fbe1db8c518a6a4220f9d08/src/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs).

Mono version of `SmtpClient` [was marked as Obsolete few years ago](https://github.com/mono/mono/commit/fa081c5ecd3b21353809d01ac2b08f7281f49ab0) by @migueldeicaza, and then that external lib link somehow made its way to official 4.7 docs. Please remove it.

**Comment by soniczoo** [comment]
If intellisense showed Obsolete, we probably wouldn’t have invested 100s of hours expanding our use of smtpclient recently, only to find an issue in one deployment. Then to see some rouge looking notes and a “here’s what’s popular” recommendation ( which will take 100s more hours of our teams time, if we can even get through the open source hoops and audits from our own and customer’s security teams/policies ) is a kick in the shorts. 
I’m all for progress. But, pulling the plug on framework improvements / established classes is a slippery slope. On this situation microsoft is acting like the framework is used for exclusively new, practice / personal, or hosted / managed products. Folks that sell windows programs or service packages to other companies be damned. 
My suggestion to save face on this one is similar to (to their credit) what was done with MSOLEDBSQL which was ”undepricated” after MS realized there are thousands of every day programs and probably billions of lines of code that need to work with tls 1.2.. fix it! - that’s what i have to do for my customers.

**Comment by mairaw** [comment]
@mimisasouvanh any updates on when we're going to be able to show attributes for the right version selected?

**Comment by migueldeicaza** [comment]
Folks, the story of how this attribute got added is worthy of a blog post.

That said, in a world where you want the best interop in the world, the most efficient encodings, the most efficient code, the comformance to the best protocols available at your disposal, you are not doing yourself or your users any favors by using SmtpClient.   This is like embracing HTTP in an era that has moved to HTTPS.

**Comment by PashaPash** [comment]
@migueldeicaza what exactly is wrong with SmtpClient in terms of encoding support or protocols support? It does support TLS, it does support UTF-8, that covers 99% of common cases for most of the apps. 

That is some kind of strange path of single person decision making. You put that attribute on a mono codebase, providing subjective "we strongly recommend ...", and apparently that "we" becomes official framework-wide decision. And that decision it still half-applied - class still not marked as obsolete in docs. It should be either marked obsolete in main .NET codebase, or unmarked as obsolete in docs. Just to avoid "100-hours invested" surprises.

The final warning in DE0005 is actually sounds like "SmtpClient is insecure. We have no standard, secure and reliable way to send mail in .NET anymore. Please use 3-rd party library with bus factor 1 and pray it will not be abandoned".

Already hit that "use 3-rd party" multiple times:

- MS marked System.Web.Script.Serialization as obsolete and recommended 3-rd party JSON.NET instead. Ended up re-introducing built-in JSON serializer in .NET Core 3.
- [PushSharp](https://github.com/Redth/PushSharp) was most efficient, community standard way to send push notifications in C#. Then author was hired by MS, and the project is now abandoned. That project is still mentioned by thousands of blogposts, and people still wasting time trying to plug in that "best" library just to find out it fails in production.

There is no difference between MailKit and PushSharp for me. They are both 3-rd party non-MS libraries with a single maintainer. The only difference is that MailKit is not abandoned (yet). 
Official MS clone of MailKit could be a solution - at least it will mark MailKit as some kind of "official" library.

**Comment by svick** [comment]
@PashaPash 

> Please use 3-rd party library with bus factor 1 and pray it will not be abandoned

[MailKit is part of the .NET Foundation](https://dotnetfoundation.org/projects?searchquery=mailkit&type=project), so if the maintainer decided to abandon it, somebody else should take their place.

**Comment by soniczoo** [comment]
It would really be nice to know exactly what's wrong with system.net.mail.smtpclient but I cannot get/find a straight answer. This lack of info and professional courtesy looks bad for Microsoft and the developers of Mailkit (especially if they are affiliated).  
Mailkit seems awesome in every way, and it works in the ONLY environment (of 100s) SMTPClient has had a problem in - thank god it's our own QA environment.  But getting railroaded into 100s of hours of change-over without knowing why is unfair. And I hope policies change, but many people working in large companies don't even have the option to use open source - so we MUST know what is wrong with SMTPClient. Without that common courtesy, t-shooting is impossible, and a simple fixable config issue may result in all kinds of hurt.

**Comment by PashaPash** [comment]
> [MailKit is part of the .NET Foundation](https://dotnetfoundation.org/projects?searchquery=mailkit&type=project), so if the maintainer decided to abandon it, somebody else should take their place.

Not sure how dotnetfoundation.org membership implies change of project ownership. Dotnetfoundation is about technical services and marketing, not about code contribution.

There is a hope that a second contributor will pick up the project, but for MailKit jstedfast is the only major contributor. 2-nd contributor is Redth, the owner of now abandoned PushSharp. And he has only 9 commits. 3-rd is migueldeicaza, mostly documentation, 6 years ago. It is clear that project is owned and maintained by one person, and no chance someone else can quickly became a full grade maintainer.

**Comment by mimisasouvanh** [comment]
@mairaw We will be rolling out the attribute versioning feature later this week.

**Comment by GreatFireWall** [comment]
So, what should I use now?

**Comment by migueldeicaza** [comment]
> @migueldeicaza what exactly is wrong with SmtpClient in terms of encoding support or protocols support? It does support TLS, it does support UTF-8, that covers 99% of common cases for most of the apps.

Please read the landing page for MailKit to get an idea of how much is missing.

**Comment by soniczoo** [comment]
The landing page that says smtpclient doesn’t, and mailkit does these things.. “cross-platform support and ability to save and re-load MIME messages before sending them”? That’s all I see.. not an explanation of issues with smtpclient. The whole point here is that Microsoft needs to support their “supported” software.. and I trust they will, they always have. Mailkit looks/works great. But business doesn’t care about that. It invests in software and platforms to make money. And business expects to have ample sunset warning, so it can plan its next investment. This healthy lifecycle is not happening in the case of System.Net.SmtpClient. Its like someone on a whim just yanked the plug on it.

**Comment by mairaw** [comment]
@mimisasouvanh @TianqiZhang the new feature does not display the wrong attribute anymore, but it continues to display the obsolete warning for all versions. That information also needs to be version/target aware.

**Comment by migueldeicaza** [comment]
Bad code and bad API design exists in the wild.   When the world understands those problems, they move to new systems that prevent that.

Just like we moved away from SSL to TLS, and then to version 1.1 and 1.2 and now we are hoping to move to 1.3, there are mistakes in the past that can not be solved.   This is one of those.

You should avoid using SmtpClient in my humble opinion, and do your users a favor in the process.   

Or you could live dangerously and roll the dice.

**Comment by alex-jitbit** [comment]
@migueldeicaza you made a claim but then instead of proving it, you send everyone to read some page online.

**The burden of proof is on the person who makes a claim**

SmtpClient is still a robust working piece of code (tested on our SaaS app used by 1000s of companies). 

MimeKit is indeed a fine, fast MIME parsing library for _inbound_ email, that has SMTP as an addon.

**Comment by mwwhited** [comment]
This is probably going to end up like json.net.  An API that everyone love snit Microsoft things they can do better so they create the bastard that is text.json.  Horrible library and attempt to blind port people leading to breaking changes everywhere.

**Comment by carlossanlop** [comment]
@mimisasouvanh what's the status of this?

**Comment by TianqiZhang** [comment]
@mimisasouvanh @mairaw now the page (https://docs.microsoft.com/en-us/dotnet/api/System.Net.Mail.SmtpClient?view=net-5.0) displays obsolete messages correctly, the warning will only show for 3 versions ( xamarinandroid-7.1 xamarinios-10.8 xamarinmac-3.0 ).

**Comment by mairaw** [comment]
Thanks @TianqiZhang. Closing this.

**Comment by mdell-seradex** [comment]
> @mimisasouvanh @mairaw now the page (https://docs.microsoft.com/en-us/dotnet/api/System.Net.Mail.SmtpClient?view=net-5.0) displays obsolete messages correctly, the warning will only show for 3 versions ( xamarinandroid-7.1 xamarinios-10.8 xamarinmac-3.0 ).

This is not entirely true because it still has a generic statement at the top that `The SmtpClient type is now obsolete.`

**Comment by mairaw** [comment]
I'll let @BillWagner and @gewarren analyze this. The issue here was that the warning was being displayed all the time. The generic statement at the top was added as part of the summary, so it will always show.
However, even though SmtpClient isn't marked as obsolete in newer platforms, it's not recommended by the team: https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md

**Comment by mdell-seradex** [comment]
@mairaw, there is actually another issue (#4114) where it has been suggested to modify this note.
The suggested change there is to this: `The SmtpClient type is now obsolete on some platforms and not recommended on others - see Remarks for details.`

**Comment by PashaPash** [comment]
@mairaw could you please update docs with some technical justification of using external library (MailKit) over standard SmtpClient?

All that we have now is:

Statement added as obsolete attribute for Xamarin by one of MimeKit contributors. Kind of "use my favorite lib, it's cool!":
> SmtpClient and its network of types are poorly designed, we strongly recommend you use https://github.com/jstedfast/MailKit and https://github.com/jstedfast/MimeKit instead

DE0005 note, with no technical details:
> SmtpClient doesn't support many modern protocols. It is compat-only. It's great for one off emails from tools, but doesn't scale to modern requirements of the protocol.

A real list of unsupported modern SMTP protocols and unsupported modern requirements of SMTP protocol would be great.

**Comment by mdell-seradex** [comment]
> @mairaw could you please update docs with some technical justification of using external library (MailKit) over standard SmtpClient?
> 
> All that we have now is:
> 
> Statement added as obsolete attribute for Xamarin by one of MimeKit contributors. Kind of "use my favorite lib, it's cool!":
> 
> > SmtpClient and its network of types are poorly designed, we strongly recommend you use https://github.com/jstedfast/MailKit and https://github.com/jstedfast/MimeKit instead
> 
> DE0005 note, with no technical details:
> 
> > SmtpClient doesn't support many modern protocols. It is compat-only. It's great for one off emails from tools, but doesn't scale to modern requirements of the protocol.
> 
> A real list of unsupported modern SMTP protocols and unsupported modern requirements of SMTP protocol would be great.

@PashaPash, I think your point may be better suited over here: #7355
That issue is recent and still open.  I know that I logged it as a question, but that doesn't mean it could not bring up valid points that cause the documentation to be changed.

**Comment by gewarren** [comment]
https://github.com/dotnet/dotnet-api-docs/pull/7359 clarifies the obsoletion statement in the summary text.
