### ISSUE TITLE
[Serializable] attribute shown on types that do not have it in .NET Core

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/dotnet-api-docs#3149]
In .NET Core only a limited subset of types have `[Serializable]`. These are listed in https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization

Can we hide the `[Serializable]` attribute from individual type topics when the filter is .NET Core? 

Eg., https://docs.microsoft.com/en-us/dotnet/api/system.drawing.printing.margins?view=netcore-3.0 shows the attribute even though I'm filtering for .NET Core. 

It should only appear for types in the list above. I am not sure whether this is technically possible.

cc @ViktorHofer 

It caused confusion eg https://github.com/dotnet/winforms/issues/1835

**Comment by mairaw** [comment]
Thanks @danmosemsft for your feedback. There are a few issues with how .NET API docs work on docs.microsoft.com and showing the appropriate attributes for the version you selected is one of them. 

I feel like this would be a duplicate of #2986. Would you agree?

You can see that the reflection tool already identifies the versions that should have serializable correctly:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Drawing.Printing/Margins.xml#L28

**Comment by danmosemsft** [comment]
@mairaw sure both seem tracking the same thing. thanks!
