### ISSUE TITLE
Aes missing F# example (offer to PR)

### ISSUE THREAD

**Issue by danieljsummers** [dotnet/dotnet-api-docs#3154]
The [page demonstrating how to use the Aes class](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes?view=netframework-4.8) has no F# sample. The way F#'s `use` statement works, it doesn't go out of scope until the end of the function; so, before reading `msEncrypt`, the user should call `swEncrypt.Flush()`.

This just bit me in another project, so I thought I'd offer to convert that sample to F# if you think it's a good idea. This would affect both this repository and the `samples` repo.

**Comment by mairaw** [comment]
Thank you for your kind offer @danieljsummers. @cartermp can you weigh in on this?

**Comment by cartermp** [comment]
@danieljsummers is correct on how to use it. How would the sample get pulled into the API doc though? Would love to have a sample but I just want to ensure nothing gets overwritten.

**Comment by mairaw** [comment]
We’d add a line with the fsharp entry here:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/Aes.xml#L51

The samples come from the dotnet/samples repo.

**Comment by cartermp** [comment]
Sounds good. @danieljsummers sounds like we're green for a contribution here!
