### ISSUE TITLE
Incorrect Assemblies for .NET Core?

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#3178]
Many types are defined in *System.Private.CoreLib.dll* in .NET Core.

For example, [List\<T\>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1) is not defined in *System.Collections.dll*.

```cs
Console.WriteLine(typeof(System.Collections.Generic.List<>).AssemblyQualifiedName);
```

```
System.Collections.Generic.List`1, System.Private.CoreLib...
```

**Comment by mairaw** [comment]
Thanks @NextTurn. That matches the information that is in the API Catalog as well:
https://apisof.net/catalog/System.Collections.Generic.List%3CT%3E

I’ll have to investigate what’s going on.

**Comment by mairaw** [comment]
Tagging @safern @ericstj and @terrajobst to comment. As @safern indicated offline, System.Private.CoreLib.dll is the runtime assembly, but the one we show it's the reference assembly at compile time. I think the behavior is correct and that's what we should show on docs/API catalog, but I'd like to double check that with you all.

**Comment by safern** [comment]
>  that's what we should show on docs/API catalog, but I'd like to double check that with you all.

I agree the compile time assembly is the one we should show and the one we've been showing across places.

**Comment by NextTurn** [comment]
Closing as by design.
