### ISSUE TITLE
No information about throwing exceptions by ChannelReader.WaitToReadAsync()

### ISSUE THREAD

**Issue by mrEDitor** [dotnet/dotnet-api-docs#3182]
I use System.Threading.Channels API for providing internal application API and faced some sort of ambiguity in documentation of method `ChannelReader.WaitToReadAsync()`. There is no mention about throwing exception, stored in closed channel, but it said

**Returns** `ValueTask<Boolean>` A ValueTask<TResult> that will complete with a true result when data is available to read or with a false result when no further data will ever be available to be read."

It often makes people think that method returns `false` value, in case the channel being closed with exception. How is about some clarification?

https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.waittoreadasync?view=netcore-3.0
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading.Channels/ChannelReader%601.xml

**Comment by mairaw** [comment]
Thank you for your feedback @mrEDitor. @tarekgh, @stephentoub can you look at this feedback about  ChannelReader.WaitToReadAsync()? Thanks!

**Comment by tarekgh** [comment]
@stephentoub please correct me if I say anything not true here or missing more info:

WaitToReadAsync can throw in the following cases: 

- The channel is not closed but it is empty. It will throw InvalidOperationException.
- The channel is empty and the channel writer is completed with exception. Something like channel.Writer.Complete(new Exception("Channel Closed")). At that time will get the exception passed to the complete.

**Comment by stephentoub** [comment]
> WaitToReadAsync can throw in the following cases

It shouldn't.  The purpose of WaitToReadAsync is to let you be notified when either a) there's data available to try to read, or b) there will never be data available to try to read.  In both cases the task returned from WaitToReadAsync completes successfully, with true in the former case and false in the latter case.  The latter case happens when the channel has been marked as completed and there's no data available, and that's true whether or not the channel was marked as completed successfully or with an exception.

**Comment by tarekgh** [comment]
@stephentoub 

The following code is throwing InvalidoperationException 

```C#
            var c = Channel.CreateBounded<int>(new BoundedChannelOptions(100));
            ValueTask<bool> r = c.Reader.WaitToReadAsync();
            bool rb = r.GetAwaiter().GetResult(); 
            try {  Console.WriteLine($"WaitToReadAsync() didn't throw and return {rb}"); } catch (Exception e) { Console.WriteLine($"WaitToReadAsync throw: {e}");}
```

Is this happen for other reasons?

Alos, it will throw if you do the following too:

```C#
            c.Writer.Complete(new Exception("Channel Closed"));
            rb = r.GetAwaiter().GetResult(); // throw Exception("Channel Closed");
```

note, I didn't write any item to the channel.

**Comment by stephentoub** [comment]
Are you sure the InvalidOperationException is coming from WaitToReadAsync?  Seems more likely it'd be coming from r.GetAwaiter().GetResult(), which isn't supported on a ValueTask that's not completed.

**Comment by tarekgh** [comment]
You are right. here is the stack:

```
WaitToReadAsync throw: System.InvalidOperationException: The asynchronous operation has not completed.
   at System.Threading.Channels.AsyncOperation.ThrowIncompleteOperationException()
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at NetCoreApp.Program.Main(String[] args) in F:\Temp\NetCoreApp\Program.cs:line 22
```

When using await instead, it worked as you described.

**Comment by mrEDitor** [comment]
The second case is the one I'm speaking about:
```csharp
public static async Task Main(string[] args)
{
    var c = Channel.CreateBounded<int>(new BoundedChannelOptions(100));
    c.Writer.Complete(new Exception("user exception"));
    var r = await c.Reader.WaitToReadAsync();
    Console.WriteLine($"WaitToReadAsync() returned {r}");
}
```

Output:
```
Unhandled exception. System.Exception: user exception
   at Program.Main(String[] args) in /home/edward/Проекты/trydotnet/Program.cs:line 15
   at Program.<Main>(String[] args)
```
