### ISSUE TITLE
GC.SuppressFinalize clarification (minor)

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/dotnet-api-docs#3223]
https://github.com/dotnet/dotnet-api-docs/blob/ca19f49f2fc78fa5e1a535998961fcf6c1bfd20e/xml/System/GC.xml#L1418

The existing text:
> If _obj_ does not have a finalizer, the call to the `SuppressFinalize` method has no effect.

I suggest the following minor addition/clarification:

> If _obj_ does not have a finalizer, ***or if the finalizer has already started executing,*** the call to the `SuppressFinalize` method has no effect.

Alternative wording might be...

> If _obj_ does not have a finalizer, ***or if the object is already being finalized,*** the call to the `SuppressFinalize` method has no effect.

Some related discussion can be found [here](https://stackoverflow.com/questions/58044679/is-it-harmless-to-call-gc-suppressfinalize-within-the-finalizer) (StackOverflow).

**Comment by rpetrusha** [comment]
@Maoni0, what do you think?

**Comment by Maoni0** [comment]
I would go with

> If obj does not have a finalizer, or if GC has already signaled the finalizer thread to run the finalizer, the call to the SuppressFinalize method has no effect.

**Comment by mairaw** [comment]
Opened PR #3279 to fix this.
