### ISSUE TITLE
Update NotifyCollectionChangedAction enum "Reset" description to not let it look like clearing collection

### ISSUE THREAD

**Issue by chingucoding** [dotnet/dotnet-api-docs#3253]
Currently, the description of the "Reset" value on the [NotifyCollectionChangedAction enum](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedaction?view=netframework-4.8) page indicates that the collection was cleared. However some collection (for example `Platform::Collections::Vector`) use the reset event do indicate that the collection went through dramatic changes, such as `ReplaceAll`.

The [UWP documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.interop.notifycollectionchangedaction) for the enum describe the "Reset" value better: 

    The content of the collection changed dramatically.

In order for the value to be understand correctly, I think the documentations should line up regarding on what this value should or is used for.

See [this issue over at WinUI](https://github.com/microsoft/microsoft-ui-xaml/issues/1379) for more context.

**Comment by mairaw** [comment]
Thanks for your feedback @chingucoding. Would you like to submit a PR to fix this? And then we can get the dev team to review the change.
Here's some info about that: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by mairaw** [comment]
I also noticed that this would match what's in the source code: https://source.dot.net/#System.ObjectModel/System/Collections/Specialized/NotifyCollectionChangedAction.cs,33

**Comment by GF-Huang** [comment]
So how can I access the `OldItems` when I got a `Reset` which casued by `.Clear()`?
