### ISSUE TITLE
There is a dead link to get PossessProperty xml schema

### ISSUE THREAD

**Issue by vp40** [dotnet/dotnet-api-docs#3258]
This link is dead:
http://schemas.xmlsoap.org/ws/2005/05/identity/right/PossessProperty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee00e326-b334-8b60-2283-e508275208e2
* Version Independent ID: 14e26578-4f61-3776-30d0-04832caa6a56
* Content: [Rights.PossessProperty Property (System.IdentityModel.Claims)](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.claims.rights.possessproperty?view=netframework-4.7.2)
* Content Source: [xml/System.IdentityModel.Claims/Rights.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Claims/Rights.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I'm closing this issue. The value is no longer styled as link and the value returned by the property is correct:
https://referencesource.microsoft.com/#System.IdentityModel/System/IdentityModel/Claims/Rights.cs
