### ISSUE TITLE
Duplexing support is incomplete in PrintTicket and PrintCapabilities

### ISSUE THREAD

**Issue by KutanaDev** [dotnet/dotnet-api-docs#3282]
The documentation source files `dotnet-api-docs/xml/System.Printing/PrintTicket.xml`   and `PrintCapabilities.xml` both describe printer Duplexing support, and both have a Remark saying:

This property corresponds to the [Print Schema](https://go.microsoft.com/fwlink/?LinkId=186397)'s `JobDuplexAllDocumentsContiguously` keyword, not the `DocumentDuplex` keyword.  

I'm puzzled that the printing schema contains _two_ keywords for duplex support but the accompanying classes only support _one_ of them.  Ideally I'd like the classes modified to support _both_ schema keywords, or (failing that) some new note in the documentation suggesting what to do if the Printer Driver reports duplex behaviour using `DocumentDuplex` rather than `JobDuplexAllDocumentsContiguously.` Both classes are sealed, so cannot be extended to add the new behaviour - the classes themselves would need to change.

**Comment by mairaw** [comment]
@merriemcgaw @karelz do you know which team would own System.Printing?

**Comment by karelz** [comment]
That is .NET Framework I assume. I have no idea, but @tarekgh will likely know where to route it ...

**Comment by mairaw** [comment]
Apparently they're in .NET Core too:
![image](https://user-images.githubusercontent.com/12971179/66529948-52792b00-eaba-11e9-8b3f-b8aecacf1797.png)

**Comment by karelz** [comment]
Oh, it is `System.Drawring.Printing` -- I think @safern will know about that more ...

**Comment by safern** [comment]
This is definitely not `System.Drawing.Printing` this is under `System.Printing` and it is part of `ReachFramework.dll` which is from `WPF` (I know it is very confusing as in `System.Drawing.Common` we have printing APIs as well 😄)

@vatsan-madhavan @rladuca should know more

**Comment by rladuca** [comment]
As far as I can tell the WPF does only support `JobDuplexAllDocumentsContiguously`.  A change to `System.Printing` to support this would have to be filed as a feature request in [WPF](https://github.com/dotnet/wpf) and then we can triage it accordingly.

I don't have any specific guidance on what to do if a printer reports via `DocumentDuplex`.

**Comment by mairaw** [comment]
So it seems this is a product request and there's no specific guidance to be added, I'm closing this doc issue then. Thanks!
