### ISSUE TITLE
The documented Default Http Request version is incorrect.

### ISSUE THREAD

**Issue by dotMorten** [dotnet/dotnet-api-docs#3319]
Currently the doc is listing the default HTTP version for .NET Core 2.1+ to be v2.0, when in fact it's 1.1.

This page says .NET Core 2.1+ uses HTTP/2 by default:
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.version?view=netcore-3.0#property-value
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpRequestMessage.xml#L464

But here's where the version is being set:
https://github.com/dotnet/corefx/blob/release/3.0/src/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs#L195

That version comes from this constant which says 1.1 (except for UWP):
https://github.com/dotnet/corefx/blob/release/3.0/src/System.Net.Http/src/System/Net/Http/HttpUtilities.cs#L17

/cc @karelz

**Comment by mairaw** [comment]
Thanks @dotMorten. This was a breaking change introduced in 3.0 and the fix was done in PR #3285. 

If you see the line you're referencing on this repo, you'll see that it says it's 2.0 only for .NET Core 2.1 or 2.2.

That fix should be live in a few hours.

**Comment by dotMorten** [comment]
@mairaw Nice! You beat me to it!

**Comment by karelz** [comment]
Super fast! 😮
Thanks @mairaw!

And thanks @dotMorten for reporting it ...
