### ISSUE TITLE
Directory.EnumerateFiles documentation is misleading

### ISSUE THREAD

**Issue by danielmarbach** [dotnet/dotnet-api-docs#3356]
The `Directory.EnumerateFiles` documentation seems to indicate that the return values are Directory Names only. This is metioned and hinted multiple times. Only if you look closer at the Return value definition you actually see that  full names including paths are returned. Maybe I'm the only one that fell into this trap but I think the documentation should be improved to make it clear that full names including path are returned.

![image](https://user-images.githubusercontent.com/174258/66953397-b7a2c280-f05e-11e9-9b22-b4eef079dff6.png)

So my suggestion is to either change the occurrence of _directory names_  to _directory full names_ or to _ full names_ or _full names (including paths) like mentioned in the returns documentation

**Comment by carlossanlop** [comment]
Thanks for reporting.

What version of .NET were you using? There are behavior differenced between Framework and Core. We need to make sure to explain them.

cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
The behavior hasn't changed. It's "essentially" the full path based on the passed in path. The exact rules are sort of crazy, but we've kept them for compatibility. You can see the full details in this method:

https://source.dot.net/#System.IO.FileSystem/System/IO/Enumeration/FileSystemEntry.cs,77a3d4d002575f14,references

**Comment by danielmarbach** [comment]
😍😎
