### ISSUE TITLE
System.IO.Path.Join example code doesn't produce commented output

### ISSUE THREAD

**Issue by bbarry** [dotnet/dotnet-api-docs#3367]
The C# code example at the bottom of https://docs.microsoft.com/en-us/dotnet/api/system.io.path.join?view=netcore-3.0#System_IO_Path_Join_System_ReadOnlySpan_System_Char__System_ReadOnlySpan_System_Char__System_ReadOnlySpan_System_Char__

has a WriteLine:

        Console.WriteLine($"   {Path.GetFullPath(result)}");

which is not present in the output.

**Comment by carlossanlop** [comment]
Thanks for reporting. 

What version of.NET did you use? There are some behavior differences between Framework and Core. 

cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
The rules have not changed here. The sample just isn't showing the given `WriteLine`.
