### ISSUE TITLE
Distinguish between SDKs in .NET Core documentation

### ISSUE THREAD

**Issue by rladuca** [dotnet/dotnet-api-docs#3375]
This is a general documentation issue that came up from a specific instance of confusion in https://github.com/dotnet/wpf/issues/2045.

For instance, the documentation for [ICollectionView](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.icollectionview?view=netcore-3.0) contains the following called out binaries:

![image](https://user-images.githubusercontent.com/20006987/67125137-f17fe000-f1a8-11e9-8bc1-9120a5401e50.png)

However, in .NET Core 3.0 and above, `WindowsBase.dll` exists in both `Microsoft.NETCore.App` and  `Microsoft.WindowsDesktop.App`.  This can be confusing as developers won't know they are required to use the `Microsoft.WindowsDesktop.App` in order to get this functionality.

I believe a reasonable fix would be to, for .NET Core APIs, also include the specific shared SDK that the API is present in.  In the above scenario, something like:

![image](https://user-images.githubusercontent.com/20006987/67125533-e0839e80-f1a9-11e9-8db9-c7d0dc2367ea.png)

Would help to eliminate confusion in the case where a DLL exists in multiple places in .NET Core.

**Comment by BillWagner** [comment]
Moved to MicrosoftDocs/feedback#2067

This would have to be fixed by the site engineering team.
