### ISSUE TITLE
FileSecurity parameter is described as an enum

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3377]
This parameter is an instance of the [FileSecurity class](https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.filesecurity?view=netcore-3.0), not an enum value.

It should be reworded because it sounds like it's describing an enum value:
https://github.com/dotnet/dotnet-api-docs/blob/514e781bd6ca1ea8c68bb9cf9b05b4949c81e1a3/xml/System.IO/File.xml#L1195

**Comment by carlossanlop** [comment]
I forgot i had already opened a PR to fix this https://github.com/dotnet/dotnet-api-docs/pull/3352

**Comment by mairaw** [comment]
Thanks @carlossanlop. Good catch! Added to our backlog and the up-for-grabs label.
