### ISSUE TITLE
CacheExtensions.Get undefined

### ISSUE THREAD

**Issue by breyed** [dotnet/dotnet-api-docs#3442]
Does [CacheExtensions.Get](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheextensions.get) return null or throw (or do something else) if the key isn't found?

This a core question with no obvious answer (there are arguments for each way of doing it). IntelliSense and the docs need this basic information for the caching part of .NET Core to be ready for prime time.

**Comment by mairaw** [comment]
Thanks for your feedback @breyed. We're adding more and more docs each month and we'll start looking into the missing extensions API docs next quarter. /cc @carlossanlop 

Perhaps @davidfowl or @Tratcher can help here but the source is here:
https://source.dot.net/#Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs

**Comment by Tratcher** [comment]
It returns null.

**Comment by maryamariyan** [comment]
Closing as answered. It's annotated as per PR https://github.com/dotnet/runtime/pull/64018
