### ISSUE TITLE
.NET Version dropdown is inconsistent with displayed content and "Applies to" section

### ISSUE THREAD

**Issue by johndaintree** [dotnet/dotnet-api-docs#3445]
I suspect that this is a problem with many pages, but, for example, the page:

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedtype

Shows LPUTF8Str as a valid member AND shows Xamarin.iOS in the "Applies to" section. However LPUTF8Str is NOT implemented in Xamarin.

It's only when one selects Xamarin.iOS from the the "Version" drop down that the LPUTF8Str member disappears from the document. 

IMO it would be more helpful/intuitive if the member LPUTF8Str was annotated to indicate that it is NOT available on all platforms.

Similarly:

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal?view=netcore-3.0

Shows StringToCoTaskMemUTF8 as a member AND includes "Xamarin.iOS" in the "Applies to" section. However this function is NOT in the Xamarin implementation.

**Comment by mairaw** [comment]
Thanks @johndaintree for your feedback. That's a bit tricky to solve since the information in the Applies to section is about the class and not the individual fields. I'll move this issue to the MicrosoftDocs/feedback for discussion with the engineering team.

**Comment by mairaw** [comment]
This issue was moved to MicrosoftDocs/feedback#2166
