### ISSUE TITLE
Defective rendering of docs for LoggingEventSource

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/dotnet-api-docs#3447]
docs: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.eventsource.loggingeventsource
source: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Logging.EventSource/LoggingEventSource.xml

**Comment by mairaw** [comment]
It's not really a rendering issue but a problem with how these docs were done in the first place:
https://source.dot.net/#Microsoft.Extensions.Logging.EventSource/LoggingEventSource.cs,14

But I'll move the content of the summary to the remarks to fix this.
