### ISSUE TITLE
"Edit" button seems to link to wrong page

### ISSUE THREAD

**Issue by jzabroski** [dotnet/dotnet-api-docs#3467]
Hi,

I wanted to fix an "error of omission" on the `[SqlConnectionStringBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.applicationname?view=netframework-4.8)` class documentation, but when I click Edit, it sends me to the following GitHub page, which doesn't match at all the page I was just on: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlConnectionStringBuilder.xml

I've included two screenshots so that it's obvious to whoever is reading this that there may be something seriously wrong.

![image](https://user-images.githubusercontent.com/447485/68620625-e4020100-049b-11ea-852e-cfe0ff8cd11f.png)

![image](https://user-images.githubusercontent.com/447485/68620700-16abf980-049c-11ea-9da3-60a2ab814607.png)

**Comment by mairaw** [comment]
The edit button takes you to a file that has the documentation for all the APIs inside a class.

Those remarks are found at https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=netframework-4.8#remarks. 

The content for ApplicationName starts at https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlConnectionStringBuilder.xml#L238.

Does that help?
