### ISSUE TITLE
System.Security.Cryptography. CngKey.Import doesn't work on Linux.

### ISSUE THREAD

**Issue by VladislavMorozov** [dotnet/dotnet-api-docs#3503]
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cngkey.import?view=netcore-2.2#System_Security_Cryptography_CngKey_Import_System_Byte___System_Security_Cryptography_CngKeyBlobFormat_

Please add a remark to the documentation that this method doesn't work on Linux.

**Comment by mairaw** [comment]
Thanks @VladislavMorozov for your feedback. @bartonjs can you confirm that?

**Comment by bartonjs** [comment]
Nothing with CNG in the name works on non-Windows systems.  Including CngKey.Import.

**Comment by VladislavMorozov** [comment]
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Windows Cryptography Next Generation (CNG) is not supported on this platform.
  Source=System.Security.Cryptography.Cng
  StackTrace:
   at System.Security.Cryptography.CngKeyBlobFormat.get_Pkcs8PrivateBlob()

I run it on Linux container in docker.

**Comment by mairaw** [comment]
Ok, thanks for confirming. I'm adding this to our backlog.
