### ISSUE TITLE
LoggingEventSource remarks section is malformed: code snippets are displayed incorrectly

### ISSUE THREAD

**Issue by NikiforovAll** [dotnet/dotnet-api-docs#3508]
Please see: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.eventsource.loggingeventsource?view=dotnet-plat-ext-3.0

Expected result: code snippets are rendered in standard way

**Comment by NikiforovAll** [comment]
Found related closed issue: #3447

**Comment by mairaw** [comment]
Thanks @NikiforovAll for the feedback. That's exactly the same issue. The fix I made last week is currently building and should be pushed into production in the next 30-60 minutes.

The example will look like this:
![image](https://user-images.githubusercontent.com/12971179/69080926-c2e86580-09f1-11ea-9a4a-5c2bc6b93256.png)
