### ISSUE TITLE
some documentation would be nice

### ISSUE THREAD

**Issue by Ttxman** [dotnet/dotnet-api-docs#3513]
what does length stands for in this case? (i'm going to read source code...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54fc2a5d-b460-3579-46f2-8ea7e964be79
* Version Independent ID: 1a7f2054-8134-3dd3-550b-50094bbef749
* Content: [MemoryMarshal.CreateSpan(T, Int32) Method (System.Runtime.InteropServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.createspan?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Runtime.InteropServices.MemoryMarshal.CreateSpan%60%601);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-2.1)
* Content Source: [xml/System.Runtime.InteropServices/MemoryMarshal.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices/MemoryMarshal.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by carlossanlop** [comment]
Hello @Ttxman, not sure what you mean. The `length` parameter is documented in [the MS Docs page](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.createspan?view=netcore-3.0) for `MemoryMarshal.CreateSpan`:

> The number of T elements that reference contains.

**Comment by Ttxman** [comment]
The documentation is perfectly fine now..
But I'm pretty sure there were no details visible 1 year and 4 moths ago, just argument names without any text.

**Comment by carlossanlop** [comment]
Right. It [got documented in the last year](https://github.com/dotnet/dotnet-api-docs/blame/8d5e275f30bc2271f565e1ec1f485337cb3c0202/xml/System.Runtime.InteropServices/MemoryMarshal.xml#L483). We've been slowly adding documentation to all the .NET APIs that are missing it. Thanks for reporting this.
If you have any more comments/suggestions, let us know. I'll close as it seems to be resolved.
