### ISSUE TITLE
TrySetCanceled(CancellationToken cancellationToken) availability is wrong

### ISSUE THREAD

**Issue by 0xced** [dotnet/dotnet-api-docs#3534]
[TrySetCanceled(CancellationToken cancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1.trysetcanceled?view=netframework-4.8#applies-to) is documented to be available for the following versions of .NET Framework: 4.8 4.7.2 4.7.1 4.7 4.6.2 4.6.1 4.6 4.5.2 4.5.1 4.5 4.0

It is actually only available since version 4.6, which is actually correct in the [source](https://github.com/dotnet/dotnet-api-docs/blob/44250ea610ccb67d83e0a139e4b6b094f0d8e6fe/xml/System.Threading.Tasks/TaskCompletionSource%601.xml#L500-L505), but not properly reflected on the aforementioned public documentation.

**Comment by mairaw** [comment]
Thanks for your feedback @0xced. This is being tracked at https://github.com/MicrosoftDocs/feedback/issues/314.
