### ISSUE TITLE
System.IO.Path documentation claims that some platforms limit file extensions to three characters

### ISSUE THREAD

**Issue by jyrkive** [dotnet/dotnet-api-docs#3579]
"The format of a file name extension is platform-dependent; for example, some systems limit extensions to three characters, and others do not."

https://github.com/dotnet/dotnet-api-docs/blob/3a6c7ff2a7723d194b2d3109a47f42d3bf2bbfed/xml/System.IO/Path.xml#L44

The last major desktop platform that limited file extensions to three characters was Windows 3.x. .NET, neither Framework nor Core, has never supported it. I'm not aware of any other platforms .NET has ever supported with a three-character limit either.

As such, I suggest removing the remark about three-character extensions.

**Comment by shdvr** [comment]
Some filesystems still in use today limit filenames to 8.1, including FAT16/32 commonly used on flash storage and ISO 9660  used on CDs. Granted, modern implementations of FAT include long file name support and ISO 9660 Level 2 & above supports longer names as well, but I do not believe removing this remark is justified as it is useful to know there _may_ be limitations depending on the filesystem driver the app ends up working with.

**Comment by jyrkive** [comment]
So the remark is about **file** systems?

> The format of a file name extension is platform-dependent; for example, some systems limit extensions to three characters, and others do not.

The wording only talks about "platforms" and "systems" and it didn't really give me the impression that it's about file systems.

**Comment by shdvr** [comment]
> So the remark is about **file** systems? 

It's a bit more complicated than that. Don't know the original author's intent here, but both the **file** system and the **operating** system may affect what is a valid file name. And even for the same file system and same OS it may depend on the file system **driver** in use. Perhaps a combination of all three is what they meant by **system**?
Don't get me wrong, ≫99% of the time you would not have to worry about any of this for file extensions today, but I do think that this comment has value beyond a purely historical one.

**Comment by eiriktsarpalis** [comment]
Tagging @adamsitnik @carlossanlop @jozkee for triage.

**Comment by carlossanlop** [comment]
> The last major desktop platform that limited file extensions to three characters was Windows 3.x. .NET

Since an API documentation is shared for all the versions where that API existed, we need to keep remarks like this one, making sure we specify which API has such restriction.

Here's my suggestion: We can expand the remark and be more specific about which particular .NET versions had this restriction, as well as which OS/platforms have that restriction (if any).

@jyrkive @shdvr would any of you be interested in submitting a PR to fix this?
