### ISSUE TITLE
Incorrectly rendered xref link

### ISSUE THREAD

**Issue by svick** [dotnet/dotnet-api-docs#3586]
[The remarks for `MethodBase.Invoke(Object, Object[])`](https://docs.microsoft.com/en-us/dotnet/api/System.Reflection.MethodBase.Invoke?view=netframework-4.7#System_Reflection_MethodBase_Invoke_System_Object_System_Object___) contain an `xref` link to the other overload (`MethodBase.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)`), but it renders as:

> [Invoke(Object, BindingFlags, Binder, Object\<xref:System.Reflection.MethodBase.Invoke%28System.Object%2CSystem.Reflection.BindingFlags%2CSystem.Reflection.Binder%2CSystem.Object%5B%5D%2CSystem.Globalization.CultureInfo%29>

![](https://cloud.githubusercontent.com/assets/287848/25103514/27999b7a-23bd-11e7-8901-8cb711544868.png)

[The source](https://github.com/dotnet/docs/blob/17edc15/xml/System.Reflection/MethodBase.xml#L654) seems to be fine, so my guess is that this is some issue with converting `xref` links to markdown, likely caused by the presence of encoded square brackets in the link.

**Comment by carlossanlop** [comment]
@guardrex have you had a chance to get all the instances of this issue fixed?

**Comment by guardrex** [comment]
@carlossanlop ... I moved to the ASP.NET Core docs a few years ago. I'm not sure where this stands today

**Comment by gewarren** [comment]
I think this issue can be closed. I checked and the `~/includes` and `~/samples` links are rendering correctly in the few that I checked.

- See the Notes to Callers section of [Convert.ChangeType](https://docs.microsoft.com/en-us/dotnet/api/system.convert.changetype?view=netcore-3.1#System_Convert_ChangeType_System_Object_System_Type_).
- [GetControlInstanceType](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.compatibility.vb6.basecontrolarray.getcontrolinstancetype?view=netframework-4.7#Microsoft_VisualBasic_Compatibility_VB6_BaseControlArray_GetControlInstanceType).

There's a separate issue in the GetControlInstanceType type, where [this information probably shouldn't be in the return block](https://github.com/dotnet/dotnet-api-docs/blob/7e69b7f156d4b65663e15b404ea203ca44fb055a/xml/Microsoft.VisualBasic.Compatibility.VB6/BaseControlArray.xml#L586), but I don't think it's worth fixing.
