### ISSUE TITLE
Evaluate BinarySerialization documentation, samples

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/dotnet-api-docs#3613]
## Evaluate BinaryFormatter documentation and samples

Because the use of [BinaryFormatter](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter) is not recommended, we should:

- Display the existing warning that appears in the **BinaryFormatter** class documentation and the documentation of selected **BinaryFormatter** members in the documentation for all **BinaryFormatter** members.
- Remove the BinaryFormatter and SoapFormatter examples.
- Replace existing examples, such as the existing date and time serialization examples, with serialization examples that use JSON serialization.

Consider C#, C++, VB, and F# snippets.

See [Remove BinaryFormatter from the shared framework in .NET 5](https://github.com/dotnet/corefx/issues/38760).

---
[Associated WorkItem - 90993](https://dev.azure.com/msft-skilling/Content/_workitems/edit/90993)

**Comment by carlossanlop** [comment]
@GrabYourPitchforks you were working on this, I believe. Can we update this issue or close it if the work is done?
