### ISSUE TITLE
Roslyn API reference is empty for older versions

### ISSUE THREAD

**Issue by svick** [dotnet/dotnet-api-docs#3652]
[The API reference for Roslyn is now versioned](https://docs.microsoft.com/en-us/dotnet/api/?view=roslyn-dotnet), which is great:

![](https://user-images.githubusercontent.com/287848/70447024-57e4f880-1a9e-11ea-9a37-38b38f325726.png)

[But the older versions of Roslyn that are included seem to be empty:](https://docs.microsoft.com/en-us/dotnet/api/?view=roslyn-dotnet-3.3.1)

![](https://user-images.githubusercontent.com/287848/70447099-7c40d500-1a9e-11ea-8cb7-80b3ab35e999.png)

Personally, I don't think documenting older versions of the Roslyn to be that important, so I would be fine if the older versions were just removed. But if they are included in the version selection, they should not be empty.

**Comment by mairaw** [comment]
We have a new feature now that auto indexes the content after new publishing. So it seems that it got sorted out since you filed.
