### ISSUE TITLE
Reference on page of "RsaProtectedConfigurationProvider Class" pointed to a out-of-support page

### ISSUE THREAD

**Issue by shampeter** [dotnet/dotnet-api-docs#3677]
The reference on "Walkthrough: Encrypting Configuration Information using Protected Configuration" in the "See Also" section of the "RsaProtectedConfigurationProvider Class" ended up on a page which, from what I understood, meant out-of-support.

I was reading "RsaProtectedConfigurationProvider Class" on the following URL:
https://docs.microsoft.com/en-us/dotnet/api/system.configuration.rsaprotectedconfigurationprovider?view=netcore-3.1

And the out-of-support page mentioned was:
https://docs.microsoft.com/en-us/previous-versions/dtkwfdky(v=vs.140)?redirectedfrom=MSDN

**Comment by mairaw** [comment]
Thanks for your feedback @shampeter. It means that the documentation set is no longer being maintained. I'll change those links to go to https://docs.microsoft.com/en-us/previous-versions/aspnet/dtkwfdky(v=vs.100) since at least you get the TOC for the archived ASP.NET docs.
