### ISSUE TITLE
UriBuilder.Query behaves differently than documented on .NET Core

### ISSUE THREAD

**Issue by spanglerco** [dotnet/dotnet-api-docs#3699]
The documentation for [UriBuilder.Query](https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.query?view=netcore-3.1) has a note to "retrieve the property value as a string, remove the leading question mark, append the new query string, and set the property with the combined string" as a way to indicate a leading ? is significant in the property setter.

That's true for .NET Framework, but this behavior changed in .NET Core such that the setter is now tolerant to a leading ?. If you actually want the query string to begin with a ? you must include ?? in your Query setter. See https://github.com/dotnet/runtime/issues/1081#issuecomment-568006337.

This applies to [UriBuilder.Fragment](https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.fragment?view=netcore-3.1) as well.

**Comment by mairaw** [comment]
Thanks @spanglerco for your feedback. @Priya91 @gewarren seems like a breaking change between Framework and Core.

**Comment by gewarren** [comment]
@PriyaPurkayastha Can you investigate whether we should document this as a breaking change?

**Comment by PriyaPurkayastha** [comment]
@karelz can you please help confirm that this is a breaking change between .NET Framework and .NET Core and if yes, help create a breaking change issue for this so that it can be documented? The template for the breaking change issue is https://github.com/dotnet/docs/issues/new?template=doc-breaking-change.md

**Comment by gewarren** [comment]
Ping @karelz

**Comment by gewarren** [comment]
The breaking change was added in https://github.com/dotnet/docs/pull/18168. The API docs still need to be updated.
