### ISSUE TITLE
Classes removed from .NET Core 3.1 show up as available

### ISSUE THREAD

**Issue by mairaw** [dotnet/dotnet-api-docs#3738]
Related to #3471 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menu#applies-to should not have applies to 3.1, for example

**Comment by mairaw** [comment]
Given that API Catalog shows the same information, this might be a bad version of the assemblies 
https://apisof.net/catalog/System.Windows.Forms.Menu

/cc @RussKie @safern

**Comment by RussKie** [comment]
I just checked System.Windows.Forms in ILSpy and both 3.0 and 3.1 share the same identity

```
// C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0\System.Windows.Forms.dll
// System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Global type: <Module>
// Architecture: x64
// This assembly contains unmanaged code.
// Runtime: v4.0.30319
// Hash algorithm: SHA1
// Public key: 00000000000000000400000000000000
```

```
// C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.0\System.Windows.Forms.dll
// System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Global type: <Module>
// Architecture: x64
// This assembly contains unmanaged code.
// Runtime: v4.0.30319
// Hash algorithm: SHA1
// Public key: 00000000000000000400000000000000
```

**Comment by safern** [comment]
> I just checked System.Windows.Forms in ILSpy and both 3.0 and 3.1 share the same identity

So, is this a bug in WinForms directly?

**Comment by mairaw** [comment]
So it's not an issue with the docs @RussKie?

**Comment by RussKie** [comment]
I don't think so, I believe it is by design. 
@ericstj

**Comment by mairaw** [comment]
But then our other docs are wrong saying these controls were removed in 3.1 (breaking changes, what's new, etc.)?

**Comment by RussKie** [comment]
I would think the docs generation should go off `TargetFramework` attribute, not the identity

```
// 3.0.0
[assembly: TargetFramework(".NETCoreApp,Version=v3.0", FrameworkDisplayName = "")]
// 3.1.0
[assembly: TargetFramework(".NETCoreApp,Version=v3.1", FrameworkDisplayName = "")]
```

There's also assembly info, but I'm not sure it is a reliable indicator as we may still have .NET Framework 4.8.1...
```
// 3.0.0
[assembly: AssemblyInformationalVersion("4.8.0-rc2.19462.10+1a89b41114eb292f835ed7038fd3cba3a02896f7")]
// 3.1.0
[assembly: AssemblyInformationalVersion("4.8.1-rtm.19564.4+4bcd68c8b29476fc3c5ca1b496214584aadfdc84")]
```

**Comment by ericstj** [comment]
> I don't think so, I believe it is by design.

I've been telling both WinForms and WPF for a year now that they need to version their assemblies and deal with what breaks.  We started out keeping them the same as desktop to limp along features in VS and elsewhere that might use desktop assemblies in place of the Core assemblies, but we need to change them and fix what breaks.

**Comment by mairaw** [comment]
The docs generation goes by what's in the package. If they're present in the 3.1 Desktop SDK, our tool will just reflect over the assemblies that are there and include them.
I'm not sure how I should proceed here. Which part of docs is wrong? The one that shows this is present in 3.1 in the API docs or the conceptual docs that claim these controls were removed in 3.1?

**Comment by RussKie** [comment]
> Which part of docs is wrong?

All removed controls (e.g. `Menu`, `ContextMenu`, etc) are still listed under 3.1 version as noted in https://github.com/dotnet/docs/issues/15813#issuecomment-570129908. 
Also `Form`, `Control`, etc list removed members (e.g. `ContextMenu`, `ContextMenuChanged`, etc) - https://github.com/dotnet/docs/issues/15813#issuecomment-570393021, https://github.com/dotnet/docs/issues/15813#issuecomment-570396146

**Comment by mairaw** [comment]
Ok, but those APIs still exist in the 3.1 version of the System.Windows.Forms.dll. So  how exactly were they removed and how I can fix this? The reflection process is all automated.

**Comment by RussKie** [comment]
No, they don't exist in System.Windows.Forms.dll, and that's why the docs are incorrect.
What version of System.Windows.Forms.dll is used to generate docs for 3.1?

**Comment by mairaw** [comment]
Ok, I just downloaded the latest version from https://www.nuget.org/packages/Microsoft.WindowsDesktop.App.Ref/ and managed to confirm that indeed it's not there. The version I had gotten from \\scratch2\scratch\safern\ApiCatalogLayout\3.1\frameworks\microsoft.windowsdesktop.app.ref had those. So @safern I probably have a bad version of the ref assemblies for those (and same applies to API Catalog). I should be able to just grab the assemblies from the NuGet package and run reflection again, correct?

**Comment by safern** [comment]
> I should be able to just grab the assemblies from the NuGet package and run reflection again, correct?

Correct. Anyway, I will update the API Catalog as well. Sorry about that.

**Comment by RussKie** [comment]
Thank you!
