### ISSUE TITLE
Add note, that Calendar.GetWeekOfYear differs from ISO 8601 week of year

### ISSUE THREAD

**Issue by kapsiR** [dotnet/dotnet-api-docs#3754]
Affected docs: `/xml/System.Globalization/Calendar.xml`

Hints:
 - Workaround for .NET Framework:
https://docs.microsoft.com/en-us/archive/blogs/shawnste/iso-8601-week-of-year-format-in-microsoft-net
 - Solution from .NET Standard 2.1 onwards (>= .NET Core 3.0)
ISOWeek class
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.isoweek

**Comment by kapsiR** [comment]
I found out, that this is already in `/xml/System.Globalization/CalendarWeekRule.xml`...
But the referenced blog entry link is broken: https://go.microsoft.com/fwlink/?LinkId=160851

**Comment by rohansp** [comment]
@kapsiR @mairaw Is this already resolved or can I work on this issue? Do we need to correct the link in CalendarWeekRule.xml What about Calendar.xml?

**Comment by kapsiR** [comment]
The broken link in `/xml/System.Globalization/CalendarWeekRule.xml` has been fixed.

Nevertheless I would prefer that the remarks of [Calendar.GetWeekOfYear](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar.getweekofyear) in `/xml/System.Globalization/Calendar.xml` would be updated accordingly too.

@mairaw Would be cool if @rohansp can update the `Remarks` section of `Calendar.GetWeekOfYear` to have this information there too?

**Comment by carlossanlop** [comment]
@tarekgh can you please help triage?

**Comment by tarekgh** [comment]
The comment needed to be added looks reasonable to me. @kapsiR do you want open a PR for it?

**Comment by kapsiR** [comment]
@tarekgh Yes I can submit a PR for this, but if @rohansp wants to try it he can do it too

**Comment by rohansp** [comment]
@kapsiR go ahead.
