### ISSUE TITLE
Include params keyword in method overloads section

### ISSUE THREAD

**Issue by CallumWatkins** [dotnet/dotnet-api-docs#3756]
This is a suggestion to include the `params` parameter keyword in the method overloads section (plus in the "in this article" navigation).
This would apply to, for example, to the `Split(Char[])` overload in [System.String.Split](https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netframework-4.8#overloads).

Current:
![current](https://user-images.githubusercontent.com/18353194/72101298-4ea8af00-331c-11ea-926d-48b530690d76.png)

Suggested:
![suggestion](https://user-images.githubusercontent.com/18353194/72101286-45b7dd80-331c-11ea-827c-db55df168b86.png)

**Comment by mairaw** [comment]
This issue was moved to MicrosoftDocs/feedback#2367
