### ISSUE TITLE
Document platform differences of Socket.DuplicateAndClose() and related API-s

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/dotnet-api-docs#3774]
The docs for [Socket.DuplicateAndClose()](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.duplicateandclose), and related API-s [Socket(SocketInformation)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.-ctor?System_Net_Sockets_Socket__ctor_System_Net_Sockets_SocketInformation_), [Socket.UseOnlyOverlappedIO](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.useonlyoverlappedio) do not mention throwing `PlatformNotSupportedException` on .NET Core.

In addition, we plan to reintroduce the API-s in .NET 5, with some behavioral differences (See: dotnet/runtime#1760). The proposed differences should be documented as well. 

@mairaw I wonder if this should/could be done as part of #1683, manually, or both. Here is the compatibility matrix for the given API-s, which is a good example how far behavioral incompatibility could go between different platforms, OS-versions and .NET versions:

|  Platform          | `DuplicateAndClose()` and `Socket(SocketInformation)` | `UseOnlyOverlappedIO`        |
|--------------------|-------------------------------------------------------|------------------------------|
| .NET Framework     | ✔️ Works as documented                               | ✔️ Works as documented       |
| .NET Core + Any OS | ❌ Throws PNSE                                       | ⚠️ always false/does nothing |
| .NET 5 + Windows   | ⚠️ Supported, slightly different behavior            | ⚠️ always false/does nothing |
| .NET 5 + Any Unix  | ❌ Throws PNSE                                       | ⚠️ always false/does nothing |

Edited by gewarren to change mariaw to mairaw.

**Comment by mairaw** [comment]
Thank you @antonfirsov. Parts of this would be covered by #1683. .NET 5 behavior would be documented later.

Adding @gewarren for breaking changes between the two platforms that we're trying to document in this section: https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core and https://docs.microsoft.com/en-us/dotnet/core/compatibility/unsupported-apis

**Comment by gewarren** [comment]
@antonfirsov If the change in UseOnlyOverlappedIO from .NET Fx to .NET Core is actually a breaking change, could you fill out [this template](https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md) please?
