### ISSUE TITLE
Clarify that the StrReverse function reverses text elements, not chars

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/dotnet-api-docs#3775]
### API affected

`Microsoft.VisualBasic.Strings.StrReverse`
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.strings.strreverse

### Issue description

The API's phrasing makes it seem as if the individual `char` elements in a `string` are reversed. This is true for some strings; e.g., `StrReverse("abc")` results in `"cba"`. However, it actually reverses __text elements__ (see [the `StringInfo` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.stringinfo)).

Consider the string `"re\u0301sume\u0301"`, where `'\u0301'` is the code point `U+0301 COMBINING ACUTE ACCENT`. When displayed to the user, this will appear as the word __résumé__ with the accent correctly placed over the 'e' character.

If the `StrReverse` function were to naively reverse all the `char` elements of the string, the resulting string would be `"\u0301emus\u0301er"` and would appear as __́emuśer__ when displayed to the user, with the accents placed over the wrong characters.

Instead, the actual behavior of the `StrReverse` function is that it subdivides the input string into its individual _text elements_, keeping each text element intact but swapping the positions of each text element within the resulting string.

```txt
StrReverse("re\u0301sume\u0301") = StrReverse("r" + "e\u0301" + "s" + "u" + "m" + "e\u0301")
                                 = "e\u0301muse\u0301r"
                                 = "émusér"
```

See https://docs.microsoft.com/en-us/dotnet/api/system.globalization.stringinfo for more information on hoe the .NET Framework subdivides a string instance into text elements.

**Comment by mairaw** [comment]
Would you like to submit a PR to fix that @GrabYourPitchforks? 

The docs for that start at https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualBasic/Strings.xml#L3880
