### ISSUE TITLE
Incorrect parameter description in FocusManager.GetFocusScope

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/dotnet-api-docs#3785]
https://github.com/dotnet/dotnet-api-docs/blob/abc0627d2772d6ce3b2c624dd18162ca3faf0dd9/xml/System.Windows.Input/FocusManager.xml#L185

No, actually the 'element' parameter supplies the "specified focus scope" for which this function returns the "element with logical focus."

As shown, the docs conflate the input parameter and the return value:

> "The element with logical focus in the specified focus scope."

...is basically the same as...

> "The element in the specified focus scope with logical focus."

**Comment by mairaw** [comment]
You're right. That description is incorrect. I've opened PR #3804 to fix that but I'm asking the devs to verify my change is correct.
