### ISSUE TITLE
Migrate Microsoft.Management.Infrastructure

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#3787]
Nuget: https://www.nuget.org/packages/Microsoft.Management.Infrastructure/

Previous version docs: https://docs.microsoft.com/previous-versions/windows/desktop/wmi_v2/mi-managed-api/hh832958(v=vs.85)

Current version docs: https://docs.microsoft.com/dotnet/api/microsoft.management.infrastructure

The current version docs are empty and marked as applicable only to PowerShell, but in fact this library is compatible with .NET Standard 1.6.

**Comment by mairaw** [comment]
This issue was moved to MicrosoftDocs/feedback#2433
