### ISSUE TITLE
allow to specify default language and store it

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/dotnet-api-docs#3814]
Please, please... allow us to save the language we want to use when reading the documentation.
Save it in LocalStorage, in cookie, wherever but please do that :)

There is language selection at the bottom of the page but the selection doesn't get stored and so everytime I google for something and I'm taken to the https://docs.microsoft.com/ I'm presented to my local language, while I want to stick to english.

This is very annoying
Thanks.

**Comment by mairaw** [comment]
Thank you for your feedback @MithrilMan. We already have this issue being tracked at https://github.com/MicrosoftDocs/feedback/issues/462. So closing this one as duplicate.
