### ISSUE TITLE
DateTime.Subtract documentation has incorrect return type for first overload

### ISSUE THREAD

**Issue by DavidWBrooks** [dotnet/dotnet-api-docs#3835]
Subtract(DateTime) | Returns a new DateTime that subtracts the specified date and time from the value of this instance.

Should be "Returns a new TimeSpan that is equal to the date and time represented by this instance minus the specified date and time".

The text appears twice. I can see the text in the markup but not sure how to submit the fix.

This may be a dup of #2640, but the fix doesn't appear in docs.microsoft.com.

**Comment by carlossanlop** [comment]
@tarekgh can you please take a look?

**Comment by tarekgh** [comment]
@DavidWBrooks looking at the docs https://docs.microsoft.com/en-us/dotnet/api/system.datetime.subtract?view=netcore-3.1 I am seeing everything is correct there. which docs you are referring to?

**Comment by DavidWBrooks** [comment]
I guess it got fixed in some update between February and now. I can't see the specific update in git history (and not familiar enough with the blame feature), but picking a commit from 11 months ago, c5faff8461, I can see the incorrect text. So you can close either as Fixed or NR. Thanks.

One day I'll get more comfortable with pull requests so I wouldn't need to do this random probing.

**Comment by DavidWBrooks** [comment]
Actually, I opened it so I can close it. It seems to have been fixed incidentally some time since February,

**Comment by DavidWBrooks** [comment]
I found the fix:   d7dc8f4ca897c1a5d063522fd4cfb6e887909102, from Mar 5. Sorry to be so noisy on email over a little thing.
