### ISSUE TITLE
LogLevel enum documentation is out of order.

### ISSUE THREAD

**Issue by PaulStegler** [dotnet/dotnet-api-docs#3847]
It would be nice to order the enum values based on their numeric value. Right now it is ordered 5,1,4,2,6,0,3 which is mildly annoying.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel

https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Extensions.Logging/LogLevel.xml

**Comment by PaulStegler** [comment]
I'm not sure if this documentation is autogenerated somehow but if not I created a pull request which should resolve this issue.

https://github.com/dotnet/dotnet-api-docs/pull/3849

**Comment by mairaw** [comment]
It is auto-generated and the default ordering is based on field name. You can see some discussion around this at https://github.com/MicrosoftDocs/feedback/issues/351.
