### ISSUE TITLE
FieldBuilder.SetValue for static init-only fields in .NET Core 3.0+

### ISSUE THREAD

**Issue by n9** [dotnet/dotnet-api-docs#3851]
The documentation says:

https://github.com/dotnet/dotnet-api-docs/blob/eb7cd6ec7fe65807ae94c55bc152a128a8224014/xml/System.Reflection.Emit/FieldBuilder.xml#L941

For static init-only fields, this workaround was working in .NET Framework, however this is no longer supported in .NET Core 3.0+ (see https://github.com/dotnet/runtime/issues/11571#issuecomment-442675193).

So, how to initialize static init-only field of dynamic type in .NET Core 3.0+?
It would be great if the documentation will provide this hint:)

**Comment by mairaw** [comment]
@jkotas can you help with this feedback? Would this be a breaking change between Framework and Core? /cc @gewarren

**Comment by jkotas** [comment]
I have submitted https://github.com/dotnet/dotnet-api-docs/pull/3869/ with the doc update.

> So, how to initialize static init-only field of dynamic type in .NET Core 3.0+?

The best way to initialize static init-only fields is by code in static constructor. This applies equally to both dynamic and non-dynamic types.

**Comment by n9** [comment]
@jkotas There is a use case of passing references to static initonly fields described here https://stackoverflow.com/q/60061066/121968 (see comments to this question). What is an "official" recommended solution for this particular use case in .NET Core 3.0+?

**Comment by jkotas** [comment]
Option 1: Remove `FieldAttributes.InitOnly` from the type field attributes. This is the easiest.
Option 2: Add static constructor to the type (ie call `typeBuilder.DefineDefaultConstructor(MethodAttributes.Static)`) and emit code to initialize the static field into this static constructor.

**Comment by gewarren** [comment]
Besides #3869, we also need to update the FieldBuilder.SetValue recommendation. I'll change "fixes" to "contributes to" in #3869.

**Comment by gewarren** [comment]
It's a breaking change between .NET Framework and .NET Core, but it's also a breaking change between .NET Core versions. So, I don't think it belongs in the [.NET Framework -> .NET Core breaking changes article](https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core), but rather the [2.2-3.0](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0) and 2.2-3.1 articles. Thoughts on this more generally? @PriyaPurkayastha

**Comment by PriyaPurkayastha** [comment]
Yes, on reading through #3869, this is a breaking change introduced in .NET Core 3.0, so 2.x to 3.x articles will feature this. It is a bit tricky - breaking changes introduced in .NET Core in any release would typically be between .NET Framework and .NET Core as well but I am not sure how we manage the documentation. Currently, .NET Framework to .NET Core article is primarily for WPF/Winforms introduced in 3.0 and any breaking changes introduced prior to .NET Core 2.x that have been observed by customers and are being retroactively documented on a case-by-case basis.

**Comment by jkotas** [comment]
> Besides #3869, we also need to update the FieldBuilder.SetValue recommendation.

`FieldBuilder.SetValue` recommendation looks fine to me. 

`FieldInfo.SetValue` throws exceptions for number of different situations that it does not handle. None of them are mentioned in the FieldBuilder.SetValue recommendation. I do not think it makes sense to duplicate the content to mention them.

**Comment by gewarren** [comment]
> `FieldBuilder.SetValue` recommendation looks fine to me.
> 
> `FieldInfo.SetValue` throws exceptions for number of different situations that it does not handle. None of them are mentioned in the FieldBuilder.SetValue recommendation. I do not think it makes sense to duplicate the content to mention them.

Makes sense, I changed the 3869 PR comment back to "fixes". Thanks!
