### ISSUE TITLE
Update doc for AssemblyLoadContext

### ISSUE THREAD

**Issue by JojoEffect** [dotnet/dotnet-api-docs#3878]
Hi all,

I just noticed that the docs for the AssemblyLoadContext class seems to be outdated.

At least this 
https://github.com/dotnet/dotnet-api-docs/blob/49bc77c1122713c4519ec8870ae4c5faa0397d4c/xml/System.Runtime.Loader/AssemblyLoadContext.xml#L32
is not correct anymore since .net core 3.0 as far as I can judge.

See [this issue](https://github.com/dotnet/runtime/issues/28491).

I hope this is the right place to mention this!?

Thank you for your effort.

**Comment by mairaw** [comment]
Thanks @JojoEffect. This is the right place indeed. 

@sdmaclea can you take a look at the API docs for this class?
This is potentially a breaking change for .NET Core and between Core and Framework.
We'd need a breaking change issue filed as well @sdmaclea. 

/cc @gewarren

**Comment by sdmaclea** [comment]
Yes it was an abstract class in 2.x, but in 3.0 it got a concrete implementation.  The API review board decided this was not a breaking change.

It wasn't clear how to document this.

This class was not present in `.NET Framework`.

**Comment by sdmaclea** [comment]
@mairaw I am happy to make a change, but I do not really know how.  I believe everything else from that API review was handled.

/cc @vitek-karas @elinor-fung

**Comment by mairaw** [comment]
My bad. I didn't look at the docs online to see the applies to section.

The content inside the remarks is in Markdown:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.Loader/AssemblyLoadContext.xml#L32

**Comment by CoffeeFlux** [comment]
This bit one of the Xamarin guys with the .NET 5 migration, so I'd really like to get it fixed and will happily submit a patch. Should I just say in the markdown that the comment only applies to earlier versions of .NET Core, or is there a way to make a section of the markdown conditional on the selected version? @mairaw
