### ISSUE TITLE
Update DataTable.Merge Method example

### ISSUE THREAD

**Issue by kdbdevops** [dotnet/dotnet-api-docs#3883]
In the example code for Merge(DataTable, Boolean):

table1Copy.Merge(modifiedTable, false);
PrintValues(modifiedTable, "Merged data (don't preserve changes)");

should be

table1Copy.Merge(modifiedTable, false);
PrintValues(table1Copy, "Merged data (don't preserve changes)");

**Comment by mairaw** [comment]
Thank you @kdbdevops. I've opened a PR to fix that.
