### ISSUE TITLE
Documentation plan for 1.0+ Runtime APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3904]
The plan is to document all APIs introduced in version 1.0 in the next 3 months, ensuring we document 1/3 of them at the end of every month.

The effort begins on February 24th.

1) 33% milestone: March 24th.
2) 66% milestone: April 24th.
3) 100% milestone: May 24th.

The following table lists the total number of undocumented APIs per namespace and the version where they were introduced.
_Note: Undocumented APIs in the 2.0 and 3.0 columns are debt from the previous efforts._

CC @danmosemsft @karelz @ericstj @jeffhandley @stephentoub

### All APIs

Version | 1.0 | 2.0 | 3.0 | Grand Total
--- | --- | --- | --- | ---
**Undoc APIs** | **639** | **166** | **21** | **826** | 

### APIs owned by the Libraries team

Namespace\Version | 1.0 | 2.0 | 3.0 | Grand Total | Owner
--- | --- | --- | --- | --- | ---
System.Reflection | 204 | 10 | 0 | 214 | @steveharter @GrabYourPitchforks
System.Reflection.PortableExecutable | 136 | 0 | 0 | 136 | @steveharter @GrabYourPitchforks
System.Collections.Immutable | 69 | 3 | 0 | 72 | @eiriktsarpalis @layomia
System.Reflection.Emit | 32 | 13 | 0 | 45 | @steveharter @GrabYourPitchforks
System.Xml.Serialization | 45 | 0 | 0 | 45 | @buyaa-n @krwq
System.Net.Security | 0 | 40 | 0 | 40 | @dotnet/ncl
System.Text.RegularExpressions | 0 | 39 | 0 | 39 | @pgovind @eerhardt
System | 22 | 3 | 0 | 25 | Various
System.Security.Cryptography.Pkcs | 4 | 18 | 0 | 22 | @bartonjs @GrabYourPitchforks @krwq
System.Diagnostics | 15 | 1 | 0 | 16 | @tommcdon @sywhang @krwq
System.Net.Http | 2 | 13 | 0 | 15 | @dotnet/ncl 
System.Threading.Tasks.Dataflow | 12 | 0 | 0 | 12 | @tarekgh @stephentoub
System.Collections.Generic | 0 | 10 | 0 | 10 | @eiriktsarpalis @layomia
System.Xml | 9 | 0 | 0 | 9 | @buyaa-n @krwq
System.Security.Cryptography | 7 | 2 | 0 | 9 | @bartonjs @GrabYourPitchforks @krwq
System.Threading | 7 | 0 | 0 | 7 | @kouvel
System.Drawing | 0 | 6 | 0 | 6 | @JeremyKuhne @maryamariyan
System.IdentityModel.Selectors | 0 | 0 | 6 | 6 | @HongGit @StephenBonikowsky @mconnew 
Microsoft.Win32.SafeHandles | 6 | 0 | 0 | 6 | @maryamariyan @Anipik
System.Runtime.CompilerServices | 6 | 0 | 0 | 6 | @Anipik @steveharter
System.Runtime.InteropServices | 5 | 0 | 0 | 5 | @AaronRobinsonMSFT @jkoritzinsky
System.Net | 5 | 0 | 0 | 5 | @dotnet/ncl
System.Security.AccessControl | 5 | 0 | 0 | 5 | @bartonjs @GrabYourPitchforks @krwq
System.Security.Authentication.ExtendedProtection | 5 | 0 | 0 | 5 | @bartonjs @GrabYourPitchforks @krwq
Microsoft.Win32 | 4 | 0 | 0 | 4 | @maryamariyan @Anipik
System.ServiceModel.Channels | 4 | 0 | 0 | 4 | @HongGit @StephenMolloy @StephenBonikowsky @mconnew 
System.ComponentModel | 3 | 0 | 0 | 3 | @JeremyKuhne @safern
System.Linq | 3 | 0 | 0 | 3 | @eiriktsarpalis
System.Security.Permissions | 0 | 3 | 0 | 3 | @bartonjs @GrabYourPitchforks @krwq
System.ServiceModel | 3 | 0 | 0 | 3 | @StephenMolloy @StephenBonikowsky @mconnew 
System.Collections | 0 | 3 | 0 | 3 | @eiriktsarpalis @layomia
System.Net.Mime | 0 | 2 | 0 | 2 | @dotnet/ncl
System.Net.NetworkInformation | 1 | 0 | 0 | 1 | @dotnet/ncl
System.ServiceProcess | 1 | 0 | 0 | 1 | @Anipik
System.Security.Principal | 1 | 0 | 0 | 1 | @bartonjs @GrabYourPitchforks @krwq
**Undoc APIs** | **616** | **166** | **6** | **788** | 

### APIs owned by System.Data

Namespace\Version | 1.0 | 2.0 | 3.0 | Grand Total | Owner
--- | --- | --- | --- | --- | ---
System.Data.SqlClient | 13 | 0 | 0 | 13 | @cheenamalhotra @david-engel @karinazhou @JRahnama
System.Data.Common | 10 | 0 | 0 | 10 | @ajcvickers @cheenamalhotra @david-engel
**Undoc APIs** | **23** | **0** | **0** | **23** | 

### APIs owned by WinForms

Namespace\Version | 1.0 | 2.0 | 3.0 | Grand Total | Owner
--- | --- | --- | --- | --- | ---
System.ComponentModel.Design | 0 | 0 | 2 | 2 | @RussKie @merriemcgaw
System.Windows.Forms | 0 | 0 | 7 | 7 | @RussKie @merriemcgaw
System.Windows.Forms.Design | 0 | 0 | 4 | 4 | @RussKie @merriemcgaw
**Undoc APIs** | **0** | **0** | **13** | **13** | 

### APIs owned by WPF

Namespace\Version | 1.0 | 2.0 | 3.0 | Grand Total | Owner
--- | --- | --- | --- | --- | ---
System.Xaml.Permissions | 0 | 0 | 2 | 2 | @vatsan-madhavan
**Undoc APIs** | **0** | **0** | **2** | **2** |

**Comment by cheenamalhotra** [comment]
@CarlHeinrichs 

Re: System.Data.SqlClient (13)
Could you also provide us list of these 13 APIs that we can work on?

**Comment by carlossanlop** [comment]
Gladly, @cheenamalhotra . I'm preparing that information right now. I'll create an issue for each area and will also send the usual email.
