### ISSUE TITLE
WPF undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3909]
@vatsan-madhavan,
Here are the undocumented API owned by WPF. They were introduced in 3.0.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?
Although since your team only has 2 undocumented APIs they could be documented on the first pass.

For more information on the plan, see: https://github.com/dotnet/dotnet-api-docs/issues/3904

Total: 2
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Xaml.Permissions.XamlLoadPermission.Equals(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xaml.Permissions/XamlLoadPermission.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xaml.Permissions.XamlLoadPermission.Equals
M:System.Xaml.Permissions.XamlLoadPermission.GetHashCode | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xaml.Permissions/XamlLoadPermission.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xaml.Permissions.XamlLoadPermission.GetHashCode

**Comment by vatsan-madhavan** [comment]
@fabiant3-zz can we reassign this to you? 

/cc @dotnet/wpf-developers

**Comment by carlossanlop** [comment]
@fabiant3-zz @vatsan-madhavan can you please share your action plan for these undocumented APIs?

**Comment by vatsan-madhavan** [comment]
Action plan => handing over to  @fabiant3-zz for an action plan ;-)
