### ISSUE TITLE
System.Data 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3910]
@ajcvickers @cheenamalhotra @David-Engel @karinazhou @JRahnama @CarlHeinrichs

Here are the undocumented API owned by `System.Data.Common` and `System.Data.SqlClient`. They were all introduced in 1.x. Your team has no debt from 2.x or 3.x (thank you!).
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?
For more information on the plan, see: #3904

Total: 23
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Data.Common.DbCommand.Dispose | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbCommand.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbCommand.Dispose
M:System.Data.Common.DbCommand.Dispose(System.Boolean) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbCommand.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbCommand.Dispose
M:System.Data.Common.DbConnection.Dispose(System.Boolean) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnection.Dispose
M:System.Data.Common.DbConnection.Dispose | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnection.Dispose
P:System.Data.Common.DbConnectionStringBuilder.System#Collections#IDictionary#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnectionStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnectionStringBuilder.System-Collections-IDictionary-IsFixedSize
P:System.Data.Common.DbConnectionStringBuilder.System#Collections#IDictionary#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbConnectionStringBuilder.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbConnectionStringBuilder.System-Collections-IDictionary-IsReadOnly
P:System.Data.Common.DbParameter.System#Data#IDataParameter#SourceVersion | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameter.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameter.System-Data-IDataParameter-SourceVersion
P:System.Data.Common.DbParameterCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameterCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameterCollection.System-Collections-ICollection-IsSynchronized
P:System.Data.Common.DbParameterCollection.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameterCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameterCollection.System-Collections-IList-IsFixedSize
P:System.Data.Common.DbParameterCollection.System#Collections#IList#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Common/DbParameterCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.Common.DbParameterCollection.System-Collections-IList-IsReadOnly
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.Count
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.GetEnumerator
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-ICollection-CopyTo
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-ICollection-IsSynchronized
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-ICollection-SyncRoot
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Add
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Contains(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Contains
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#IndexOf(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-IndexOf
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Insert(System.Int32,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Insert
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-IsFixedSize
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-IsReadOnly
P:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Item
M:System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System#Collections#IList#Remove(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlBulkCopyColumnMappingCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Data.SqlClient.SqlBulkCopyColumnMappingCollection.System-Collections-IList-Remove

**Comment by cheenamalhotra** [comment]
Hi @carlossanlop 

I see classes of System.Data.SqlClient including "[SqlBulkCopyColumnMappingCollection](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopycolumnmappingcollection?view=dotnet-plat-ext-3.1)" has mixed up monikers among ".NET Core" and ".NET Platform Extensions".

Documentations for above mentioned APIs are available though.

I also see the same "Applies To" for [SqlConnection](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection?view=dotnet-plat-ext-3.1) class, where they all only apply to ".NET Core" for v1.1 and v1.0, but moniker has changed to ".NET Platform Extensions" for > v2.1.

Could you confirm where exactly are the documentations missing?

![image](https://user-images.githubusercontent.com/13396919/75716100-6f89e280-5c83-11ea-9325-d2386699c4f3.png)

**Comment by cheenamalhotra** [comment]
For System.Data.Common, I can see that while most of APIs are available across all ".NET Core" versions, the above list of APIs are not available for v1.1 and v1.0.

/cc: @saurabh500 for System.Data.Common.

**Comment by carlossanlop** [comment]
@cheenamalhotra the APIs I automatically ported were not among the ones in the list I shared in this issue. They were from .NET Framework. So the list remains the same: 23 undoc APIs introduced in .NET Core 1.0 and 1.1.

**Comment by carlossanlop** [comment]
@cheenamalhotra I added support to the [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to be able to automatically copy Explicit Interface Implementations. I noticed the list above has a few of those. I left instructions and a usage example in the README file. Let me know if you have any questions about it.
