### ISSUE TITLE
Winforms undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3911]
@Russkie @merriemcgaw 

Here are the undocumented API owned by the WinForms team. They were introduced in 3.0.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

Total: 13
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.ComponentModel.Design.DesignerActionService.GetComponentActions(System.ComponentModel.IComponent,System.Windows.Forms.Design.ComponentActionsType) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.Design/DesignerActionService.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.ComponentModel.Design.DesignerActionService.GetComponentActions
M:System.ComponentModel.Design.ObjectSelectorEditor.ApplyTreeViewThemeStyles(System.Windows.Forms.TreeView) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.Design/ObjectSelectorEditor.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.ComponentModel.Design.ObjectSelectorEditor.ApplyTreeViewThemeStyles
M:System.Windows.Forms.ComboBox.ProcessCmdKey(System.Windows.Forms.Message@,System.Windows.Forms.Keys) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ComboBox.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.ComboBox.ProcessCmdKey
M:System.Windows.Forms.DataGridView.ProcessControlShiftF10Keys(System.Windows.Forms.Keys) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/DataGridView.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.DataGridView.ProcessControlShiftF10Keys
M:System.Windows.Forms.Form.CreateAccessibilityInstance | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/Form.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.Form.CreateAccessibilityInstance
M:System.Windows.Forms.ListBox.OnGotFocus(System.EventArgs) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ListBox.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.ListBox.OnGotFocus
M:System.Windows.Forms.MonthCalendar.OnGotFocus(System.EventArgs) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/MonthCalendar.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.MonthCalendar.OnGotFocus
M:System.Windows.Forms.ToolStripControlHost.ToolStripHostedControlAccessibleObject.#ctor(System.Windows.Forms.Control,System.Windows.Forms.ToolStripControlHost) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ToolStripControlHost+ToolStripHostedControlAccessibleObject.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.ToolStripControlHost.ToolStripHostedControlAccessibleObject.-ctor
T:System.Windows.Forms.ToolStripControlHost.ToolStripHostedControlAccessibleObject | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ToolStripControlHost+ToolStripHostedControlAccessibleObject.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.ToolStripControlHost.ToolStripHostedControlAccessibleObject
F:System.Windows.Forms.Design.ComponentActionsType.All | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/ComponentActionsType.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.Design.ComponentActionsType
F:System.Windows.Forms.Design.ComponentActionsType.Component | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/ComponentActionsType.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.Design.ComponentActionsType
T:System.Windows.Forms.Design.ComponentActionsType | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/ComponentActionsType.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.Design.ComponentActionsType
F:System.Windows.Forms.Design.ComponentActionsType.Service | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/ComponentActionsType.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Windows.Forms.Design.ComponentActionsType

**Comment by merriemcgaw** [comment]
@carlossanlop we should be able to get these all in March. @JuditRose took a look at some of them and found the content on docs.microsoft.com. Has the report been rerun lately?

**Comment by carlossanlop** [comment]
> _Has the report been rerun lately?_

Yes, @merriemcgaw . This table was obtained from the latest report, which was generated on 02/22. It's the freshest data.

I found a bug in the report that is showing certain APIs (like some delegates) as undocumented, but they have content. I reported it to the Docs team and they'll take a look soon.

@JuditRose can you please tell me which APIs had documentation already?

**Comment by JuditRose** [comment]
Maybe I am just reading it the wrong way... But I can see these methods and fields including return value and parameter in Github and also on docs.microsoft.com as well.
DesignerActionService.GetComponentActions [Github DesignerActionService L478](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.Design/DesignerActionService.xml#L478) [MS Docs DesignerActionService GetComponentActions](https://docs.microsoft.com/en-us/dotnet/api/System.ComponentModel.Design.DesignerActionService.GetComponentActions?view=netcore-3.1)
ObjectSelectorEditor.ApplyTreeViewThemeStyles [GIthub ObjectSelectorEditor L96](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.Design/ObjectSelectorEditor.xml#L96) [MS Docs ObjectSelectorEditor ApplyTreeViewThemeStyles](https://docs.microsoft.com/en-us/dotnet/api/System.ComponentModel.Design.ObjectSelectorEditor.ApplyTreeViewThemeStyles?view=netcore-3.1)
ComboBox.ProcessCmdKey [Github ComboBox L3011](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ComboBox.xml#L3011)
DataGridView.ProcessControlShiftF10Keys [Github DataGridView L14867](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/DataGridView.xml#L14867)
Form.CreateAccessibilityInstance [Github Form L1332](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/DataGridView.xml#L1332)
ListBox.OnGotFocus [Github ListBox L1954](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ListBox.xml#L1954)
MonthCalendar.OnGotFocus [Github MonthCalendar ](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/MonthCalendar.xml#L1695)
ToolStripHostedControlAccessibleObject.#ctor [Github ToolStripHostedControlAccessibleObject L21](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/ToolStripControlHost+ToolStripHostedControlAccessibleObject.xml#L21)
ComponentActionsType.All [Github ComponentActionsType L20](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/ComponentActionsType.xml#L20)
ComponentActionsType.Component [Github ComponentActionsType L40](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/ComponentActionsType.xml#L40)
ComponentActionsType.Service [Github ComponentActionsType L60](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms.Design/ComponentActionsType.xml#L60)

Also this list is different from the list in the xls from Maira Wenzel's email about the undocumented APIs. That report also describes what part of the documentation is missing, for us (System.Drawing.Design and System.Windows.Forms) it's either Parameter or ReturnValue that is missing according to Maira's list. But if I look them up on Github (or MS docs) I can see those too:
System.Drawing.Design	IconEditor CreateFilterEntry Parameter missing [Github IconEditor CreateFilterEntry Parameter](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Drawing.Design/IconEditor.xml#L121) [MS Docs IconEditor CreateFilterEntry](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.design.iconeditor.createfilterentry?view=netcore-3.1)
System.Windows.Forms	CheckedListBox.CheckedIndexCollection System.Collections.IList.Add ReturnValue missing [Github CheckedListBox CheckedIndexCollection System.Collections.IList.Add ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/CheckedListBox+CheckedIndexCollection.xml#L401)
System.Windows.Forms	Control.ControlCollection Equals Parameter missing [Github Control ControlCollection Equals Parameter](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/Control+ControlCollection.xml#L402)
System.Windows.Forms	Control.ControlCollection System.Collections.IList.Remove Parameter missing [Github Control ControlCollection System.Collections.IList.Remove Parameter](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/Control+ControlCollection.xml#L1141)
System.Windows.Forms	DomainUpDown OnTextBoxKeyDown Parameter missing [Github DomainUpDown OnTextBoxKeyDown Parameter](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/DomainUpDown.xml#L327)
System.Windows.Forms	ImageList.ImageCollection System.Collections.IList.Contains ReturnValue missing [Github ImageList ImageCollection System.Collections.IList.Contains ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/ImageList+ImageCollection.xml#L383)
System.Windows.Forms	ImageList.ImageCollection System.Collections.IList.IndexOf ReturnValue missing [Github ImageList ImageCollection System.Collections.IList.IndexOf ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/ImageList+ImageCollection.xml#L1076)
System.Windows.Forms	ListBox.ObjectCollection System.Collections.IList.Add ReturnValue missing [Github ListBox ObjectCollection System.Collections.IList.Add ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/ListBox+ObjectCollection.xml#L868)
System.Windows.Forms	ListView.ColumnHeaderCollection System.Collections.IList.IndexOf ReturnValue missing [Github ListView ColumnHeaderCollection System.Collections.IList.IndexOf ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/ListView+ColumnHeaderCollection.xml#L1450)
System.Windows.Forms	ListView.SelectedIndexCollection System.Collections.IList.IndexOf ReturnValue missing [Github ListView SelectedIndexCollection System.Collections.IList.IndexOf ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/ListView+SelectedIndexCollection.xml#L635)
System.Windows.Forms	ListViewItem.ListViewSubItemCollection System.Collections.IList.Contains Parameter missing [Github ListViewItem ListViewSubItemCollection System.Collections.IList.Contains Parameter](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/ListViewItem+ListViewSubItemCollection.xml#L993)
System.Windows.Forms	Splitter PreFilterMessage Parameter missing [Github Splitter PreFilterMessage Parameter](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/Splitter.xml#L1269)
System.Windows.Forms	Splitter PreFilterMessage ReturnValue missing [Github Splitter PreFilterMessage ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/Splitter.xml#L1266)
System.Windows.Forms	StatusBar.StatusBarPanelCollection System.Collections.IList.Add ReturnValue missing [Github StatusBar StatusBarPanelCollection System.Collections.IList.Add ReturnValue](https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/StatusBar+StatusBarPanelCollection.xml#L840)

I don't see what is missing and where. Can you please help me?

**Comment by carlossanlop** [comment]
@JuditRose 

> GetComponentActions

This method has 3 overloads. The one you shared is not the same signature (DocId) as the one mentioned in the issue:
- Documented:
  - `<MemberSignature Language="DocId" Value="M:System.ComponentModel.Design.DesignerActionService.GetComponentActions(System.ComponentModel.IComponent)" />`
  - `<MemberSignature Language="DocId" Value="M:System.ComponentModel.Design.DesignerActionService.GetComponentActions(System.ComponentModel.IComponent,System.ComponentModel.Design.ComponentActionsType)" />`
- Undocumented:
  - `<MemberSignature Language="DocId" Value="M:System.ComponentModel.Design.DesignerActionService.GetComponentActions(System.ComponentModel.IComponent,System.Windows.Forms.Design.ComponentActionsType)" />`

> ApplyTreeViewThemeStyles

This method is undocumented: It does not have a param or a summary.
https://github.com/dotnet/dotnet-api-docs/blob/1e6b2e6052185c6744054acc10cd06e435a4fb8b/xml/System.ComponentModel.Design/ObjectSelectorEditor.xml#L116-L120

> ProcessCmdKey

This method is also undocumented. It's missing a description for the parameters "msg", "keyData", a summary and a returns (all say "To be added.").
https://github.com/dotnet/dotnet-api-docs/blob/1e6b2e6052185c6744054acc10cd06e435a4fb8b/xml/System.Windows.Forms/ComboBox.xml#L3030-L3036

> ProcessControlShiftF10Keys

Missing a description for param, summary, returns. Can't share a link because the file is huge and can only be viewed in raw mode, but you can search for them.


> CreateAccessibilityInstance

You didn't look at the right file. The correct file iss linked in the table in this issue, in the second column (the columns are huge).
It's missing a summary and a returns.
https://github.com/dotnet/dotnet-api-docs/blob/1e6b2e6052185c6744054acc10cd06e435a4fb8b/xml/System.Windows.Forms/Form.xml#L1348-L1352

etc.


> Also this list is different from the list in the xls from Maira Wenzel's email about the undocumented APIs. Why is that a different list from the one described in this issue? That report also describes missing APIs and includes what part of the documentation is missing.

I'm not sure what list you're referring to. I wasn't included in that email, if that's how it was shared.
But I suspect the list she sent you is different because the APIs I listed in this issue come from assemblies hosted in the dotnet/runtime repo, while the ones Maira shared are hosted in the dotnet/winforms repo.
Both lists of undocumented APIs should get addressed, although the list in this issue is expected to get addressed 100% before the end of May.

I noticed the links you shared (the ones Maira sent you) were permalinks pointing at the `<Parameters>` or the `<ReturnValue>` tags. For example:
https://github.com/dotnet/dotnet-api-docs/blob/5e0a79c1bdc5ccf63aaf802d8bb05b1f89780f3f/xml/System.Windows.Forms/CheckedListBox%2BCheckedIndexCollection.xml#L401
and
https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/Control+ControlCollection.xml#L402

But you should be looking inside the `<Docs>` tag for the `<returns>`, `<param>` and `<summary>` elements, which contain the actual documentation. If they say "To be added.", then it means they are undocumented and they should be filled out. The only one that is optional is `<remarks>`. Also, make sure to add exceptions. They are not included by default.

For example, for the two cases above:
https://github.com/dotnet/dotnet-api-docs/blob/5e0a79c1bdc5ccf63aaf802d8bb05b1f89780f3f/xml/System.Windows.Forms/CheckedListBox%2BCheckedIndexCollection.xml#L410
and
https://github.com/dotnet/dotnet-api-docs/blob/intellisense/xml/System.Windows.Forms/Control+ControlCollection.xml#L406

Hope that helps.

**Comment by JuditRose** [comment]
Yes, it does, thank you! Do you know if these gets autogenerated from the code or is there any source where these come from?

**Comment by carlossanlop** [comment]
@JuditRose 

> _Do you know if these gets autogenerated from the code or is there any source where these come from?_

These xml files are automatically generated by the Docs repo by reading the .NET reference assemblies of each version.
