### ISSUE TITLE
System.Xml 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3915]
@buyaa-n @krwq 

Here are the undocumented API from `System.Xml` that were introduced in 1.x.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

Total: 54
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Xml.XmlDocumentXPathExtensions.CreateNavigator(System.Xml.XmlDocument) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.CreateNavigator
M:System.Xml.XmlDocumentXPathExtensions.CreateNavigator(System.Xml.XmlNode) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.CreateNavigator
M:System.Xml.XmlDocumentXPathExtensions.CreateNavigator(System.Xml.XmlDocument,System.Xml.XmlNode) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.CreateNavigator
M:System.Xml.XmlDocumentXPathExtensions.SelectNodes(System.Xml.XmlNode,System.String) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.SelectNodes
M:System.Xml.XmlDocumentXPathExtensions.SelectNodes(System.Xml.XmlNode,System.String,System.Xml.XmlNamespaceManager) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.SelectNodes
M:System.Xml.XmlDocumentXPathExtensions.SelectSingleNode(System.Xml.XmlNode,System.String) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.SelectSingleNode
M:System.Xml.XmlDocumentXPathExtensions.SelectSingleNode(System.Xml.XmlNode,System.String,System.Xml.XmlNamespaceManager) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.SelectSingleNode
M:System.Xml.XmlDocumentXPathExtensions.ToXPathNavigable(System.Xml.XmlNode) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions.ToXPathNavigable
T:System.Xml.XmlDocumentXPathExtensions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocumentXPathExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.XmlDocumentXPathExtensions
M:System.Xml.Serialization.XmlAnyElementAttributes.Clear | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.Clear
P:System.Xml.Serialization.XmlAnyElementAttributes.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.Count
M:System.Xml.Serialization.XmlAnyElementAttributes.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.GetEnumerator
M:System.Xml.Serialization.XmlAnyElementAttributes.RemoveAt(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.RemoveAt
M:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-ICollection-CopyTo
P:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-ICollection-IsSynchronized
P:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-ICollection-SyncRoot
M:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-Add
M:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#Contains(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-Contains
M:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#IndexOf(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-IndexOf
M:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#Insert(System.Int32,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-Insert
P:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-IsFixedSize
P:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-IsReadOnly
P:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-Item
M:System.Xml.Serialization.XmlAnyElementAttributes.System#Collections#IList#Remove(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlAnyElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlAnyElementAttributes.System-Collections-IList-Remove
M:System.Xml.Serialization.XmlArrayItemAttributes.Clear | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.Clear
P:System.Xml.Serialization.XmlArrayItemAttributes.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.Count
M:System.Xml.Serialization.XmlArrayItemAttributes.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.GetEnumerator
M:System.Xml.Serialization.XmlArrayItemAttributes.RemoveAt(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.RemoveAt
M:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-ICollection-CopyTo
P:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-ICollection-IsSynchronized
P:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-ICollection-SyncRoot
M:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-Add
M:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#Contains(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-Contains
M:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#IndexOf(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-IndexOf
M:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#Insert(System.Int32,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-Insert
P:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-IsFixedSize
P:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-IsReadOnly
P:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-Item
M:System.Xml.Serialization.XmlArrayItemAttributes.System#Collections#IList#Remove(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlArrayItemAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlArrayItemAttributes.System-Collections-IList-Remove
M:System.Xml.Serialization.XmlElementAttributes.Clear | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.Clear
P:System.Xml.Serialization.XmlElementAttributes.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.Count
M:System.Xml.Serialization.XmlElementAttributes.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.GetEnumerator
M:System.Xml.Serialization.XmlElementAttributes.RemoveAt(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.RemoveAt
M:System.Xml.Serialization.XmlElementAttributes.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-ICollection-CopyTo
P:System.Xml.Serialization.XmlElementAttributes.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-ICollection-IsSynchronized
P:System.Xml.Serialization.XmlElementAttributes.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-ICollection-SyncRoot
M:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-Add
M:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#Contains(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-Contains
M:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#IndexOf(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-IndexOf
M:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#Insert(System.Int32,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-Insert
P:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-IsFixedSize
P:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-IsReadOnly
P:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-Item
M:System.Xml.Serialization.XmlElementAttributes.System#Collections#IList#Remove(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlElementAttributes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Xml.Serialization.XmlElementAttributes.System-Collections-IList-Remove

**Comment by carlossanlop** [comment]
@buyaa-n can you please share your action plan for these undocumented APIs?

**Comment by jeffhandley** [comment]
I'll work with @buyaa-n to get this work scheduled after we get through our current focus on analyzers.

**Comment by carlossanlop** [comment]
Thanks @jeffhandley.
@buyaa-n I'm seeing a bunch of DocIds in the list that are Explicit Interface Implementations. You can use [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to document them quickly and easily. There are instructions in the README with an example. Let me know if you have any questions about it.

**Comment by jeffhandley** [comment]
FYI @carlossanlop - we're projecting the end of May before this area will be completed.

**Comment by krwq** [comment]
The auto-annotated parts are merged, @carlossanlop will send me a list of what's left once he gets a build (ETA Monday)
