### ISSUE TITLE
System.Net 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3916]
@dotnet/ncl 

Here are the undocumented API from `System.Net`. Some of them were introduced in 1.x, but there's also some debt from the 2.x effort.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

Total: 63.
_Note: The table has 4 really long columns._

PR|DocId | Source File Path | Docs URL
-- | -- | -- | --
#4373 | M:System.Net.CookieCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/CookieCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.CookieCollection.System-Collections-ICollection-CopyTo
#4373 | P:System.Net.CookieCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/CookieCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.CookieCollection.System-Collections-ICollection-IsSynchronized
#4373 | P:System.Net.CookieCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/CookieCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.CookieCollection.System-Collections-ICollection-SyncRoot
#4268 | P:System.Net.WebHeaderCollection.Item(System.String) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/WebHeaderCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.WebHeaderCollection.Item
#4268 | M:System.Net.WebHeaderCollection.System#Collections#IEnumerable#GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/WebHeaderCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.WebHeaderCollection.System-Collections-IEnumerable-GetEnumerator
#4276 | P:System.Net.Http.HttpMethod.Patch | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpMethod.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.HttpMethod.Patch
#4277 | M:System.Net.Http.ReadOnlyMemoryContent.#ctor(System.ReadOnlyMemory{System.Byte}) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/ReadOnlyMemoryContent.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.ReadOnlyMemoryContent.-ctor
#4277 | T:System.Net.Http.ReadOnlyMemoryContent | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/ReadOnlyMemoryContent.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.ReadOnlyMemoryContent
#4290 | M:System.Net.Http.SocketsHttpHandler.#ctor | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.-ctor
#4290 | P:System.Net.Http.SocketsHttpHandler.AllowAutoRedirect | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.AllowAutoRedirect
#4290 | P:System.Net.Http.SocketsHttpHandler.ConnectTimeout | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.ConnectTimeout
#4290 | P:System.Net.Http.SocketsHttpHandler.Credentials | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.Credentials
#4290 | P:System.Net.Http.SocketsHttpHandler.Expect100ContinueTimeout | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.Expect100ContinueTimeout
#4290 | P:System.Net.Http.SocketsHttpHandler.PooledConnectionLifetime | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.PooledConnectionLifetime
#4290 | P:System.Net.Http.SocketsHttpHandler.Properties | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.Properties
#4290 | P:System.Net.Http.SocketsHttpHandler.ResponseDrainTimeout | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.ResponseDrainTimeout
#4290 | P:System.Net.Http.SocketsHttpHandler.UseCookies | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.UseCookies
#4290 | P:System.Net.Http.SocketsHttpHandler.UseProxy | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.SocketsHttpHandler.UseProxy
#4323 | M:System.Net.Http.WinHttpHandler.Dispose(System.Boolean) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/WinHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.WinHttpHandler.Dispose
#4323 | P:System.Net.Http.WinHttpHandler.Properties | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/WinHttpHandler.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Http.WinHttpHandler.Properties
#4324 | F:System.Net.Mime.MediaTypeNames.Application.Json | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Mime/MediaTypeNames+Application.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Mime.MediaTypeNames.Application.Json
#4324 | F:System.Net.Mime.MediaTypeNames.Application.Xml | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Mime/MediaTypeNames+Application.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Mime.MediaTypeNames.Application.Xml
#4333 | M:System.Net.NetworkInformation.Ping.Dispose | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.NetworkInformation/Ping.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.NetworkInformation.Ping.Dispose
#4335 | M:System.Net.Security.NegotiateStream.FlushAsync(System.Threading.CancellationToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/NegotiateStream.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.NegotiateStream.FlushAsync
#4351 | T:System.Net.Security.ServerCertificateSelectionCallback | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/ServerCertificateSelectionCallback.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.ServerCertificateSelectionCallback
#4350 | M:System.Net.Security.SslApplicationProtocol.#ctor(System.Byte[]) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.-ctor
#4350 | M:System.Net.Security.SslApplicationProtocol.#ctor(System.String) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.-ctor
#4350 | M:System.Net.Security.SslApplicationProtocol.Equals(System.Net.Security.SslApplicationProtocol) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.Equals
#4350 | M:System.Net.Security.SslApplicationProtocol.Equals(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.Equals
#4350 | M:System.Net.Security.SslApplicationProtocol.GetHashCode | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.GetHashCode
#4350 | F:System.Net.Security.SslApplicationProtocol.Http11 | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.Http11
#4350 | F:System.Net.Security.SslApplicationProtocol.Http2 | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.Http2
#4350 | M:System.Net.Security.SslApplicationProtocol.op_Equality(System.Net.Security.SslApplicationProtocol,System.Net.Security.SslApplicationProtocol) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.op_Equality
#4350 | M:System.Net.Security.SslApplicationProtocol.op_Inequality(System.Net.Security.SslApplicationProtocol,System.Net.Security.SslApplicationProtocol) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.op_Inequality
#4350 | P:System.Net.Security.SslApplicationProtocol.Protocol | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.Protocol
#4350 | T:System.Net.Security.SslApplicationProtocol | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol
#4350 | M:System.Net.Security.SslApplicationProtocol.ToString | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslApplicationProtocol.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslApplicationProtocol.ToString
#4366 | M:System.Net.Security.SslClientAuthenticationOptions.#ctor | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.-ctor
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.AllowRenegotiation | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.AllowRenegotiation
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.ApplicationProtocols | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.ApplicationProtocols
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.CertificateRevocationCheckMode | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.CertificateRevocationCheckMode
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.ClientCertificates | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.ClientCertificates
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.EnabledSslProtocols | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.EnabledSslProtocols
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.EncryptionPolicy | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.EncryptionPolicy
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.LocalCertificateSelectionCallback | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.LocalCertificateSelectionCallback
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.RemoteCertificateValidationCallback | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.RemoteCertificateValidationCallback
#4366 | T:System.Net.Security.SslClientAuthenticationOptions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions
#4366 | P:System.Net.Security.SslClientAuthenticationOptions.TargetHost | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslClientAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslClientAuthenticationOptions.TargetHost
#4367 | M:System.Net.Security.SslServerAuthenticationOptions.#ctor | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.-ctor
#4351 | P:System.Net.Security.SslServerAuthenticationOptions.AllowRenegotiation | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.AllowRenegotiation
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.ApplicationProtocols | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.ApplicationProtocols
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.CertificateRevocationCheckMode | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.CertificateRevocationCheckMode
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.ClientCertificateRequired | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.ClientCertificateRequired
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.EnabledSslProtocols | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.EnabledSslProtocols
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.EncryptionPolicy | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.EncryptionPolicy
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.RemoteCertificateValidationCallback | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.RemoteCertificateValidationCallback
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.ServerCertificate | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.ServerCertificate
#4367 | P:System.Net.Security.SslServerAuthenticationOptions.ServerCertificateSelectionCallback | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions.ServerCertificateSelectionCallback
#4367 | T:System.Net.Security.SslServerAuthenticationOptions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslServerAuthenticationOptions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslServerAuthenticationOptions
#4372 | M:System.Net.Security.SslStream.AuthenticateAsClientAsync(System.Net.Security.SslClientAuthenticationOptions,System.Threading.CancellationToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslStream.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslStream.AuthenticateAsClientAsync
#4372 | M:System.Net.Security.SslStream.AuthenticateAsServerAsync(System.Net.Security.SslServerAuthenticationOptions,System.Threading.CancellationToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslStream.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslStream.AuthenticateAsServerAsync
#4372 | M:System.Net.Security.SslStream.FlushAsync(System.Threading.CancellationToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslStream.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslStream.FlushAsync
#4372 | P:System.Net.Security.SslStream.NegotiatedApplicationProtocol | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Security/SslStream.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Net.Security.SslStream.NegotiatedApplicationProtocol

**Comment by carlossanlop** [comment]
@dotnet/ncl has there been any progress on this?

**Comment by carlossanlop** [comment]
@dotnet/ncl @karelz can you please share your action plan for these undocumented APIs?

**Comment by karelz** [comment]
@carlossanlop right now we are a bit swamped, so we do not have sadly a plan yet :(

**Comment by jeffhandley** [comment]
Thank you, @karelz - that's helpful to know to have expectations set. Please let me know if there's anything you need other than time.

**Comment by aik-jahoda** [comment]
Closing as all attached PRs are closed.
