### ISSUE TITLE
System.Text.RegularExpressions 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3918]
@pgovind @eerhardt 

Here are the undocumented API from `System.Text.RegularExpressions`. No APIs were introduced in 1.x, but there's debt from the 2.x effort.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

Total: 39.
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Text.RegularExpressions.CaptureCollection.CopyTo(System.Text.RegularExpressions.Capture[],System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.CopyTo
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Capture>#Add(System.Text.RegularExpressions.Capture) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Capture--Add
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Capture>#Clear | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Capture--Clear
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Capture>#Contains(System.Text.RegularExpressions.Capture) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Capture--Contains
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Capture>#Remove(System.Text.RegularExpressions.Capture) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Capture--Remove
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#IEnumerable<System#Text#RegularExpressions#Capture>#GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-IEnumerable-System-Text-RegularExpressions-Capture--GetEnumerator
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Capture>#IndexOf(System.Text.RegularExpressions.Capture) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Capture--IndexOf
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Capture>#Insert(System.Int32,System.Text.RegularExpressions.Capture) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Capture--Insert
P:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Capture>#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Capture--Item
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Capture>#RemoveAt(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Capture--RemoveAt
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-Add
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#Clear | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-Clear
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#Contains(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-Contains
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#IndexOf(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-IndexOf
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#Insert(System.Int32,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-Insert
P:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-IsFixedSize
P:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-Item
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#Remove(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-Remove
M:System.Text.RegularExpressions.CaptureCollection.System#Collections#IList#RemoveAt(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/CaptureCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.CaptureCollection.System-Collections-IList-RemoveAt
M:System.Text.RegularExpressions.GroupCollection.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/GroupCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.GroupCollection.System-Collections-IList-Add
M:System.Text.RegularExpressions.MatchCollection.CopyTo(System.Text.RegularExpressions.Match[],System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.CopyTo
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Match>#Add(System.Text.RegularExpressions.Match) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Match--Add
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Match>#Clear | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Match--Clear
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Match>#Contains(System.Text.RegularExpressions.Match) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Match--Contains
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#ICollection<System#Text#RegularExpressions#Match>#Remove(System.Text.RegularExpressions.Match) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-ICollection-System-Text-RegularExpressions-Match--Remove
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#IEnumerable<System#Text#RegularExpressions#Match>#GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-IEnumerable-System-Text-RegularExpressions-Match--GetEnumerator
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Match>#IndexOf(System.Text.RegularExpressions.Match) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Match--IndexOf
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Match>#Insert(System.Int32,System.Text.RegularExpressions.Match) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Match--Insert
P:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Match>#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Match--Item
M:System.Text.RegularExpressions.MatchCollection.System#Collections#Generic#IList<System#Text#RegularExpressions#Match>#RemoveAt(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-Generic-IList-System-Text-RegularExpressions-Match--RemoveAt
M:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#Add(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-Add
M:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#Clear | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-Clear
M:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#Contains(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-Contains
M:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#IndexOf(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-IndexOf
M:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#Insert(System.Int32,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-Insert
P:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#IsFixedSize | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-IsFixedSize
P:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#Item(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-Item
M:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#Remove(System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-Remove
M:System.Text.RegularExpressions.MatchCollection.System#Collections#IList#RemoveAt(System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Text.RegularExpressions.MatchCollection.System-Collections-IList-RemoveAt

**Comment by pgovind** [comment]
Interesting, everything is in the *Collection methods/classes. This will be a good reason to spend time understanding what these methods do where appropriate

**Comment by eerhardt** [comment]
I believe all these new APIs came from https://github.com/dotnet/runtime/commit/526552679afc5e07c7862c113d15e647ad431c7a#diff-dbdb54cdcb40d86a43ab6f5fe45cea13 and documenting these new APIs will be mechanical. All the methods are just implementing the `IList<T>`, `IReadOnlyList<T>`, and `IList` interfaces, so we should be able to copy-paste the documentation from the interfaces.

**Comment by carlossanlop** [comment]
@pgovind @eerhardt if they are explicit interface implementations, and their parent interface is properly documented in source code, you can use the [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to automatically port them.

I think the tool can be tweaked to detect normal interface implementations and automatically port those comments as well, but I haven't done that.

Can you please share your action plan to address these undocumented APIs?
