### ISSUE TITLE
System.Security 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3920]
@bartonjs @GrabYourPitchforks @krwq

Here are the undocumented API from `System.Security`. There's some debt from the 2.x and 3.x efforts.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

Total: 45.
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
P:System.Security.AccessControl.AuthorizationRuleCollection.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.AccessControl/AuthorizationRuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.AccessControl.AuthorizationRuleCollection.Count
M:System.Security.AccessControl.AuthorizationRuleCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.AccessControl/AuthorizationRuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.AccessControl.AuthorizationRuleCollection.System-Collections-ICollection-CopyTo
P:System.Security.AccessControl.AuthorizationRuleCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.AccessControl/AuthorizationRuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.AccessControl.AuthorizationRuleCollection.System-Collections-ICollection-IsSynchronized
P:System.Security.AccessControl.AuthorizationRuleCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.AccessControl/AuthorizationRuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.AccessControl.AuthorizationRuleCollection.System-Collections-ICollection-SyncRoot
M:System.Security.AccessControl.AuthorizationRuleCollection.System#Collections#IEnumerable#GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.AccessControl/AuthorizationRuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.AccessControl.AuthorizationRuleCollection.System-Collections-IEnumerable-GetEnumerator
P:System.Security.Authentication.ExtendedProtection.ServiceNameCollection.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Authentication.ExtendedProtection/ServiceNameCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Authentication.ExtendedProtection.ServiceNameCollection.Count
M:System.Security.Authentication.ExtendedProtection.ServiceNameCollection.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Authentication.ExtendedProtection/ServiceNameCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Authentication.ExtendedProtection.ServiceNameCollection.GetEnumerator
M:System.Security.Authentication.ExtendedProtection.ServiceNameCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Authentication.ExtendedProtection/ServiceNameCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Authentication.ExtendedProtection.ServiceNameCollection.System-Collections-ICollection-CopyTo
P:System.Security.Authentication.ExtendedProtection.ServiceNameCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Authentication.ExtendedProtection/ServiceNameCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Authentication.ExtendedProtection.ServiceNameCollection.System-Collections-ICollection-IsSynchronized
P:System.Security.Authentication.ExtendedProtection.ServiceNameCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Authentication.ExtendedProtection/ServiceNameCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Authentication.ExtendedProtection.ServiceNameCollection.System-Collections-ICollection-SyncRoot
P:System.Security.Cryptography.AsnEncodedDataCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/AsnEncodedDataCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.AsnEncodedDataCollection.System-Collections-ICollection-IsSynchronized
P:System.Security.Cryptography.AsnEncodedDataCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/AsnEncodedDataCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.AsnEncodedDataCollection.System-Collections-ICollection-SyncRoot
P:System.Security.Cryptography.CryptographicAttributeObjectCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/CryptographicAttributeObjectCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.CryptographicAttributeObjectCollection.System-Collections-ICollection-IsSynchronized
P:System.Security.Cryptography.CryptographicAttributeObjectCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/CryptographicAttributeObjectCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.CryptographicAttributeObjectCollection.System-Collections-ICollection-SyncRoot
P:System.Security.Cryptography.OidCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/OidCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.OidCollection.System-Collections-ICollection-IsSynchronized
P:System.Security.Cryptography.OidCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/OidCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.OidCollection.System-Collections-ICollection-SyncRoot
P:System.Security.Cryptography.Rfc2898DeriveBytes.HashAlgorithm | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/Rfc2898DeriveBytes.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Rfc2898DeriveBytes.HashAlgorithm
M:System.Security.Cryptography.RSA.TrySignHash(System.ReadOnlySpan{System.Byte},System.Span{System.Byte},System.Security.Cryptography.HashAlgorithmName,System.Security.Cryptography.RSASignaturePadding,System.Int32@) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/RSA.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.RSA.TrySignHash
P:System.Security.Cryptography.TripleDESCng.LegalKeySizes | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/TripleDESCng.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.TripleDESCng.LegalKeySizes
P:System.Security.Cryptography.Pkcs.CmsRecipientCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/CmsRecipientCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.CmsRecipientCollection.System-Collections-ICollection-IsSynchronized
P:System.Security.Cryptography.Pkcs.CmsRecipientCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/CmsRecipientCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.CmsRecipientCollection.System-Collections-ICollection-SyncRoot
P:System.Security.Cryptography.Pkcs.RecipientInfoCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/RecipientInfoCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.RecipientInfoCollection.System-Collections-ICollection-IsSynchronized
P:System.Security.Cryptography.Pkcs.RecipientInfoCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/RecipientInfoCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.RecipientInfoCollection.System-Collections-ICollection-SyncRoot
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampToken.VerifySignatureForHash(System.ReadOnlySpan{System.Byte},System.Security.Cryptography.Oid,System.Security.Cryptography.X509Certificates.X509Certificate2@,System.Security.Cryptography.X509Certificates.X509Certificate2Collection) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampToken.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampToken.VerifySignatureForHash
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.#ctor(System.Security.Cryptography.Oid,System.Security.Cryptography.Oid,System.ReadOnlyMemory{System.Byte},System.ReadOnlyMemory{System.Byte},System.DateTimeOffset,System.Nullable{System.Int64},System.Boolean,System.Nullable{System.ReadOnlyMemory{System.Byte}},System.Nullable{System.ReadOnlyMemory{System.Byte}},System.Security.Cryptography.X509Certificates.X509ExtensionCollection) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.-ctor
P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.AccuracyInMicroseconds | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.AccuracyInMicroseconds
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Encode | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Encode
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetExtensions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetExtensions
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetMessageHash | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetMessageHash
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetNonce | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetNonce
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetSerialNumber | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetSerialNumber
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetTimestampAuthorityName | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.GetTimestampAuthorityName
P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.HasExtensions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.HasExtensions
P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.HashAlgorithmId | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.HashAlgorithmId
P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.IsOrdering | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.IsOrdering
P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.PolicyId | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.PolicyId
T:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo
P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Timestamp | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Timestamp
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.TryDecode(System.ReadOnlyMemory{System.Byte},System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo@,System.Int32@) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.TryDecode
M:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.TryEncode(System.Span{System.Byte},System.Int32@) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.TryEncode
P:System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Version | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.Pkcs/Rfc3161TimestampTokenInfo.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Cryptography.Pkcs.Rfc3161TimestampTokenInfo.Version
M:System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.#ctor | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Permissions/KeyContainerPermissionAccessEntryCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.-ctor
M:System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Permissions/KeyContainerPermissionAccessEntryCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.CopyTo
M:System.Security.Permissions.KeyContainerPermissionAccessEntryEnumerator.#ctor | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Permissions/KeyContainerPermissionAccessEntryEnumerator.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Permissions.KeyContainerPermissionAccessEntryEnumerator.-ctor
P:System.Security.Principal.IdentityReferenceCollection.System#Collections#Generic#ICollection<System#Security#Principal#IdentityReference>#IsReadOnly | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Principal/IdentityReferenceCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Security.Principal.IdentityReferenceCollection.System-Collections-Generic-ICollection-System-Security-Principal-IdentityReference--IsReadOnly

**Comment by carlossanlop** [comment]
@bartonjs @GrabYourPitchforks can you please share your action plan for these undocumented APIs? I know @bartonjs has been constantly documenting, so if you can share your progress here, that would be great.

**Comment by bartonjs** [comment]
No progress, no plan; busy with planning activities. There'll probably be a plan when I resurface.

**Comment by carlossanlop** [comment]
I'll create a new issue in dotnet/runtime with updated data.
