### ISSUE TITLE
System.Diagnostics 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3921]
@tommcdon @sywhang @krwq

Here are the undocumented API from `System.Diagnostics`. There is one API that was debt from the 2.x effort.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

Total: 5.
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Diagnostics.DiagnosticListener.IsEnabled(System.String) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListener.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListener.IsEnabled
T:System.Diagnostics.DiagnosticListenerExtensions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions
M:System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter(System.Diagnostics.DiagnosticListener,System.Object) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter
M:System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter(System.Diagnostics.DiagnosticListener,System.Object,System.Func{System.String,System.Boolean}) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter
M:System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter(System.Diagnostics.DiagnosticListener,System.Object,System.Func{System.String,System.Object,System.Object,System.Boolean}) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter

**Comment by carlossanlop** [comment]
@sywhang @tommcdon can you please share your action plan for these undocumented APIs?

**Comment by carlossanlop** [comment]
@sywhang @tommcdon I noticed there are a few Explicit Interface Implementations among the APIs in the list. You can quickly and easily port them with [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool). You can find instructions and a usage example in the README file. Let me know if you have any questions about it.

**Comment by carlossanlop** [comment]
@sywhang @tommcdon I updated the table to reflect the APIs that area in your areas. Total APIs: 5.

**Comment by krwq** [comment]
@tommcdon @sywhang do you perhaps know where do I find source for Microsoft.Extensions.DiagnosticAdapter? I coudn't find it in dotnet/runtime or dotnet/extensions

**Comment by sywhang** [comment]
It was removed in https://github.com/dotnet/extensions/pull/3165.

**Comment by krwq** [comment]
Thanks @sywhang! @carlossanlop do we still need to document it or better not advertise what we removed?

**Comment by carlossanlop** [comment]
This is an interesting case: It is the first time I see shipped code being removed from .NET. I've only seen that happen with experimental code.
The code was removed just 20 days ago, which sounds to me like the change will be available when we ship .NET 5 (unless dotnet/extensions get shipped in a separate cadence).
Any user still using .NET 3.1 or lower would still be needing documentation for these APIs. My gut says that since 3.1 is still being serviced, then we should get the APIs documented.
@shywhang @krwq @tommcdon do you agree or disagree?

**Comment by krwq** [comment]
IMO documentation is useful when writing new code or debugging. If we are removing type that means we have a better alternative and we don't want people to use the old one. I think the documentation should just say "use this other type instead" to make it so that people are not tempted to use it but not sure about documenting it.

**Comment by carlossanlop** [comment]
I'll create a new issue in dotnet/runtime with updated data.

**Comment by vchirikov** [comment]
> If we are removing type that means we have a better alternative and we don't want people to use the old one

So do we have a better alternative for `System.Diagnostics.DiagnosticSource` ?
And can we unlist this nupkg from nuget.org or do something, because it's not obvious what happened to this lib.

**Comment by sywhang** [comment]
@vchirikov We never removed System.Diagnostics.DiagnosticSource. The API that was removed was Microsoft.Extensions.DiagnosticAdapter.
