### ISSUE TITLE
System.IdentityModel.Selectors undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3925]
@mconnew @StephenBonikowsky @HongGit 

Here are the undocumented API from `System.IdentityModel.Selectors`. These were introduced in 3.0+, and there were no undocumented APIs in 1.x or 2.x in this namespace. The new APIs were introduced in the PR https://github.com/dotnet/wcf/pull/3935.

I didn't find any area owners for this namespace in the [area ownership page](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md), so feel free to reassign this issue if you're not the code owners. 

We are asking all area/code owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

_Note: This table contains 3 really wide columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.IdentityModel.Selectors.SecurityTokenProvider.CancelTokenAsync(System.TimeSpan,System.IdentityModel.Tokens.SecurityToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Selectors/SecurityTokenProvider.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.IdentityModel.Selectors.SecurityTokenProvider.CancelTokenAsync
M:System.IdentityModel.Selectors.SecurityTokenProvider.CancelTokenCoreAsync(System.TimeSpan,System.IdentityModel.Tokens.SecurityToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Selectors/SecurityTokenProvider.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.IdentityModel.Selectors.SecurityTokenProvider.CancelTokenCoreAsync
M:System.IdentityModel.Selectors.SecurityTokenProvider.GetTokenAsync(System.TimeSpan) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Selectors/SecurityTokenProvider.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.IdentityModel.Selectors.SecurityTokenProvider.GetTokenAsync
M:System.IdentityModel.Selectors.SecurityTokenProvider.GetTokenCoreAsync(System.TimeSpan) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Selectors/SecurityTokenProvider.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.IdentityModel.Selectors.SecurityTokenProvider.GetTokenCoreAsync
M:System.IdentityModel.Selectors.SecurityTokenProvider.RenewTokenAsync(System.TimeSpan,System.IdentityModel.Tokens.SecurityToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Selectors/SecurityTokenProvider.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.IdentityModel.Selectors.SecurityTokenProvider.RenewTokenAsync
M:System.IdentityModel.Selectors.SecurityTokenProvider.RenewTokenCoreAsync(System.TimeSpan,System.IdentityModel.Tokens.SecurityToken) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IdentityModel.Selectors/SecurityTokenProvider.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.IdentityModel.Selectors.SecurityTokenProvider.RenewTokenCoreAsync

**Comment by carlossanlop** [comment]
@mconnew @HongGit @StephenBonikowsky can you please share your action plan for these undocumented APIs?

**Comment by mconnew** [comment]
I forgot about the identitymodel api's. I'll make another update to the ownership document to include them.
