### ISSUE TITLE
Microsoft.Win32 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3926]
@maryamariyan @Anipik 

Here are the undocumented API from `Microsoft.Win32`, introduced in 1.x.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?

For more information on the plan, see: #3904

Total: 6.
_Note: The table contains 3 really wide columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:Microsoft.Win32.RegistryAclExtensions.GetAccessControl(Microsoft.Win32.RegistryKey) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32/RegistryAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.RegistryAclExtensions.GetAccessControl
M:Microsoft.Win32.RegistryAclExtensions.GetAccessControl(Microsoft.Win32.RegistryKey,System.Security.AccessControl.AccessControlSections) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32/RegistryAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.RegistryAclExtensions.GetAccessControl
T:Microsoft.Win32.RegistryAclExtensions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32/RegistryAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.RegistryAclExtensions
M:Microsoft.Win32.RegistryAclExtensions.SetAccessControl(Microsoft.Win32.RegistryKey,System.Security.AccessControl.RegistrySecurity) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32/RegistryAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.RegistryAclExtensions.SetAccessControl
P:Microsoft.Win32.SafeHandles.SafeMemoryMappedFileHandle.IsInvalid | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32.SafeHandles/SafeMemoryMappedFileHandle.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.SafeHandles.SafeMemoryMappedFileHandle.IsInvalid
P:Microsoft.Win32.SafeHandles.SafeNCryptHandle.IsInvalid | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32.SafeHandles/SafeNCryptHandle.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.SafeHandles.SafeNCryptHandle.IsInvalid
P:Microsoft.Win32.SafeHandles.SafePipeHandle.IsInvalid | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32.SafeHandles/SafePipeHandle.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.SafeHandles.SafePipeHandle.IsInvalid
P:Microsoft.Win32.SafeHandles.SafeProcessHandle.IsInvalid | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32.SafeHandles/SafeProcessHandle.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.SafeHandles.SafeProcessHandle.IsInvalid
P:Microsoft.Win32.SafeHandles.SafeRegistryHandle.IsInvalid | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32.SafeHandles/SafeRegistryHandle.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.SafeHandles.SafeRegistryHandle.IsInvalid
P:Microsoft.Win32.SafeHandles.SafeX509ChainHandle.IsInvalid | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32.SafeHandles/SafeX509ChainHandle.xml | https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.Win32.SafeHandles.SafeX509ChainHandle.IsInvalid

**Comment by carlossanlop** [comment]
@maryamariyan @Anipik can you please share your action plan for these undocumented APIs?

**Comment by Anipik** [comment]
I will try to document them by end of this week
