### ISSUE TITLE
System.Threading 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3930]
@kouvel 

Here are the undocumented API from `System.Threading`, introduced in 1.x.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?
Since this namespace only has 7 undocumented APIs, it's possible to tackle them all on the first month.

For more information on the plan, see: #3904

_Note: The table contains 3 really wide columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Threading.ThreadingAclExtensions.GetAccessControl(System.Threading.EventWaitHandle) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadingAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Threading.ThreadingAclExtensions.GetAccessControl
M:System.Threading.ThreadingAclExtensions.GetAccessControl(System.Threading.Mutex) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadingAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Threading.ThreadingAclExtensions.GetAccessControl
M:System.Threading.ThreadingAclExtensions.GetAccessControl(System.Threading.Semaphore) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadingAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Threading.ThreadingAclExtensions.GetAccessControl
M:System.Threading.ThreadingAclExtensions.SetAccessControl(System.Threading.EventWaitHandle,System.Security.AccessControl.EventWaitHandleSecurity) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadingAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Threading.ThreadingAclExtensions.SetAccessControl
M:System.Threading.ThreadingAclExtensions.SetAccessControl(System.Threading.Mutex,System.Security.AccessControl.MutexSecurity) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadingAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Threading.ThreadingAclExtensions.SetAccessControl
M:System.Threading.ThreadingAclExtensions.SetAccessControl(System.Threading.Semaphore,System.Security.AccessControl.SemaphoreSecurity) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadingAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Threading.ThreadingAclExtensions.SetAccessControl
T:System.Threading.ThreadingAclExtensions | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ThreadingAclExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Threading.ThreadingAclExtensions

**Comment by carlossanlop** [comment]
@kouvel can you please share your action plan for these APIs?

**Comment by kouvel** [comment]
I don't think it would be very difficult to add docs for these APIs, it would mostly be copying the existing docs. I plan to get them done for 5.0 but I can't give a timeframe from my side at the moment.

**Comment by jeffhandley** [comment]
Thanks for letting us know, @kouvel. We'll check back in a couple weeks to see if you have an idea of when this work could get scheduled.
