### ISSUE TITLE
System.Linq 1.x undocumented APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3932]
@eiriktsarpalis 

Here are the undocumented API from `System.Linq`, introduced in 1.x.
We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 33% of the APIs in the next month. Can you please help us with that?
Since this namespace only has 3 undocumented APIs, it's possible to tackle them all on the first month.

For more information on the plan, see: #3904

_Note: The table contains 3 really wide columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Linq.ImmutableArrayExtensions.Aggregate\`\`3(System.Collections.Immutable.ImmutableArray{\`\`2},``0,System.Func{\`\`0,\`\`2,\`\`0},System.Func{\`\`0,\`\`1}) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/ImmutableArrayExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Linq.ImmutableArrayExtensions.Aggregate
M:System.Linq.ImmutableArrayExtensions.Single\`\`1(System.Collections.Immutable.ImmutableArray{\`\`0},System.Func{\`\`0,System.Boolean}) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/ImmutableArrayExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Linq.ImmutableArrayExtensions.Single
M:System.Linq.ImmutableArrayExtensions.ToArray\`\`1(System.Collections.Immutable.ImmutableArray{\`\`0}) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/ImmutableArrayExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Linq.ImmutableArrayExtensions.ToArray

**Comment by carlossanlop** [comment]
@eiriktsarpalis can you please post your action plan for these undoc APIs?

**Comment by eiriktsarpalis** [comment]
Tagging @adamsitnik as well.

**Comment by adamsitnik** [comment]
I've talked with Jeff and I've scheduled this for the begning of May.

**Comment by carlossanlop** [comment]
I'll create a new issue in dotnet/runtime with updated data.
