### ISSUE TITLE
Update CAS documentation to clarify its non-support within the package ecosystem

### ISSUE THREAD

**Issue by churstz** [dotnet/dotnet-api-docs#3957]
The documentation for System.Text.Encodings.Web.TextEncoder (Encode specifically) needs to include details around required permissions needed in order to use this method based on SecurityRules / Trust, especially if it's using non typesafe code (i.e. unsafe) like it is.

As this is a core piece of code for handling encoding for UrlEncoding, HtmlEncoding and JavascriptEncoding that gets referenced by multiple third party libraries, tracking down a System.VerificationException (Operation could destabilize the runtime.) in System.Text.Encodings.Web.TextEncoder.Encode(String value) is a pain.

**Comment by carlossanlop** [comment]
Adding @GrabYourPitchforks @layomia @tarekgh for triage.

**Comment by tarekgh** [comment]
The request looks reasonable to me.

**Comment by GrabYourPitchforks** [comment]
What's the specific problem being reported? Is there an environment where these APIs are failing? If so, I can open a product bug, as we wouldn't expect any failures for these APIs in supported environments.

If the issue is about Code Access Security (CAS), that technology has been dead for ages. The .NET team stopped testing new code against partial trust environments circa 2012. Since the tech itself is unsupported there's no need to call out that our libraries don't work in such an environmnet.

**Comment by churstz** [comment]
While the CAS technology may be dead for ages, these APIs are still building on top of the technology.  Code such as Microsoft Reporting Server still actively utilize CAS under the hood.  Other third party APIs that reference this core functionality (i.e. Identity Server) without knowledge of the underlying dependencies creates a fragile code base until such time that dead functionality is replace or removed.  Simply documenting this is a minimum bar that should be crossed at this point to aid in troubleshooting.

**Comment by GrabYourPitchforks** [comment]
Ok, then the appropriate place for this documentation would be at https://docs.microsoft.com/dotnet/framework/misc/code-access-security. We should make sure that the note at the top calls out three specific talking points:

- In .NET Framework, the CAS infrastructure exists but is no longer supported and will receive no security servicing
- In .NET Core / .NET 5, the CAS infrastructure no longer even exists in the runtime
- All libraries and NuGet packages (both first-party and third-party) should be assumed _not_ to work correctly in a partial trust environment unless they are explicitly documented as being tested in such an environment

I'll retitle this work item to reflect these changes.
