### ISSUE TITLE
Progress<T>: Link to example on .NET Framework Blog is broken

### ISSUE THREAD

**Issue by wldevries** [dotnet/dotnet-api-docs#3981]
> For more information and a code example, see the article Async in 4.5: Enabling Progress and Cancellation in Async APIs in the .NET Framework blog.

Link is broken, should be https://devblogs.microsoft.com/dotnet/async-in-4-5-enabling-progress-and-cancellation-in-async-apis/

**Comment by wldevries** [comment]
This is about https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Progress%601.xml

**Comment by gewarren** [comment]
This has been fixed.
