### ISSUE TITLE
Possible typo on https://docs.microsoft.com/en-us/dotnet/api/system.string.substring?view=netframework-4.8

### ISSUE THREAD

**Issue by nishantsny** [dotnet/dotnet-api-docs#4040]
https://docs.microsoft.com/en-us/dotnet/api/system.string.substring?view=netframework-4.8 

Should the line towards the end be

If startIndex is equal to zero and **results** equals the length of the current string, the method returns the original string unchanged.

**Comment by carlossanlop** [comment]
Although I would select a different wording, your suggestion makes sense. Would you like to submit a PR to fix it, @nishantsny ?

**Comment by rodeten** [comment]
Submitted a push Request to the <live> branch #5090 .

Let me know if that works!
