### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by paukuk** [dotnet/dotnet-api-docs#4046]
Spelling mistake in [https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.8](url)
**_SupressFinalize_**

`        public void Dispose()
        {
            Dispose(true);
            // This object will be cleaned up by the Dispose method.
            // Therefore, you should call GC.SupressFinalize to
            // take this object off the finalization queue
            // and prevent finalization code for this object
            // from executing a second time.
            GC.SuppressFinalize(this);
        }`

**Comment by carlossanlop** [comment]
Thank you for reporting, @paukuk. Would you like to submit a PR to fix it?
