### ISSUE TITLE
System.Diagnostics.Process 1.x undocumented APIs 

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#4065]
@adamsitnik @eiriktsarpalis 

Here are the undocumented API from `System.Diagnostics.Process`.

We are asking all area owners to report back their plan/commitment for their undocumented APIs in order to tackle 66% of the APIs in the month of April, and 100% by the end of May.

Can you please help us with that?

For more information on the plan, see: #3904

Total: 11.
_Note: The table has 3 really long columns._

DocId | Source File Path | Docs URL
-- | -- | --
M:System.Diagnostics.Process.Dispose | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/Process.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.Process.Dispose
P:System.Diagnostics.ProcessModuleCollection.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessModuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessModuleCollection.Count
M:System.Diagnostics.ProcessModuleCollection.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessModuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessModuleCollection.GetEnumerator
M:System.Diagnostics.ProcessModuleCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessModuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessModuleCollection.System-Collections-ICollection-CopyTo
P:System.Diagnostics.ProcessModuleCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessModuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessModuleCollection.System-Collections-ICollection-IsSynchronized
P:System.Diagnostics.ProcessModuleCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessModuleCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessModuleCollection.System-Collections-ICollection-SyncRoot
P:System.Diagnostics.ProcessThreadCollection.Count | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessThreadCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessThreadCollection.Count
M:System.Diagnostics.ProcessThreadCollection.GetEnumerator | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessThreadCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessThreadCollection.GetEnumerator
M:System.Diagnostics.ProcessThreadCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32) | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessThreadCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessThreadCollection.System-Collections-ICollection-CopyTo
P:System.Diagnostics.ProcessThreadCollection.System#Collections#ICollection#IsSynchronized | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessThreadCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessThreadCollection.System-Collections-ICollection-IsSynchronized
P:System.Diagnostics.ProcessThreadCollection.System#Collections#ICollection#SyncRoot | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessThreadCollection.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.ProcessThreadCollection.System-Collections-ICollection-SyncRoot

**Comment by carlossanlop** [comment]
@adamsitnik I noticed there are 6 Explicit Interface Implementations. You can use [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to port them automatically. @eiriktsarpalis already used it for the areas where he is main owner.

**Comment by eiriktsarpalis** [comment]
I'll be taking this since Adam has already committed to work on System.Linq. I'll start working on this on the second half of April.
