### ISSUE TITLE
Target version-specific remarks

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/dotnet-api-docs#4080]
Is there a way to add type documentation, specific to a selected target version?

For example, Uri has a lot of comments in remarks that only apply to framework and not Core.
Is there a way to hide such text when a newer target version is selected / add text that is shown on Core only?

**Comment by carlossanlop** [comment]
Tagging @gewarren in case there is official guidance.

What we have done in the past is explicitly split the sentences in remarks by version. For example:

```
.NET Framework only: This is the behavior.

.NET Core 3.1: This is another behavior.

.NET 5.0: Yet another one.
```

**Comment by gewarren** [comment]
Currently, there's no way to version the remarks to only show what's applicable to the currently selected version. Carlos' guidance is correct (except I'd use ".NET 5.0 and later versions" for the last one).

**Comment by carlossanlop** [comment]
Also, I don't think there is a way to hide information. I think we had this discussion in the past with the Docs infrastructure team. I'll see if I can find the internal bug and ping them to see if they plan on splitting this information in the near future. But for now, the answers above describe all we can do.

@MihaZupan I'll go ahead and close the question as resolved. If you want to discuss further, feel free to reopen.
