### ISSUE TITLE
Is System.Net.Mail.SmtpClient obsolete in 4.7.2 and 4.8 ?

### ISSUE THREAD

**Issue by MatthieuHernandez** [dotnet/dotnet-api-docs#4114]
I can't see any trace of `System.Obsolete` inside the code of [SmtpClient.cs](https://referencesource.microsoft.com/#System/net/System/Net/mail/SmtpClient.cs). Does this mean that this class is not obsolete?

Because in [docs.microsoft.com](https://referencesource.microsoft.com/#System/net/System/Net/mail/SmtpClient.cs) it states clearly, This API is now obsolete.

**Comment by MSDN-WhiteKnight** [comment]
See https://github.com/dotnet/dotnet-api-docs/issues/2986 for prior discussion. SmtpClient is marked with ObsoleteAttribute in Xamarin/Mono, and due to docs site engine bug it causes the obsolete notice to be displayed for all frameworks. In .NET Framework/Core, it is **not** marked obsolete, but it's still considered legacy API (not updated to new protocol features).

**Comment by mdell-seradex** [comment]
It has been a year already and the docs still say this is obsolete in Framework 4.  Can't this be manually corrected?

**Comment by eerhardt** [comment]
@dotnet/ncl - thoughts?

**Comment by karelz** [comment]
There is no mention of obsoletion in the docs beside Xamarin when I open them: [SmtpClient docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.8)

The [Remarks section](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.8#remarks) explicitly calls it out:

_The `SmtpClient` class is obsolete in Xamarin. However:_
- _It is included in the .NET Standard 2.0 and later versions and therefore must be part of any .NET implementation that supports those versions._
- _It is present and can be used in .NET Framework 4 through .NET Framework 4.8._
- _It is usable in .NET Core, but its use isn't recommended._

**Comment by karelz** [comment]
The original question has been answered in the docs, closing.

**Comment by mdell-seradex** [comment]
The mention of obsolete in the docs is in the first paragraph:
`Allows applications to send email by using the Simple Mail Transfer Protocol (SMTP). The SmtpClient type is now obsolete.
`
The remarks section does not contradict this statement, or explicitly say "only in Xamarin".
It is confusing for the first paragraph to say this as most people won't ever reach the Remarks section to see it try and fail to explain further.

**Comment by karelz** [comment]
OK, that was missing in the original report - the link wasn't there and the text quoted was slightly different. Reopening.

I think we can change the text to "_The SmtpClient type is now obsolete on some platforms and not recommended on others - see Remarks for details._"
Would that satisfy your concerns?

**Comment by mdell-seradex** [comment]
That sounds much better.  I believe that should clarify things sufficiently.  Hopefully, the original poster agrees with me.
