### ISSUE TITLE
NullReferenceException when removing items from a CheckedListBox in the ItemCheck handler

### ISSUE THREAD

**Issue by AustinWise** [dotnet/dotnet-api-docs#4138]
* .NET Core Version: 3.1.3

* Have you experienced this same bug with .NET Framework?: On 3.5, no. On 4.8 (Windows 10 178363.778), yes. I suspected this exception did not happen on some earlier versions of .NET Framework 4.x.

**Problem description:**

NullReferenceException from WinForms code after removing items from a CheckedListBox in the ItemCheck handler:

```
   at System.Windows.Forms.CheckedListBox.CheckedItemCollection.SetCheckedState(Int32 index, CheckState value)
   at System.Windows.Forms.CheckedListBox.LbnSelChange()
   at System.Windows.Forms.CheckedListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.CheckedListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Expected behavior:**
I'm not sure how legitimate this bug is, as it does seem a bit questionable to clear the list of Items in an ItemChecked handler. However the the documentation makes no mention of this not being supported and it used to work (though perhaps by chance).

**Minimal repro:**

```csharp
using System;
using System.Windows.Forms;

namespace ConsoleApp4
{
    class Program : Form
    {
        [STAThread]
        static void Main(string[] args)
        {
            Application.EnableVisualStyles();
            Application.Run(new Program());
        }

        readonly CheckedListBox mLb;

        Program()
        {
            mLb = new CheckedListBox();
            mLb.Dock = DockStyle.Fill;
            mLb.Items.Add("A");
            mLb.Items.Add("B");
            mLb.Items.Add("C");
            mLb.ItemCheck += MLb_ItemCheck;
            this.Controls.Add(mLb);
        }

        private void MLb_ItemCheck(object sender, ItemCheckEventArgs e)
        {
            mLb.Items.Clear();
            //program crashes after this callback returns
        }
    }
}
```

**Comment by RussKie** [comment]
The documentation for [`CheckedListBox.ItemCheck`](https://docs.microsoft.com/dotnet/api/system.windows.forms.checkedlistbox.itemcheck) must state that the listbox's items must not be cleared in this event. 
Applies to all versions.

**Comment by AustinWise** [comment]
Thanks, I agree that "fixing" this is probably not worth it; I took a look and it would not be entirely straightforward to deal with this.

I have a work around too, which may or may not be worth adding to the documentation: use `BeginInvoke` to remove items after the `CheckedBoxList` has finished updating its internal state.
