### ISSUE TITLE
FileStream example bug

### ISSUE THREAD

**Issue by malghabr** [dotnet/dotnet-api-docs#4141]
Hi,

Not sure if this is considered a bug but the first example on the FileStream docs only works if you have a file with less than 1024 bytes or bytes%1024 == 0. This is due to the buffer byte array being reused. 
If you use a 4 byte array and try read the string "hello" you end up with the following in the buffer
loop iteration 0:  hell 
loop iteration 1: oell
> hell
> oell
This is because the byte array holds data from the first loop
https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream?view=netframework-4.8

**Comment by GSPP** [comment]
What a weird example anyway. So random, what's the idea behind it? Reminds me of the socket documentation.

**Comment by Jozkee** [comment]
Yes, it is a bit silly. Feel free to send a PR to propose an improved snippet. 

Here's where you can find the snippets of the current ones:
https://github.com/dotnet/dotnet-api-docs/blob/77bcd7bc0b2589ce422c84f9223c854610543a0e/xml/System.IO/FileStream.xml#L94-L96

**Comment by malghabr** [comment]
Sure I can pick this up when i have time
