### ISSUE TITLE
Chinese requirements for documents for .NET API browser

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4188]
_From @SmRiley on Friday, May 1, 2020 3:27:06 PM_

Hello, I'd like to ask if there is a schedule for the localization of. Net API browser documents, because I notice that the documents in this section do not seem to be maintained by the community

_Copied from original issue: MicrosoftDocs/feedback#2713_

**Comment by gewarren** [comment]
_From @welcome[bot] on Friday, May 1, 2020 3:27:08 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
_From @gewarren on Friday, May 1, 2020 7:04:36 PM_

@JasonCard Can you help answer this?

**Comment by srvbpigh** [comment]
Hello, @gewarren
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @SmRiley,

Thank you for your question.
Usually, it could take up to two weeks for updates in .NET API reference content to be localized. 
Currently, we are aware of technical build issue for all localized contents and working to resolve the issue.

Best regards,
Jason

cc @gewarren

**Comment by JasonCard** [comment]
Hi @SmRiley 

Sorry for the delay, but all localized content should be up-to-date with English content now.
Please let me know if you still see any issues.

Best regards,
Jason
