### ISSUE TITLE
HttpClient.GetAsync can throw UriFormatException

### ISSUE THREAD

**Issue by dmondrik** [dotnet/dotnet-api-docs#4201]
There are 4 overloads of GetAsync that take a string and convert it to a URI in the implementation. All 4 of these should have UriFormatException documented as a possible exception:
```
GetAsync(String)
GetAsync(String, HttpCompletionOption)
GetAsync(String, CancellationToken)
GetAsync(String, HttpCompletionOption, CancellationToken)
```

**Comment by glihm** [comment]
@dmondrik hello,

`UriFormatException` is never thrown by the `HttpClient.GetAsync` method.

If you check the [code](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs), there is a function `CreateUri` that accepts both relative and absolute Uri -- it means that every string can be accepted here. If the string is null, null is returned, and the function `PrepareRequestMessage` will throw an `InvalidOperationException`.

You can close the issue, as this is not an issue. :)

**Comment by dmondrik** [comment]
@glihm unfortunately the documentation does not match the implementation. I'll admit I ought to have included the culprit when I originally mentioned the issue. If you pass in a string with an extra slash such as "http:///extra-slash/uri", it will indeed throw `UriFormatException` when it tries to parse the string.

**Comment by glihm** [comment]
@dmondrik that's a very good catch, I have tried lot's of dummy URI but not like your example. And indeed it throws!

In my opinion it deserves a PR so. :)

**Comment by glihm** [comment]
@dmondrik also, thanks to your issue, I have made a PR because the `ArgumentNullException` is not thrown, an `InvalidOperationException` is thrown instead.
