### ISSUE TITLE
List DayOfWeek enum by value instead of alphabetized by name

### ISSUE THREAD

**Issue by nullforce** [dotnet/dotnet-api-docs#4210]
Fields should not be alphabetized and instead follow the order:
* Sunday - 0
* Monday - 1
* Tuesday - 2
* Wednesday - 3
* Thursday - 4
* Friday - 5
* Saturday - 6

https://github.com/dotnet/dotnet-api-docs/blob/b4ec0e45b0e446a1f632ff4c9eca1753d3c377b0/xml/System/DayOfWeek.xml#L68

**Comment by gewarren** [comment]
I agree this looks weird: https://docs.microsoft.com/en-us/dotnet/api/system.dayofweek?view=netcore-3.1#fields

**Comment by gewarren** [comment]
The order of enum fields is auto-generated and I don't think we can customize it for a given enum. I have let @mimisasouvanh know about this request so hopefully we can implement it system-wide.

**Comment by gewarren** [comment]
Internal work item to track this is https://dev.azure.com/ceapex/Engineering/_workitems/edit/321397.

**Comment by xtqqczze** [comment]
It would be great to fix this, see: #8892, #6786, #6749, #4725, #4558, #4352, #3852.

**Comment by gewarren** [comment]
> It would be great to fix this, see: #8892, #6786, #6749, #4725, #4558, #4352, #3852.

Also #9334.

**Comment by gewarren** [comment]
This is finally fixed!!

https://learn.microsoft.com/en-us/dotnet/api/system.dayofweek?view=net-8.0#fields

![Image](https://github.com/user-attachments/assets/3d824cfb-ab1c-4c2c-99e8-88fe4fc023e5)
