### ISSUE TITLE
The various System.Math and System.MathF functions should clarify there results may differ across platforms

### ISSUE THREAD

**Issue by tannergooding** [dotnet/dotnet-api-docs#4231]
Several of the functions currently have incorrect documentation that only applies to 32-bit Windows. For example, `Math.Sin` currently documents:
> Acceptable values of a range from approximately -9223372036854775295 to approximately 9223372036854775295. For values outside of this range, the Sin method returns a unchanged rather than throwing an exception.

The implementation currently just invokes down to the underlying C Runtime implementation for each OS/Architecture, so the results you get may differ between the various permutations of:
* Architecture: x86, x64, ARM, ARM64
* OS: Windows, Linux, macOS
They may further differ between releases of .NET based on the underlying C Runtime implementation version that the .NET runtime was compiled against.

The documentation should explicitly call out this fact and should likely clarify what OS/Architecture specific remarks apply to.

For example, the input domain for `sin` is (−∞, +∞) and while the 32-bit Windows implementation limits it as stated, the 64-bit Windows implementation recognizes the full domain and does not return the input for values outside the listed range. Likewise, the documentation doesn't account for inputs that are +/-Infinity, which return `NaN`.

**Comment by tannergooding** [comment]
CC. @pgovind, @jeffhandley

**Comment by tannergooding** [comment]
Assigning to myself as I'll likely be responsible for updating these docs.

**Comment by carlossanlop** [comment]
@tannergooding Hey there's no `area-System.Math` area, so let me know if you're ok with having Math-related issues tagged as `area-System.Numerics` or something else. This will help the autolabeling bot.

**Comment by tannergooding** [comment]
That's fine, we do the same for dotnet/runtime!
