### ISSUE TITLE
Bad link in SslProtocols Enum

### ISSUE THREAD

**Issue by DavidEshtehari** [dotnet/dotnet-api-docs#4235]
Hi,
There is a mistake in content here [SslProtocols Enum](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Security.Authentication.SslProtocols);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-3.1) to refer to the [FlagsAttribute Class](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute).
I have intentionally removed the `<` symbol to illustrate the mistake.

> This enumeration has a a href="https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute">FlagsAttribute</a> attribute that allows a bitwise combination of its member values.

**Comment by svick** [comment]
This seems to happen for all `enum`s with `FlagsAttribute`. I have noticed it on [`MethodImplOptions`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?view=netcore-3.0):

![](https://user-images.githubusercontent.com/287848/83301780-7ed4e980-a1fa-11ea-9656-e0df294dc84c.png)

**Comment by glihm** [comment]
Duplicate #4391 , seems to be corrected since.

**Comment by carlossanlop** [comment]
Looks like it's fixed.
