### ISSUE TITLE
CultureInfo.CurrentCulture document default on Unix-likes

### ISSUE THREAD

**Issue by kevinoid** [dotnet/dotnet-api-docs#4254]
The procedure described in [How a Thread's Culture Is Determined](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture#how-a-threads-culture-is-determined) section of the documentation for [`CultureInfo.CurrentCulture`](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture) currently ends with

> * By calling the Windows `GetUserDefaultLocaleName` function.

Which clearly does not apply to .NET Core on non-Windows systems.  After a bit of digging I've found the following:

* [`CultureInfo.CurrentCulture.get`](https://github.com/dotnet/runtime/blob/v5.0.0-preview.3.20214.6/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureInfo.cs#L388) calls
* [`CultureInfo.GetUserDefaultCulture()`](https://github.com/dotnet/runtime/blob/v5.0.0-preview.3.20214.6/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureInfo.Unix.cs#L11) calls
* [`GlobalizationNative_GetDefaultLocaleName`](https://github.com/dotnet/runtime/blob/1db45ed953745c0e270d09df99828cb58772f4ad/src/libraries/Common/src/Interop/Interop.Locale.cs#L21) defined as
* [`GlobalizationNative_GetDefaultLocaleName`](https://github.com/dotnet/runtime/blob/v5.0.0-preview.3.20214.6/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L208) calls
* [`DetectDefaultLocaleName`](https://github.com/dotnet/runtime/blob/v5.0.0-preview.3.20214.6/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L131) calls
* [`uloc_getDefault`](https://github.com/unicode-org/icu/blob/release-67-1/icu4c/source/common/uloc.cpp#L2103) (in [ICU](https://icu-project.org)) calls
* [`locale_get_default`](https://github.com/unicode-org/icu/blob/release-67-1/icu4c/source/common/locid.cpp#L240) calls
* [`Locale::getDefault`](https://github.com/unicode-org/icu/blob/release-67-1/icu4c/source/common/locid.cpp#L926) calls
* [`locale_set_default_internal`](https://github.com/unicode-org/icu/blob/release-67-1/icu4c/source/common/locid.cpp#L172) calls
* [`uprv_getDefaultLocaleID`](https://github.com/unicode-org/icu/blob/release-67-1/icu4c/source/common/putil.cpp#L1615) calls
* [`uprv_getPOSIXIDForDefaultLocale`](https://github.com/unicode-org/icu/blob/release-67-1/icu4c/source/common/putil.cpp#L1589) calls
* [`uprv_getPOSIXIDForCategory(LC_MESSAGES)`](https://github.com/unicode-org/icu/blob/release-67-1/icu4c/source/common/putil.cpp#L1526) calls
* [`setlocale(3)`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/setlocale.html) with `category` `LC_MESSAGES`, which is specified by XBD [Locale](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap07.html#tag_07) and [Internationalization Variables](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_02) to use the first valid value from `$LC_ALL`, `$LC_MESSAGES`, or `$LANG`.

Assuming ICU is an implementation detail and that developers are more likely to be familiar with `setlocale(3)` than `uloc_getDefault()`, I'd suggest changing the last bullet point to something like:

* By calling the Windows `GetUserDefaultLocaleName` function, or POSIX `setlocale(3)` with `LC_MESSAGES` on Unix-like systems.

With appropriate caveats if this behavior is not guaranteed.

Thanks for considering,
Kevin

**Comment by carlossanlop** [comment]
cc @GrabYourPitchforks @safern @tarekgh @krwq

**Comment by tarekgh** [comment]
The proposal looks good to me. We may do extra things in 6.0 for MacOS but we can update the doc during then.

**Comment by tarekgh** [comment]
@kevinoid maybe would be better if you go ahead and open a PR for this change. Thanks for reporting this issue.

**Comment by kevinoid** [comment]
Thanks @tarekgh.  I just opened PR #5071 to address this issue.

**Comment by tarekgh** [comment]
Thanks @kevinoid I have added a comment there if you want to take a look.
