### ISSUE TITLE
ImmutableArray<T>.ToBuilder method has incorrect remark

### ISSUE THREAD

**Issue by joost-morsink** [dotnet/dotnet-api-docs#4262]
The remarks section of the ToBuilder method of the ImmutableArray<T> class (System.Collections.Immutable) incorrectly states it is an O(1) operation. 
The implementation calls an AddRange on the Builder class, which is clearly O(n).

**Comment by svick** [comment]
I believe you are right. Do you want to submit a Pull Request to fix this? The relevant text is here:

https://github.com/dotnet/dotnet-api-docs/blob/9a8ca60aade8c08759280b7a5b7fc26bdf0dcc51/xml/System.Collections.Immutable/ImmutableArray%601.xml#L3690-L3691

**Comment by joost-morsink** [comment]
I Will. Probably on Friday.
