### ISSUE TITLE
Documentation doesn't fully translate to other languages 

### ISSUE THREAD

**Issue by mikadumont** [dotnet/dotnet-api-docs#4269]
We received this request regarding documentation not fully translating from English to other languages: 

https://developercommunity.visualstudio.com/content/idea/1024535/go-to-the-docsmicrosoftcom-from-classes.html

For example here is the same page in Russian:

https://docs.microsoft.com/ru-ru/dotnet/api/system.console.writeline?view=netcore-3.1#System_Console_WriteLine_System_String_

Notice how a lot of it is still in English and can be hard to understand if you are not fluent in English.

**Comment by gewarren** [comment]
@JasonCard Any idea why this is happening?

**Comment by srvbpigh** [comment]
Hello, @mikadumont
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
@gewarren Yes, we run into a couple of technical issue with our loc platform and currently try to get them resolved. Will update when resolved. Assigning to myself.

**Comment by JasonCard** [comment]
Hi @mikadumont @gewarren 
Sorry for the delay, this articles is now fully localized in live page:
<https://docs.microsoft.com/ru-ru/dotnet/api/system.console.writeline?view=netcore-3.1#System_Console_WriteLine_System_String>
