### ISSUE TITLE
ExpandoObject Class "Implements" is broken

### ISSUE THREAD

**Issue by dhcgn** [dotnet/dotnet-api-docs#4292]
You can see, that the section "Implements" is broken: https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.expandoobject?view=netcore-3.1

I don't know you this xml files are interpreted, but this should be a minor bug.

https://github.com/dotnet/dotnet-api-docs/blob/1d5e621501f4fdfbaa76189ed17dc4a3183f72cd/xml/System.Dynamic/ExpandoObject.xml#L42-L70

![image](https://user-images.githubusercontent.com/6566207/83015868-6362b680-a021-11ea-95f6-eaea843b03f9.png)

**Comment by carlossanlop** [comment]
@dhcgn I cannot repro the issue. Are you still seeing it? Maybe it was a transient bug.
