### ISSUE TITLE
Previewing API documentation changes

### ISSUE THREAD

**Issue by justin-kendrick** [dotnet/dotnet-api-docs#4302]
I'd like to contribute to the docs, but I want to make sure my changes build okay and look right before I send a pull request.  I can preview markdown files easily enough, but I haven't figured out how to generate HTML from the XML API docs.  How should I check my changes before submitting them?

**Comment by gewarren** [comment]
The easiest way to build and preview is to create a draft pull request. Unfortunately, only Microsoft employees can view the preview site (review.docs.microsoft.com) currently, but one of us can check it for you.

**Comment by carlossanlop** [comment]
@justin-kendrick thanks for offering to help! We welcome all contributions.

It's difficult to make the dotnet-api-docs build to get to work in your locally machine. And even if you manage to make it work, it could take between 4 to 6 hours to finish (believe me, I tried).

If your offer is to add missing documentation to our APIs, then my suggestion (and this is what my team has recently started to do) is to add the triple slash comments to source first, build the project where you added them, then use the [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to help you automatically port the documentation to the dotnet-api-docs repo.

I'll be happy to help you with any questions you have.

**Comment by carlossanlop** [comment]
Feel free to contribute whenever you'd like, @justin-kendrick . I'll go ahead and close this issue, and we welcome any PRs from you.
