### ISSUE TITLE
Superfuous trailing comma in attribute list

### ISSUE THREAD

**Issue by svick** [dotnet/dotnet-api-docs#4307]
When listing the attributes for a type, the list contains an extra comma at the end. For example for [`MethodImplOptions`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?view=netcore-3.0), the list is:

![](https://user-images.githubusercontent.com/287848/83308462-1a6c5700-a207-11ea-9697-e4059c783d95.png)

Notice that the list contains only a single item, but a comma is shown after it.

**Comment by glihm** [comment]
@svick I haven't got this behavior, it was probably fixed. Can you confirm?

**Comment by svick** [comment]
@glihm  Yeah, seems to be fixed, closing.
