### ISSUE TITLE
Broken links in ConnectionString

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4308]
The [ConnectionString property article](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=dotnet-plat-ext-3.1#remarks) has a number of broken links. For example:

https://go.microsoft.com/fwlink/?LinkId=393996 goes to error page: https://msdn.microsoft.com/en-us/library/dn632678.aspx

https://support.microsoft.com/kb/258858 goes to: https://support.microsoft.com/en-us/help/258858

**Comment by glihm** [comment]
@gewarren hello,

yup, and the KB 258858 is also broken [here](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15) and perhaps more pages.

about the link 393996, I would suggest to use the same link for direct download as [Connection resiliency driver](https://docs.microsoft.com/en-us/sql/connect/odbc/windows/connection-resiliency-in-the-windows-odbc-driver?view=sql-server-ver15) page. The link would be: https://download.microsoft.com/download/D/2/0/D20E1C5F-72EA-4505-9F26-FEF9550EFD44/Idle%20Connection%20Resiliency.docx.

**Comment by carlossanlop** [comment]
Tagging area owners @ajcvickers @cheenamalhotra @David-Engel to help fix the broken links.
