### ISSUE TITLE
Improve String.Split article

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4309]
35K page views per month, CSAT ~33%.

Verbatims:

Moreover, the example which uses regular expressions takes a lot of space in this topic, … yet clearly does not belong here! You really should remove it from this topic (perhaps leaving a hyperlink to the example's new Location).
Put the alternatives on a separate page. This expo of regex within what is supposed talking ONLY about Split() is confusing and messy.
Use simple, not convoluted, examples.
This page works for people who already have an understanding of the .net framework. However for newbies who are trying to learn this, it is difficult to understand.
There's an overload that takes a single string...pretty simple, only available in VB.
Split(String[], StringSplitOptions):
(1) "Return value details", first paragraph: There are only two return elements! Try it yourself!

(2) "The separator array", first paragraph: "consists of multiple characters": separator does not consist of characters, but of strings!

(3) "The separator array", second paragraph: "If the separator parameter is null or contains no characters,": Same as before. Moreover, it is not unambiguously specified what happens if separator does contain one or more strings which all are null or empty, cf. "Comparison details", third paragraph.

Not clear
It will be beter if there is an example
I want to see an example with the actual Split() funcion
It is extremely difficult to find out what the default separator is without reading the entire document.
It is a good idea to start with a simple and focused example on the subject. This page is about Split not RegEx wonders.

Splits not even in the first example. 35 pages of what it this?
ejemplos terribles

**Comment by glihm** [comment]
@gewarren I do agree with most of this issue.

However, the (2) is completely fine for me. A string can be null, empty (0 character) or 1+ characters. So the sentence `If any of the elements in separator consists of multiple characters` does make sense for me, what do you think?

**Comment by gewarren** [comment]
@glihm Yes, you are right, thanks for pointing that out!

**Comment by glihm** [comment]
Some other points to keep them here and get them back for me or someone that want to help rewriting this:

> A very basic example can be:

```C#
        string str = "Hello, world!";

        string[] substrings = str.Split(' ');
        // substrings = ['Hello', 'world!'];

        foreach (string s in substrings)
        {
            Console.WriteLine(s);
        }

        // The example outputs:
        //     Hello,
        //     world!
```

> The functions signatures use `separator(s)` but the text sometimes use delimiter. We may try to make this more consistent.

> Some code snippets use `String`, `string` might be more appropriated and in accordance with most of other snippets in the same page and the documentation.

> The alternative to `String.Split` are not that bad, but as mentioned by @gewarren , they are misplaced and far too long. We need to make either a very short example and redirect to regex/substring pages or no examples but only text with redirection to regex/substring pages.

> The [code snippet 1](https://github.com/dotnet/dotnet-api-docs/blob/master/samples/snippets/csharp/VS_Snippets_CLR/string.split3/CS/omit.cs) from `omit.cs` is used several times and it's waaaaay too long. We must consider changing it, or not repeating it too much with new examples.
Moreover, this example is already used in the `StringSplitOption` documentation.

> Overloads are not logically ordered. I would suggest and order based on overload parameters and starting with the most used in general cases. The descriptions are also with a suggested rewording in my example below to be clearer and homogenized.

```C#
Split(Char, StringSplitOptions)	
Splits a string into substrings based on the provided character <delimiter_word>.

Split(String, StringSplitOptions)	
Splits a string into substrings that are based on the provided string <delimiter_word>.

Split(String, Int32, StringSplitOptions)	
Splits a string into a maximum number of substrings based on the provided string <delimiter_word>.

Split(Char, Int32, StringSplitOptions)	
Splits a string into a maximum number substrings based on the provided character <delimiter_word>.

Split(String[], StringSplitOptions)	
Splits a string into substrings based on the strings in an array.

Split(Char[], StringSplitOptions)	
Splits a string into substrings based on the characters in an array.

Split(Char[], Int32, StringSplitOptions)	
Splits a string into a maximum number of substrings based on the characters in an array.

Split(String[], Int32, StringSplitOptions)	
Splits a string into a maximum number of substrings based on the strings in an array.

Split(Char[])	
Splits a string into substrings that are based on the characters in the separator array.

Split(Char[], Int32)
Splits a string into a maximum number of substrings based on the characters in an array. You also specify the maximum number of substrings to return.
```

> There is a lot of repetitions of examples and text when an array is used as `separator` parameter. We may find a way to factor this text in the first remark to avoid this page to be too long (lot's of scroll to reach the bottom).
