### ISSUE TITLE
BitConverter issues

### ISSUE THREAD

**Issue by bradmarder** [dotnet/dotnet-api-docs#4327]
`public static ulong ToUInt64(ReadOnlySpan<byte> value);` is missing the following exception

```
        // Exceptions:
        //   T:System.ArgumentOutOfRangeException:
        //     The length of value is less than the length of a System.Int64 value.
```

...but I'm not sure if that is intended or whether `System.Int64` should be a hardcoded `8`. Different methods have alternating styling. The implementations all compare `sizeof(T)` and don't use constants.

`public static bool ToBoolean(ReadOnlySpan<byte> value)` has an incorrect exception.
```
        // Exceptions:
        //   T:System.ArgumentOutOfRangeException:
        //     The length of value is less than 0.
```
The 0 should be a 1.
It should read `The length of value is less than the length of a System.Byte value.` or something more explicit like "The length of the value is zero."

`public static ushort ToUInt16(ReadOnlySpan<byte> value)` has a typo in the exception signature.

```
        // Exceptions:
        //   T:System.ArgumentOutOfRangeException:
        //     The length of value is less than the 2.
```

Note, I just did a cursory glance so there may be other issues. I can submit a PR if you specify which styling you'd prefer (sizeof(T) vs constant)

**Comment by glihm** [comment]
@bradmarder hello,

I do agree with these typos and suggestions and as you mentioned, a global revision of BitConverter documentation can be a great thing to do.

And for the PR, let's see what maintainers think about it. 👍

**Comment by carlossanlop** [comment]
@tannergooding @pgovind any chance you can triage this issue?

**Comment by pgovind** [comment]
Thank you for reporting this. The docs should definitely be improved here, I agree. For whether we should prefer `sizeof(T)` vs constant, I'll let @gewarren or @tannergooding chime in. We'd definitely be interested in a PR (I would recommend using `sizeof(T)` until we get a reply so you can do find-replace easily if you need to) :) Please tag me or @tannergooding or @carlossanlop and we'll be happy to review it!
