### ISSUE TITLE
Missing & incorrect examples in xml/System/Boolean.xml

### ISSUE THREAD

**Issue by paulmasri** [dotnet/dotnet-api-docs#4368]
### Missing example

The following paragraph says that an example follows, but this example is absent:

> When converting from floating-point values to Boolean values, the conversion methods perform an exact comparison with zero. If the floating-point value has lost precision, the result can be unexpected. This is illustrated in the following example, in which a Double variable whose value should be zero is converted to a Boolean value. As the example shows, the result is true because repeated additions of 0.2 have resulted in a loss of precision.

### Incorrect example

The wrong example is in the page _following_ this excerpt:

> However, when you want to compare a Boolean variable with the literal Boolean value true or false, it is not necessary to do an explicit comparison, because the result of evaluating a Boolean value is that Boolean value. For example, the expressions
>
> `if (booleanValue) {`
>
> and

Presumably the example should be

    if (booleanValue == true) {

However it is:

```
using System;

public class Example
{
   public static void Main()
   {
      bool[] hasServiceCharges = { true, false };
      Decimal subtotal = 120.62m;
      Decimal shippingCharge = 2.50m;
      Decimal serviceCharge = 5.00m;

      foreach (var hasServiceCharge in hasServiceCharges) {
         Decimal total = subtotal + shippingCharge +
                                (hasServiceCharge ? serviceCharge : 0);
         Console.WriteLine("hasServiceCharge = {1}: The total is {0:C2}.",
                           total, hasServiceCharge);
      }
   }
}
// The example displays output like the following:
//       hasServiceCharge = True: The total is $128.12.
//       hasServiceCharge = False: The total is $123.12.
```

**Comment by glihm** [comment]
@paulmasri that's a good catch!

I have opened a pull-request #4551 , feel free to check and add comment if something is missing.
