### ISSUE TITLE
[WinForms] Incorrect default value for `ListView.HideSelection` since net48

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4385]
---
**Issue moved from dotnet/docs#18952**
- Please respond to @RussKie.

---

_From @RussKie on Monday, June 15, 2020 5:36:27 AM_

**Issue description**

In net48 as part of accessibility enhancement work the default value for [`ListView.HideSelection` property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.hideselection?view=netframework-4.8#remarks) has changed to `false` unless a user opted out of accessibility enhancements introduced in net48 (i.e. `Switch.UseLegacyAccessibilityFeatures.3=false`). More information can be found here: https://docs.microsoft.com/en-us/dotnet/framework/whats-new/whats-new-in-accessibility

In .NET Core 3.x and .NET 5 onwards the accessibility quirks available in .NET Framework were removed, and the default value is `false`.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

**Comment by carlossanlop** [comment]
@Russkie this issue you opened was transferred to dotnet-api-docs. We are asking area owners to get these issues addressed, so in this case, please feel free to assign to someone in the Winforms team.

**Comment by RussKie** [comment]
We need help/guidance to make the doc display different information between the different versions.

**Comment by RussKie** [comment]
Thank you @gewarren. I totally missed the notification so some belated feedback/question.

We're currently presenting the information like this:
    ![image](https://user-images.githubusercontent.com/4403806/97247725-56f2bc00-1854-11eb-9df4-4bb8fe83a9e7.png)

Could we have presented the info like this?
    ![image](https://user-images.githubusercontent.com/4403806/97247671-3cb8de00-1854-11eb-89f6-a0e12fa382a4.png)
