### ISSUE TITLE
Link for FlagsAttribute in DateTimeStyles Enum doc does not display correctly

### ISSUE THREAD

**Issue by hswan-msft** [dotnet/dotnet-api-docs#4391]
Hi,
The link for FlagsAttribute in [DateTimeStyles Enum doc](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimestyles?view=netcore-3.1#System_Globalization_DateTimeStyles_AdjustToUniversal) does not display correctly.
![image](https://user-images.githubusercontent.com/50006033/84764394-3c841880-b000-11ea-831c-80a7d864ddda.png)

**Comment by mstefarov** [comment]
Seems to be a common problem on Flags enum docs -- e.g. [DllImportSearchPath](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportsearchpath?view=netstandard-2.1) and [BindingFlags](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.bindingflags?view=netcore-3.1) show the same issue.

**Comment by glihm** [comment]
@hswan-msft @mstefarov which web-browser are you using guys? It seems to be fixed, can you confirm?

Chrome based
![chome based](https://i.ibb.co/QJGqdfT/dnet-chrome.png)

Firefox
![firefox](https://i.ibb.co/QkdHtYf/dnet-firefox.png)

**Comment by hswan-msft** [comment]
Thanks for the update! I'm using Firefox and I can confirm this is fixed.
