### ISSUE TITLE
Document ValueTask default constructor

### ISSUE THREAD

**Issue by pepone** [dotnet/dotnet-api-docs#4397]
https://github.com/dotnet/dotnet-api-docs/blob/892ea1386d69a7a1f1b33ac3011b63df0025f423/xml/System.Threading.Tasks/ValueTask.xml#L48

The behavior of the ValueTask default constructor is not documented, apparently it is equivalent to `new ValueTask(Task.CompletedTask)`

**Comment by glihm** [comment]
@pepone hello,

This is not an issue, ValueTask is a structure. So the default constructor is provided by C#. You can't implement it.

```C#
    // Default constructor is implicitly defined, it sets all the struct's fields to their default value.
    ValueTask v = new ValueTask();
```

**Comment by pepone** [comment]
It will be useful if the documentation tells that a default constructed task is a completed task, equivalent to `new ValueTask(Task.CompletedTask)`. Afaik this info is not provided in ValueTask documentation.

**Comment by glihm** [comment]
@pepone in that sense you're right and I didn't get you right at the first reading. The documentation might need to be more accurate.

I am just wondering that, the default state of `ValueTask` can't be an other one. It must be `Completed` because `Fault` and `Cancel` have no sense for a new `ValueTask`.

**Comment by pepone** [comment]
We wanted to use `default` in our product but we decided against it because this was not documented behavior.

**Comment by glihm** [comment]
> We wanted to use `default` in our product but we decided against it because this was not documented behavior.

We need now to wait maintainer's point of view and suggestions. :)

**Comment by glihm** [comment]
@pepone ,

I was using ValueTask and wasn't to use it as a black box. :)
I have checked the code, and there are some dev comments about this, look at this one:

* For `ValueTask`
> // An instance created with the default ctor (a zero init'd struct) represents a synchronously, successfully completed operation.

* For `ValueTask<TResult>`
> // An instance created with the default ctor (a zero init'd struct) represents a synchronously, successfully completed operation
   // with a result of default(TResult).

I do think those comments can be added to the documentation to provide a clear and deterministic information about default initialization of `ValueTask`. :+1:

**Comment by glihm** [comment]
@carlossanlop what do you thing about the changes? Should we rework them?
Thanks!

**Comment by carlossanlop** [comment]
Tagging area owners @tarekgh @stephentoub. Do you agree with the text addition @glihm [is suggesting ](https://github.com/dotnet/dotnet-api-docs/issues/4397#issuecomment-663926108) for the `ValueTask` type's remarks?

**Comment by tarekgh** [comment]
@carlossanlop I think there is already opened PR https://github.com/dotnet/dotnet-api-docs/pull/4576 for that.
