### ISSUE TITLE
MethodBase.IsFamilyAndAssembly docs outdated

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4400]
---
**Issue moved from MicrosoftDocs/feedback#2857**
- Please respond to @EamonNerbonne.

---

_From @EamonNerbonne on Friday, June 12, 2020 1:32:02 PM_

**Describe the bug**
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/private-protected
now exists, rendering the docs at https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase.isfamilyandassembly?view=net-5.0 incorrect.

**Expected behavior**
The note that "The Visual Basic and C# languages cannot define methods with MethodAttributes.FamANDAssem visibility; that access level appears only in the C++ example." is outdated.  Instead, the docs should refer to private protected.

The same issue is present at https://docs.microsoft.com/en-us/dotnet/api/system.reflection.fieldinfo.isfamilyandassembly?view=net-5.0#System_Reflection_FieldInfo_IsFamilyAndAssembly too

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#2857**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Friday, June 12, 2020 1:32:04 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by MSDN-WhiteKnight** [comment]
The MethodBase part is already fixed by https://github.com/dotnet/dotnet-api-docs/pull/4184

I'll submit similar PR for FieldInfo

**Comment by carlossanlop** [comment]
@MSDN-WhiteKnight were you able to address the request for `FieldInfo`?

Tagging area owners @steveharter @GrabYourPitchforks.
