### ISSUE TITLE
Some typos in Decimal.Parse code example.

### ISSUE THREAD

**Issue by Rodhern** [dotnet/dotnet-api-docs#4419]
I think there are a few inaccuracies around this point:
https://github.com/dotnet/dotnet-api-docs/blob/c72b36ed0cc623ba2dcb0ad33ceb1b0e7aea6cbc/samples/snippets/csharp/VS_Snippets_CLR_System/system.Decimal.Parse/CS/parse.cs#L114

The text example says:
```
// Parse string using "." as the thousands separator
// and " " as the decimal separator.
```
and
```
// Displays:
//    892 694,12' converted to 892694.12.
```

Should it not be "**,**" as a decimal separator. Possibly "**&nbsp;**" as the thousand separator. Also there is no reason to expect that the first "**'**" character is missing in the output. I.e. the expected output (including the leading "**'**") is:
> '892 694,12' converted to 892694.12.

**Comment by glihm** [comment]
@Rodhern hello,

PR submitted, feel free to comment / complete it.
