### ISSUE TITLE
Matrix.Prepend does not have a correct example

### ISSUE THREAD

**Issue by cloudstrifebro** [dotnet/dotnet-api-docs#4465]
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Media/Matrix.xml

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.matrix.multiply?view=netcore-3.1

If you look at the example noted, it displays an example for `Matrix.RotateAt()` instead of `Matrix.Prepend()`.  The example should be updated to include the correct usage of prepend.

**Comment by glihm** [comment]
@cloudstrifebro I am not sure to understand your issue.

In your link of the documentation example the matrix multiply code is just fine.

And following the [link](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.matrix.prepend?view=netcore-3.1#System_Windows_Media_Matrix_Prepend_System_Windows_Media_Matrix_) of `Matrix.Prepend` the example seems completely fine.

Did you link the correct example page?

**Comment by glihm** [comment]
@cloudstrifebro hello,

not sure to get the point. You've linked the `Matrix.Multiply` example, which is fine, no?

Also, the `Matrix.Prepend` [example](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.matrix.prepend?view=netcore-3.1#System_Windows_Media_Matrix_Prepend_System_Windows_Media_Matrix_) seems to be good too.

Did you missed a link? Can you give the line into the Matrix.xml file that is causing you troubles?

Thank!

**Comment by cloudstrifebro** [comment]
Hi @glihm , this must have gotten updated since I posted this.  Matrix.Prepend is now showing the correct example.  Before it was showing an example for `Matrix.RotateAt()` noted here: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.matrix.rotateat?view=netcore-3.1.  I believe that was the one that was appearing before.  Caching issue?

**Comment by glihm** [comment]
> Hi @glihm , this must have gotten updated since I posted this. Matrix.Prepend is now showing the correct example. Before it was showing an example for `Matrix.RotateAt()` noted here: https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.matrix.rotateat?view=netcore-3.1. I believe that was the one that was appearing before. Caching issue?

thanks for the check an update. :)
