### ISSUE TITLE
IEnumerator<T> Methods

### ISSUE THREAD

**Issue by kburgoyne** [dotnet/dotnet-api-docs#4470]
The left-hand navigation pane has the "Properties" subtree, but not the "Methods" subtree even though the class has methods.  (.NET Core 3.1). I wasn't able to easily identify in the source the mechanism which control this.

**Comment by svick** [comment]
This happens because `IEnumerator<T>` has no methods of its own, all three of its methods are inherited from other interfaces (two from `IEnumerator`, one from `IDisposable`).

**Comment by kburgoyne** [comment]
Oh... okay. Yes, I've encountered this style of thing in other ways in the docs.  I find it misleading and confusing at times.  It'd be clearer if the inherited stuff was listed and then linked to the defining class/interface.

But okay... if it's a consist standard as is right now, I recognize the legitimacy of that.
