### ISSUE TITLE
EnumerateDirectories(String, SearchOption) - Error in example

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4524]
---
**Issue moved from MicrosoftDocs/feedback#2879**
- Please respond to @DSivtsov.

---

_From @DSivtsov on Saturday, June 20, 2020 3:34:57 AM_

**Describe the bug**
In Example description of **EnumerateDirectories(String, SearchOption)** wrote
> The following example, starting from a specified directory, uses this method and the EnumerateFiles method to enumerate the files and directories within the start directory and display details of any files over 10 MB in size.

The current code
```
                    // Display each file over 10 MB;
                    if (fi.Length > 10000000)
                    {
                        Console.WriteLine($"{fi.FullName}\t\t{fi.Length.ToString("NO")}");
                    }
```
**fi.Length.ToString("NO")** - Doesn't have any correspondence to description, because it will show only NO for every file over 10 MB in size.

**Expected behavior**
The most simple variant is replace **fi.Length.ToString("NO")** on to **fi.Length**  and change description to 

> and **display size** of any files over 10 MB in size.

**Link To article**
[DirectoryInfo.EnumerateDirectories Method](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.enumeratedirectories?view=netframework-4.7.2)

**Comment by glihm** [comment]
I was editing the code and I didn't see the issue, nice catch @DSivtsov .

@gewarren do you think we should add the 'B' of byte at the end of the length, or only printing the length is fine?
