### ISSUE TITLE
Update Process.Kill exception notes

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#4564]
Since .NET Core 3.0, `Process.Kill` doesn't throw if the process has exited or is terminating.

**Comment by carlossanlop** [comment]
Adding area owners @adamsitnik @eiriktsarpalis for triaging.

**Comment by NextTurn** [comment]
Note that there is also an outdated note:

https://github.com/dotnet/dotnet-api-docs/blob/603fa72b18c58d514ce12a450b4edbf4ad64c21a/xml/System.Diagnostics/Process.xml#L2195-L2196
