### ISSUE TITLE
Skip button on Feedback box out of alignment

### ISSUE THREAD

**Issue by nschmeller** [dotnet/dotnet-api-docs#4584]
Upon viewing the feedback box

<img width="342" alt="image" src="https://user-images.githubusercontent.com/26189705/88678984-00db7480-d0bd-11ea-9aae-ff13403af6ea.png">

and selecting either option "Yes" or "No", the following layout for further feedback comes up

<img width="199" alt="image" src="https://user-images.githubusercontent.com/26189705/88679153-2799ab00-d0bd-11ea-84cb-404565cabde0.png">

The "Skip" button used to be aligned with the "Submit" button, but recently it's been to the bottom right of where it should be. 

This is on the latest version of Safari.

I took a quick look through recent issues and didn't see anything similar to this, but please let me know if this is redundant.

**Comment by gewarren** [comment]
@nschmeller Thanks for letting us know. I'll let the appropriate team know.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/feedback#2990
