### ISSUE TITLE
MethodImplOptions.SecurityMitigations is undocumented.

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4603]
---
**Issue moved from dotnet/docs#19783**
- Please respond to @teo-tsirpanis.

---

_From @teo-tsirpanis on Saturday, August 1, 2020 1:54:33 PM_

.NET Framework 4.8 [added a new field](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?view=netframework-4.8) in the `System.Runtime.CompilerServices.MethodImplOptions` named `SecurityMitigations`.

But it is _nowhere_ mentioned what this field does; even a Google search did not uncover anything.

What does `MethodImplOptions.SecurityMitigations` do?

**Comment by gewarren** [comment]
---
**Issue moved from dotnet/docs#19783**
- Please respond to @gewarren.

---

_From @gewarren on Monday, August 3, 2020 5:02:51 PM_

@teo-tsirpanis Are you looking for a description beyond the existing one?

"The JIT compiler should look for security mitigation attributes, such as the user-defined System.Runtime.CompilerServices.SecurityMitigationsAttribute. If found, the JIT compiler applies any related security mitigations."

**Comment by gewarren** [comment]
---
**Issue moved from dotnet/docs#19783**
- Please respond to @teo-tsirpanis.

---

_From @teo-tsirpanis on Monday, August 3, 2020 5:06:22 PM_

Yes. What exactly are these "security mitigations"? I have found absolutely no documentation about them.

Googling `SecurityMitigationsAttribute` yields almost zero results.

**Comment by gewarren** [comment]
@Anipik @steveharter Can you provide any more info about the security mitigations attribute?

**Comment by MichalStrehovsky** [comment]
This flag doesn't do anything. See https://github.com/dotnet/runtime/issues/40701 for details.
