### ISSUE TITLE
Update documentation about the image of picture doesn’t display immediately after set PictureBox.Visible = True

### ISSUE THREAD

**Issue by Marie-Shi** [dotnet/dotnet-api-docs#4614]
Need to add an explanation to help document to add remark for the visible property: that even if Visible is set to true, the control might not be visible to the user if it is obscured behind other controls. We can use a workaround: add **PictureBox1.Refresh()** before End Sub.

**More Info:**
This scenario can also repro in C# project.

**Minimal Reproduction Scenario**
1.	Extract “WindowsApp2.zip” and open it in VS.
[WindowsApp2.zip](https://github.com/dotnet/dotnet-api-docs/files/5032191/WindowsApp2.zip)
2.	Build and run this project.
3.	Click button1, the image of picture is invisible, that is expected.
4.	Click button3, the image of picture is still invisible, need to click Continue in VS, then it shows when the code gets to End Sub.

**Result:** The image of picture cannot show when code gets to visible= true, just shows when the code gets to End Sub. Please see the Gif: 
![Image_display_End_Sub](https://user-images.githubusercontent.com/45864017/89483802-88b53300-d7cf-11ea-91ce-e04096b4d992.gif)

**Workaround:** add **PictureBox1.Refresh()** before End Sub, the image of picture shows immediately. Please see the Gif:
![Image_display_add_Refresh](https://user-images.githubusercontent.com/45864017/89483809-8e127d80-d7cf-11ea-8de7-5a0fe4516d52.gif)

**Comment by carlossanlop** [comment]
@Marie-Shi can you please share the link to the page where you found this documentation?

**Comment by Marie-Shi** [comment]
@carlossanlop do you mean this link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.tools.excel.controls.picturebox.visible?view=vsto-2017#Microsoft_Office_Tools_Excel_Controls_PictureBox_Visible ?
