### ISSUE TITLE
SslClientAuthenticationOptions.CertificateRevocationCheckMode default value

### ISSUE THREAD

**Issue by CMEPLLl** [dotnet/dotnet-api-docs#4635]
The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.certificaterevocationcheckmode?view=netcore-3.1#System_Net_Security_SslClientAuthenticationOptions_CertificateRevocationCheckMode)  says:
`One of the values in X509RevocationMode: NoCheck, Online, or Offline. The default is Online.`

But [here](https://github.com/dotnet/runtime/blob/dbd14b4b319dea4cf152aa5f1abaa40d46cb4588/src/libraries/System.Net.Security/src/System/Net/Security/SslClientAuthenticationOptions.cs#L15) default value is `NoCheck`.

**Comment by carlossanlop** [comment]
@dotnet/ncl

**Comment by rzikm** [comment]
Closing since this was fixed by #4920
