### ISSUE TITLE
Tracking: DisablePrivateReflectionAttribute no longer supported as of .NET Core 2.1+

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/dotnet-api-docs#4646]
https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.disableprivatereflectionattribute

We should update the docs to say that the .NET Core / .NET 5.0+ runtimes don't honor `[DisablePrivateReflection]`. The attribute is a no-op on those runtimes.

**Comment by carlossanlop** [comment]
Tagging @steveharter and (_obviously_) @GrabYourPitchforks as area owners
