### ISSUE TITLE
System.Net.Sockets/Socket.xml warning from System.MonoLimitation attribute

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#4647]
The offending lines are in Socket.xml (huge file, can only [share the raw text](https://raw.githubusercontent.com/dotnet/dotnet-api-docs/dd138627654144dc492a19fd25f56822e541ec92/xml/System.Net.Sockets/Socket.xml)) in the API `"DuplicateAndClose"`:
```xml
        <Attribute FrameworkAlternate="xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0">
          <AttributeName Language="C#">[System.MonoLimitation("We do not support passing sockets across processes, we merely allow this API to pass the socket across AppDomains")]</AttributeName>
          <AttributeName Language="F#">[&lt;System.MonoLimitation("We do not support passing sockets across processes, we merely allow this API to pass the socket across AppDomains")&gt;]</AttributeName>
        </Attribute>
```

This is the warning the CI throws:

```
Line 0: [Warning] Cross reference not found: 'System.MonoLimitationAttribute'.
```

cc @joelmartinez  @TianqiZhang

**Comment by carlossanlop** [comment]
From a conversation with @joelmartinez, there are two ways to get it fixed:

- Either add System.MonoLimitation to https://github.com/dotnet/dotnet-api-docs/blob/master/_zip/missingapi.yml ... which will suppress those warnings.

- Or ... add System.MonoLimitation to https://github.com/dotnet/dotnet-api-docs/blob/master/xml/_filter.xml ... which will entirely hide that attribute

**Comment by TianqiZhang** [comment]
Joel is right, the choice actually depends on whether you want to show the `System.MonoLimitation` attribute on the page. If we should show the attribute and we only want to get rid of the warning, then `misssingapi.yml` is the way to go.

**Comment by carlossanlop** [comment]
Thanks @TianqiZhang .

If I get a chance to get this addressed, I'll take the task.
Cc'ing @dotnet/docs in case anyone from the group wants to fix it if I haven't done so.
