### ISSUE TITLE
ReflectionTypeLoadException - Types is not marked as nullable

### ISSUE THREAD

**Issue by yfital** [dotnet/dotnet-api-docs#4716]
Hey,

Following Nullable update, I'm not clear about the following declaration inside ReflectionTypeLoadException:

`public Type[]? Types { get; }`

The documentation clearly states:
An array of type Type containing the classes that were defined in the module and loaded. This array **can contain some null** values.

As such, writing such a code:
```
catch (ReflectionTypeLoadException e)
{
return e.Types?.Where(t => t != null).Select(t => t.GetTypeInfo()) ?? Array.Empty<TypeInfo>();
}
```

Provides a warning on the **where**, as t is not marked as nullable.

Shouldn't the declaration be:
`public Type?[]? Types { get; }`

**Comment by mairaw** [comment]
This seems to match the code:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Reflection/ReflectionTypeLoadException.cs#L41

However, the constructor syntax doesn't seem to match.

- https://docs.microsoft.com/en-us/dotnet/api/system.reflection.reflectiontypeloadexception.-ctor?view=netcore-3.1#System_Reflection_ReflectionTypeLoadException__ctor_System_Type___System_Exception___
- https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Reflection/ReflectionTypeLoadException.cs#L14

@mimisasouvanh @joelmartinez can you file a bug to investigate this?

**Comment by mimisasouvanh** [comment]
@mairaw @yfital @joelmartinez Internal [bug](https://ceapex.visualstudio.com/Engineering/_queries/edit/294345/) logged.

**Comment by gewarren** [comment]
This appears to have been fixed.
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.reflectiontypeloadexception.types?view=net-6.0
