### ISSUE TITLE
`System.Uri` broken example

### ISSUE THREAD

**Issue by RussKie** [dotnet/dotnet-api-docs#4718]
Location: https://docs.microsoft.com/dotnet/api/system.uri?view=netcore-3.1

![image](https://user-images.githubusercontent.com/4403806/91016717-8ad11b80-e630-11ea-90fd-e7435ae6a2bc.png)

**Comment by ygra** [comment]
Looks fine to me now:

![image](https://user-images.githubusercontent.com/1692688/91603016-89735c00-e96c-11ea-9ebe-7ff9029d4dc3.png)

**Comment by RussKie** [comment]
I suppose we call it "fixed" :D
