### ISSUE TITLE
Code sample creates unused variable

### ISSUE THREAD

**Issue by scarabdesign** [dotnet/dotnet-api-docs#4723]
In the code sample contained here:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Tuple%602.xml
... a variable `currentTuple` gets created and never used.

**Comment by mairaw** [comment]
In which page @scarabdesign? I'm not seeing on https://docs.microsoft.com/en-us/dotnet/api/system.tuple-2.

**Comment by scarabdesign** [comment]
It's actually in the `Equals` part of the page:
https://docs.microsoft.com/en-us/dotnet/api/system.tuple-2.equals

In the source link I left, it looks like it's being displayed with the following include:
[!code-csharp[System.Tuple\`2.Equals#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.tuple`2.equals/cs/equals1.cs#1)]

**Comment by mairaw** [comment]
Thanks for providing the repro.
