### ISSUE TITLE
Last sample on NumberFormatInfo class has something wrong

### ISSUE THREAD

**Issue by mairaw** [dotnet/dotnet-api-docs#4754]
I'm trying to figure out whether it's the code or the output that is wrong on the sample.

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=netcore-3.1#serializing-and-deserializing-numeric-data

When you run the sample, the original and restored values are exactly the same (I tried on different frameworks too such as VB on .NET Framework, C# on .NET Core and Try .NET).
The remarks indicate this is not the expected behavior.

@safern @tarekgh @krwq can you help with this?

**Comment by tarekgh** [comment]
It looks this code sample written at the point when the `en-GB` culture had decimal separator different than `.`. But this is not the case any more and `en-GB` already has `.` as decimal separator. If you want make this sample work, you can try replace the line

```C#
Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-GB");
```

with something like

```C#
    CultureInfo.CurrentCulture = new CultureInfo("en-GB");
    CultureInfo.CurrentCulture.NumberFormat.NumberGroupSeparator = ".";
    CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator = ",";
```

Another side comment, please in the sample replace `Thread.CurrentThread.CurrentCulture` with `CultureInfo.CurrentCulture`

**Comment by mairaw** [comment]
Ah thanks @tarekgh. I think if I change the sample to another culture like pt-br, then I can make the behavior we're trying to explain happen. I think this would be easier.

I'll make the replacement as well.

**Comment by tarekgh** [comment]
>  think if I change the sample to another culture like pt-BR, then I can make the behavior we're trying to explain happen. I think this would be easier.

That will be great if the Double.Parse will not fail as it has to interpret `.` somehow. I didn't check `pt-BR` to see what separators it uses. 

Also, I am afraid whatever culture we use will change in the future and we end at same situation.

I would suggest we can tweak the sample explanation telling we are simulating the situation of the problem when it can happen.
