### ISSUE TITLE
EventWaitHandle names clarification

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#4865]
---
**Issue moved from MicrosoftDocs/feedback#3087**
- Please respond to @rolfik.

---

_From @rolfik on Thursday, September 3, 2020 7:25:05 AM_

https://docs.microsoft.com/en-us/dotnet/api/system.threading.eventwaithandle.-ctor?view=netcore-3.1

Please describe Global\ and Local\ prefixes usable in named EventWaitHandle construction and specify which is default (Local\ one?) and that \ is reserver character.
This information could be shared with other named synchronization types.

Thank you

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3087**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Thursday, September 3, 2020 7:25:06 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by carlossanlop** [comment]
@kouvel can you please take a look?

**Comment by kouvel** [comment]
Most of this has been addressed recently, the remarks section for constructors, `OpenExisting`, and `TryOpenExisting` with the `name` parameter describe the namespaces. It currently does not mention that `\` is a reserved character, should be added.
