### ISSUE TITLE
Clarify that Guid.NewGuid is not intended to be used for security purposes

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/dotnet-api-docs#4910]
Ref: https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid

The `Guid.NewGuid()` method returns a value that is with overwhelming probability _unique_ compared to every other GUID that has ever been generated. However, the `Guid.NewGuid()` method is not guaranteed to be _unpredictable_, nor is it guaranteed to be seeded from a strong source of entropy. That is, somebody who can observe the return value of `Guid.NewGuid()` might be able to predict the method's future return values.

This behavior makes `Guid.NewGuid()` inappropriate for callers which need to generate _secret_ values, such as values used as passwords or as cryptographic keys. Callers who need to generate _secret_ data should instead use [`RandomNumberGenerator.GetBytes`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator.getbytes).

For the technically minded: "`Guid.NewGuid()` is not guaranteed to use a cryptographically secure RNG."

**Comment by iSazonov** [comment]
From https://tools.ietf.org/html/rfc4122#page-16
>6.  Security Considerations

>   Do not assume that UUIDs are hard to guess; they should not be used
   as security capabilities (identifiers whose mere possession grants
   access), for example.  A predictable random number source will
   exacerbate the situation.

>   Do not assume that it is easy to determine if a UUID has been
   slightly transposed in order to redirect a reference to another
   object.  Humans do not have the ability to easily check the integrity
   of a UUID by simply glancing at it.

>   Distributed applications generating UUIDs at a variety of hosts must
   be willing to rely on the random number source at all hosts.  If this
   is not feasible, the namespace variant should be used.

**Comment by GrabYourPitchforks** [comment]
I opened https://github.com/dotnet/runtime/issues/42752 to track changing the runtime behavior if we actually do want to make this guarantee. It also gives some historical background as to why things are as they are.

**Comment by vcsjones** [comment]
@GrabYourPitchforks given that dotnet/runtime#42752 is closed and PRs have been merged, is this issue still valid? Is `NewGuid` guaranteed to be backed by a CSPRNG from the underlying platform?

**Comment by GrabYourPitchforks** [comment]
@vcsjones Yes, I think it's still a valid issue. First, `Guid.NewGuid` still doesn't guarantee a strong 122 bits of entropy across all runtimes. Second, the value has a partially predictable bit pattern which makes it distinguishable from a proper PRF. If your usage requires a proper PRF, this API will not suit your requirements.

Given both of these I'm still of the mind that it's not to be used for security purposes.

**Comment by GrabYourPitchforks** [comment]
Update: I reworded the PR to clarify that it shouldn't be used for _cryptographic_ purposes. There may be security-related non-cryptographic purposes where it would still be allowable.
