### ISSUE TITLE
`String.Format` and params array

### ISSUE THREAD

**Issue by scottdorman** [dotnet/dotnet-api-docs#4921]
The `String.Format` methods take a `params` array as an argument which looks like it's been enabled for nullable reference types.

https://github.com/dotnet/runtime/blob/118eee973af81119fd00fe75bc9c14ce3192ff1e/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs#L481-L491

However, in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=netcore-3.1#System_String_Format_System_String_System_Object___) the signature is shown as 

`public static string Format (string format, params object[]? args);`

Is this a docs bug or should the implementation be `params object[]? args`?

Isn't one ( `params object[]? args`) effectively "a parameters array of object, where the entire argument could be `null`) while the other ( `params object?[] args`) effectively "a parameters array of nullable object, where the argument itself isn't expected to be `null`"?

**Comment by carlossanlop** [comment]
Ping @joelmartinez @TianqiZhang

**Comment by joelmartinez** [comment]
Thanks @carlossanlop ... I've created a devops item [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/317995) to track this fix in mdoc.

**Comment by gewarren** [comment]
This has been fixed - for example, https://docs.microsoft.com/en-us/dotnet/api/system.string.format?view=net-6.0#system-string-format(system-string-system-object()).
