### ISSUE TITLE
Environment.FailFast has link to raw markdown file instead of rendered version

### ISSUE THREAD

**Issue by mgrandi** [dotnet/dotnet-api-docs#5006]
I'm not sure why these docs don't have a 'report issue' button that has all the information, but i'll try to provide it here

rendered page: https://docs.microsoft.com/en-us/dotnet/api/system.environment.failfast?view=netcore-3.1
source page: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Environment.xml

It seems that under `Remarks`, on these lines:

https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Environment.xml#L642
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Environment.xml#L564

```plaintext
Calling the Environment.FailFast method to terminate execution of an application running in the Visual Studio debugger throws an ExecutionEngineException and automatically triggers the fatalExecutionEngineError managed debugging assistant (MDA).
```

and that `fatalExecutionEngineError managed debugging assistant (MDA)` link goes to `https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/fatalexecutionengineerror-mda.md` , which is the raw github markdown file and not the rendered version on docs.microsoft.com

**Comment by eiriktsarpalis** [comment]
Hi @mgrandi, would you be interested in contributing a PR that addresses the issue?

**Comment by mgrandi** [comment]
I can attempt to sure

**Comment by gewarren** [comment]
This has been fixed.
