### ISSUE TITLE
Make "Applies To" section in .NET API documentation individual per overload

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#5017]
---
**Issue moved from MicrosoftDocs/feedback#3205**
- Please respond to @GGG-KILLER.

---

_From @GGG-KILLER on Tuesday, October 20, 2020 7:48:54 PM_

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to see when a certain overload was added because there is no easy way to obtain that information.

**Describe the solution you'd like**
The "Applies To" information should be per overload instead of per method or type name.

**Describe alternatives you've considered**
1. Check the version of that documentation page for each .NET Core, .NET Framework and .NET Standard version to see which ones have the overload we're looking for and which ones don't;
2. Open Visual Studio, create a project with multi-targeting for all versions we want to check and then pick the highest version and look at the tooltip to see availability of that overload (and this doesn't always work).

**Additional context**
An example of this would be trying to find out when `string.IndexOf(Char, StringComparison)` became available, since the [docs page](https://docs.microsoft.com/en-us/dotnet/api/system.string.indexof) say the entire page is applicable to:

- .NET Framework ≥ 1.1
- .NET Standard
- .NET Core

However if you check that page for any .NET Framework versions or .NET Core versions lower than 2.1 or .NET Standard versions lower than 2.1, you'll see that overload doesn't exist because it was added on .NET Core 2.1 and .NET Standard 2.1.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3205**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Tuesday, October 20, 2020 7:48:55 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
@ggg-killer we have a design in the works to address this.

@mimisasouvanh FYI.

**Comment by mimisasouvanh** [comment]
@gewarren Each overload should have their own Applies To section now.

**Comment by gewarren** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.string.indexof?view=net-5.0#System_String_IndexOf_System_Char_System_StringComparison_
