### ISSUE TITLE
Documentation for System.Web.UrlMappingsModule is missing

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#5020]
---
**Issue moved from MicrosoftDocs/feedback#3158**
- Please respond to @rossmpersonal.

---

_From @rossmpersonal on Saturday, October 3, 2020 3:38:06 AM_

**Describe the bug**
Documentation for System.Web.UrlMappingsModule is missing.

**To Reproduce**
1. Go tohttps://docs.microsoft.com/en-us/dotnet/api/
2. Enter System.Web.UrlMappingsModule in the search box.
3. See No Results returned

**Expected behavior**
Link to documentation for System.Web.UrlMappingsModule appears.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/57814305/94982376-f481f680-0507-11eb-9ab9-8b9646fbc5cf.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - MacBook Pro
 - 10.15.7
 -Safari
 - Version 14.0

**Additional context**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3158**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Saturday, October 3, 2020 3:38:07 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
There are no docs because it's an internal class.

https://referencesource.microsoft.com/#System.Web/UrlMappingsModule.cs

**Comment by rossmpersonal** [comment]
Then where is documentation for the functionality, configuration, and/or use of the UrlMappingsModule ? I can find references to the existence of the UrlMappingsModule at:

https://docs.microsoft.com/en-us/iis/get-started/introduction-to-iis/iis-modules-overview#module-reference
https://docs.microsoft.com/en-us/powershell/module/webadministration/set-webmanagedmodule?view=windowsserver2022-ps#examples
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/modules?view=aspnetcore-6.0#managed-modules
https://docs.microsoft.com/en-us/iis/web-hosting/migrate-to-the-microsoft-web-platform/iis-for-apache-administrators#using-modules-to-control-and-customize-iis
https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee537834(v=office.14)#the-request-pipeline
https://download.microsoft.com/download/3/3/F/33F52373-3A75-422C-969B-61E05EEC5E72/SC2012_OpsMgr_Authoring.docx
https://download.microsoft.com/download/3/3/F/33F52373-3A75-422C-969B-61E05EEC5E72/SC2012_OpsMgr_Authoring.pdf

but no documentation for the use of it.

Thank you.

**Comment by gewarren** [comment]
In ASP.NET Core, it looks like this module is replace by URL Rewriting Middleware - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-6.0.

But I'll reopen this issue and transfer it to the IIS docs repo in case some conceptual or hand-written reference docs can be added.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/iis-docs#611
