### ISSUE TITLE
Very wrong advice about implementing IDisposable

### ISSUE THREAD

**Issue by slepmog** [dotnet/dotnet-api-docs#5035]
At https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netcore-3.1#implementing-idisposable it reads:

> You should implement `IDisposable` only if your type uses unmanaged resources directly.

This advice is very wrong.
You should implement `IDisposable` if you use unmanaged resources directly or if you use disposable objects yourself.

Which is why the Disposable pattern (correctly) generated by Visual Studio goes:

```cs
protected virtual void Dispose(bool disposing)
{
    if (disposing)
    {
        // get rid of managed resources
    }   
    // get rid of unmanaged resources
}
```

**Comment by eiriktsarpalis** [comment]
Hi @slepmog, would you be interested in providing a PR that improves the issue?

**Comment by slepmog** [comment]
Hi @eiriktsarpalis, I believe this has been done! https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#the-disposebool-method-overload lays out what you should be doing from your `Dispose`, so when you need to do any of that, you should implement `IDisposable`. That can be copied or even linked to the subject article.
