### ISSUE TITLE
CngExportPolicies.None - Docs wrong

### ISSUE THREAD

**Issue by Inspyro** [dotnet/dotnet-api-docs#5076]
Hi,
I think the docs for **CngExportPolicies.None** are **wrong** (see: https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cngexportpolicies?view=dotnet-plat-ext-3.1). It says
> No export policies are established. Key export is allowed without restriction.

Whereas the native docs (https://docs.microsoft.com/en-us/windows/win32/seccng/key-storage-property-identifiers)
specify
> NCRYPT_ALLOW_EXPORT_FLAG 0x00000001 - The private key can be exported.

however the "0x0" flag is not described which would lead me to the conclusion that it would indicate non-exportable.

Another indicator is your own example code here: 
https://github.com/microsoft/Intune-Resource-Access/blob/develop/src/PFXImportPowershell/EncryptionUtilities/Source/ManagedRSAEncryption.cs
Where in case "**nonExportable**" is set to "false" the flag **CngExportPolicies.None** is used

**Comment by fschmied** [comment]
> Where in case "nonExportable" is set to "false" the flag CngExportPolicies.None is used

See this line: https://github.com/microsoft/Intune-Resource-Access/blob/develop/src/PFXImportPowershell/EncryptionUtilities/Source/ManagedRSAEncryption.cs#L160

**Comment by fschmied** [comment]
Could we get any information about whether the docs are actually correct and `None` means that "Key export is allowed without restriction"? How do you express "Key export is not allowed" if that's the case?
