### ISSUE TITLE
System.Threading ApartmentState Enum - C# code example displays obsolete code

### ISSUE THREAD

**Issue by FriedLychees** [dotnet/dotnet-api-docs#5103]
The C# code example for the ApartmentState enum uses the ApartmentState property to get the ApartmentState of the thread.

`Console.WriteLine("ThreadState: {0}, ApartmentState: {1}", 
            newThread.ThreadState, newThread.ApartmentState);`

It uses GetApartmentState() further below in the file, like the ApartmentState Property documentation suggests that you should, but the first Console.WriteLine in the example uses it incorrectly.

**Comment by FriedLychees** [comment]
Same for the F# code sample

**Comment by carlossanlop** [comment]
I assume you mean this example, @FriedLychees ? https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.apartmentstate?view=net-5.0

Would you like to submit a PR with a proposed new code example? The location of the 3 files containing the examples are indicated here (paths relative to the root of this repo):
https://github.com/dotnet/dotnet-api-docs/blob/73e106e071747457441fa2bb38c51feaeabe171e/xml/System.Threading/Thread.xml#L951-L953
