### ISSUE TITLE
Linq Take() and Skip() are stated as Functinally complement, while it is not always true

### ISSUE THREAD

**Issue by dimmik** [dotnet/dotnet-api-docs#5152]
Honestly, I am not sure if it is Documentation issue of code bug.
Documentation states:
The `Take` and `Skip` methods are functional complements. Given a sequence `coll` and an integer `n`, concatenating the results of `coll.Take(n)` and `coll.Skip(n)` yields the same sequence as `coll`. 
https://github.com/dotnet/dotnet-api-docs/blob/f33aa309d83192d0563b9bb35c70c176238f8f85/xml/System.Linq/Enumerable.xml#L9591 (skip)
https://github.com/dotnet/dotnet-api-docs/blob/f33aa309d83192d0563b9bb35c70c176238f8f85/xml/System.Linq/Enumerable.xml#L11251 (take)

However, that is not always true, Take and Skip sometimes silently throw away elements, and taken.Concat(skipped) is not equal to original:
```csharp
class TakeSkipEnumerableFail
    {
        private static readonly string[] array = Enumerable.Range(1, 7).Select(i => $"{i}").ToArray();
        private static int position = 0;
        private static IEnumerable<string> GetIEnumerable()
        {
            while (position < array.Length)
            {
                yield return array[position];
                position++;
            }
        }
        static void Main()
        {
            var sequence = GetIEnumerable();
            var before = sequence.Take(3);
            var after = sequence.Skip(3);
            var concat = before.Concat(after); // should be 1,2,3,4,5,6,7
            var result = $"concat: {string.Join(",", concat)}"; // but actually it is 1,2,3,6,7
            Console.WriteLine(result);
        }
    }
```
Most probably it is due to nature of this very IEnumerable (it is true for enumerations that are not repeatable), but it makes sense to mention this in documentation.

**Comment by svick** [comment]
Yes, it's because of the nature of your enumerable. For example, I'd say that `.ElementAt(1)` and `.ElementAt(1)` are functionally equivalent (since it's the same code), but code like the following will give you two different values:

```c#
var first = sequence.ElementAt(1);
var second = sequence.ElementAt(1);
```

But I think it makes sense to change the documentation to say something like:

> Given a well-behaved sequence `coll` ...

It's probably not necessary to elaborate on what "well-behaved" means.

**Comment by eiriktsarpalis** [comment]
> it is true for enumerations that are not repeatable

While possible to define, I tend to regard such enumerables as pathological cases. On the other hand, best practices for consuming arbitrary enumerables mandate enumerating the source at most once, which is not compatible with the example at hand. 

I'd support a PR that adds a clarification on "well-behaved" enumerables, even though I don't believe this to be an essential omission.
