### ISSUE TITLE
Documentation for PolicyHttpMessageHandler is broken

### ISSUE THREAD

**Issue by NikiforovAll** [dotnet/dotnet-api-docs#5158]
page: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.http.policyhttpmessagehandler?view=dotnet-plat-ext-3.1&viewFallbackFrom=net-5.0

`PolicyHttpMessageHandler` Class

---
Do you think I can try to fix this? If so, how do I check how the fixed version would look like locally?

**Comment by gewarren** [comment]
@NikiforovAll Thanks for letting us know. Unfortunately the preview site is currently available internally to Microsoft only. We welcome contributions, but in this case, since you can't see the result, it probably doesn't make sense for you to take this on.
