### ISSUE TITLE
Switching between methods that have been moved into extension classes does not work as expected

### ISSUE THREAD

**Issue by IanKemp** [dotnet/dotnet-api-docs#5163]
In .NET Framework, the methods `GetAccessControl` and `SetAccessControl` are defined on the `System.Threading.Mutex` class.

In .NET Core and .NET 5, these methods were split out into an extension class `System.Threading.ThreadingAclExtensions`.

This breaks MSDN docs' redirection when switching between Framework and non-Framework versions of these methods.

For example, if I go to https://docs.microsoft.com/en-gb/dotnet/api/system.threading.mutex.getaccesscontrol?view=netframework-4.8, and then change the "Version" dropdown in the top-left to (say) .NET Core 3.1, I get redirected to https://docs.microsoft.com/en-gb/dotnet/api/system.threading.mutex.getaccesscontrol?view=netframework-4.8&viewFallbackFrom=netcore-3.1 which tells me "The requested page is not available for .NET Core 3.1. You have been redirected to the newest product version this page is available for." - when it should ideally redirect me to https://docs.microsoft.com/en-gb/dotnet/api/system.threading.threadingaclextensions.getaccesscontrol?view=netcore-3.1#System_Threading_ThreadingAclExtensions_GetAccessControl_System_Threading_Mutex_

Similarly, going to https://docs.microsoft.com/en-gb/dotnet/api/system.threading.threadingaclextensions.getaccesscontrol?view=netcore-3.1#System_Threading_ThreadingAclExtensions_GetAccessControl_System_Threading_Mutex_ and then switching Version to .NET Framework 4.8 sends me to https://docs.microsoft.com/en-gb/dotnet/api/system.threading.threadingaclextensions.getaccesscontrol?view=dotnet-plat-ext-5.0&viewFallbackFrom=netframework-4.8#System_Threading_ThreadingAclExtensions_GetAccessControl_System_Threading_Mutex_ which is a little better, but still not correct.

I understand this is very much an exception to the norm, but is there any way of fixing this? I.e. with a custom redirect?

**Comment by gewarren** [comment]
These are completely different APIs, which is why simply changing the version in the dropdown doesn't work. Fixing this would be a lot of effort for not much gain.

However, it would be worthwhile to add remarks to each of these methods about the new/old method.
