### ISSUE TITLE
ExecutionEngineException is obsolete in .NET 5.0 but the documentation does not say so

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/dotnet-api-docs#5181]
System.ExecutionEngineException is obsolete in .NET 5.0:

* [src/libraries/System.Private.CoreLib/src/System/ExecutionEngineException.cs](https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Private.CoreLib/src/System/ExecutionEngineException.cs#L21)
* [src/libraries/System.Runtime/ref/System.Runtime.cs](https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Runtime/ref/System.Runtime.cs#L1999)

However, the documentation does not say so:

* <https://docs.microsoft.com/en-us/dotnet/api/system.executionengineexception?view=net-5.0#applies-to>

  > Product | Introduced | Obsolete
  > -- | -- | --
  > .NET | 5.0 |  
  > .NET Core | 2.0 | 2.0
  > .NET Framework | 1.1 | 4.0
  > .NET Standard | 2.0 | 2.0
  > Xamarin.Android | 7.1 | 7.1
  > Xamarin.iOS | 10.8 | 10.8
  > Xamarin.Mac | 3.0 | 3.0

`net-5.0` seems to be missing from the FrameworkAlternate list of the attribute: <https://github.com/dotnet/dotnet-api-docs/blob/49f945bc27285a89d843903eef0f0515ba1e625f/xml/System/ExecutionEngineException.xml#L37-L40>

Is the FrameworkAlternate list intended to be updated automatically or manually?

**Comment by gewarren** [comment]
This seems to be related to a known issue that [we are working on a fix for internally](https://ceapex.visualstudio.com/Engineering/_workitems/edit/322199), where obsolete attributes aren't showing up correctly. cc @joelmartinez.

**Comment by joelmartinez** [comment]
@gewarren yes, this fix is being finalized now and will be in the next release of mdoc ... if all goes well, expect a ping from me later this week about the preview :)

**Comment by gewarren** [comment]
This is fixed now.

https://docs.microsoft.com/en-us/dotnet/api/system.executionengineexception?view=net-5.0
