### ISSUE TITLE
Obsoletion text in topic stopped not being rendered for .NET 5.0+

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/dotnet-api-docs#5253]
Eg., for [Process.NonpagedSystemMemorySize Property](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.nonpagedsystemmemorysize?view=net-5.0) there is no indication it is obsolete (and has been for 10-15 years)

But if I change to the older versions I do see it: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.nonpagedsystemmemorysize?view=netcore-2.2. The cause is that `FrameworkAlternate` attribute does not include `net-5.0`. If I edit the HTML to add that, it appears rendered.

Does a script need to be written to add 'net-5.0' to all such tags in all topics? 

@gewarren

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/pull/47137/files

**Comment by gewarren** [comment]
@danmosemsft This is a [bug in "mdoc"](https://ceapex.visualstudio.com/Engineering/_workitems/edit/322199) - the tool that generates the API docs. Hopefully it will be fixed and released in the next week, and we'll update the docs as soon as the fix is available.

Related to #5181.

**Comment by danmosemsft** [comment]
Oh missed the dupe thanks
