### ISSUE TITLE
Incorrect statement in Remarks section of StructLayoutAttribute.Pack documentation

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/dotnet-api-docs#5318]
The Remarks section of the `StructLayoutAttribute.Pack` documentation contains the following statement regarding the field:

> It affects both `LayoutKind.Sequential` and `LayoutKind.Explicit`.

https://github.com/dotnet/dotnet-api-docs/blob/733b2cecdd45ab3ed5efee2f001d9b07730f06e1/xml/System.Runtime.InteropServices/StructLayoutAttribute.xml#L265

According to a comment in an issue on the dotnet/runtime repo, `StructLayoutAttribute.Pack` does not apply to `LayoutKind.Explicit`:

> Pack should not have any affect in combination with `LayoutKind.Explicit`.

https://github.com/dotnet/runtime/issues/47907#issuecomment-774719848

I recommend that the statement in the Remarks section be updated to reflect that the `StructLayoutAttribute.Pack` field only affects `LayoutKind.Sequential`.

**Comment by carlossanlop** [comment]
Thanks for reporting this, @WizardBrony . Would you like to submit a PR to fix it?

**Comment by WizardBrony** [comment]
@carlossanlop Sure, I just submitted one.
