### ISSUE TITLE
system.object.gettype example describes type(long) as 32-bit integer

### ISSUE THREAD

**Issue by tdykstra** [dotnet/dotnet-api-docs#5414]
---
**Issue moved from MicrosoftDocs/feedback#3524**
- Please respond to @jstraw45.

---

_From @jstraw45 on Tuesday, March 2, 2021 2:47:52 PM_

Object.GetType Method (at https://docs.microsoft.com/en-us/dotnet/api/system.object.gettype?view=net-5.0) discusses using the GetType method to determine the type of a particular object. Within the example, the test to check whether the value is a long claims that the value is a 32-bit rather than a 64-bit integer. See highlights in attachment.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome Version 88.0.4324.190 (Official Build) (64-bit)
![Screenshot_1](https://user-images.githubusercontent.com/6453207/109665556-4c1aa180-7b3c-11eb-8c08-6150c2197040.png)

**Comment by antonfirsov** [comment]
VB example was also wrong. Fixes filed: #5424 #5425
