### ISSUE TITLE
Regarding the question of whether to add regionalized languages in .net6.0

### ISSUE THREAD

**Issue by mq00fc** [dotnet/dotnet-api-docs#5423]
Is there any plan to add a description plan for class libraries that include Japanese/Korean/Chinese in .net 5.0 or 6.0?
Thanks!
![8_ VP1 JR2_1FOKR49{P@GV](https://user-images.githubusercontent.com/50408721/110898048-7e48b200-8339-11eb-838c-55a03b6a84e3.png)

**Comment by antonfirsov** [comment]
@mq00fc can you be more specific on what do you mean? As your screenshot demonstrates, there are translations for the 3 languages you mentioned.

**Comment by mairaw** [comment]
Are you talking about IntelliSense files @mq00fc?

**Comment by mq00fc** [comment]
@mairaw @antonfirsov 
I'm sorry that my English is not very good. What I mean is that the local language (Chinese/English) will be displayed when the mouse moves to the system method on .netframework, but only English in .net5.0. Is there any plan to add it?

**Comment by mairaw** [comment]
No need to apologize @mq00fc. Yes, that's called IntelliSense.

Yes, you can have local language to be displayed for .NET 5 as well:
https://docs.microsoft.com/dotnet/core/install/localized-intellisense 

I'll close the issue for now but let us know if you have more questions about it.
