### ISSUE TITLE
Boolean.TrueString french documentation (auto translated) indicates a slighlty wrong value

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#5432]
---
**Issue moved from MicrosoftDocs/feedback#3511**
- Please respond to @Tecknoth.

---

_From @Tecknoth on Wednesday, February 24, 2021 11:51:39 AM_

The french translation of the documentation for Boolean.TrueString is mentioning in Remarks that the field value is equal to "true" ; which is wrong : the value is actually "True". Although not very critical, this might be a bit confusing.

The error doesn't seem to be linked to a particular .NET Version : the page for all versions seems to have the issue.

See https://docs.microsoft.com/fr-fr/dotnet/api/system.boolean.truestring?view=net-5.0

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3511**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Wednesday, February 24, 2021 11:51:40 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by carlossanlop** [comment]
@JasonCard is this a localization issue for your team?

**Comment by JasonCard** [comment]
@carlossanlop @gewarren The English source text is "This field is equal to the string "True".", so it seems to be that this feedback is for the English source text. French translation is machine translated, but appears to be correctly translated.

**Comment by Tecknoth** [comment]
Hi @JasonCard , sorry but no, the machine translation get rid of the Pascal casing here, which means that 'True' appears to be converted to 'true' in the french generated page ; you might say that it's similar, but from a code point of view, it is not.
This might have consequences regarding the usage of the TrueString constant, because the correct value ('True') is actually equal to True.ToString(), whereas 'true' wouldn't be equal to it.

**Comment by JasonCard** [comment]
@Tecknoth Thank you for the clarification.
@carlossanlop @gewarren To preserve the capitalization of "True" in translation, could you please apply the code format like `True` to English source?
