### ISSUE TITLE
ZipFile.ExtractToDirectory(string, string, bool) incorrectly states destination directory cannot exists

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#5483]
---
**Issue moved from dotnet/docs#23513**
- Please respond to @UpperAvenue.

---

_From @UpperAvenue on Friday, March 26, 2021 8:14:46 PM_

**Issue description**

[ZipFile.ExtractToDirectory(string, string, bool) documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectory?view=net-5.0#System_IO_Compression_ZipFile_ExtractToDirectory_System_String_System_String_System_Boolean_)

Documentation states the destination directory specified must not exist, but that is not true if the *overwriteFiles* parameter is set to true.  This is incorrectly stated in the Parameter documentation the Exceptions documentation and the Remarks documentation.

(I have not verified the other parts of the documentation, only the part that says the destination directory must not exists.)

**Target framework**

.NET 5

**Comment by Jozkee** [comment]
Seems like the documentation for that particular exception could be improved to reflect its interaction with the `overwriteFiles` param.

@UpperAvenue would you be interested in sending a PR proposing a fix for it?

**Comment by Jozkee** [comment]
You should be able to do so by clicking the **edit** button at the top-right of the page for `ZipFile.ExtractToDirectory`, locate the text in the xml file that you would like to change and submit a PR with your proposed change.

**Comment by ANF-Studios** [comment]
Hey @UpperAvenue, if you don't feel like it anymore, I'd be more than happy to help you out :smile:. This issue has been open for a while, thought I'd say that.
