### ISSUE TITLE
please add description for IMemoryCache Interface method 

### ISSUE THREAD

**Issue by behroozbc** [dotnet/dotnet-api-docs#6611]
hi 
Please add description for  [IMemoryCache Interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.imemorycache?view=dotnet-plat-ext-5.0) method  
like set ?

**Comment by Jozkee** [comment]
I do see that the summaries in `IMemoryCache` methods are quite simple.
Can you please be more specific what exactly is not clear to you or what's is your suggestion for improve them?

**Comment by behroozbc** [comment]
hi 
I cant find any description for [set method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.cacheextensions.set?view=dotnet-plat-ext-5.0#Microsoft_Extensions_Caching_Memory_CacheExtensions_Set__1_Microsoft_Extensions_Caching_Memory_IMemoryCache_System_Object___0_)

**Comment by maryamariyan** [comment]
@behroozbc Those Set methods are implemented here: https://github.com/dotnet/runtime/blob/b3d4eb279c1032799edeea24778b0cd1dc476f8f/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/MemoryCacheExtensions.cs#L44-L90

and their doc page is available here:
https://github.com/dotnet/dotnet-api-docs/blob/main/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml#L191-L403

Would you like to prepare a PR to add those descriptions yourself? it would involve filling up these sections:

https://github.com/dotnet/dotnet-api-docs/blob/3f8e08c385926e638ce43473c40d893db35a6cd4/xml/Microsoft.Extensions.Caching.Memory/CacheExtensions.xml#L351-L358

**Comment by Naidile-P-N** [comment]
Have raised a PR that closes this issue : 

Update CacheExtensions.xml #6853
