### ISSUE TITLE
Missing documentation for ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter in .NET Framework

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/dotnet-api-docs#6684]
A tool that verifies we are using documented APIs is telling me that System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter has no documentation for ,NET framework. I do see doc pages for [.NET Core](https://docs.microsoft.com/mt-mt/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1.configuredvaluetaskawaiter?view=netcore-1.1) and [.NET 5](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1.configuredvaluetaskawaiter?view=net-5.0&viewFallbackFrom=netframework-4.7.1) but nothing for net461(say) that we are actually using in our code. 

The nuget package that brings this support in is https://www.nuget.org/packages/System.Threading.Tasks.Extensions/ and the API exists in net461 at least.

**Comment by AbhitejJohn** [comment]
Here is what I see when I try to view the docs in  .NET framework:
![image](https://user-images.githubusercontent.com/18014426/116618953-a9d92900-a8f4-11eb-92ec-45f1ac96175e.png)

**Comment by GrabYourPitchforks** [comment]
@AbhitejJohn The docs site is correct. That API is not officially part of .NET Framework 4.6.1 and is provided by an out-of-band package. The `ConfiguredValueTaskAwaiter` type isn't unique here. See also [the `System.Text.Json.JsonSerializer` type](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer), which is also not officially part of any .NET Framework release and is provided by an out-of-band package. In both cases, the docs site will say that the page isn't available for .NET Framework, and it will direct you to a different runtime.

In these cases, the out-of-band packages are released concurrently with some .NET Core / .NET version, so the docs for these packages actually live under the .NET Core / .NET version that the package is released alongside.

For example, [the _System.Threading.Tasks.Extensions_ v4.5.4 package](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/4.5.4) was released as part of the .NET Core 3.1 wave. So the docs for this package version will live under https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.configuredvaluetaskawaitable-1.configuredvaluetaskawaiter?view=netcore-3.1 (the .NET Core 3.1 docs), regardless of whether your app targets .NET Core 3.1 or .NET Framework.

**Comment by AbhitejJohn** [comment]
@GrabYourPitchforks : So this showed up in an APIScan run. Does that tool need to be fixed to figure out the documentation for such APIs correctly then?

**Comment by GrabYourPitchforks** [comment]
> Does that tool need to be fixed to figure out the documentation for such APIs correctly then?

Yes, the tool is producing a false positive match. The tool should be updated to account for this scenario. Email the APIScan team or the SDL team for resolution.
