### ISSUE TITLE
The code presented in List<T>.Find(Predicate<T>) Method does not actually show Find

### ISSUE THREAD

**Issue by DonGlover** [dotnet/dotnet-api-docs#6710]
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.find?view=net-5.0
The code examples is from the contains topic and does not as the documentations states:
The following example demonstrates the Find method on a List<T> that contains a simple complex object.

**Comment by eiriktsarpalis** [comment]
A use of the `Find` method is demonstrated in this part of the snippet
```csharp
        // Find items where name contains "seat".
        Console.WriteLine("\nFind: Part where name contains \"seat\": {0}",
            parts.Find(x => x.PartName.Contains("seat")));
```

**Comment by GrabYourPitchforks** [comment]
Closing since this appears to have been answered. Please reopen if this resolution is incorrect.
