### ISSUE TITLE
Values should be the same in rounding modes example tables in MidpointRounding Enum

### ISSUE THREAD

**Issue by zagorec92** [dotnet/dotnet-api-docs#6744]
Docs page in question - https://docs.microsoft.com/en-us/dotnet/api/system.midpointrounding?view=net-5.0
Source file - https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/MidpointRounding.xml

If you go to [Round to nearest](https://docs.microsoft.com/en-us/dotnet/api/system.midpointrounding?view=net-5.0#round-to-nearest) section, you can see that table with example values and corresponding results after rounding has two extra values when compared to the table in [Directed rounding](https://docs.microsoft.com/en-us/dotnet/api/system.midpointrounding?view=net-5.0#directed-rounding).

_Round to nearest_ 
![image](https://user-images.githubusercontent.com/4306892/117860128-3b9b4b80-b290-11eb-8b47-48c43797c0f5.png)

_Directed rounding_
![image](https://user-images.githubusercontent.com/4306892/117860467-9cc31f00-b290-11eb-82ec-b38a1482f3ef.png)
**For the sake of consistency**, it would be great if examples for 3.5 and -3.5 are added to the table in directed rounding section.
As this seems like a fairly basic change, if accepted, let me know if I can submit a PR for this.

**Comment by GrabYourPitchforks** [comment]
I know it's not _quite_ a numerics thing, but this was the easiest way to get the bot to tag the right folks. :)

**Comment by gewarren** [comment]
This was fixed.
