### ISSUE TITLE
Asking if System.Drawing.Common is supported within ASP.NET

### ISSUE THREAD

**Issue by nt-7** [dotnet/dotnet-api-docs#6767]
# Question
[System.Drawing Namespace - Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=net-5.0#remarks) said that **System.Drawing namespace is not supported** within Windows services, ASP.NET Core, and ASP.NET.". Meanwhile, that said **System.Drawing.Common**, ImageSharp, SkiaSharp, and Windows Imaging Components is supported.

So, most of the System.Drawing namespaces aren't supported within ASP.NET.
However, **only System.Drawing.Common class** is supported, right? Or, is this a documentation error? 

From [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/), it seems that System.Drawing.Common also depends on GDI+ graphics api.

# Docs Source File
https://github.com/dotnet/dotnet-api-docs/blob/187d891bba9291682e9bf749d3962d66c474f336/includes/drawing.md

**Comment by ManickaP** [comment]
@maryamariyan @michaelgsharp @safern @tarekgh Could you please help answer this question? I, myself, am confused with the remarks note, but I know next to nothing about graphics. It might be worthwhile to improve the note, that's up to your consideration.

**Comment by tarekgh** [comment]
CC @ericstj

**Comment by tarekgh** [comment]
@nt-7 please have a look at the comment https://github.com/dotnet/runtime/issues/42499#issuecomment-696807700 which is clarifying why the docs is saying that. Please let me know if still something unclear.

**Comment by tarekgh** [comment]
@nt-7 thanks for clarifying your question. The comment is about discouraging using System.Drawing (the old library that was supported only on the Full Framework). `System.Drawing.Common` should be supported in ASP.NET and ASP.NET Core. `System.Drawing.Common` is just containing a subset classes which used to be in System.Drawing library. `System.Drawing.Common` still using gdiplus library. 

I agree the comment is confusing as it says `System.Drawing namespace` while `System.Drawing.Common` having the same namespace. We should fix/clarify this part in the docs

**Comment by tarekgh** [comment]
CC @safern

**Comment by JeremyKuhne** [comment]
System.Drawing.Common isn't recommended for the scenarios mentioned (special Windows versions) as it has a dependency on GDI+ which is only in the full Windows SKUs. On Unix machines there is an additional dependency that needs to be present (LibGdi+) that gives it "GDI+" functionality.

**Comment by nt-7** [comment]
I appreciate your help! I understand System.Drawing.Common isn't also recommended for Windows.

@JeremyKuhne, in case of Windows, we use SkiaSharp or ImageSharp?
Or, **isn't** skiaSharp and ImageSharp recommended as well as System.Drawing in case of Windows?

**Comment by JeremyKuhne** [comment]
> In case of Windows, we use SkiaSharp or ImageSharp?

System.Drawing can't be used on Windows Nano Server (doesn't have GdiPlus.dll or any other GUI for that matter). If you plan to be usable on Nano docker images you can't use System.Drawing. I'm not sure why the other things were listed, @safern will have to clarify if there are other known scenarios where GdiPlus.dll isn't part of Windows (I don't think there is anything beyond Nano).

https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/using-system-drawing-common.md

While the Unix version of System.Drawing can be used everywhere (if LibGdiPlus is installed properly), not all System.Drawing APIs are supported.

System.Drawing isn't very performant, SkiaSharp and ImageSharp are fast, fully modern cross-platform libraries.

Windows Forms is built on System.Drawing- it is totally ok for normal Windows applications. If you want modern performance and features and the ability to be used everywhere without caveats then use SkiaSharp or ImageSharp.

**Comment by nt-7** [comment]
@JeremyKuhne I intent **ASP.NET** web application on normal Windows Server, neither Nano server nor container.

**Comment by ericstj** [comment]
Here are some relevant PRs that created those notes
https://github.com/dotnet/dotnet-api-docs/pull/4594
https://github.com/dotnet/dotnet-api-docs/pull/5023

I believe this PR added the confusion and should be reverted: 
https://github.com/dotnet/dotnet-api-docs/pull/6636

Cc @alex-jitbit @gewarren

**Comment by alex-jitbit** [comment]
@ericstj `System.Drawing.Common` is cross-platform and works on Windows & Linux and you really should mention this fact at least somewhere in MS docs

**Comment by ericstj** [comment]
I believe the document that is under discussion is specifically about warning people about the problems using `System.Drawing.Common`.  Rather than encouraging use on Linux it could warn people about the differences they will encounter. Libgdiplus isn’t part of the operating system and I believe it doesn’t support all the functionality of gdiplus on Windows.  There are also platforms where libgdiplus is not available at all.  This warrants another remark.
