### ISSUE TITLE
Visual Basic comments are desplaying incorrect

### ISSUE THREAD

**Issue by LeftTwixWand** [dotnet/dotnet-api-docs#6777]
Hi. All the text after the ' symbol is getting commented in the code samples area, when selected language is Visual Basic:
![image](https://user-images.githubusercontent.com/50652041/119974504-69d19880-bfbd-11eb-89b9-a403f4aba8b9.png)

**Comment by ManickaP** [comment]
@joelmartinez @TianqiZhang

**Comment by joelmartinez** [comment]
Hi @ManickaP ... looks like this is an issue with our syntax coloring front-end functionality. Tagging in @kexugit who is working on this area

**Comment by kexugit** [comment]
I've created a but to track.

**Comment by jdanyow** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.bindingsource.sort?view=net-5.0

**Comment by gewarren** [comment]
For those with access, the bug is https://dev.azure.com/ceapex/Engineering/_queries/edit/439112/?triage=true.

**Comment by wablair** [comment]
Also seems to have issue with Visual Basic's #Region.

![region](https://user-images.githubusercontent.com/746172/124021891-b855c680-d9b1-11eb-8e57-ee8fcffa316d.png)

**Comment by gewarren** [comment]
This has been fixed...closing the issue.

**Comment by LeftTwixWand** [comment]
Thank You, guys! Now it's working much better)
