### ISSUE TITLE
Is the OnStart method document of servicebase incorrect

### ISSUE THREAD

**Issue by Vision-Zhang** [dotnet/dotnet-api-docs#6779]
look this code snippet，
```c#
Environment.GetCommandLineArgs() 
```
It's can not get registry,but in the [OnStart](https://docs.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicebase.onstart?view=dotnet-plat-ext-5.0#System_ServiceProcess_ServiceBase_OnStart_System_String___) document  that we can get registry infomation.

**Comment by ManickaP** [comment]
Hi @Vision-Zhang, could you be more specific in what is wrong where? Are you saying that `Environment.GetCommandLineArgs()` cannot/shoudn't be called from `OnStart`? Have you tested that? Could you share a piece of code demonstrating the problem? Or you could also open a PR against the this repository, fixing what you thing is wrong in the documentation.

**Comment by Vision-Zhang** [comment]
Thank you for your reply,it is introduced at the end of this document.(You can obtain the arguments from the registry using the GetCommandLineArgs method, for example: string[] imagePathArgs =Environment.GetCommandLineArgs();) but it can't   obtain arguments from the register.

**Comment by ViktorHofer** [comment]
@Anipik can you please take a look?

**Comment by krwq** [comment]
@Anipik @ViktorHofer can you give guidelines if documentation should be updated or if this is a product bug?

**Comment by Anipik** [comment]
i will take a look at this
