### ISSUE TITLE
Link to Source

### ISSUE THREAD

**Issue by SamuelEnglard** [dotnet/dotnet-api-docs#6793]
I feature I think would be particularly useful (for me at least) is to have links on API documentation pages to the source code on GitHub or Reference Sources.

Many times, I wonder how something is done in the BCL or the like and finding the source file can be a pain. Searching for APIs at docs.microsoft.com though is extremely easy. If I could go from there to the actual source code it would save me a lot of time.

**Comment by ManickaP** [comment]
cc: @gewarren This is rather generic ask.

**Comment by gewarren** [comment]
@SamuelEnglard Thanks for the suggestion. We've gotten numerous requests for this before (e.g. https://github.com/MicrosoftDocs/feedback/issues/433) and currently have an internal issue tracking it. I'll add a link to your issue to the internal issue to add some support. Is it okay if I close this issue?

**Comment by SamuelEnglard** [comment]
Awesome and please do. Could use also attach me to the internal issue?

**Comment by gewarren** [comment]
Sure - here it is: https://dev.azure.com/ceapex/Engineering/_workitems/edit/239577/

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
