### ISSUE TITLE
System.Random class doc has out-of-date Remarks

### ISSUE THREAD

**Issue by SiliconOrchid** [dotnet/dotnet-api-docs#6797]
Hey docs team! 

The "[Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=net-5.0#remarks)" section  of "System.Random Class" page states that *"The current implementation of the Random class is based on a modified version of Donald E. Knuth's subtractive random number generator algorithm..."*

**That advice is no longer fully current.**

The comment is true for legacy .NET Framework, but since .NET Core 2.x, the BCL has been updated to support different implementations of a random number generator.

---

**Current:**
Instead, the default now uses the "Xoroshiro" algorithm for random number generation.   There are actually two versions, the one used depends on whether the platform is 32bit of 64bit.

**Legacy Compatability:**
However, if the developer provides a seed number as a constructor argument,  the current code re-uses the older "Knuth" way - providing compatibility support legacy app (unit testing etc).

---

System.Random class Code:
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/Random.cs

e.g. Xoshiro implementation Code:
https://github.com/dotnet/runtime/blob/ee32ee2240f5771f9cf162695d110c2adccc5107/src/libraries/System.Private.CoreLib/src/System/Random.Xoshiro256StarStarImpl.cs

Thanks

-------------------

Edited change:

Also, 

In the section [Avoiding multiple instantiations](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=net-5.0#avoiding-multiple-instantiations), it currently states "initializing two random number generators in a tight loop or in rapid succession creates two random number generators that can produce identical sequences of random numbers".

The original implementation based the seed on `Environment.TickCouont()`,  whereas the revised code seems to use ` Interop.GetRandomBytes(...)`, which I believe has more entropy.

I've tested the current code and can't seem to reproduce identical sequences of numbers - is the advice now out of date?

**Comment by ManickaP** [comment]
Hi @SiliconOrchid,

I think that the xoroshiro implementation is pretty fresh https://github.com/dotnet/runtime/pull/47085 (only for 6.0 preview). That's why the docs do not correspond the code atm.

The linked PR has a label `new-api-needs-documentation` so there's a plan to update it for 6.0.

@carlossanlop do we need to keep a separate issue is the PR has `new-api-needs-documentation`? I'm not sure if we should keep this or close it in favor of the PR.

cc: @stephentoub

**Comment by stephentoub** [comment]
> I think that the xoroshiro implementation is pretty fresh dotnet/runtime#47085 (only for 6.0 preview).

Correct.  And it's also only used if you use `new Random()` or `Random.Shared`.  If you use `new Random(int)` or `new SomeClassDerivedFromRandom(...)`, it'll still use the previous implementation.

If we're going to make a change to the docs, I'd prefer it be to make the docs less specific rather than more.  The exact implementation used for Random is an implementation detail.

**Comment by SiliconOrchid** [comment]
Hey @ManickaP & @stephentoub, thanks for the speedy reply ! :-D

Doah - I'm so sorry ... I've been exploring around the subject ... and I hadn't registered how very new this code was - completely appreciate why the docs aren't correlating!

Agree with @stephentoub sentiment about making docs less specific.    It's an interesting topic, but probably not one that's relevant to developers consuming the library.

-------

A docs revision that *may possibly* still be worth considering, is my second point, that relates to that change of seeding mechanism to `Interop.GetRandomBytes(...)`.  That was present in the .Net Core 2.x codebase.     I'm feeling that this may still impact the current advice related to the potential problem of "creating identical sequences".

**.Net Core2.x code:**
Doah https://github.com/dotnet/corefx/blob/release/2.1/src/Common/src/CoreLib/System/Random.cs

**Comment by MSDN-WhiteKnight** [comment]
>A docs revision that may possibly still be worth considering, is my second point, that relates to that change of seeding mechanism to Interop.GetRandomBytes(...)

`Interop.GetRandomBytes` is only used for initial seed of global generator. Actual seeds of `Random` instances are pseudo random. The docs seem to correctly reflect that seeding mechanism changed in .NET Core:

>In .NET Framework, the default seed value is time-dependent. In .NET Core, the default seed value is produced by the thread-static, pseudo-random number generator.

>On the .NET Framework, initializing two random number generators in a tight loop or in rapid succession creates two random number generators that can produce identical sequences of random numbers.

What specifically needs revision?

**Comment by SiliconOrchid** [comment]
Hey @MSDN-WhiteKnight,

Have just re-visited this - I concur, the docs need no revision.
