### ISSUE TITLE
Incorrect behaviour for TimeSpan.FromFoo() methods

### ISSUE THREAD

**Issue by tdykstra** [dotnet/dotnet-api-docs#6826]
---
**Issue moved from MicrosoftDocs/Contribute#506**
- Please respond to @MikeFlowerdewAveva.

---

_From @MikeFlowerdewAveva on Thursday, June 10, 2021 9:23:59 AM_

Example: https://docs.microsoft.com/en-us/dotnet/api/system.timespan.fromseconds?view=net-5.0

These pages state explicitly that `TimeSpan.FromSeconds()` and related methods are only accurate to the nearest millisecond. To be fair, the docstrings on `TimeSpan` say the same, but it seems this has not been true since 2019 (specifically, from [this PR](https://github.com/dotnet/coreclr/pull/24279)). When I run the example code on the page in a .NET 5.0 unit test, I see full-precision output (with truncated ticks):
```
This example of TimeSpan.FromSeconds( double )
generates the following output.

          FromSeconds          TimeSpan
          -----------          --------
                0.001          00:00:00.0010000
               0.0015          00:00:00.0015000
              12.3456          00:00:12.3455999
          123456.7898        1.10:17:36.7898000
      1234567898.7654    14288.23:31:38.7654000
                    1          00:00:01        
                   60          00:01:00        
                 3600          01:00:00        
                86400        1.00:00:00        
            1801220.2       20.20:20:20.2000000
```

Strangely, the interactive run command on the page itself produces the advertised output, i.e. rounded to the nearest millisecond. I don't know how that works internally, so I can only speculate as to why that might be the case, as the change was made well before .NET 5.0 was released. This is the main reason I cannot create a PR to update the text, as that's no good without a working example.

**Comment by MikeRosoft** [comment]
It seems that the documentation is somewhat misleading. The real problem is that some values, like 0.1, cannot be exactly represented as the `double` type (because `double` is binary rather than decimal, and the binary representation of 0.1 has infinitely many digits); and that's why for example `TimeSpan.FromSeconds(0.1)` may not have exactly 0.1 seconds (even though the value of 0.1 s can be exactly represented as `TimeSpan`).

**Comment by tarekgh** [comment]
Closing this as we are tracking the same issue using https://github.com/dotnet/dotnet-api-docs/issues/9156
