### ISSUE TITLE
IsNullOrWhitespace doesn't work as documented.

### ISSUE THREAD

**Issue by rkulzer** [dotnet/dotnet-api-docs#6829]
During Unit Testing using the Microsoft.VisualStudio.TestTools.UnitTesting framework (otherwise known as
MSTest.TestFramework, version 1.3.2), it was discovered that the System.String.IsNullOrWhiteSpace(string) method
does NOT work as documented in the .NET Framework, Version 4.6, documentation pages
(https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=netframework-4.6). Specifically, the
documentation page for the System.String.IsNullOrWhiteSpace(string) method states:

"Indicates whether a specified string is null, empty, or consists only of white-space characters."

 and,

"Returns true if the value parameter is null or Empty, or if value consists exclusively of white-space characters."

However, as discovered during Unit Testing of code using the System.String.IsNullOrWhiteSpace(string) method  method, passing in the string "e f" to the System.String.IsNullOrWhiteSpace(string) method returns a value of true.

So, either the method's operation is correct and the documentation is incorrect, or the documentation is correct and
System.String.IsNullOrWhiteSpace(string) method.

**Comment by krwq** [comment]
@rkulzer I'm unable to repro, I've tried .NET 4.8 (full framework), .NET 5.0, .NET Core 2.1 and all of them produce `false`. Here is the code I used:

```csharp
Console.WriteLine(string.IsNullOrWhiteSpace("e f"));
```

Please make sure the string matches 1 to 1 with what you have.

If that still doesn't work for you can you see if it repros on other versions of .NET?
