### ISSUE TITLE
No example code for F# language, defaults to showing C#

### ISSUE THREAD

**Issue by IvenBach** [dotnet/dotnet-api-docs#6862]
Page for [SortedList<TKey,TValue> Class](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedlist-2?view=net-5.0) has no F# code blocks under the sections for [Examples](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedlist-2?view=net-5.0#examples) nor [Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedlist-2?view=net-5.0#remarks). The language shown is defaulting to C#.

**Comment by krwq** [comment]
cc: @cartermp

**Comment by eiriktsarpalis** [comment]
This is true for most collections docs. I could only find F# code samples under the [`List<T>` document](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=net-5.0) but not much else.

I would generally assume that most F# users are fairly fluent in C#, so curious what the cost-to-benefit ratio of providing F# translations is. cc @gewarren

**Comment by gewarren** [comment]
The language drop-down changes the syntax for the API to whichever language you choose, but Eirik is right - most APIs don't have any F# examples to show. Many APIs don't have any examples at all, so at this point, I don't see us adding many F# examples. Sorry. Feel free to submit a PR with a corresponding F# example, however.
