### ISSUE TITLE
Process WorkingSet64 Summary Wrong

### ISSUE THREAD

**Issue by Khirath-bit** [dotnet/dotnet-api-docs#6882]
WorkingSet64 summary states that it will return the memory usage in bytes but it actually returns it in bits. 

Maybe im totally wrong and i miss a trivial fact but i think its wrong.

My Task Manager says a service has 0,8 MB Ram Usage but WorkingSet64 / 1024 / 1024 gives me 6,xxx MB but one more division by 8 gives me the proper result. 

Did i miss something or is the documentation just wrong?

**Comment by acesolucoes** [comment]
@Khirath-bit I was having the same issue on native code, but I found out some information:
WorkingSet returns the memory used for your process, that is, the exclusive memory + shared memory that is used by pieces of your executable that other process also share. 
At first glimpse I thought there was some bug, but the amount retrieved by workingSet is matched by that _Resource Monitor_ app presents. The info returned on Task Manager was presented on the field _private_ at _Resource Monitor_. So, to match the information brought by _Task manager_ you need to invoke System.Diagnostic.Process.GetCurrentProcess().PrivateMemorySize64

**Comment by Khirath-bit** [comment]
@acesolucoes Ah okay! Thank you very much! 😄
