### ISSUE TITLE
IPAddress.TryParse documentation is misleading

### ISSUE THREAD

**Issue by MikeRosoft** [dotnet/dotnet-api-docs#6913]
The Remarks section of the documentation of IPAddress.TryParse at https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.tryparse is misleading. What it seems to be hinting at is that IP address does not need to have the usual format A.B.C.D; there are other possible formats, including:
* A (4-byte integer)
* A.B (1+3 bytes)
* A.B.C (1+1+2 bytes)

The segments can be in decimal, hexadecimal, or octal; for example, 127.1 and 127.0x01 are both perfectly valid ways to specify the address 127.0.0.1; so is 2130706433. (All of these addresses can be used with the ping command.) This is being discussed at https://thedailywtf.com/articles/comments/validate-freely .

0.0.0.1 is a syntactically perfectly valid IP address, though it's a part of a reserved range and can't be resolved (it's a 'Martian' address).

**Comment by karelz** [comment]
@MikeRosoft which part of the docs is misleading? What kind of changes would you suggest?

**Comment by MikeRosoft** [comment]
It's completely misleading about why `IPAddress.TryParse` (or `IPAddress.Parse`) accepts a numeric string like `"1"`. The real reason is: `1` is a perfectly valid IP address. (You can probably find a RFC defining a format of an IP address.) Conversely, the claim that `0.0.0.1` is not a valid IP address is false. It's a perfectly valid IP address, though it's a part of a reserved range and cannot be resolved. (On the other hand, `IPAddress.Parse(long.MaxValue.ToString())` fails with `FormatException`.)

Instead of giving an incorrect explanation of why the function accepts numeric strings, it should point out that there are other formats of an IP address apart from the usual A.B.C.D where the segments are decimal numbers from 0 to 255, and point to an appropriate RFC.

**Comment by karelz** [comment]
There does not seem to be any RFC defining IPv4 textual format -- https://en.wikipedia.org/wiki/IPv4#Address_representations and https://en.wikipedia.org/wiki/Dot-decimal_notation#IPv4_address
I think that [IPAddress.Parse](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.parse) documentation (see Remarks) is probably most accurate at describing behavior we implement. We should reuse it here as well IMO - perhaps just refer to each other?

**Comment by kjacobsen** [comment]
Sorry to comment on an old issue, but while the text now makes sense, the example definitely doesn't.
