### ISSUE TITLE
System.Uri: enabling IDN in .NET 5

### ISSUE THREAD

**Issue by beho** [dotnet/dotnet-api-docs#6934]
[Internal Resource Identifier section of System.Uri for .NET 5](https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-5.0#international-resource-identifier-support) shows an example for enabling IDN parsing using `app.config`/`machine.config`. But these are obsolete for .NET 5. I have no idea how to properly enable it.

**Comment by gewarren** [comment]
@JeremyKuhne Could you help with this question?

**Comment by safern** [comment]
cc: @dotnet/ncl

**Comment by ManickaP** [comment]
cc: @MihaZupan what's the current alternative?

**Comment by MihaZupan** [comment]
Those flags don't apply on .NET 5+.
Now it "just works". IDN support is **ON** with no way to turn it off.
