### ISSUE TITLE
WebSocketState.Abort is not "Reserved for future use"

### ISSUE THREAD

**Issue by chenxinyanc** [dotnet/dotnet-api-docs#6951]
**Issue description**
Doc link here: https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocketstate?view=net-5.0

Apparently `WebSocketState.Abort` is not "reserved for future use" as it has appeared in various locations of dotnet/runtime codebase.
![image](https://user-images.githubusercontent.com/50703224/127444540-b2e42d81-8b89-4cae-b401-27791ed0cd3e.png)

**Target framework**

- [x] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by safern** [comment]
@karelz could you or someone from the networking team help with this issue?

**Comment by ManickaP** [comment]
The docs should get fixed, the state is valid and used.

@chenxinyanc would you want to put up a PR with fix for the docs?

**Comment by chenxinyanc** [comment]
See #6967.
