### ISSUE TITLE
ImmutableList<T> should documented performance

### ISSUE THREAD

**Issue by briangithex** [dotnet/dotnet-api-docs#6958]
Moved from https://github.com/MicrosoftDocs/feedback/issues/1311

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablelist-1?view=netcore-2.2

**Problem:**
ImmutableList<T> should have documented performance guarantees for the Item and Add operations.  Note that this information is already formulated in the remarks section of https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1#remarks , so documenting these guarantees will not add new constraints on development of this class.

**Comment by eiriktsarpalis** [comment]
Related to #5282.
