### ISSUE TITLE
ImmutableSortedDictionary's CreateRange documentation states the wrong usage for the value comparer

### ISSUE THREAD

**Issue by quixoticaxis** [dotnet/dotnet-api-docs#7015]
The documentation of `ImmutableSortedDictionary.CreateRange<TKey,TValue>(IComparer<TKey>, IEqualityComparer<TValue>, IEnumerable<KeyValuePair<TKey,TValue>>)` says that "valueComparer" is used "to compare values for equality and sorting", while it cannot be used for the later.

**Comment by quixoticaxis** [comment]
@eiriktsarpalis the auto label is probably wrong. Are there any ways for a reporter to add a hint for bot what the label should be?

**Comment by adamsitnik** [comment]
I've changed the label from `System.Runtime` to `System.Collections`
