### ISSUE TITLE
AutoEllipsis documentation is ambiguous

### ISSUE THREAD

**Issue by ptoye** [dotnet/dotnet-api-docs#7046]
🛑 IMPORTANT: You can get your feedback addressed faster if you use the comment section for the article in which you encountered a problem.
There isn't a "comment" section in this article!

Link to article:
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.buttonbase.autoellipsis?view=netframework-4.7.1#System_Windows_Forms_ButtonBase_AutoEllipsis

Problem:
What's wrong with the article?
The "remarks" section is ambiguous. It says that text is displayed when the mouse hovers over a button where the text is too wide. It doesn't say what this means. It turns out that this is done with a Tooltip. I suggest that this is made clearer in the doc.

In addition, there are bugs in the code which displays the tooltip. Firstly, if the text can flow over more than one line no ellipsis is shown (correct) but the Tooltip still appears (incorrect). Secondly, if there is just enough space for the text on one line, the same happens. Surely, the pseudo-code should read something like
on Mousehover if auto-ellipsis is showing then display tooltip rather than trying to work out if the text is too wide and getting it wrong.

It would also be more user-friendly if the automatic Tooltip didn't overwrite any programmed tooltips.

I've got screenshots and a program which shows the issue, but they won't upload for some reason.

I'm using Visual Studio Community 2017 and Windows 7 if that helps.

**NOTE - This was first posted 2 years ago as https://github.com/MicrosoftDocs/feedback/issues/1399 but I have just been asked to move this topic to another issue. The latest documentation has the same bug. I have not been able to determine whether the issue is still present in .NET 5.0 **

**Comment by MihaZupan** [comment]
cc: @RussKie

**Comment by RussKie** [comment]
Ack the question, but I won't be able to look at this for sometime.
/cc: @dotnet/dotnet-winforms

**Comment by Marie-Shi** [comment]
@RussKie Have filed a issue: [5527](https://github.com/dotnet/winforms/issues/5527) in Winforms runtime repo.

**Comment by ptoye** [comment]
The documentation is better now - thanks. But the further issues that I pointed out - te program bugs and that if there's a tooltip associated with the control it's overwritten - are not addressed.

**Comment by Tanya-Solyanik** [comment]
@ptoye  - the code bug is tracked at a different repo - https://github.com/dotnet/winforms/issues/5527
