### ISSUE TITLE
`string.ToLower(CultureInfo? culture)` does not throw `ArgumentNullException` for a null culture

### ISSUE THREAD

**Issue by steveberdy** [dotnet/dotnet-api-docs#7059]
When a null culture is passed into `string.ToLower(CultureInfo? culture)`, no `ArgumentNullException` is thrown, despite what the docs say: `ToLower()` documentation: https://docs.microsoft.com/en-us/dotnet/api/system.string.tolower?view=net-5.0

This is due to a null check that assigns the null culture to `CultureInfo.CurrentCulture`: https://github.com/dotnet/runtime/blob/37d6d80d40b8fafd876d95d5eb07f676ac7b380c/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs#L1905-L1909

**Comment by MihaZupan** [comment]
This is the desired behavior given that the argument is nullable, so the documentation is wrong here. Same goes for `ToUpper`

**Comment by steveberdy** [comment]
Yes. The same may be true for the other methods taking in a nullable `CultureInfo`. I'll see if I can submit a PR later.

**Comment by tarekgh** [comment]
Right, we need to remove the exception section from the doc and add a small remark explaining the behavior when the input culture is `null`.
