### ISSUE TITLE
string.StartsWith(char) and string.EndsWith(char) remarks are incorrect

### ISSUE THREAD

**Issue by slozier** [dotnet/dotnet-api-docs#7060]
Both of these methods have the following remark:
>This method performs an ordinal (case-sensitive and culture-insensitive) comparison.

but I believe the comparison is actually ordinal?

**Comment by MihaZupan** [comment]
You are correct, these are all doing ordinal comparisons.

`Contains(char)` has the correct remark `This method performs an ordinal (case-sensitive and culture-insensitive) comparison.`, but [`StartsWith(char)`](https://docs.microsoft.com/en-us/dotnet/api/system.string.startswith?view=net-5.0#System_String_StartsWith_System_Char_) and [`EndsWith(char)`](https://docs.microsoft.com/en-us/dotnet/api/system.string.endswith?view=net-5.0#System_String_EndsWith_System_Char_) do not.

**Comment by danmoseley** [comment]
Do you want to offer a quick PR @slozier ?

**Comment by slozier** [comment]
Sure, I can do that.
