### ISSUE TITLE
Missing space in System.Linq.Enumerable

### ISSUE THREAD

**Issue by jbhensley** [dotnet/dotnet-api-docs#7119]
Docs for `System.Linq.Enumerable.Sum(IEnumerable<Nullable<Decimal>>)` are missing a space between the words "does" and "not" in the sentence "The result doesnot include values that are `null`". This appears to be on line 11105 of xml/System.Linq/Enumerable.xml

**Comment by eiriktsarpalis** [comment]
Hi @jbhensley, would you be interested in submitting a PR that address this?

**Comment by eiriktsarpalis** [comment]
Thanks for your contribution @jbhensley !
