### ISSUE TITLE
ValueTask Struct – GetResult() should be avoided (not .GetAwaiter())

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/dotnet-api-docs#7237]
From [ValueTask Struct|Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.valuetask?view=net-5.0#remarks)

>  A ValueTask instance may only be awaited once, and consumers may not call GetAwaiter() until the instance has completed.

Regard [ValueTask<TResult> Struct|Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.valuetask-1?view=net-5.0#remarks) or [Valid consumption patterns for ValueTasks](https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/#valid-consumption-patterns-for-valuetasks) problematic is call to `GetResult()` (`.GetAwaiter().GetResult()`) not `GetAwaiter()`.

I would fix it myself If knew rules to source XML.

**Comment by MSDN-WhiteKnight** [comment]
Correct. The similar fix was already done for generic value task: https://github.com/dotnet/dotnet-api-docs/pull/3716

>I would fix it myself If knew rules to source XML.

What are you having trouble with? The reference to GetResult would be `<xref:System.Runtime.CompilerServices.ValueTaskAwaiter%601.GetResult>`

**Comment by Uzivatel919** [comment]
> Correct. The similar fix was already done for generic value task: #3716
> 
> > I would fix it myself If knew rules to source XML.
> 
> What are you having trouble with? The reference to GetResult would be `<xref:System.Runtime.CompilerServices.ValueTaskAwaiter%601.GetResult>`

My trouble was that I was considering HTML entities like %60 as some kind of notion used in XML files.
