### ISSUE TITLE
Type signature of Span<T> in documentation is wrong

### ISSUE THREAD

**Issue by Saborion** [dotnet/dotnet-api-docs#7284]
The type signature says [public struct Span&lt;T&gt;](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-5.0&source=docs), whereas the source code says the type signature is [public readonly ref struct Span&lt;T&gt;](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Span.cs).

If I understand how to read the documentation and source code that is, but reacted since the [Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-5.0&source=docs#remarks) section in the documentation says that "Span<T> is a ref struct", which was not consistent with the type signature on the same page.

**Comment by gewarren** [comment]
I do see these attributes [in the ECMAXML](https://github.com/dotnet/dotnet-api-docs/blob/068a536522b6aa52f7a163e6657bba85d80ca9f0/xml/System/Span%601.xml#L40-L45) in case it's relevant:

```
      <AttributeName Language="C#">[System.Runtime.CompilerServices.IsByRefLike]</AttributeName>
      <AttributeName Language="F#">[&lt;System.Runtime.CompilerServices.IsByRefLike&gt;]</AttributeName>

      <AttributeName Language="C#">[System.Runtime.CompilerServices.IsReadOnly]</AttributeName>
      <AttributeName Language="F#">[&lt;System.Runtime.CompilerServices.IsReadOnly&gt;]</AttributeName>
```

**Comment by Saborion** [comment]
The same appears to hold true for https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1?view=net-5.0 as well.

**Comment by gewarren** [comment]
Thanks @Saborion. I've noted this issue in the internal tracking item and will close this now.
