### ISSUE TITLE
`Type.Namespace` property doesn't seem to ever return null if instance represents a generic parameter

### ISSUE THREAD

**Issue by cristicatalan** [dotnet/dotnet-api-docs#7340]
Documentation of [`Type.Namespace` property](https://docs.microsoft.com/en-us/dotnet/api/system.type.namespace?view=net-5.0#remarks) states:

> If the current Type represents a constructed generic type, this property returns the 
namespace that contains the generic type definition. Similarly, **if the current Type represents a generic parameter T** this property returns the namespace that contains the generic type definition that defines T.
>
> **If the current Type object represents a generic parameter**, this property returns null.

Initially I raised this issue on StackOverflow [here](https://stackoverflow.com/questions/69786564/when-does-type-namespace-return-null-if-instance-represents-a-generic-parameter). This post [answer](https://stackoverflow.com/a/69786923/2304432) and [comment](https://stackoverflow.com/questions/69786564/when-does-type-namespace-return-null-if-instance-represents-a-generic-parameter#comment123356287_69786923) strenghtened my believe this might be an issue in documentation.

The code that demonstrates the cases where .NET framework (.NET 5.0) itself says a type is generic parameter via `Type.IsGenericParameter property`, but actually returns a namespace:

```
using System;

namespace TypeDemo
{
    internal static class Program
    {
        public static void Main()
        {
            Console.WriteLine(typeof(Foo.C<>).GetGenericArguments()[0].IsGenericParameter);
            Console.WriteLine(typeof(Foo.C<>).GetGenericArguments()[0].Namespace);
            Console.WriteLine(typeof(Foo.C).GetMethod("Foo").GetGenericArguments()[0].IsGenericParameter);
            Console.WriteLine(typeof(Foo.C).GetMethod("Foo").GetGenericArguments()[0].Namespace);
        }
    }
}

namespace Foo
{
    class C<T>
    {
        public void Foo()
        {
        }
    }

    class C
    {
        public void Foo<T>()
        {
        }
    }
}
```

The statements in bold from cited documentation seem to contradict each other, and I think the second one in bold is not correct. Or I got it wrong and is there actually a case when `Type.Namespace` returns null if `Type` object represents a generic parameter?

**Comment by eerhardt** [comment]
cc @steveharter @buyaa-n @joperezr

**Comment by MSDN-WhiteKnight** [comment]
>Or I got it wrong and is there actually a case when Type.Namespace returns null if Type object represents a generic parameter?

```
Type t=Type.MakeGenericMethodParameter(0);
Console.WriteLine("IsGenericParameter: "+t.IsGenericParameter);
Console.WriteLine("Namespace: "+(t.Namespace==null?"(null)":t.Namespace));
```

These remarks should be changed to state that namespace is null when generic definition is not available.

**Comment by buyaa-n** [comment]
> These remarks should be changed to state that namespace is null when generic definition is not available.

That sound right to me
