### ISSUE TITLE
Why is System.Net.Mail.SmtpClient recommended to be replaced with the 3rd party MailKit and not Microsoft's own Microsoft.Graph?

### ISSUE THREAD

**Issue by mdell-seradex** [dotnet/dotnet-api-docs#7355]
Why do the docs recommend that the 3rd party `MailKit` is used instead of `System.Net.Mail.SmtpClient`, and the Mail component of Microsoft's own `Microsoft.Graph` is not given as an alternative?
`MailKit` has a single maintainer so it is more likely than projects with multiple maintainers to be abandoned, and while `MailKit` is part of the .NET Foundation, that means that if the maintainer decided to abandon it, somebody else should take their place, but should does NOT mean WILL.
In addition, there are issues currently with `MailKit` authenticating in certain scenarios, where apparently `Microsoft.Graph` works.

At the very least I feel it would be nice to state that using the Mail component of `Microsoft.Graph` is an alternative, and possibly listing limitations to `Microsoft.Graph` that `MailKit` addresses.
This would allow developers to choose a Microsoft solution if the limitations do not affect them.

Thank you

**Comment by karelz** [comment]
We recommend MailKit, because it is (or was at least back when we added that) the most popular library for SMPT client.
We intentionally gave it only as an example (calling "other libraries") -- see [Remarks section of SmtpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netframework-4.8#remarks):

> We don't recommend that you use the `SmtpClient` class for new development because SmtpClient doesn't support many modern protocols. Use [MailKit](https://github.com/jstedfast/MailKit) or other libraries instead. For more information, see [SmtpClient shouldn't be used](https://github.com/dotnet/platform-compat/blob/master/docs/DE0005.md) on GitHub.

Until this post we were not aware of Microsoft.Graph having SMTP client. If it is truly fully functional and superior to MailKit, we could mention it too, assuming it is popular in the community.
Are there docs / APIs in Microsoft.Graph targeting SMTP client functionality?

**Comment by mdell-seradex** [comment]
I cannot say with complete certainty, but from what I know, users can send and retrieve mail using `Microsoft.Graph`, unless I completely misunderstood.
My understanding is that it is using a REST API to do this, so it is perhaps not exactly an SMTP client, but for many, I believe it fits the intended purpose.
It may also be limited to Office 365 access, but I am not certain.
My main point, which perhaps I should have stated better, was that `Microsoft.Graph` is a Microsoft maintained library for handling mail, and could be used as a replacement for the SMTPClient, if it meets the developers needs.
I have only started working with `Microsoft.Graph` within the past year or two as it was recommended somewhere for accessing an Office 365 email account to do many things, including retrieving mail.  I do not recall where the recommendation came from.

**Comment by PashaPash** [comment]
@mdell-seradex Microsoft.Graph is Office 365-only, and it is not a replacement for SMTPClient.

**Comment by karelz** [comment]
Agreed, Microsoft.Graph does not sound like real replacement of general SmtpClient, though it may be useful in some narrow scenarios.

**Comment by mdell-seradex** [comment]
> @mdell-seradex Microsoft.Graph is Office 365-only, and it is not a replacement for SMTPClient.
I have started wondering if this may be the case, however many clients that I have been dealing with seem to be moving to Office 365, so it is still quite relevant, even if it is limited by the endpoint it can connect to.

FYI, I got the impression that MailKit uses Microsoft.Graph, from my limited reading, at least in some cases, but perhaps I was wrong.
It does seem sad that Microsoft does not have a proper library of their own for this.

**Comment by scalablecory** [comment]
MailKit is a .NET Foundation project, so it is an appropriate recommendation with long-term stability.

**Comment by scalablecory** [comment]
As discussed previously, Microsoft.Graph is not a viable replacement for SmtpClient in all cases. So, closing this issue.

**Comment by mdell-seradex** [comment]
> As discussed previously, Microsoft.Graph is not a viable replacement for SmtpClient in all cases. So, closing this issue.

I understand that it is not viable for all cases, however, being that it is a Microsoft owned project, I think that, if it meets their needs, people would feel it is more suitable, especially since it seems like many companies are transitioning to Office 365.   Of course, at least the primary limitation (only for Office 365) should be mentioned.
I also think that people would feel more comfortable with a Microsoft owned project, rather than some 3rd party one.

Yes, MailKit is part of the .NET Foundation, but I feel that many people don't know what that is or how to explain it to decision makers to get its use approved.  There is also the recent news about the .NET Foundation, that seems to cast a cloud over it, rightly or wrongly, which unfortunately can affect that.
