### ISSUE TITLE
HttpClient/HttpClientHandler/SocketsHttpHandler misleading documents

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/dotnet-api-docs#7369]
# Docs:

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0#constructors

![image](https://user-images.githubusercontent.com/4510984/140945553-8252c41f-e4b3-4131-8fa1-e69942a72fde.png)

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-5.0

![image](https://user-images.githubusercontent.com/4510984/140944684-d03e5f56-8dc4-4037-8e84-de1e2dcaab52.png)

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler?view=net-5.0

![image](https://user-images.githubusercontent.com/4510984/140945351-0c4589cb-c5d9-49fe-b64f-0a2294966fae.png)

# Actual

https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L134-L137

![image](https://user-images.githubusercontent.com/4510984/140945022-1ded4c16-2f91-4dff-98e5-fd8f20c67512.png)

**Comment by ManickaP** [comment]
And `HttpClientHandler`: 
https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L32

The `SocketsHttpHandler` is eventually underneath and it is the one used by default when instantiating `HttpClient`, we just don't name all the layers used to get there. This is very much implementation detail which might or might not change in the future.

**Comment by GF-Huang** [comment]
> And `HttpClientHandler`: [dotnet/runtime@`cf258a1`/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L32](https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L32)
> 
> The `SocketsHttpHandler` is eventually underneath and it is the one used by default when instantiating `HttpClient`, we just don't name all the layers used to get there. This is very much implementation detail which might or might not change in the future.

God, the source code browser fakes me: https://source.dot.net/#System.Net.Http/System/Net/Http/HttpClientHandler.cs,38
How can I choose .NET version in the source code browser?

**Comment by karelz** [comment]
Look higher up in the file - it is defined there:
https://source.dot.net/#System.Net.Http/System/Net/Http/HttpClientHandler.cs,16

**Comment by GF-Huang** [comment]
I click the `HttpHandlerType`, it jump to `SocketsHttpHandler`, this is something I didn't expect, so I missing the `using` definition.

**Comment by MihaZupan** [comment]
Technically the comment is correct for desktop, but as of 5.0, it isn't true on all platforms.
The default may be `BrowserHttpHandler` or a native handler depending on the platform.

**Comment by GF-Huang** [comment]
Got it, thanks all. 🌹
