### ISSUE TITLE
docs.microsoft.com/en-us/dotnet/api docs not updated to .Net 6 Release.

### ISSUE THREAD

**Issue by kirsan31** [dotnet/dotnet-api-docs#7390]
Still .Net 6 RC1 with _prerelease_ waning:
![image](https://user-images.githubusercontent.com/17767561/141773413-cad9cb92-bee2-4e25-b2db-5227e9375643.png)

By default docs refer to .Net5:
![image](https://user-images.githubusercontent.com/17767561/141738392-537c7e4d-8bf2-4ad9-8047-e34a41ad40b3.png)

Oh, I missed https://github.com/dotnet/dotnet-api-docs/pull/7387 PR - all of this will be addressed?

**Comment by eiriktsarpalis** [comment]
cc @gewarren

**Comment by gewarren** [comment]
Once #7384 is merged, I'll update the moniker and the prerelease warning will go away.

**Comment by gewarren** [comment]
The PR has been merged. The live APIs will refresh within 30 minutes from now.

**Comment by gewarren** [comment]
Oops, will reopen to track fixing the version in the link under the APIs header. Thanks for pointing that out.

**Comment by gewarren** [comment]
This should all be fixed now - closing.
