### ISSUE TITLE
Please add clarification that PriorityQueue does not guarantee Dequeue order of items with the same priority

### ISSUE THREAD

**Issue by datvm** [dotnet/dotnet-api-docs#7397]
[PriorityQueue<TElement,TPriority>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.priorityqueue-2?view=net-6.0) should clarify that items with the same priority does not have any dequeuing order. [Doc page code is here](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Collections.Generic/PriorityQueue%602.xml).

Sorry the name `Queue` made me think it should work like a queue with items with the same priority. Still a clarification should help (and I think it's important?)

Example:

```
var queue = new PriorityQueue<string, int>();
queue.Enqueue("A", 1);
queue.Enqueue("B", -1);
queue.Enqueue("C", 1);

while (queue.TryDequeue(out var foo, out _))
{
    Console.WriteLine(foo);
}
```

Output is
```
B
C
A
```

**Comment by eiriktsarpalis** [comment]
That's a reasonable clarification. We added it in the announcement but somehow it got left out of the docs. I've created #7397 to address this.
