### ISSUE TITLE
CustomFieldTemplate: the sample does not illustrate the description

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/dotnet-api-docs#7443]
I am reading the sample [Product](../blob/main/samples/snippets/csharp/VS_Snippets_WebNet/DynamicData.CustomFieldTemplate/CS/Product.cs). It shows me how to add a field template `UnitsInStock`.  But the [page](../blob/main/xml/System.ComponentModel.DataAnnotations/UIHintAttribute.xml) where it is referenced from does not mention `UnitsInStock`, so this is wholly unexpected and does not help at all.

**Comment by jeffhandley** [comment]
Hello @yecril71pl. It looks like the `UnitsInStock` template content is in the same folder as the `Product.cs` file you referenced:
https://github.com/dotnet/dotnet-api-docs/tree/main/samples/snippets/csharp/VS_Snippets_WebNet/DynamicData.CustomFieldTemplate/CS

Please let us know if this doesn't address your issue. Thanks.
