### ISSUE TITLE
FileStream.Handle is obsolete in .NET6 too.

### ISSUE THREAD

**Issue by iwkjosec** [dotnet/dotnet-api-docs#7455]
[FileStream.Handle Property > Applies to](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.handle?view=net-6.0#applies-to)
![image](https://user-images.githubusercontent.com/20414138/144702565-aa6878ad-4038-4ad0-992d-4be180204448.png)

**Comment by carlossanlop** [comment]
Hello @iwkjosec - .NET 6 shows in the list, it's the first item, so I'm not sure what is being reported here. Can you please clarify?

**Comment by svick** [comment]
@carlossanlop The "Versions *(Obsolete)*" heading indicates that the property is obsolete in versions in italics and parentheses, but .Net 6 is not one of those.

My guess is that this is related to the XML source for the page, which looks like this (simplified):

```xml
<Attribute FrameworkAlternate="net-5.0;netcore-3.0;netcore-3.1;netstandard-2.1">
    <AttributeName Language="C#">[System.Obsolete("This property has been deprecated.  Please use FileStream's SafeFileHandle property instead.  https://go.microsoft.com/fwlink/?linkid=14202")]</AttributeName>
</Attribute>
<Attribute FrameworkAlternate="net-6.0">
    <AttributeName Language="C#">[System.Obsolete("FileStream.Handle has been deprecated. Use FileStream's SafeFileHandle property instead.")]</AttributeName>
</Attribute>
<Attribute FrameworkAlternate="netcore-2.0;netcore-2.1;netcore-2.2;netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;netframework-4.8;netstandard-2.0">
    <AttributeName Language="C#">[System.Obsolete("This property has been deprecated.  Please use FileStream's SafeFileHandle property instead.  http://go.microsoft.com/fwlink/?linkid=14202")]</AttributeName>
</Attribute>
<Attribute FrameworkAlternate="xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0">
    <AttributeName Language="C#">[System.Obsolete("Use SafeFileHandle instead")]</AttributeName>
</Attribute>
```

Notice that the property is obsolete in many frameworks, but only those in the first group are marked that way in the Applies to section.

**Comment by carlossanlop** [comment]
Ah thanks for clarifying this, @svick.

@gewarren @mimisasouvanh this looks like a bug in the way mdoc groups the obsolete frameworks.

.NET 6 should be grouped with the others, not separate.

**Comment by svick** [comment]
@carlossanlop I think it's because .Net 6 has a different description for the `Obsolete` attribute (see https://github.com/dotnet/runtime/pull/56690). I'm not sure why .Net Core 2.0 and others are also listed separately.

**Comment by gewarren** [comment]
.netcore-2.0 and the others are listed separately because the info link is `http://` instead of `https://`.

**Comment by gewarren** [comment]
I logged internal issue https://dev.azure.com/ceapex/Engineering/_workitems/edit/528676 and assigned to Mimi.

**Comment by Jozkee** [comment]
This is fixed now, I can see all .NET (core) versions in italics and paretheses. Thanks @mimisasouvanh @gewarren.
