### ISSUE TITLE
Enumerable.MaxBy should describe behavior of throw Sequence contains no elements InvalidOperationException for empty primitive type enumerables

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#7461]
---
**Issue moved from MicrosoftDocs/feedback#3721**
- Please respond to @Smoovsky.

---

_From @Smoovsky on Thursday, December 2, 2021 5:39:28 AM_

**Describe the bug**
I noticed new Sytem.Linq.Enumrable.MaxBy method provided in .NET 6.0:
[doc](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.maxby?view=net-6.0)
The documentation states two types of exception ArgumentException and ArgumentNullException to be expected.
But InvalidOperationException may also be thrown for empty primitive type enumerables, see the example below.

**To Reproduce**
Snippet:
```
void Main()
{
	var test1 = new Test[] { }.MaxBy(x => x.MyProperty); // no problem
	var test2 = new Test[] { new Test { MyProperty = 1 }, new Test { MyProperty = 1 } }.MaxBy(x => x.MyProperty); // no problem
	var test3 = new int[] { }.MaxBy(x => x); // exception here
}

public class Test
{ 
	public int MyProperty { get; set; }
}
```
Run result:
![image](https://user-images.githubusercontent.com/34542126/144364210-26543990-4609-4bbc-ad41-21912e6446de.png)

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3721**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Thursday, December 2, 2021 5:39:30 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by eiriktsarpalis** [comment]
Yes, we should be documenting that exception. Note that this is also missing from the `Max` and `Min` and `MinBy` methods.

**Comment by jamesHargreaves12** [comment]
@eiriktsarpalis I was just tripped up by this issue as well and wanted to check if there had been any progress made?

I think the issue is not only that the docs are missing documentation of the Exception but also that for MinBy and MaxBy the current Remarks are actually incorrect.

> If TKey is a reference type and the source sequence is empty or contains only values that are null, this method returns null.

TKey should be replaced with TSource.
