### ISSUE TITLE
CancellationToken ThrowIfCancellationRequested exceptions in documentation seems incorrect

### ISSUE THREAD

**Issue by mkwaner** [dotnet/dotnet-api-docs#7497]
The documentation for `CancellationToken.ThrowIfCancellationRequested` indicates an `ObjectDisposedException` will be thrown if "The associated CancellationTokenSource has been disposed." This doesn't seem correct from inspecting the source code. Looks like it just calls `IsCancellationRequested` before throwing `OperationCanceledException` and `IsCancellationRequested` wouldn't throw `ObjectDisposedException` either when tracing it through to `CancellationTokenSource`.

**Comment by mkwaner** [comment]
Thanks for the quick reply. I'm hoping it's just a documentation issue and would have similar behavior as `IsCancellationRequested`. As the code consuming the `CancellationToken` I don't want to have to worry about knowing whether the token's `CancellationTokenSource` has already been disposed and be expected to handle `ObjectDisposedException`.

**Comment by buyaa-n** [comment]
Right, I feel the same, @mkwaner feel free to contribute to fixing the doc

**Comment by stephentoub** [comment]
The docs are wrong, most likely due to a copy/paste error from other members when the code was initially written.  ThrowIfCancellationRequested does not throw ObjectDisposedException nor is it intended to.  We should just fix the docs. Thanks.
