### ISSUE TITLE
File.ReadAllText() also detects UTF-16

### ISSUE THREAD

**Issue by WelliSolutions** [dotnet/dotnet-api-docs#7515]
The [remarks of File.ReadAlltext()](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.IO/File.xml#L4117) say

> Encoding formats UTF-8 and UTF-32 (both big-endian and little-endian) can be detected.

But according to [referencesource](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/file.cs#L827) it uses a [StreamReader which supports more encoding detections](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.-ctor?view=netframework-4.8#System_IO_StreamReader__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean_System_Int32_System_Boolean_)

> It automatically recognizes UTF-8, little-endian Unicode, big-endian Unicode, little-endian UTF-32, and big-endian UTF-32 text if the file starts with the appropriate byte order marks.

**Comment by Jozkee** [comment]
Sure, we can complete the list to match what's in StreamReader.

**Comment by eriawan** [comment]
@Jozkee 

The proposed update seems quite straightforward. Could you assign this to me?

**Comment by eriawan** [comment]
@Jozkee 

PR submitted: #8562
