### ISSUE TITLE
Typo error in NumberFormatInfo.NegativeSign Property example 

### ISSUE THREAD

**Issue by prasadtelkikar** [dotnet/dotnet-api-docs#7552]
There is typo error in [NumberFormatInfo.NegativeSign Property Example](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.negativesign?view=net-6.0#examples) Doc.

In the example, an instance of `CultureInfo` is defined with the variable name `ci`. While converting a number into a string, `culture` variable is used instead of variable name `ci`.

Due to this typo error, C# compile is throwing below error,

> Compilation error (line 13, col 44): The name 'culture' does not exist in the current context

Affected Languages: C#, VB.NET

[.net Fiddle](https://dotnetfiddle.net/AEPCji)

**Comment by prasadtelkikar** [comment]
I will raise PR soon

**Comment by tarekgh** [comment]
Thanks for the catch @prasadtelkikar. Feel free to tag me in the PR when you open it.

**Comment by prasadtelkikar** [comment]
Hi @tarekgh,

I raised PR against issue #7553, Kindly review it and let me know if there is anything I missed. 
This is my First PR to dotnet-api-docs repository.

Happy coding.... 😇

Thanks,
Prasad
