### ISSUE TITLE
RuntimeHelpers.Equals return documentation is misleading

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/dotnet-api-docs#7568]
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.equals?view=net-6.0#returns

https://github.com/dotnet/dotnet-api-docs/blob/282e7fea4ef2d866847f8d4ef57bc362c49ef86f/xml/System.Runtime.CompilerServices/RuntimeHelpers.xml#L213

Return documentation claims that if `object.Equals` would return `true` then this method returns `true`. However, this doesn't seem to be the case. It seems like this method is actually an internal call which may be comparing the underlying memory of structs. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoAldBKMAU2oGEB7MABygBtmyAMqCAblADGzAM4BuYsSoBOABT0YjFgAlmfboOnUAogEdUEPtJUxmAd3JDyAb3IAPcgF5yecgF845Db2ji7uXj6+AJSRsuQA9HHkACpozIp4quqazDp6BsZmFlZBDs5unt5+ASUh5V44ftGxCeQAYkXM5CrozK76EgjMACaR6ao1ZWGVvgXmltZ2paEVEU3xiSmoaSQZC8GTK36zRXtLdeQNUTHryakKRNIIaAMOxE7E5J+UAMzksAhueRED5fLC/DiiQTIKBDTrADgcPjkUxzKwcYAAK2YL3RGNGRC+zhBhM+WAA7OQnlsgYTfMRfEA=)

```cs
using System;
using System.Runtime.CompilerServices;

Console.WriteLine(RuntimeHelpers.Equals(new S { x = 1 }, new S { x = 1 })); // True
Console.WriteLine(RuntimeHelpers.Equals(new S { x = 1 }, new S { x = 2 })); // False (unexpected)
Console.WriteLine(new S { x = 1 }.Equals(new S { x = 1 })); // True
Console.WriteLine(new S { x = 1 }.Equals(new S { x = 2 })); // True

struct S
{
    public int x;

    public override bool Equals(object obj)
    {
        return true;
    }
}
```

cc @jnm2

**Comment by buyaa-n** [comment]
It is indeed comparing the contents for value type https://github.com/dotnet/runtime/blob/main/src/coreclr/classlibnative/bcltype/objectnative.cpp#L165

**Comment by steveharter** [comment]
> It is indeed comparing the contents for value type https://github.com/dotnet/runtime/blob/main/src/coreclr/classlibnative/bcltype/objectnative.cpp#L165

For value types, there is also this:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/System.Private.CoreLib/src/System/ValueType.cs#L44-L49
which will compare each field independently for non-blittable value types (e.g. fields that can hold reference types).

Given that code in `ValueType.cs`, however, then I'm not sure when this branch will be hit: https://github.com/dotnet/runtime/blob/main/src/coreclr/classlibnative/bcltype/objectnative.cpp#L161-L176

**Comment by buyaa-n** [comment]
> In any case, this code is different than RuntimeHelpers since it doesn't always do a mem compare. I'll attach a sample later that verifies the semantic differences.

Are you suggesting to mention the mem compare in the doc? What i have now in the PR is `if both are the same value type and the values of all fields from both are equal;` i can update it into `if both are the same value type and the values of the underlying memory from both are equal;`

**Comment by steveharter** [comment]
Calling out the mem compare may be good, since we just say every field is "equal" which may imply calling .Equals() on such fields which doesn't occur when using `RuntimeHelpers`.

e.g.
```cs
using System.Runtime.CompilerServices;

Console.WriteLine(RuntimeHelpers.Equals(new S(), new S())); // True
Console.WriteLine(new S().Equals(new S())); // False (due to calling S2.Equals)

Console.WriteLine(RuntimeHelpers.Equals(new S2(), new S2())); // True
Console.WriteLine(new S2().Equals(new S2())); // False (due to calling S2.Equals)

struct S
{
    public S2 s2;
}

struct S2
{
    public override bool Equals(object obj) => false;
}

```

**Comment by jnm2** [comment]
(And this is also the exact use case for me for RuntimeHelpers.Equals; doing a memory comparison rather than allowing arbitrary equality logic to run)
