### ISSUE TITLE
Possible Errors in System.Security.AccessControl Documentation

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#7587]
---
**Issue moved from MicrosoftDocs/feedback#3735**
- Please respond to @nick1941.

---

_From @nick1941 on Monday, December 27, 2021 10:48:44 PM_

In the .NET 6 documentation for System.Security.AccessControl in the topic on FileSystemRights Enum (https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.filesystemrights?view=net-6.0) in the Fields list, there are a number of duplicate values.
    AppendData and CreateDirectories both have a value of 4
    CreateFiles and WriteData both have a value of 2

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3735**
- Please respond to @gewarren.

---

_From @gewarren on Saturday, January 15, 2022 12:51:35 AM_

@nick1941 This appears to be by design: https://github.com/dotnet/runtime/blob/513fe2863ad5ec6dc453d223d4b60f787a0ffa78/src/libraries/System.IO.FileSystem.AccessControl/src/System/Security/AccessControl/FileSystemRights.cs#L16.

**Comment by carlossanlop** [comment]
As @gewarren already pointed out, yes, it's by design.
