### ISSUE TITLE
Errors in .NET 6 System.Reflection.Emit documentation

### ISSUE THREAD

**Issue by gewarren** [dotnet/dotnet-api-docs#7588]
---
**Issue moved from MicrosoftDocs/feedback#3733**
- Please respond to @nick1941.

---

_From @nick1941 on Friday, December 24, 2021 4:35:08 PM_

In the .NET 6 System.Reflection.Emit documentation, in the topic AssemblyBuilder Class, in Remarks > Dynamic Assembly Access Modes (link: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder?view=net-6.0&source=docs#dynamic-assembly-access-modes) there are references and links to three supposed fields of AssemblyBuilderAccess, namely, Run, Save, and RunAndSave.  However, in the System.Reflection.Emit documentation for AssemblyBuilderAccess, the only fields shown in that topic are Run and RunAndCollect (link: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilderaccess?view=net-6.0#System_Reflection_Emit_AssemblyBuilderAccess_Run).

**Comment by gewarren** [comment]
Some of the fields are only available in .NET Framework (if you change the moniker about the table of contents, you'll see them). However, we should note that in the Remarks, which are shared across all versions.

**Comment by MSDN-WhiteKnight** [comment]
Duplicate of https://github.com/dotnet/dotnet-api-docs/issues/5321

**Comment by gewarren** [comment]
Thanks @MSDN-WhiteKnight. Closing as a duplicate.
