### ISSUE TITLE
Remove TrackBar/DataGrid altmember from ScrollEventHandler

### ISSUE THREAD

**Issue by CaiusJard** [dotnet/dotnet-api-docs#7600]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrolleventhandler?view=windowsdesktop-6.0 cites

> Represents the method that handles the Scroll event of a DataGridView, ScrollBar, TrackBar, or DataGrid.

This is in conflict with the documentation for [DataGrid.Scroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagrid.scroll?view=netframework-4.8) and [TrackBar.Scroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.trackbar.scroll?view=windowsdesktop-6.0) which state that those controls' Scroll event is handled by a method that conforms to an EventHandler shaped delegate 

Recommend removing TrackBar and DataGrid from the list in the Definition section (summary tag) as it appears from a quick check in VS Intellisense that TrackBar and DataGrid do indeed use an EventHandler

**Comment by bartonjs** [comment]
That seems correct to me.

I've gone ahead and opened a pull request for the change, but in case you weren't aware you can propose edits by hitting the edit button at the top of the documentation page.  (It comes here and opens the usually-relevant file, then you can use the GitHub edit button to propose an edit)

**Comment by CaiusJard** [comment]
Thanks for the tip; will do that next time
