### ISSUE TITLE
Some markup error in System.Threading/CancellationTokenSource.xml

### ISSUE THREAD

**Issue by JHBonarius** [dotnet/dotnet-api-docs#7642]
https://github.com/dotnet/dotnet-api-docs/blob/5d1b21f7d6852d1edeca140ae7483b6be62c9ec1/xml/System.Threading/CancellationTokenSource.xml#L83

This part is marked as quote. That doesn't seem right and disable all parsing of references. I think it's an error.

**Comment by gewarren** [comment]
I'm not quite sure what the issue is here. In docs-markdown, we use this syntax for blocks such as Note, Important, and Warning. It seems to display correctly: https://docs.microsoft.com/dotnet/api/system.threading.cancellationtokensource?view=net-6.0#remarks. Can you elaborate on the issue?

**Comment by JHBonarius** [comment]
Hi Genevieve, thank you for your polite answer.
I don't know what happened or what changed. Indeed, now I see the correct markup (tried firefox and chrome). But honestly, when I filed this issue I was seeing the raw markup on this page for that section. I refreshed the page to double check it before filing the issue.
So I think it's good ow and this issue can be closed. Thank you for your time.
