### ISSUE TITLE
OWASP link(s) to their old wiki should be updated to link their "historical site"

### ISSUE THREAD

**Issue by Sausbolle** [dotnet/dotnet-api-docs#7643]
Happened to notice that (one particular) OWASP link are out of date and should be changed to their legacy wiki link (or equivalent location on new site).

I.e. all `https://www.owasp.org/index.php` links should be changed to `https://wiki.owasp.org/index.php`
_Looks like it is only doc pages referencing `[Data Validation](https://www.owasp.org/index.php/Data_Validation)` that uses the old link and should be updated._

**Comment by wenz** [comment]
Looks like that has already been fixed. Scanned all of dotnet-api-docs for "owasp" and found no dead line.

**Comment by Sausbolle** [comment]
Yes, looks like all the links have been updated in this pull https://github.com/dotnet/dotnet-api-docs/pull/8243/
Closing this Issue.
