### ISSUE TITLE
Buffer size

### ISSUE THREAD

**Issue by ygoe** [dotnet/dotnet-api-docs#765]
How large must the buffer array be? What happens if it was too small, so the received message was longer than the array? Can I just come back with more space to receive the rest? I guess the result.EndOfMessage property should be checked to determine that, but that's just a guess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f712007-895c-803c-b566-9ef3a8270834
* Version Independent ID: 98b29b49-2e42-4a20-330f-ee1546517b01
* Content: [ClientWebSocket.ReceiveAsync(ArraySegment<Byte>, CancellationToken) Method (System.Net.WebSockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket.receiveasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.WebSockets.ClientWebSocket.ReceiveAsync);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Net.WebSockets/ClientWebSocket.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.WebSockets/ClientWebSocket.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by karelz** [comment]
Seems to be answered
