### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by jfranki** [dotnet/dotnet-api-docs#766]
Definitions both for the method and its parameters are missing. Also for the return value and there are no exceptions. Would be great an example using a cancellation token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87fffb1e-8373-4aca-dc0d-89b4d8507124
* Version Independent ID: 7311cb48-8da9-b0d0-9da2-0292f8ce1b58
* Content: [NetworkStream.ReadAsync(Byte\[\], Int32, Int32, CancellationToken) Method (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.readasync?view=netcore-2.0#System_Net_Sockets_NetworkStream_ReadAsync_System_Byte___System_Int32_System_Int32_System_Threading_CancellationToken_)
* Content Source: [xml/System.Net.Sockets/NetworkStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/NetworkStream.xml)
* Service: **unspecified**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I've scheduled this for a future sprint.

**Comment by mairaw** [comment]
Moving to the backlog until I can actually pick this up to start working on it.

**Comment by dinobu** [comment]
How is this documentation helpful again?

**Comment by mairaw** [comment]
The definitions were added to the docs a while back. Given the low number of visits to this particular API, I think the probability of getting an example added would be low, so closing this.
