### ISSUE TITLE
network distrubutors

### ISSUE THREAD

**Issue by marlabeau** [dotnet/dotnet-api-docs#7666]
taking down websites

**Comment by marlabeau** [comment]
bitcoins  within the same website name was moved, are they allowed ?

**Comment by bartonjs** [comment]
I'm not quite sure what your issue is about, can you describe it more clearly?

This repository is for documentation for .NET, available at https://docs.microsoft.com/en-us/dotnet/?view=net-6.0

**Comment by tarekgh** [comment]
@marlabeau I am closing this issue as it doesn't have enough information. Feel free to reply with detailed info and we'll consider opening it again.
