### ISSUE TITLE
Is `Delegate` really base class for many (among them `Action`, Predicate<T>)?

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/dotnet-api-docs#7667]
At [Delegate Class](https://docs.microsoft.com/en-us/dotnet/api/system.delegate?view=net-6.0) I see many types denoted as derived one. E.g. _System.Action_ or _System.Predicate<T>_.

At [Object.GetType Method](https://docs.microsoft.com/en-us/dotnet/api/system.object.gettype?view=net-6.0) one can find

> NET recognizes the following five categories of types:
> …
> • Delegates, which are derived from System.MulticastDelegate.

same as at [Common type system](https://docs.microsoft.com/en-us/dotnet/standard/base-types/common-type-system#delegates)
> All delegates inherit from System.MulticastDelegate, which inherits from System.Delegate. The C#, Visual Basic, and C++ languages do not allow inheritance from these types. Instead, they provide keywords for declaring delegates.

And runtime proves same 

```csharp
> typeof(Predicate<object>).BaseType
[System.MulticastDelegate]
> typeof(Action).BaseType
[System.MulticastDelegate]
```

I searched _Delegate Class_ page for explanation but did not find it. There are some explanations that can resemble reason why **Derived** lists these but not clearly-understandably.

> The Delegate class is the base class for delegate types. However, only the system and compilers can derive explicitly from the Delegate class or from the MulticastDelegate class. It is also not permissible to derive a new type from a delegate type. The Delegate class is not considered a delegate type; it is a class used to derive delegate types.
>
> Most languages implement a delegate keyword, and compilers for those languages are able to derive from the MulticastDelegate class; therefore, users should use the delegate keyword provided by the language.

**Comment by bartonjs** [comment]
I think the general idea behind that documentation is that `Delegate` is the base class that we expect developers to interact with, and `MulticastDelegate` is sort of an implementation detail, so we just skip that link in the documentation.

@dotnet/area-system-runtime For further comment.

**Comment by tannergooding** [comment]
This might be an area where @jkotas is better to comment.

AFAIR there is intent and reality here and the runtime actually doesn't allow "single-cast delegates" (that is delegates that derive directly from `System.Delegate`) to exist, even where the ECMA-335 spec might.

`Delegate` and `MulticastDelegate` have always been special, in many of the same ways that `Enum` and `ValueType` are special.

**Comment by jkotas** [comment]
A bit of history: The early beta versions of .NET Framework 1.0 had both single-cast and multi-cast delegates. This distinction was removed based on feedback (introduced a lot of extra complexity), but it was too late to push a breaking change to delete the superfluous MulticastDelegate type.

For guidance, I agree with what @bartonjs said above.

**Comment by Uzivatel919** [comment]
> I think the general idea behind that documentation is that Delegate is the base class that we expect developers to interact with, and MulticastDelegate is sort of an implementation detail, so we just skip that link in the documentation.

FMPOV, any inheritance chain I saw was exact. (AFAIK) This page for me is more confusing than if I would have needed to skim trhough some note and Multicast delegate page to get full overview.

> A bit of history: The early beta versions of .NET Framework 1.0 had both single-cast and multi-cast delegates. This distinction was removed based on feedback (introduced a lot of extra complexity), but it was too late to push a breaking change to delete the superfluous MulticastDelegate type.

Thank you for history window.

**Comment by MSDN-WhiteKnight** [comment]
Monodoc has special logic that replaces any System.MulticastDelegate base type with System.Delegate: https://github.com/mono/api-doc-tools/blob/main/mdoc/Mono.Documentation/MDocUpdater.cs#L2263

                // Initially CLR used to support both singlecast and multicast for delegates. But then distinction was removed later.
                // The line could be added to reduces clutter in the docs by not showing the redundant MulticastDelegate.
                // Although all delegates are multicast now. We will keep this line to avoid huge changes in ecmaxml files.
                // https://ceapex.visualstudio.com/Engineering/_workitems/129591
                if (basetypename == "System.MulticastDelegate") basetypename = "System.Delegate";

This explains why there's a swarm of types derived from Delegate, and none from MulticastDelegate. So if this is by design, mentions like "Delegates, which are derived from System.MulticastDelegate" should be purged from docs. But the Common Type System part might be not possible to get rid of, if it's a direct reflection of ECMA-335 spec. I wonder what is tracked by "ceapex" workitem 129591 mentioned in comments above. Is it the same issue as this one?

**Comment by BillWagner** [comment]
One additional note for consideration: Following the history and @bartonjs 's comment above, the ECMA committee removed all mention of `System.MulticastDelegate` in the C# standard.  (Trivia: we referred to is as the "The class that shall not be named" in some meetings.)

There's some weasel words about allowing "intermediate base classes" when `System.Delegate` is mentioned, because the implementation does use `System.MulticastDelegate`, but we worked to avoid calling it out.

**Comment by Uzivatel919** [comment]
@bartonjs 

> I think the general idea behind that documentation is that Delegate is the base class that we expect developers to interact with, and MulticastDelegate is sort of an implementation detail, so we just skip that link in the documentation.

So by hiding true inheritance developers are forced/encouraged to work with `Delegate` instead of `MulticastDelegate` which is just beauty defect since .NET FW 1.0?

**Comment by Uzivatel919** [comment]
@bartonjs, @BillWagner, I got that `MulticastDelegate`  should stay hidden behind scenes because it is irreversible design decision. Still I miss any benefit. I mean stating out false inheritance chain in documentation has **potential to motivate** developers to use `Delegate` in API (let say method parameter) instead of `MulticastDelegate`?

This could be expressed differently, deliberately:
- technically it’s no issue to go with `MulticastDelegate`, so it is quite countermeasure
- this page is in antinomy to other pages that refers type system, it is confusing
- lowers documentation credence rank
-  `MulticastDelegate` and `Delegate` are both uninheritable, so it is totally unimportant which of them is base class for anything because `delegate` declaration is translated internally by compiler
- compiler warning or suggestion recommending `Delegate` usage could be find more pleasent
- …

So, I tell once again that this is zero benefit workaround. I would say cheap, unsmart solution to something that has transited to shade level rather than bold motivation to anyone, if I were about to be vague.

Note that I should stick with `Delegate` for simplicity and why to avoid `MulticastDelegate` instead of uncovering implementation details could spare my spare time.

On other hand I expect nobody to change anything. That is for sure.
