### ISSUE TITLE
Documentation on Enumerable.Sum(IEnumerable<Nullable<double>>) should be clearer on whether/when it returns null 

### ISSUE THREAD

**Issue by m-ringler** [dotnet/dotnet-api-docs#7669]
The current documentation says
~~~
This method returns zero if source contains no elements.

The result does not include values that are null.
~~~
You could deduce from this that the method never returns null, but I think 
* `the result does not include` could be put more precisely
* whether the method returns null should be stated explicitly, because users need to know whether they need to handle a null return value. 
~~~
This method returns zero if source contains no elements.

Items in source that are null are excluded from the computation of the sum.
This method never returns null.
~~~

The same goes for all the other `Enumerable.Sum(IEnumerable<Nullable<TNumber>>)` overloads.

**Comment by layomia** [comment]
@eiriktsarpalis @stephentoub is it an error for these `Sum(IEnumerable<TNumber?>)` overloads to return `TNumber?` instead of `TNumber` since they never return `null`?

**Comment by stephentoub** [comment]
> @eiriktsarpalis @stephentoub is it an error for these Sum(IEnumerable<TNumber?>) overloads to return TNumber? instead of TNumber since they never return null?

It's not an "error"... it's how they were defined, with `Nullable<double>` being the return type.  Even if we wanted to change it, doing so would be a breaking change.

**Comment by layomia** [comment]
I think the proposed text is fair:

```
This method returns zero if source contains no elements.

Items in source that are null are excluded from the computation of the sum. This method never returns null.
```

We'd be happy to take a community PR updating the text.

**Comment by eriawan** [comment]
@layomia 

Looking at your wording, this seems quite straightforward. Could you assign this to me?

**Comment by eiriktsarpalis** [comment]
@eriawan done.
