### ISSUE TITLE
System.IO.Directory.GetFiles method, path Relative or Absolute when-which returned?

### ISSUE THREAD

**Issue by MightyPen** [dotnet/dotnet-api-docs#768]
The article for 'System.IO.Directory.GetFiles' method says the returned filenames might or might not includes the full Absolute path, or just the Relative path: But the article neglects to explain when the returned path portion will be Absolute vs Relative.
The article should explain when-which path type is returned.

Thank you.
(GitHub MightyPen = GeneMi at Msft)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be5663f7-3d2a-e997-7b92-be71df72f101
* Version Independent ID: 111b99c7-202a-c2ec-9a88-ae3cf4836309
* Content: [Directory.GetFiles Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=netframework-4.6.1)
* Content Source: [xml/System.IO/Directory.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Directory.xml)
* Service: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by carlossanlop** [comment]
We do explain this information in the remarks for all the `GetFiles` overloads:

```
 The returned file names are appended to the supplied `path` parameter.
...
 The `path` parameter can specify relative or absolute path information. Relative path information is interpreted as relative to the current working directory. To obtain the current working directory, see <xref:System.IO.Directory.GetCurrentDirectory%2A>.
```

Closing.
