### ISSUE TITLE
Is ProcessStartInfo.ArgumentList secure against untrusted input?

### ISSUE THREAD

**Issue by tghosth** [dotnet/dotnet-api-docs#7697]
This question refers to "ProcessStartInfo.ArgumentList" which is documented in the following file:
https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics/ProcessStartInfo.xml

The documentation [says](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=net-6.0#definition):
> Strings added to the list don't need to be previously escaped.

and also [says](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=net-6.0#remarks):

> ```ArgumentList``` takes care of escaping the provided arguments 

My question: is ArgumentList considered to be secure against untrusted/malicious input? i.e. any untrusted input will be safely escaped.

Based on the comments in [this issue here](https://github.com/OWASP/CheatSheetSeries/pull/789), I do not think it will be secure against a situation where a malicious user provides input which will break out of one argument being passed and allow them to tamper with another argument being passed.

As such, should a warning be added to the documentation indicating that this is not intended as a security control?

**Comment by tghosth** [comment]
Refers to [System.Diagnostics](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics?view=net-6.0), System.Diagnostics.ProcessStartInfo.ArgumentList

**Comment by joshbouncesecurity** [comment]
Looks like uhis was handled by #8802 which is a bit of a disappointing cop-out but I guess at least it is something...

**Comment by tghosth** [comment]
Looks like this was handled by https://github.com/dotnet/dotnet-api-docs/pull/8802 which is a bit of a disappointing cop-out but I guess at least it is something...
