### ISSUE TITLE
What is time unit for timeout?

### ISSUE THREAD

**Issue by morriekken** [dotnet/dotnet-api-docs#773]
Is it seconds or milliseconds?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07b9ab7d-aa53-004c-6e2b-8a1285cb44bc
* Version Independent ID: c24f546a-2960-846a-bfae-8b42293c3ec4
* Content: [DataContext.CommandTimeout Property (System.Data.Linq)](https://docs.microsoft.com/en-gb/dotnet/api/system.data.linq.datacontext.commandtimeout?view=netframework-4.7.1#System_Data_Linq_DataContext_CommandTimeout)
* Content Source: [xml/System.Data.Linq/DataContext.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Linq/DataContext.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@divega do you know who can help with questions about this API in the System.Data.Linq namespace?

**Comment by divega** [comment]
The remarks clarify that the value in the property is used to set the IDbCommand.CommandTimeout for the commands created, which is expressed in seconds. 

I agree that the language is unclear and non-committal. Perhaps there are historical reasons. However, the documentation for [IDbCommand.CommandTimeout](https://docs.microsoft.com/dotnet/api/system.data.idbcommand.commandtimeout?view=netcore-2.2#System_Data_IDbCommand_CommandTimeout ) clearly says it is in seconds.

**Comment by SeanKilleen** [comment]
Since this seemed to be a case where a clear answer was provided, and it was ranked as a high priority, I submitted a PR to attempt to get this out there.
