### ISSUE TITLE
HttpListener.Stop() and HttpListener.Close() examples are swapped; HttpListener.Close() example insufficient

### ISSUE THREAD

**Issue by bgottfried91** [dotnet/dotnet-api-docs#776]
The example code for this document uses HttpListener.Close() (see the last line of the example) instead of HttpListener.Stop(). The documentation for HttpListener.Stop() uses HttpListener.Close() (see the last line of the example on that page). This could make it seem as if the methods are interchangeable.

Additionally, presumably the correct way to use the two methods is to stop the listener to prevent new requests coming in, handle any remaining requests, then close the listener.  It'd be good to see this in an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a791382f-cae9-5f48-3362-a68da37e949b
* Version Independent ID: 8b263156-c717-f048-3b22-1b076d93d9ac
* Content: [HttpListener.Stop Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.stop?view=netframework-4.7.1)
* Content Source: [xml/System.Net/HttpListener.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/HttpListener.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This was fixed in https://github.com/dotnet/dotnet-api-docs/pull/2243.

Sorry for the delay on getting this one done.
