### ISSUE TITLE
Socket.SetSocketOption docs are misleading/confusing

### ISSUE THREAD

**Issue by zivcaspi** [dotnet/dotnet-api-docs#7843]
https://github.com/dotnet/dotnet-api-docs/blob/13425c2d339c9f517577e57ff51e0aa727915541/xml/System.Net.Sockets/Socket.xml

The doc for at least _some_ overloads of Socket.SetSocketOption (specifically, the one that takes a System.Object as the last argument) are highly misleading.
A casual reading of them might lead one to assume that _any_ option is supported through this overload. However, in reality the code actually is only willing to accept a few possible options.
Other options require using other overloads. This should be clarified in the docs.
For example, trying to set the TCP option TcpKeepAliveTime with a TimeSpan value won’t work – it throws an ArgumentException (note that this is not a documented exception BTW). One has to use the overload that takes an int and “magically know” that the int is the intended number of msec. (It’s also possible that the overload taking a byte array works, but I didn’t test that.)

**Comment by liveans** [comment]
This is already documented in `Remarks` section, but the example is misleading because we're using the same example for both `object` and `int` overload. I'll address them separately.
