### ISSUE TITLE
Directory.Exists is case sensitive on linux

### ISSUE THREAD

**Issue by Alaric84** [dotnet/dotnet-api-docs#7989]
**Issue description**

(https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.exists?view=net-6.0)

The docs state that the "path" parameter is not case sensitive.
This is not correct for .Net running in Linux.
I'd say the behavior is what one needs but then it should be documented properly.

**Target framework**

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

**Comment by Jozkee** [comment]
Probably the best thing to do here is remove the misleading sentence. [`File.Exists`](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.exists?view=net-6.0) doesn't even mention case sensitiveness.

**Comment by Alaric84** [comment]
wow - this seems to be wrong in [Directory.xml](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.IO/Directory.xml) at 50 locations.
But in [File.xml L751](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.IO/File.xml#L751) Path is said to be not case-sensitive.

Removing it would be a good step. "Incorrect documentation is worse than none"
But what's about: "The  case sensitiveness of the `path` parameter depends on the rules of the current operating systems"
