### ISSUE TITLE
[Improvement] Link reference source in .NET API browser

### ISSUE THREAD

**Issue by JKamsker** [dotnet/dotnet-api-docs#7992]
I'd love to see directly how a class is implemented in .net.

Currently, i have to search the dotnet/runtime repo.
Linking the source file on github would make my life easier.

**Comment by gewarren** [comment]
This has been requested before and we know it's important to customers. We are tracking it under https://github.com/MicrosoftDocs/feedback/issues/433. Also previously logged in this repo as #6793.

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/en-us/dotnet/api/system.string.chars?view=net-8.0

**Comment by JKamsker** [comment]
Uhhh THIS is super nice thank you :3
