### ISSUE TITLE
Missing from .NET Core 2.1 documentation

### ISSUE THREAD

**Issue by burnchar** [dotnet/dotnet-api-docs#802]
System.IO.Ports should be in .NET Core 2.1 if it is in 2.0, but documentation is missing when one selects 2.1 as their version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa765d00-19f8-74e4-4be1-1d7f1e7dc6ce
* Version Independent ID: 260749e3-69c6-a370-89b0-4f90d944fac7
* Content: [SerialPort Class (System.IO.Ports)](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport?view=netcore-2.0)
* Content Source: [xml/System.IO.Ports/SerialPort.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Ports/SerialPort.xml)
* Product: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
This works now. So closing this issue.

https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport?view=netcore-2.1
