### ISSUE TITLE
Some docs pages recommend to instantiate HttpClient once and reuse it for the lifetime of the application, others recommend to instantate HttpClient many times with IHttpClientFactory

### ISSUE THREAD

**Issue by gaazkam** [dotnet/dotnet-api-docs#8082]
Two different docs pages seem to be inconsistent with each other.

[HttpClient Class § Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0#remarks) says:

> [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0) is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.

This page makes no reference to `IHttpClientFactory`.

However, [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0) recommends to instead use `IHttpClientFactory` to create multiple instances of `HttpClient` and manage them. **Note that this page does not limit itself to the context of ASP.NET Core, in section [§ Use IHttpClientFactory in a console app](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0#use-ihttpclientfactory-in-a-console-app) it also instructs us how to do this outside of ASP.NET Core**.

From this docs page:

> IHttpClientFactory offers the following benefits:
> 
> (…)
> 
> - Manages the pooling and lifetime of underlying HttpClientMessageHandler instances. Automatic management avoids common DNS (Domain Name System) problems that occur when manually managing HttpClient lifetimes.

Section [§ HttpClient and lifetime management](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0#httpclient-and-lifetime-management) elaborates that:

> IHttpClientFactory pools the HttpMessageHandler instances created by the factory to reduce resource consumption. An HttpMessageHandler instance may be reused from the pool when creating a new HttpClient instance if its lifetime hasn't expired.
> 
> Pooling of handlers is desirable as each handler typically manages its own underlying HTTP connections. Creating more handlers than necessary can result in connection delays. Some handlers also keep connections open indefinitely, which can prevent the handler from reacting to DNS (Domain Name System) changes.

It later explicitly hints that creating a single instance of `HttpClient` and reusing it for the lifetime of the application is made obsolete by `IHttpClientFactory`:

> Keeping a single HttpClient instance alive for a long duration is a common pattern used before the inception of IHttpClientFactory. This pattern becomes unnecessary after migrating to IHttpClientFactory.

OTOH in section [§ Cookies](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0#cookies) this page mentions that `IHttpClientFactory` might not be the best option when using cookies:

> The pooled HttpMessageHandler instances results in CookieContainer objects being shared. Unanticipated CookieContainer object sharing often results in incorrect code. For apps that require cookies, consider either:
>
> - Disabling automatic cookie handling
> - Avoiding IHttpClientFactory

Suggestion
===

Given the above I belive that the docs should be made consistent by either:

- Mentioning in HttpClient Class § Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0#remarks) that, with the possible exception of applications heavily utilizing cookies, `IHttpClientFactory` is the recommended alternative to manually creating one `HttpClient` instance and reusing it for the lifetime of the application;
- Or no longer recommending `IHttpClientFactory` in the ASP.NET Core docs.

**Comment by gewarren** [comment]
Related to https://github.com/dotnet/docs/issues/26510.

**Comment by gewarren** [comment]
Also similar to #8021.

**Comment by wfurt** [comment]
Part of the problem is that there is no single best solution. It feels it would be useful to better describe the behavior instead of driving them to particular path.
