### ISSUE TITLE
Suggestion: Add a link referencing the corresponding source file defining a type.

### ISSUE THREAD

**Issue by melgmry0101b** [dotnet/dotnet-api-docs#8086]
First of all, deeply appreciate the incredible work you are doing maintaining and updating the docs!

### Description
_________________

I would like to suggest adding a link referencing the file that defines the type described in a document. I often reference the source code of a component or a type while working on different .NET applications. For example, I am now working on an authentication schema for an ASP.NET Core 6 application, referencing the source code was very convenient for me to spin up proper implementation for the application. The inconvenience I got while doing that was digging up the file that defines the type of interest. I understand I can clone the repository and browse the code locally on my machine, but, this would be enough of a burden on my limited computing resources to be able to.

### Implementation Hints.. Maybe?
______________________________________

As the docs are -generally speaking from what I saw- is generated dynamically from the xml documentations written within the source code, I believe it may be viable to add a link referencing the file from which these docs are generated and from which commit (a GitHub link). This would be very helpful in my opinion. I understand this might not be a priority or even in the roadmap, but, considering it will be very appreciated.

**P.S.** I searched within the open issues for similar suggestions but couldn't land on one.

**Comment by svick** [comment]
This is a duplicate of https://github.com/MicrosoftDocs/feedback/issues/433. (It's understandable you didn't find it, since it's in another repo.)

**Comment by melgmry0101b** [comment]
No worries, thanks for your comment! I think I will close this issue for now and keep an eye on there.

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/en-us/dotnet/api/system.string.chars?view=net-8.0
