### ISSUE TITLE
Missing System.IO.Hashing docs on website

### ISSUE THREAD

**Issue by ptasev** [dotnet/dotnet-api-docs#8090]
I'm not sure if this is the right repo for this issue, but I was trying to find documentation regarding Crc32, and I noticed this entire library seems to be missing from the docs website from what I can tell.

I was able to find it only on the apisof.net website.
https://apisof.net/catalog/24de7164-bb66-a74a-4765-cf26fb2218a5

**Comment by gewarren** [comment]
@bartonjs It looks like it might be missing from this file: https://github.com/dotnet/api-catalog-infra/blob/main/eng/droplayout.props

**Comment by bartonjs** [comment]
The content hasn't migrated in yet, but the skeleton pages seem to be up now.  https://docs.microsoft.com/en-us/dotnet/api/system.io.hashing?view=dotnet-plat-ext-7.0

**Comment by bartonjs** [comment]
And now I see all the content is there.  Closing the issue.  Thanks for reporting it, @ptasev.

**Comment by ptasev** [comment]
I believe .NET 6 should be shown here:
![image](https://user-images.githubusercontent.com/23424044/188286682-9ef9682f-0fa6-45db-8f4b-ddc2317f5be1.png)

**Comment by gewarren** [comment]
@carlossanlop Can we regenerate a drop for .NET 6 so the versioning shows up correctly for System.IO.Hashing?

**Comment by carlossanlop** [comment]
Good question, I think it should be possible. I'd have to switch to an old 6.0 branch both in the api-catalog repo and runtime, then generate a drop.

**Comment by carlossanlop** [comment]
@gewarren I sent you the drop network location via chat.
