### ISSUE TITLE
file

### ISSUE THREAD

**Issue by sayhurtz33** [dotnet/dotnet-api-docs#811]
whats file is this for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48baa81e-33e9-2659-ad69-65a6071cad7f
* Version Independent ID: 63265d87-90a5-3e37-aae8-8b8ebbe68981
* Content: [ElementLocation.File Property (Microsoft.Build.Construction)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.construction.elementlocation.file?view=netframework-4.7.1#Microsoft_Build_Construction_ElementLocation_File)
* Content Source: [xml/Microsoft.Build.Construction/ElementLocation.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Build.Construction/ElementLocation.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by carlossanlop** [comment]
The description does not describe the issue. Closing.
