### ISSUE TITLE
Documentation for ImmutableList<T>.Empty is incorrect

### ISSUE THREAD

**Issue by mjolka** [dotnet/dotnet-api-docs#8129]
The [summary for ImmutableList&lt;T&gt;.Empty](https://github.com/dotnet/dotnet-api-docs/blob/792c515f3b6be9c7b44807644baccb8d9548a6d2/xml/System.Collections.Immutable/ImmutableList%601.xml#L565) says, "Gets an empty set with the default sort comparer."

To match [ImmutableArray&lt;T&gt;.Empty](https://github.com/dotnet/dotnet-api-docs/blob/792c515f3b6be9c7b44807644baccb8d9548a6d2/xml/System.Collections.Immutable/ImmutableArray%601.xml#L744), I think it should say, "Gets an empty immutable list."

**Comment by eiriktsarpalis** [comment]
Yep, that seems off. Would you be interested in contributing a PR that improves it?
