### ISSUE TITLE
[System.String.Split] StringSpiltOptions missing examples for .NET 5 and later

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/dotnet-api-docs#8133]
The [StringSplitOptions page](https://docs.microsoft.com/en-us/dotnet/api/system.stringsplitoptions?view=net-6.0) is missing an example of how to use `StringSplitOptions.RemoveEmptyEntries` and `StringSplitOptionsTrimEntries` in the same method.

An example should be crafted that uses the `|` or `'` characters to separate values, so there can be leading spaces, trailing spaces, and blank values in the string being split. It should also demonstrate using the correct syntax of:

```
var value = somestring.Split('|', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
```

I'm bringing this up because I used `StringSplitOptions.TrimEntries & StringSplitOptions.RemoveEmptyEntries` first and that didn't work.

**Comment by gewarren** [comment]
TrimEntries was added in https://github.com/dotnet/runtime/pull/35740.
