### ISSUE TITLE
Improve example for Enumerable.Skip<TSource> documentation

### ISSUE THREAD

**Issue by nedsalk** [dotnet/dotnet-api-docs#8144]
The current example is:
```csharp
int[] grades = { 59, 82, 70, 56, 92, 98, 85 };

IEnumerable<int> lowerGrades =
    grades.OrderByDescending(g => g).Skip(3);

Console.WriteLine("All grades except the top three are:");
foreach (int grade in lowerGrades)
{
    Console.WriteLine(grade);
}

/*
 This code produces the following output:

 All grades except the top three are:
 82
 70
 59
 56
*/
```

IMHO there is no need to add the `OrderByDescending` method as it's not relevant to the `Skip` functionality. It adds unnecessary mental burden. The proposed improved example is:

```csharp
int[] grades = { 59, 82, 70, 56, 92, 98, 85 };

Console.WriteLine("All grades except the first three:");
foreach (int grade in grades.Skip(3))
{
    Console.WriteLine(grade);
}

/*
 This code produces the following output:

All grades except the first three:
 56
 92
 98
 85
*/
```

**Comment by eiriktsarpalis** [comment]
While I agree it is not directly relevant, it is not obfuscating the example either. If anything, it does show that `Skip` can be used in combination with other LINQ methods (in case the reader didn't know this already).

**Comment by nedsalk** [comment]
@eiriktsarpalis Here's what led me to submitting this issue:
I was wanting to see if the `Skip` functionality works as I understood it works. I went to see the documentation and was met with the current example. The thought process was as follows:
"Okay, I have this array of numbers and I guess they're going to skip a number of elements and show the result. Let's see, they skipped the first three elements, so the first logged grade should be 56... What? Why is 82 the first one? Ah, they ordered it by descending... So now I have to order it in my head by descending or run the code in the console. Okay, I'll run it in the console, remove the `OrderByDescending` and see if the `Skip` behaves as I expected."

**Comment by gewarren** [comment]
What if we change the sequence to be pre-ordered? That way the example will still make sense (it doesn't really make sense to me to skip three random grades).

**Comment by nedsalk** [comment]
Given that the point of this documentation is first and foremost to show the `Skip` functionality, I'm of the opinion that anything which requires additional thinking not related to the actual functionality should be avoided. If the minimum example of logging the results of e.g. `{1, 2, 3, 4, 5, 6, 7, 8}.Skip(3)` is enough to get the point across of how the method works, I don't see the point in adding anything additional to the example - the functionality has been shown.

However you decide - thanks for the hard work, the language and its documentation are great. :)

**Comment by eiriktsarpalis** [comment]
I have no strong objections. If @gewarren agrees to the change then I'd be happy to look at a PR improving the docs.

**Comment by gewarren** [comment]
I have no strong objection either if you want to open a PR. I can see that each way has its pros and cons (the con of the suggested way is that it doesn't show how skip might be used in practice).

**Comment by eiriktsarpalis** [comment]
@nedsalk would you be interested in contributing?

**Comment by nedsalk** [comment]
@eiriktsarpalis Yes, sure. I can create a PR and set you as a reviewer.
