### ISSUE TITLE
Some method are not already available as public in HttpContent Class

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/dotnet-api-docs#8162]
https://github.com/dotnet/dotnet-api-docs/blob/7a80591780725ab7052a26cd9d971063938f6487/xml/System.Net.Http/HttpContent.xml#L392
Some methods of `HttpContent` abstract class are already internal and they are not public. These methods are internal and it is not clear what is their usage from Public point of view (I personally thought they are used by `SendAsync` method of `HttpClient` to write request content to TCP connection opened since there is already a method to read from it to stream for example!!)
1- `SerializeToStreamAsync`
2- `CreateContentReadStreamAsync`
3- `LoadIntoBufferAsync`
This method are not available in intellisense an they are internal according to Github open source of code. Is there any reason for presenting them in API documentations? 
Thanks

**Comment by abdollahkahne** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

I change the title to `HttpClient`. You can add the area to it or **http** for example! I hope this help you:|

**Comment by rzikm** [comment]
- SerializeToStreamAsync - (both overloads) are protected virtual, so if you create derived class from HttpContent, you have access to them
- CreateContentReadStreamAsync - same as above
- LoadIntoBufferAsync - is public according to git blame has been for at least 5 years

All of the methods show in intellisense for me. Can you provide more info regarding versions (VS and .NET version) where you are facing problems?

**Comment by abdollahkahne** [comment]
@rzikm I am searching for their usage which as you say it is used in creation of another HttpContent derived type.  I was thinking about the process which happen on sending request till receiving the response And I want to know role of these methods in this cycle. It is almost old for me but certainly learn me something new. 
Thanks for your response and It is helpful.
