### ISSUE TITLE
Remarks section for KeyGesture missing text

### ISSUE THREAD

**Issue by carpenterx** [dotnet/dotnet-api-docs#8196]
https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Windows.Input/KeyGesture.xml#L38

Line 38 contains a phrase that ends suddenly ("In general, you can"). I'm assuming there is some text content that is missing from this section.

**Comment by wenz** [comment]
I checked the history of that file - looks like the text is missing since 2017 when the documentation was added. I'd recommend just removing the "paragraph" since even the original author(s) might not remember what was in it.
