### ISSUE TITLE
Broken link to "Default WPF Themes"

### ISSUE THREAD

**Issue by PatrikBak** [dotnet/dotnet-api-docs#821]
The Default WPF Themes link is dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a526a5b0-8f94-a527-d706-797cb8590bed
* Version Independent ID: 6878b9d6-71dc-951f-e973-19df176540fa
* Content: [GridSplitter Class (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.gridsplitter?view=netframework-4.7.1)
* Content Source: [xml/System.Windows.Controls/GridSplitter.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/GridSplitter.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Kissaki** [comment]
It’s quite unfortunate there are invalid and misdirecting links. The documentation makes it seem like there is more information to be had, links to something, but then you have to figure out yourself that what you opened is not actually related to the documentation you followed at all.

IMO the documentation should remove those wrong links and reword what the surrounding text says, if it was specifically for/with the link. Especially so given that this has been open for almost a year, so there’s no indication for a fix to be soon - which is quite bad for misleading or wrong documentation.

I came here from the WPF `Control Styles and Templates` documentation. I did not check the other pages listed here for if they have the same kind of issue and context, and how much sense this suggestion makes there.

That page says (and links to a random/generic WPF sample repository):

> To get the resource dictionaries for the desktop themes, see _Default WPF Themes_.

In this case the sentence could simply be removed, as the information that there are resource dictionaries and what they are for (in this context) is mentioned in the sentence right before:

> The desktop themes determine which resource dictionary is used.

**Comment by gewarren** [comment]
#7638 fixes the links in this repo. The previously mentioned /dotnet/framework links have been resolved in the dotnet/docs-desktop repo.
