### ISSUE TITLE
"the error number may change"

### ISSUE THREAD

**Issue by ygoe** [dotnet/dotnet-api-docs#822]
From this page: https://docs.microsoft.com/en-us/windows/desktop/winsock/windows-sockets-error-codes-2

 "Note that this error is returned by the operating system, so the error number may change in future releases of Windows."

What does that mean? Should I revisit that page regularly to update my applications? Why should any of these values change? And why others not? Am I safe when using the SocketError enum?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adca59ab-df1d-37f0-bc69-50b603bbdf51
* Version Independent ID: 6361d39a-9367-429e-6f0a-e5d86e5a12f6
* Content: [SocketError Enum (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketerror?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.Sockets.SocketError.HostDown);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/SocketError.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/SocketError.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I'm moving this one to the backlog given we don't own this and can't control whether this is fixed or not.

**Comment by stevewhims** [comment]
The fix to the WinSock topic is now live. https://docs.microsoft.com/windows/desktop/winsock/windows-sockets-error-codes-2. That was the last bit of work that Ron was keeping the issue open for.

**Comment by mairaw** [comment]
Thank you @stevewhims! Closing the issue.
