### ISSUE TITLE
Indentation Error on System.Net.PreAuthenticate Example

### ISSUE THREAD

**Issue by brianb12321** [dotnet/dotnet-api-docs#8283]
# Steps to Reproduce
1. Navigate to https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.preauthenticate?view=net-6.0
2. Scroll down to section "Examples"
3. There is an indentation error on the line saying, `// Create a new webrequest to the mentioned URL.`

I can also create a PR for this issue if need be.

**Comment by gewarren** [comment]
> I can also create a PR for this issue if need be.

That would be great, thank you!

**Comment by brianb12321** [comment]
@gewarren Great! I will get to it ASAP.
