### ISSUE TITLE
XmlWriterSettings.NewLineChars defaults to "\n" on Linux, contrary to docs

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/dotnet-api-docs#8315]
### Description

On Linux, the default value of XmlWriterSettings.NewLineChars is "\n", even though the [documentation](https://docs.microsoft.com/dotnet/api/system.xml.xmlwritersettings.newlinechars?view=net-6.0) says it is "\r\n".

### Reproduction Steps

PowerShell 7.2.5 using .NET 6.0.6 on Debian:

```PowerShell
[System.Xml.XmlWriterSettings]::new().NewLineChars.GetEnumerator() | % { [int]$_ }
```

### Expected behavior

Should output

```
13
10
```

### Actual behavior

Outputs only

```
10
```

### Regression?

I don't know

### Known Workarounds

Assign XmlWriterSettings.NewLineChars after construction.

### Configuration

.NET 6.0.6 on Debian 11.3 amd64.
The issue does not occur on Windows.

### Other information

<https://github.com/dotnet/runtime/blob/7cca709db2944a09b4db6ca7b20c457ff260fb5a/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlWriterSettings.cs#L159-L160>

<https://github.com/dotnet/runtime/blob/7cca709db2944a09b4db6ca7b20c457ff260fb5a/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlWriterSettings.cs#L723>

**Comment by krwq** [comment]
@KalleOlaviNiemitalo if you're interested in contributing a fix click edit button on the documentation page. You might want to match description with https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline?view=net-6.0 or just say we use that as the default

**Comment by krwq** [comment]
You might want to search for NewLineChars in the xml folder: https://github.com/dotnet/dotnet-api-docs/tree/main/xml/System.Xml - there seem to be more places which might need update (some other samples etc)

**Comment by wenz** [comment]
Took a shot at it - hopefully I caught everything.
