### ISSUE TITLE
Documentation for File.Decrypt(String) Method is incorrect

### ISSUE THREAD

**Issue by paul1956** [dotnet/dotnet-api-docs#8322]
**Issue description**
Documentation says "If the file is not encrypted, [Decrypt](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.decrypt?view=net-6.0) will return a nonzero value, which indicates success."

Decript is a Sub and does not return anything. It would be great if it worked as documented but that is a different issue.
**Target framework**

- [ ] .NET Core

**Comment by adamsitnik** [comment]
@paul1956 you are right, it's a bug. Would you like to send a PR with a fix?

**Comment by paul1956** [comment]
@adamsitnik I have been unable to get it or any of the encryption API examples to work. Some reference MemoryProtectionScope which does not exist, and others say the API is obsolete. I am very new to encryption and can't get anything to work, so I have no idea how to correct the documentation.

**Comment by wenz** [comment]
I'd recommend just removing the sentence, since there is no return value. Took a quick shot at it.

**Comment by adamsitnik** [comment]
> I have been unable to get it or any of the encryption API examples to work.

I've just tried and I think that I've failed as well.

I've used following code:

<details>

```cs
using System;
using System.IO;

namespace FileEncryptDecrypt
{
    internal class Program
    {
        static void Main(string[] args)
        {
#if NET7_0
            if (!OperatingSystem.IsWindows())
            {
                return;
            }
#endif

            string contents = new string('a', 100);
            string encryptedFilePath = "encryptedFile.txt";
            string nonEncryptedFilePath = "nonEncryptedFile.txt";

            File.WriteAllText(encryptedFilePath, contents);
            File.WriteAllText(nonEncryptedFilePath, contents);

            try
            {
                File.Decrypt(nonEncryptedFilePath);
                Console.WriteLine("Decrypting non-encrypted file has NOT thrown.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Decrypting non-encrypted file has failed with: {ex.Message}.");
            }
            finally
            {
                File.Delete(nonEncryptedFilePath);
            }

            try
            {
                
                File.Encrypt(encryptedFilePath);

                string encrypted = File.ReadAllText(encryptedFilePath);

                if (encrypted == contents)
                {
                    Console.WriteLine("The file was not encrypted at all.");
                }
                else
                {
                    Console.WriteLine("The file got encrypted!");
                    Console.WriteLine($"Content before: {contents}");
                    Console.WriteLine($"Content  after: {encrypted}");
                }

                File.Decrypt(encryptedFilePath);
                string decrypted = File.ReadAllText(encryptedFilePath);

                if (encrypted == contents)
                {
                    Console.WriteLine("The file was succesfully decrypted.");
                }
                else
                {
                    Console.WriteLine("The file got decrypted, but contents differ!");
                    Console.WriteLine($"Content before: {contents}");
                    Console.WriteLine($"Content  after: {decrypted}");
                }
            }
            finally
            {
                File.Delete(encryptedFilePath);
            }
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net7.0</TargetFrameworks>
  </PropertyGroup>

</Project>
```

</details>

And got:

```log
PS C:\Users\adsitnik\source\repos\FileEncryptDecrypt> dotnet run -c Release -f net48
Decrypting non-encrypted file has NOT thrown.
The file was not encrypted at all.
The file was succesfully decrypted.
PS C:\Users\adsitnik\source\repos\FileEncryptDecrypt> dotnet run -c Release -f net7.0
Decrypting non-encrypted file has NOT thrown.
The file was not encrypted at all.
The file was succesfully decrypted.
```

I am using Windows 11 Enterprise, according to the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.encrypt?view=net-6.0):

> This method is not available on all versions of Windows. For example, it is not available on Home editions.

So I would either expect it to work or throw.

@bartonjs @GrabYourPitchforks @krwq am I doing something wrong or my understanding of how the APIs should work is wrong?

**Comment by paul1956** [comment]
The problem is you need to the documented result to successfully use the API. After decrypting, it might need to be re-encrypted but since the API isn't supported on all versions of windows that may fail.

**Comment by gewarren** [comment]
I tried @adamsitnik 's code and it does appear to work. Before the file is encrypted, it has a regular file icon, and after it's encrypted, the icon changes and it has a lock on it:

<img width="111" alt="image" src="https://github.com/dotnet/dotnet-api-docs/assets/24882762/5deb5d81-c35e-49b9-8da0-594849014a2e">
