### ISSUE TITLE
Doesn't work with Zip64 files

### ISSUE THREAD

**Issue by EbrahimMajdey** [dotnet/dotnet-api-docs#834]
The ZipArchive can't read any entry that is larger than 4,294,967,295 bytes .. which is the old limit for zip files although the OS can read this.. would appreciate if such capabilities is enabled instead of using other packages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a46d025-34f1-9ac4-6d29-a8e527cc5f91
* Version Independent ID: 5642d6cc-6abc-e662-bc03-d284ca9cb438
* Content: [ZipArchive Class (System.IO.Compression)](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.IO.Compression/ZipArchive.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Compression/ZipArchive.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by carlossanlop** [comment]
I think this was answered a long time ago, so we should close it.
