### ISSUE TITLE
SocketsHttpHandler.PooledConnectionIdleTimeout - Description

### ISSUE THREAD

**Issue by ahaleiii** [dotnet/dotnet-api-docs#843]
The description for this property is empty. What does it do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60aa45a1-13df-651d-a76e-272340101889
* Version Independent ID: 625861ca-de59-a421-bbd5-de2bae9f4f52
* Content: [SocketsHttpHandler.PooledConnectionIdleTimeout Property (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionidletimeout?view=netcore-2.1#System_Net_Http_SocketsHttpHandler_PooledConnectionIdleTimeout)
* Content Source: [xml/System.Net.Http/SocketsHttpHandler.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/SocketsHttpHandler.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rmkerr** [comment]
Here's the description listed in the code: `"How long a connection can have been idle in the pool to be considered reusable."`

I just took a look at the implementation, and it seems to be accurate. If a connection goes unused for > PooledConnectionIdleTimeout, requests will no longer be queued to that connection.

**Comment by caesar1995** [comment]
By default, the value is 120 seconds (2 minutes).

How do we update the docs?

**Comment by davidsh** [comment]
>How do we update the docs?

Submit a PR to this repo via the usual process (fork the repo, clone the repo, etc.).

I recently created a PR to update the documentation: #1544

**Comment by caesar1995** [comment]
Ok, I will take this issue and submit a PR.

**Comment by mairaw** [comment]
You can also just click edit on the API page and edit via the GitHub UI.

Properties are usually described as Gets or sets...
