### ISSUE TITLE
The description is ambiguous about ConcurrentDictionary<TKey,TValue> thread safety

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/dotnet-api-docs#8441]
At the end of [the document](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=net-7.0#thread-safety) says: 
```
All public and protected members of ConcurrentDictionary<TKey,TValue> are thread-safe and may be used   
concurrently from multiple threads.
```

But the document also says:
```
All these operations are atomic and are thread-safe with regards to all other operations on the 
ConcurrentDictionary<TKey,TValue> class.  The only exceptions are the methods that accept a delegate, that is, 
AddOrUpdate and GetOrAdd.
```
The **AddOrUpdate** and **GetOrAdd** method is not thread-safe, different places in the document are in conflict. If developers do not read the entire document, they could be under the illusion that all APIs of ConcurrentDictionary<TKey,TValue> are thread-safe.

**Comment by gewarren** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2?view=net-7.0#thread-safety

**Comment by eiriktsarpalis** [comment]
> All these operations are atomic and are thread-safe with regards to all other operations on the 
ConcurrentDictionary<TKey,TValue> class.  The only exceptions are the methods that accept a delegate, that is, AddOrUpdate and GetOrAdd.

I would say that this section is inaccurate. The delegate accepting methods _are_ thread-safe, however the delegates themselves are not invoked in a synchronized manner and could be invoked multiple times per operation. Assuming that the add/update delegates are not pure and somehow end up updating external user state in a non-synchronized manner, then it is possible that this state gets corrupted.

That being said, we should document that stateful add/update delegates are strongly discouraged and users should be using pure/static delegates instead.

**Comment by CwjXFH** [comment]
@eiriktsarpalis  
So, thread-safe means that even if the delegate is invoked multiple times, only one result of them will be used by the method, and atomic means the delegate is only invoked once, right?

```c#
ConcurrentDictionary<uint, uint> _stockObservers = new();

void Record(uint key)
{
    _stockObservers.AddOrUpdate(key, 1, (key, oldVal) => oldVal + 1);
}


Parallel.For(0, 10000, i =>
{
    Record(100);
});
```
The above code will execute correctly, right?

**Comment by eiriktsarpalis** [comment]
The methods perform atomic updates on the dictionary, so your example would work without problem. What is impacted in this case are update delegates that modify state, i.e.
```C#
ConcurrentDictionary<uint, uint> _stockObservers = new();
int totalUpdates = 0;

void Record(uint key)
{
    _stockObservers.AddOrUpdate(key, 1, (key, oldVal) => { Interlocked.Increment(ref totalUpdates) ; return oldVal + 1; });
}


Parallel.For(0, 10000, i => Record(100));
Console.WriteLine(totalUpdates); // Nondeterministic result, generally larger than the total number of insertions
```
