### ISSUE TITLE
Not !!!

### ISSUE THREAD

**Issue by PHuhn** [dotnet/dotnet-api-docs#852]
Intelli-sense says 
byte[]  System.Web.HttpServerUtility.UrlTokenDecode(string)
So what is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a625c136-577d-4872-de63-ec982e3fa173
* Version Independent ID: c0047e8a-d89b-d6ac-5387-ad0e1a0211f4
* Content: [HttpServerUtility.UrlDecode Method (System.Web)](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpserverutility.urldecode?redirectedfrom=MSDN&view=netframework-4.6.1#overloads)
* Content Source: [xml/System.Web/HttpServerUtility.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web/HttpServerUtility.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
It's not clear for me what's the issue here. @PHuhn do you remember what exactly was this? Otherwise, we should close this since I can't find the problem.
