### ISSUE TITLE
DirectoryInfo.GetDirectories does not list IOException

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/dotnet-api-docs#8544]
If, on a FAT32 partition, a corrupt file or directory entry exists, an `IOException` is thrown when calling `DirectoryInfo.GetDirectories()`:

```
System.IO.IOException: The file or directory is corrupted and unreadable. : 'D:\fakepath'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetDirectories()
   at <>.FileBrowserPageViewModel.GetAllFoldersAndFiles() in <>\ViewModels\FileBrowserPageViewModel.cs:line 695
```

This is not listed in the documentation:

![`DirectoryInfo.GetDirectories()` documentation as of Oct 21, 2022](https://user-images.githubusercontent.com/11381599/197263332-f73f2643-67f0-434c-89f0-e40be55b5cd6.png)

**Comment by colejohnson66** [comment]
Confirming it's caused by corrupt FAT entries. After running `chkdsk`, the exception no longer occurs

![Screenshot of `chkdsk D: /F` showing the removal of the corrupt directory](https://user-images.githubusercontent.com/11381599/197265313-097cc35d-2bc0-415a-ab55-52ed09b236aa.png)

**Comment by adamsitnik** [comment]
Hi @colejohnson66 

Thank you for a detailed bug report! Would you like to send a PR with docs update?

If you press following button on the docs page:

![image](https://user-images.githubusercontent.com/6011991/197507909-32d6dfb4-7e37-434f-aa84-1042060b006c.png)

It will take you to GitHub to appropriate file.

**Comment by colejohnson66** [comment]
@adamsitnik I considered it, but I'm unsure how to word it. "If a child file or folder contains a corrupt entry in the FAT/MFT" doesn't feel right.

**Comment by adamsitnik** [comment]
@colejohnson66 I've sent #8725, PTAL

**Comment by colejohnson66** [comment]
Looks fine to me
