### ISSUE TITLE
Span<T>(void* pointer, int length) ctor document null-pointer behaviour

### ISSUE THREAD

**Issue by fredrikhr** [dotnet/dotnet-api-docs#861]
What if the pointer passed in to the Span constructor is a null pointer (e.g. created from `IntPtr.Zero.ToPoiner()`)? It might be helpful to special case the documentation what the behaviour is in such cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12542bab-90d5-ee4f-fe42-3ad37dd133a1
* Version Independent ID: 1265f19b-bf12-ea32-0b5a-1bfae94b1be4
* Content: [Span&lt;T&gt; Constructor (System)](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.-ctor?view=netcore-2.1#System_Span_1__ctor_System_Void__System_Int32_)
* Content Source: [xml/System/Span`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Span`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by colejohnson66** [comment]
5 years later... It makes a `[ReadOnly]Span<T>` pointing to null with the specified length. That's pretty dangerous, but it is an unsafe method.

**Comment by colejohnson66** [comment]
Actually, it's pretty bad. It says, "[...] if the constructor succeeds in creating a new `Span<T>` object, all subsequent uses are correct." That is a boldfaced lie. `new Span<byte>((void*)(nint)0, 4096)` creates a `Span<T>` that will throw an `AccessViolationException` on any access. It is not "correct" to do so.

Perhaps it should say:

> This constructor should be used with care, since it creates arbitrarily typed `T`s from a `void*`-typed block of memory, and neither `pointer nor `length` are checked. However, if `pointer` and `length` point to a valid object, all subsequent uses are correct.
