### ISSUE TITLE
SHA256.ComputeHash is not thread safe

### ISSUE THREAD

**Issue by acouvert-msft** [dotnet/dotnet-api-docs#8620]
Concurrently computing hashes from a unique SHA256 engine is not reliable and will produce unexpected hashes as shown here: https://wanderingdeveloper.medium.com/c-cautionary-tail-the-dangers-of-sha256-reuse-2b5bb9c6fde9

The documentation should mention that it's not thread safe as a warning for developers. 

Documentation: ~~[hashdata](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.hashdata)~~ [computehash](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.computehash?view=netstandard-2.0#system-security-cryptography-hashalgorithm-computehash(system-byte()))
Source: ~~[SHA256](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Security.Cryptography/SHA256.xml)~~ [HashAlgorithm](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Security.Cryptography/HashAlgorithm.xml)

Similar limitations are probably true for other crypto engines as well.

**Comment by vcsjones** [comment]
> SHA256.HashData is not thread safe

That is not true. The static `HashData` method is thread safe. If it is not, then it is a bug.

> will produce unexpected hashes as shown here: https://wanderingdeveloper.medium.com/c-cautionary-tail-the-dangers-of-sha256-reuse-2b5bb9c6fde9

That blog post is talking about the instance-based member `ComputeHash`. It makes no mention of `HashData`. Instance members are generally assumed to be thread-unsafe unless explicitly documented otherwise.

**Comment by acouvert-msft** [comment]
My bad, like the link I provided, I was talking about `ComputeHash`: https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.computehash?view=netstandard-2.0#system-security-cryptography-hashalgorithm-computehash(system-byte())

I'm fine with the _"Instance members are generally assumed to be thread-unsafe unless explicitly documented otherwise."_ I was just surprised that this API was not thread safe and felt that it might be worth to emphasis this point as other people seems to be surprised by this as well.
