### ISSUE TITLE
[Intellisense doc] System.Net.Sockets.Socket.Close

### ISSUE THREAD

**Issue by viordash** [dotnet/dotnet-api-docs#8633]
### Description

I got an error when trying to send any remaining data because I set a timeout for Socket.Close in seconds based on the intellisense hint. 
Socket.Close method intellisense hint has message:
`timeout: Wait up to timeout seconds to send any remaining data, then close the socket.`
But in the [help for this method](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.close?view=net-7.0#system-net-sockets-socket-close) says that the timeout is in milliseconds.

To be sure, I checked the [source code](https://github.com/dotnet/runtime/blob/8918adf2e5255920aed3c61f9b92c2a51eec0fe3/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3209) and made sure that milliseconds is the correct unit of time.

NET Framework 4.8 (and probably older versions too) also has the wrong unit of time.

### Reproduction Steps

VS2022 (.NET6 Console app). Type `Socket.Close(1`
then see the intellisense hint

### Expected behavior

intellisense:
`timeout: Wait up to timeout milliseconds to send any remaining data, then close the socket.`

### Actual behavior

intellisense:
`timeout: Wait up to timeout seconds to send any remaining data, then close the socket.`

### Other information

:) Initially I tried to create a [PR ](https://github.com/dotnet/source-build-reference-packages/pull/478)but didn't carefully read the [README.md](https://github.com/dotnet/source-build-reference-packages)

**Comment by liveans** [comment]
In the .NET API Docs it says: `Wait up to timeout milliseconds to send any remaining data, then close the socket.`
But we can see it as `Wait up to timeout seconds to send any remaining data, then close the socket.` in the Intellisense.

@dotnet/docs @gewarren

**Comment by gewarren** [comment]
@liveans The IntelliSense is correct for .NET 7 projects. I don't think we retroactively update IntelliSense unfortunately.

![image](https://user-images.githubusercontent.com/24882762/202007243-ccfeee9b-906d-4303-8b1b-c9106f3cd1f2.png)

**Comment by antonfirsov** [comment]
This is strange, I always thought that the intellisense is just a copy of the API docs.

**Comment by liveans** [comment]
Triage: Looks like we're not updating IntelliSense retroactively as @gewarren said. It's fixed in 7.0 already, closing.
