### ISSUE TITLE
TrailingZeroCount / LeadingZeroCount

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/dotnet-api-docs#8640]
The base used for this count (base 2) should be specified in the docs.

I made tests for `Int64.TrailingZeroCount` with decimal numbers like 10, 1_000, 10_000 ... and it appears that by coincidence the binary equivalence has the same number of trailing zeroes for all powers of 10. But this is misleading, as e.g.  for 64 it returns 6.

**Comment by gfoidl** [comment]
> the same number of trailing zeroes for all powers of 10

Can you share how did you came to that conclusion?
See [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYAGAWAChqBGRxi5gTgAoAbCPAHMAdABUoAQwCWvKUIBaMKBADCEfBm7MAlNoDc7LnwEjx02QqWr1eTcxq6DTI/yFjJMuYMXK1GrTQO+oY8rqYeFt5WfrZaAPqBQU4coSbu5l4+1v72CYGOIcZuZp6WvjZ2gXlJbM48wXVF4Rll2bGojkA).
