### ISSUE TITLE
Enumerable.ToHashSet missing exception

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/dotnet-api-docs#8666]
Like all LINQ methods it throws `ArgumentNullException`

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Linq/Enumerable.xml

**Comment by tarekgh** [comment]
@OwnageIsMagic do you want to submit a PR for that?

**Comment by OwnageIsMagic** [comment]
@tarekgh I'm would be glad but, Enumerable.xml is too large to edit online and I currently have some problems with local git.
