### ISSUE TITLE
Cannot search API docs by .NET version / product

### ISSUE THREAD

**Issue by maxima120** [dotnet/dotnet-api-docs#8818]
Use case:

I am reading through Whats New in .NET 7
It does not mention for example new type `Int128`

I had to look at it here: https://learn.microsoft.com/en-us/dotnet/api/system.int128?view=net-7.0 
scrolling down to see supported versions which is '.NET 7' therefore I conclude its a new feature.

But I need to see all the new features. 

One way is to add all new classes to Whats New document
Another is to introduce filter in .NET API search where I can filter classes / methods / fields etc available in .NET 7 or later

**Comment by gewarren** [comment]
@maxima120 You can see all the API changes from .NET 6 to .NET 7 here: https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.0/api-diff/Microsoft.NETCore.App/7.0.0.md. Does that help?
