### ISSUE TITLE
Exception description of 'Dictionary<TKey,TValue>.TrimExcess(Int32)' missing property reference

### ISSUE THREAD

**Issue by TiltonJH** [dotnet/dotnet-api-docs#8822]
In [Dictionary<TKey,TValue>.TrimExcess(Int32)](https://learn.microsoft.com/dotnet/api/system.collections.generic.dictionary-2.trimexcess#system-collections-generic-dictionary-2-trimexcess(system-int32)) under Exceptions it reads
```
ArgumentOutOfRangeException
capacity is less than Dictionary<TKey,TValue>
```

I guess it should instead read:
```
ArgumentOutOfRangeException
capacity is less than Dictionary<TKey,TValue>.Count
```

**Comment by tarekgh** [comment]
@TiltonJH thanks for the report. Are you interested to submit a PR to fix this issue?

**Comment by ahmedtahami** [comment]
@tarekgh created pull request #8877 please verify!
