### ISSUE TITLE
Rename Parameter FileName in Directory.GetAccessControl Method Examples Documentation

### ISSUE THREAD

**Issue by pampas-gaucho** [dotnet/dotnet-api-docs#8831]
In the Examples section there are two Methods called:

        public static void AddDirectorySecurity(string FileName, string Account, FileSystemRights Rights, AccessControlType ControlType)
and
        public static void RemoveDirectorySecurity(string FileName, string Account, FileSystemRights Rights, AccessControlType ControlType)

Since this is a DirectoryExample, the Parameter "FileName" should be changed to "DirectoryName".

Seems that the snippet used is the same as File.GetAccessControl Method Example.

**Comment by adamsitnik** [comment]
@pampas-gaucho would you like to send a PR with a fix?
