### ISSUE TITLE
System.CommandLine "Applies To" section is empty

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#9005]
Example: https://learn.microsoft.com/en-us/dotnet/api/system.commandline.handler.sethandler#system-commandline-handler-sethandler-16(system-commandline-command-system-func((-0-1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-system-threading-tasks-task))-system-commandline-binding-ivaluedescriptor())

**Comment by gewarren** [comment]
This is fixed now. The reason is that the moniker wasn't set to "live".
