### ISSUE TITLE
SmtpClient is not disposed in doc

### ISSUE THREAD

**Issue by Bykiev** [dotnet/dotnet-api-docs#9048]
Refer to this docs: https://learn.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.sendcompleted?view=net-6.0

Only `MailMessage` is disposed, but `SmtpClient` is not disposing. I believe it should be correctly disposed.

**Comment by avinash-550** [comment]
Hi @adamsitnik, I would like to work on this issue.
