### ISSUE TITLE
Exception information for DateTime.Subtract(DateTime) is incorrect

### ISSUE THREAD

**Issue by markwhitaker** [dotnet/dotnet-api-docs#9051]
The exception information for [the `DateTime.Subtract(DateTime)` method](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.subtract?view=net-7.0#system-datetime-subtract(system-datetime)) incorrectly refers to the result of the operation being a `DateTime`. It seems to have been copied/pasted from the overloaded `DateTime.Subtract(TimeSpan)`:

> ## Exceptions
> `ArgumentOutOfRangeException`
> The result is less than `DateTime.MinValue` or greater than `DateTime.MaxValue`.

**Comment by tarekgh** [comment]
@markwhitaker thanks for reporting the issue. We need to delete the exception section from the doc as this API doesn't throw anyway. Are you interested in submitting a PR fixing it?

**Comment by markwhitaker** [comment]
> @markwhitaker thanks for reporting the issue. We need to delete the exception section from the doc as this API doesn't throw anyway. Are you interested in submitting a PR fixing it?

Sure!
