### ISSUE TITLE
TimeSpan.TotalMicroseconds and TimeSpan.TotalNanoseconds (NET7+) Remarks section displayed incorrectly

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/dotnet-api-docs#9058]
TimeSpan.TotalMicroseconds and TimeSpan.TotalNanoseconds (NET7+) Remarks section displayed incorrectly

https://learn.microsoft.com/en-us/dotnet/api/system.timespan.totalnanoseconds?view=net-7.0
https://learn.microsoft.com/en-us/dotnet/api/system.timespan.totalmicroseconds?view=net-7.0

**Comment by tarekgh** [comment]
@OwnageIsMagic are you interested in submitting a PR to fix the issue?

**Comment by OwnageIsMagic** [comment]
@tarekgh No

**Comment by tarekgh** [comment]
@OwnageIsMagic thanks for letting us know and for reporting the issue.
