### ISSUE TITLE
DataRowExtensions "nullable types" support clarity.

### ISSUE THREAD

**Issue by mdell-seradex** [dotnet/dotnet-api-docs#9077]
The [DataRowExtensions](/dotnet/dotnet-api-docs/tree/main/xml/System.Data/DataRowExtensions.xml) documentation states that a `DataSet` `does not support nullable types`, however it is really the `DataColumn` object that does not support this.
I recommend that it is changed to say `DataColumn` instead of `DataSet`, because some may think "I am using a DataTable, not a DataSet, so I can use nullable types", which would be untrue.  Note that in some cases, it uses the contraction "doesn't" instead of "does not".

There also seems to be an issue with some of the wording in the Remarks.  For example `If the underlying value in the 'DataSet' is 'Value', the returned nullable type will have a value of null`.  Note that I added single quotes around `Value` and `DataSet` because they are links.  As it turns out, the `Value` link actually points to [system.dbnull.value](https://learn.microsoft.com/en-us/dotnet/api/system.dbnull.value), but as stated, it appears to be confusing.  
The next statement says `If the value of the specified 'DataColumn' is null ...`.  Again `DataColumn` is quoted because it is a link.  This statement seems to be attempting to re-state the DBNull point, but is not doing it in a clear way.
If either of those were clear, then I think only one of them would be needed.

These statements appear multiple times on that page.

**Comment by roji** [comment]
@mdell-seradex thanks, opened #9080 to address these comments.
