### ISSUE TITLE
My PR fails checks: Some checks were not successful

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/dotnet-api-docs#9082]
My PR https://github.com/dotnet/dotnet-api-docs/pull/9081 have some strange checks error https://github.com/dotnet/dotnet-api-docs/pull/9081/commits/7d5c59687036b4916054eca9b7d98de21af81d22
```
Check failure on line 1 in snippets/visualbasic/VS_Snippets_CLR_System/system.globalization.numberformatinfo.currencynegativepattern/vb/currencynegativepattern1.vb
GitHub Actions / snippets-build

😵 Project missing. A project (and optionally a solution file) must be in this directory or one of the parent directories to validate and build this code.
```

How can I fix it?

**Comment by AlexRadch** [comment]
My PR generates some preview URLs:

https://review.learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=net-8.0&branch=pr-en-us-9081
https://review.learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=net-8.0&branch=pr-en-us-9081
https://review.learn.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=net-8.0&branch=pr-en-us-9081

But I don't have access. Can I get it? Or is it only for the Microsoft team?

**Comment by adamsitnik** [comment]
> Project missing. 

It's most likely causes by the fact that our infrastructure does not provide a project file for every code sample that we have in this repo.

I think it's safe to ignore, but @gewarren please correct me if I am wrong.

**Comment by gewarren** [comment]
> But I don't have access. Can I get it? Or is it only for the Microsoft team?

Unfortunately they are internal links only.

**Comment by gewarren** [comment]
We try to add any missing project files for small PRs like that so the automation can verify that code snippets compile. Adam has already added one, so I'll close this issue now.
