### ISSUE TITLE
Thanks to customer feedback, we have identified that Node.js developers would benefit from a new authentication approach that matches more closely their experience.

### ISSUE THREAD

**Issue by Toohott23** [dotnet/dotnet-api-docs#9089]
Thanks to customer feedback, we have identified that Node.js developers would benefit from a new authentication approach that matches more closely their experience.

Node.js developers tend to work in localhost environments that are deployed to the cloud, and are more often than not involved with the authentication of users in web servers.

This issue is to tie up the development of a new feature: a credential specifically designed for Node.js developers. This credential is initially called `WebRedirectCredential`.

This issue discusses the current approach for Node.js developers, then highlights the current challenges, and finally describes how `WebRedirectCredential` solves these challenges.

If you want to try out how the new design looks in comparison to the old design, I’m working on mocked tests here:

- [Mocked test with the current approach, the AuthorizationCodeCredential](https://github.com/sadasant/identity-browser-tests/blob/dev/AuthorizationCodeCredential/current/test/test.spec.ts).
- [Mocked test with the new approach, the WebRedirectCredential](https://github.com/sadasant/identity-browser-tests/blob/dev/AuthorizationCodeCredential/new/test/test.spec.ts).

## Current approach with AuthorizationCodeCredential

The current approach available for Node.js developers wanting to authenticate their end-users with Azure is to use the `AuthorizationCodeCredential`. This credential uses the [Authorization Code flow](https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow#1-get-an-authorization-code).

To authenticate with the `AuthorizationCodeCredential`, developers need to redirect their end-users to the `/authorize` endpoint, specifying a query parameters `response_type` with the value `code`, and `redirect_uri` with the escaped version of the redirect URI configured in the App Registration. They would have to do that themselves as the Identity SDK does not provide an intuitive way to go to this `/authorize` endpoint. Here is a sketch of the code the developers would need to write to go to this endpoint:

```ts
function getAuthorizeUrl(
  tenantId: string,
  clientId: string,
  scopes: string,
  state: string // IMPORTANT, see below
): string {
  const params = new URLSearchParams({
    client_id: clientId,
    response_type: "code",
    redirect_uri: redirectUri,
    scope: scopes,
    state,  // IMPORTANT, see below
  });
  const query = params.toString();
  return `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/authorize?${query}`;
}
```

> **IMPORTANT:**  
> The `state` parameter is necessary for backend apps to identify the metadata around the authentication. For example: the user ID, or the domain of the client application authenticating, in case more than one clients are being served by the same API.

The initial redirection can be made from the browser directly, or from the backend service. In either case, the redirection from Azure will include a `code` query parameter, which then can be used to initialize the `AuthorizationCodeCredential`.

Here's how it would look for Node.js users using Express:

```ts
app.get(
  "/azureLogin",
  async (req: express.Request, res: express.Response) => {
    // Probably authenticate (non-Azure) the user making this request...

    // Build the /authorize URI.
    const authorizeUrl = getAuthorizeUrl(
      tenantId,
      clientId,
      scope,
      session.username // EXAMPLE STATE
    );

    // Redirect the user.
    res.redirect(authorizeUrl);
  }
);
```

After the user finishes authenticating on Azure, it will redirect back to the `redirect_uri` provided. Only then, the backend service can initialize the `AuthorizationCodeCredential` with the received token.

```ts
app.get(
  "/azureResponse",
  async (req: express.Request, res: express.Response): Promise<void> => {
    // The redirect will either contain a "code" or an "error"
    const authorizationCode = req.query["code"];

    // Error handling will probably happen here...

    // If a "state" parameter was sent on the query of the /authorize request,
    // we would be able to receive it back here.
    const username = req.query["state"];

    // We could access and/or update a record on the database,
    // or on an in-memory cache...

    // With the code received, we can create the AuthorizationCodeCredential
    const credential = new AuthorizationCodeCredential(
      tenantId,
      clientId,
      authorizationCode as string,
      redirectUri
    );

    // Then we can retrieve a token calling to `getToken`,
    // or pass the credential to an SDK client, then use the client...

    // Then we should redirect users again to a page they can interact with:
    res.redirect("/");
  }
);
```

## Challenges of the current approach

1. No detailed authentication sample using `express`.
2. No way to get the `/authorize` URL through the `@azure/identity` package.
3. No notion of the `state` parameter, therefore no way to tie a redirect code with the authenticating user, or with the application the user is coming from.
4. No recommended way to cache the credential per user session (or the token).
5. No way to log out. Even if the user can create new credentials, we also don’t have a sample showing how to log out.

## Concept of a new approach

A new `WebRedirectCredential()`, provided through a new plugin package, `@azure/identity-web` or similar, can be used to solve all of these challenges.

```ts
const credential = new WebRedirectCredential(
  tenantId,
  clientId,
  redirectUri
);
```

It would have a `getRedirectUri` method:

```ts
app.get(
  "/azureLogin",
  async (req: express.Request, res: express.Response) => {
    // Here we authenticate...
    
    // Then we make the credential.
    const credential = new WebRedirectCredential(
      tenantId,
      clientId,
      redirectUri
    );

    // We save the credential in an in-memory cache, or not...
    // The sample will elaborate with recommended approaches.

    // We set something that can identify the user as the state parameter.
    const state = session.username; // or ID

    // We get the authorize URL.
    const authorizeUrl = credential.getRedirectUri(scope, {
      state,
    });

    // We redirect to it.
    res.redirect(authorizeUrl);
  }
);
```

It would allow retrieving the `authenticationRecord` with `authenticate()`, showcasing how to quickly store serialized info that can be used to retrieve the account from the cache:

```ts
app.get(
  "/azureResponse",
  async (req: express.Request, res: express.Response): Promise<void> => {
    const authorizationCode = req.query["code"];
    if (!authorizationCode) {
      // throw...
    }

    const username = req.query["state"];

    // Check that we're logged in, and that the state is valid...


    // Either retrieve the credential from in-memory cache, or:
    const credential = new WebRedirectCredential(
      tenantId,
      clientId,
      redirectUri
    );

    const authenticationRecord = await credential.authenticate(scope, authorizationCode);
    // save the authenticationRecord in a database or in-memory cache...

    // Go to home, or acknowledge the authentication has completed...
  }
);

// A separate endpoint that uses the Azure API:
app.get(
  "/me",
  async (req: express.Request, res: express.Response): Promise<void> => {
    // Check that we're logged in, and that we have authenticated before...

    // Retrieve the authentication record...
    // const authenticationRecord = //...

    const credential = new WebRedirectCredential(
      tenantId,
      clientId,
      redirectUri,
      { authenticationRecord }
    );

    // use the credential...
  }
);
```

_Originally posted by @sadasant in https://github.com/Azure/azure-sdk-for-js/issues/21045_

**Comment by adamsitnik** [comment]
If you have any comments regarding https://github.com/Azure/azure-sdk-for-js/issues/21045, please post them there.
