### ISSUE TITLE
Need more details ...

### ISSUE THREAD

**Issue by bdcoder2** [dotnet/dotnet-api-docs#909]
The documentation states: "...The TrySkipIisCustomErrors property is used only when your application is hosted in IIS 7.0...."; however, we are using this when hosted on IIS 8.5 and it works just fine -- some mention of other IIS versions should be made as it clearly works in 8.5.  The way it is written makes it sound like this property is ONLY available when hosted/running on IIS 7.0

Also -- if one sets the property to True or False does this effect ONLY the current request or the current requests AND all subsequent requests; that is, is this a global setting? (I am ASSUMING it is just for the current request) - correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df18659-579f-2ad8-3157-4d06d990fde7
* Version Independent ID: 50b331b7-641f-1d4a-d1b2-4138deb364eb
* Content: [HttpResponse.TrySkipIisCustomErrors Property (System.Web)](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.tryskipiiscustomerrors?view=netframework-4.6.2)
* Content Source: [xml/System.Web/HttpResponse.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web/HttpResponse.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@shirhatti can you help with this issue?

**Comment by shirhatti** [comment]
What Rick said, it's IIS 7 **and above**.

**Comment by mairaw** [comment]
@Rick-Anderson can you help with the fix?

**Comment by bdcoder2** [comment]
Do we have any tests that confirm that behavior?   If so, then it really needs to be stated in the documentation that setting the property to True effects ALL requests -- but I suspect it only effects the current request -- again, clarification needs to be added to the docs.
