### ISSUE TITLE
Incorrect description of `SafeBuffer.Read` in the `SafeBuffer.AcquirePointer` method

### ISSUE THREAD

**Issue by udaken** [dotnet/dotnet-api-docs#9097]
The following note on the [`SafeBuffer.AcquirePointer`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safebuffer.acquirepointer?view=net-7.0#remarks) method appears unnecessary.

> Unlike the [Read](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safebuffer.read?view=net-7.0) method, it does not change the current position of the pointer.

`SafeBuffer.Read` method has no such remark, and the "current position" does not change when checked by the test program.

```csharp
using System.IO.MemoryMappedFiles;

File.WriteAllBytes("a.bin", new byte[]{0x1, 0x02, 0x03});
using(var mmf =  System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile("a.bin"))
{
  using (var accessor = mmf.CreateViewAccessor())
  {
     Console.WriteLine( $"{accessor.SafeMemoryMappedViewHandle.Read<byte>(0):X}"); // 1
     Console.WriteLine( $"{accessor.SafeMemoryMappedViewHandle.Read<byte>(0):X}"); // 1
     Console.WriteLine( $"{accessor.SafeMemoryMappedViewHandle.Read<byte>(0):X}"); // 1
  }
}
```

_Originally posted by @udaken in https://github.com/dotnet/runtime/discussions/86752_

**Comment by ViktorHofer** [comment]
cc @agocke @AaronRobinsonMSFT @jkoritzinsky
