### ISSUE TITLE
Missing documentation for empty enumerables for Min, Max, MinBy, MaxBy

### ISSUE THREAD

**Issue by lilinus** [dotnet/dotnet-api-docs#9109]
### Description

Documentation doesn't specifu InvalidOperationException is thrown for methods below when values aren't nullable (i.e. non-nullable value types) and the enumerable argument is empty:
- Enumerable.Min
- Enumerable.Max
- Enumerable.MinBy
- Enumerable.MaxBy

**Comment by MichaelDeutschCoding** [comment]
Hey @lilinus , I've tried out some samples (I only actually tested `Enumerable.Min()` methods), and the reason the InvalidOperationException is not documented is because it's not thrown 😉

Nullable value types are valid to just return `null`, and that's what happens if the source sequence is empty.

```
var nullableSource = Enumerable.Empty<float?>();
// Does not throw, but returns null
var min = Enumerable.Min(nullableSource);

var nonNullableSource = Enumerable.Empty<float>();
// Throws InvalidOperationException - Sequence contains no elements
Enumerable.Min(nonNullableSource);
```

**Comment by lilinus** [comment]
Yeah exactly, what i meant isn't this supposed to be reflected in the documentation?

**Comment by lilinus** [comment]
Oh yes you are completely right. My bad, not sure how I missed it! Can we close this issue then?

**Comment by MichaelDeutschCoding** [comment]
I can't close it, I think only someone who's a project owner has permissions to close someone else's issue. But I'm pretty sure you should be able to 😇.
