### ISSUE TITLE
Incorrect description (copy-paste from Services property?)

### ISSUE THREAD

**Issue by andreasbuykx** [dotnet/dotnet-api-docs#9111]
https://github.com/dotnet/dotnet-api-docs/blob/15d7aa9863dafaca34a70794741fc13a0b154af4/xml/Microsoft.Extensions.Hosting/HostApplicationBuilder.xml#L146

Configuration holds a ConfigurationManager, not a collection of services.

**Comment by buyaa-n** [comment]
Thanks for reporting @andreasbuykx [put up a fix](https://github.com/dotnet/dotnet-api-docs/pull/9128)
