### ISSUE TITLE
Machine translation shouldn't be used for method names (French)

### ISSUE THREAD

**Issue by hadrienbecle** [dotnet/dotnet-api-docs#9124]
Hi :)

You can see it on this page: https://learn.microsoft.com/fr-fr/dotnet/api/system.runtime.caching.memorycache.add?view=dotnet-plat-ext-7.0

In the menu, method names are translated, when they should be ignored for machine translation.

![Screenshot of the menu on the Microsoft Learn website, with methods like 'Create' or 'Contains' translated in French as 'Ajouter' or 'Contient'](https://github.com/dotnet/dotnet-api-docs/assets/2971470/ca5e1428-a4eb-4101-b5a2-5ad7803a4196)

*Create* becomes *Ajouter*, *Contains* becomes *Contient*, etc.

**Comment by gewarren** [comment]
Thank you @hadrienbecle. I've logged an internal tracking item for the localization team: https://dev.azure.com/ceapex/CEINTL/_workitems/edit/910837.

**Comment by gewarren** [comment]
Closing as duplicate of #8814.
