### ISSUE TITLE
ActivityTraceId.ToHexString contradicts itself

### ISSUE THREAD

**Issue by dealloc** [dotnet/dotnet-api-docs#9136]
The documentation for `ActivityTraceId.ToHexString` contradicts itself:
![image](https://github.com/dotnet/dotnet-api-docs/assets/2164354/e0a862b5-0f4d-41cd-82f6-4cc78afc3a48)

see [link](https://learn.microsoft.com/en-us/dotnet/api/System.Diagnostics.ActivityTraceId.ToHexString?view=net-7.0)

**Comment by tarekgh** [comment]
Pasting the doc link: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitytraceid.tohexstring?view=net-7.0. 

@dealloc are you interested in submitting a PR to fix it? it should be `32-character`

**Comment by dealloc** [comment]
Sure, I can give it a go this weekend
