### ISSUE TITLE
Which of the `CngExportPolicies` value to use when one wants the key to be non-exportable? 

### ISSUE THREAD

**Issue by ralienpp** [dotnet/dotnet-api-docs#9159]
https://github.com/dotnet/dotnet-api-docs/blob/3854df0ff95bc26f339b5184b7cdb67bfc3276e1/xml/System.Security.Cryptography/CngExportPolicies.xml#L57

In the old CryptoAPI one could do this by NOT setting the `CRYPT_EXPORTABLE` flag when calling `CryptGenKey`. What would be the equivalent approach in CNG?

**Comment by Jozkee** [comment]
cc @bartonjs @vcsjones @dotnet/area-system-security.

**Comment by ralienpp** [comment]
Thanks for the feedback. This contradicts the documentation, which currently says `None | 0 | No export policies are established. Key export is allowed without restriction.`
