### ISSUE TITLE
Make Enumerable examples interactive

### ISSUE THREAD

**Issue by tchadwick** [dotnet/dotnet-api-docs#918]
In Bing, you have the ability to run the sample code it finds as a result.  So incorporating that technology into these docs so we can run the examples and play with them on the page with the documentation would be great for people learning how to use these methods and classes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d4a3e1d-3299-92ba-4ca2-040fd0452055
* Version Independent ID: 0068d1dc-81f6-7f2f-4277-a13792f6ea69
* Content: [Enumerable.Range(Int32, Int32) Method (System.Linq)](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.range?view=netframework-4.7.2)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
We have a big push to enable more interactive C# samples throughout our API docs. This page has the Run button enabled now and other Enumerable already have or are scheduled to have the Run button enabled.
