### ISSUE TITLE
WriteEventCore documentation specifies handling DateTime inconsistently

### ISSUE THREAD

**Issue by msnilsen** [dotnet/dotnet-api-docs#9246]
DateTime.MinValue causes arg.ToFileTimeUtc() to throw an exception.

When using mc.exe to translate a manifest specifying a Data element with inType="win:SYSTEMTIME" outType="xs:dateTime" to c# code, the generated code can handle DateTime.MinValue and it clamps the value to 0b11110000.

However, when using EventRegister to convert an EventSource class to a manifest, the manifest it builds uses inType="win:FILETIME" for a parameter of type DateTime. Then, when using mc.exe to translate that manifest to c#, it generates the code specified in this documentation:

```
long argFileTime = arg.ToFileTime();
userDataPtr[0].DataPointer = (UInt64)(&argFileTime);
userDataPtr[0].Size = (uint)(sizeof(long));
```

Which causes the code using this class to throw an exception instead of acting how it did previously, which was having the datetime clamped to the earliest systemtime.

**Comment by tarekgh** [comment]
CC @davmason
