### ISSUE TITLE
System.ServiceModel.Channels.ServiceChannelProxy should not be public

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#9276]
As reported here https://github.com/dotnet/dotnet-api-docs/pull/9245#issuecomment-1703563626

ServiceChannelProxy isn't a public type but it's listed in the docs as such. In the ServiceModel package there are a ref assembly and an implementation assembly. It's public in the implementation assembly as it needs (or needed I think from back in the UAP/UWP days) to work with DispatchProxy, but it's never been in the reference assembly. So we need to figure out why it is showing up in MS Docs.

cc @mconnew

**Comment by gewarren** [comment]
@huangmin-ms Do you know why this type is showing up in the ECMAXML? It is not in the reference assembly that mdoc ingested.

https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.servicechannelproxy?view=dotnet-plat-ext-7.0

**Comment by huangmin-ms** [comment]
@gewarren To pick up the reference assemblies, you can update the [csv](https://apidrop.visualstudio.com/_git/binaries?path=/dotnet/dotnet-plat-ext-7.0/dotnet-plat-ext-7.0.) from 
```
pac78,[tfm=net7.0;includeXml=false]System.ServiceModel.Primitives,6.0.0
```
to

```
pac78,[tfm=net7.0;libpath=ref;includeXml=false]System.ServiceModel.Primitives,6.0.0
```

**Comment by gewarren** [comment]
This has been resolved.
