### ISSUE TITLE
Sync MediaTypeNames docs from dotnet/runtime

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/dotnet-api-docs#9314]
This is a follow up on https://github.com/dotnet/dotnet-api-docs/pull/9301#issuecomment-1725010573: https://github.com/dotnet/runtime/pull/92220 had some changes that did not make into the dotnet-api-docs repo in #9301.

**Comment by rzikm** [comment]
This was fixed by https://github.com/dotnet/dotnet-api-docs/pull/9313. The comments are now in sync.
