### ISSUE TITLE
No content

### ISSUE THREAD

**Issue by ericrrichards** [dotnet/dotnet-api-docs#939]
So, where is the documentation?  I guess we're still at auto-generated stubs, without any of the old doc moved over.  
This is the top Google search result, so at least the SEO is working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81498c77-e953-d79b-d758-09e63edc61fd
* Version Independent ID: 51907d96-b483-143d-0462-45d3b3cd2b30
* Content: [Dictionary&lt;TKey,TValue&gt;.TryAdd(TKey, TValue) Method (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=netcore-2.1)
* Content Source: [xml/System.Collections.Generic/Dictionary`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/Dictionary`2.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by SvenJedeck** [comment]
???

**Comment by mairaw** [comment]
Sorry this hasn't been done yet but I'm working on several releases on the past couple of weeks. I'll get this added as soon as possible.

**Comment by mairaw** [comment]
Moving to the backlog until I can actually pick this up to start working on it. But I've marked this as P1 and it's still assigned to me.

**Comment by SeanKilleen** [comment]
I took first pass at this over on #2260. This seemed like a high priority so figured I'd try to help out.

**Comment by mairaw** [comment]
Really appreciated @SeanKilleen! ❤️ I'm reviewing your PR right now.
