### ISSUE TITLE
`Activator.CreateInstance` does not document `null` returns

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/dotnet-api-docs#9407]
**Issue description**

All overloads of [`Activator.CreateInstance`](https://learn.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=net-7.0) are documented as possibly returning `null`, but the situations where `null` could be returned are not documented.

Specifically, for the overloads taking a `System.Type`, "[a] reference to the newly created object" _implies_ that `null` will never be returned, but digging into the source shows the return types of all inner calls returning a possibly null `object?`. At the very bottom, `RuntimeType.CreateUninitializedObject` calls `_pfnAllocator`, which is a `delegate*` returning `object?`, but no comments to explain why.

*EDIT*: As pointed out by @vcsjones below, `null` is returned when the type is a `Nullable<T>`. Such behavior is documented, but is not obvious. See [my comment below](https://github.com/dotnet/dotnet-api-docs/issues/9407).

**Comment by gewarren** [comment]
@colejohnson66 Yes I'd be fine with such a PR. I would phrase it as "A reference to the newly created object, or <see langword="null"/> for <xref:System.Nullable%601> instances".
