### ISSUE TITLE
Selecting .NET 8.0 on .NET API Browser Page Displays APIs for .NET Aspire 8.0

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/dotnet-api-docs#9461]
If you go to the [.NET API Browser](https://learn.microsoft.com/en-us/dotnet/api/) page and select .NET > 8.0 from the APIs dropdown, the page displays APIs for .NET Aspire (query params = `?view=dotnet-aspire-8.0`).

This affects individual API topics for .NET as well, as selecting .NET 8.0 documentation for any .NET API shows " You have been redirected to the newest product version available for this page." and displays .NET 7.0 documentation instead. See [MethodImplOptions](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions) for an example.

**Comment by gewarren** [comment]
Thanks - this has been fixed now.
