### ISSUE TITLE
.NET API Browser Has Options for .NET 8 and .NET 8.0

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/dotnet-api-docs#9462]
If you go to the [.NET API Browser](https://learn.microsoft.com/en-us/dotnet/api/) page and click the API dropdown and select .NET, there are options for 8.0 and 8 shown. Selecting 8 will display content for .NET 8.0 RC2 instead of .NET 8.0.

**Comment by gewarren** [comment]
Thanks - this has been fixed now.
