### ISSUE TITLE
Old Xamarin content

### ISSUE THREAD

**Issue by davidbritch** [dotnet/dotnet-api-docs#9471]
If you look in the dotnet folder of the binaries repo, you'll see that API docs are being built for the System.* namespaces for xamarinandroid-7.1, xamarinios-10.8 and xamarinmac-3.0. This dates back to 2017. I'd guess that this was an attempt to show which of the System.* types/members could be used on the Xamarin platform (because not all of them can be used).

However, these versions of the product are no longer supported. Xamarin.Android is up to v14. Xamarin.iOS is up to v17, and Xamarin.Mac is up to v14 (I suspect there was a change of approach to version numbering at some point because there's no way it jumped from 3 to 14 in this timeframe). There's also .NET equivalent versions of these products.

If you look in OPS you'll see the following statuses for these monikers:

- xamarinandroid-7.1 - deprecated
- xamarinios-10.8 - live (but shouldn't be, xamarin-ios-sdk-12 is the latest moniker for published Xamarin.iOS API docs).
- xamarinmac-3.0 - live (but shouldn't be, xamarin-mac-sdk-14 is the latest moniker for published Xamarin.Mac API docs).

The Xamarin conceptual docs direct iOS users to the API docs at https://learn.microsoft.com/en-us/dotnet/api/uikit?view=xamarin-ios-sdk-12, rather than https://learn.microsoft.com/en-gb/dotnet/api/?view=xamarinios-10.8. Similarly, Mac users are directed to https://learn.microsoft.com/en-gb/dotnet/api/appkit.nstextblocklayer?view=xamarin-mac-sdk-14 rather than https://learn.microsoft.com/en-gb/dotnet/api/?view=xamarinmac-3.0.

I see three possible solutions here:

1. Update the binaries for the System.* namespaces to use the latest versions of the Xamarin products.

    OR

2. Delete the binaries/monikers for the System.* namespaces for the Xamarin products.

    OR

3. Delete the binaries/monikers for the System.* namespaces for the Xamarin products, and return to this for the .NET Android/iOS/Mac products at a later date.

I remain to be convinced about the value of (1). Currently, without having looked at any data, (2) or (3) would be my preferred option. This is also backed up by the difficulties in even updating the Xamarin.iOS/Mac API docs, or publishing new API docs for .NET iOS/Mac.

FYI @gewarren to start a discussion about this.

**Comment by rzikm** [comment]
@dotnet/area-system-runtime can you please have a look?

**Comment by gewarren** [comment]
I'm happy to just remove the monikers.

<img width="535" alt="image" src="https://github.com/dotnet/dotnet-api-docs/assets/24882762/95f13708-fe7a-4ea0-99ed-d3f8ca020129">

**Comment by davidbritch** [comment]
I've started an email thread with the Xamarin.iOS/Android teams about this, and shared page view data.

**Comment by davidbritch** [comment]
Emailed @jonpryor and @dalexsoto on 22nd Nov with page view data. No response.

**Comment by dalexsoto** [comment]
@davidbritch Looks like I missed the email, I am fine with 2 or 3. We can revisit this at a later date with .NET if we decide for 3.

**Comment by gewarren** [comment]
I've removed the affected binaries and also deprecated the following monikers:

xamarinios-10.8
xamarinmac-3.0
