### ISSUE TITLE
Socket.ReceiveBufferSize default value incorrect

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/dotnet-api-docs#9493]
https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.receivebuffersize?view=net-7.0#definition

> An [Int32](https://learn.microsoft.com/en-us/dotnet/api/system.int32?view=net-7.0) that contains the size, in bytes, of the receive buffer. The default is 8192.

Which is not `8192`.

![image](https://github.com/dotnet/dotnet-api-docs/assets/4510984/764aa64a-1e01-4192-8b6d-bf6fa1da3254)

**Comment by wfurt** [comment]
AFAIK we don't explicitly set anything when socket is created e.g.  the value comes from underlying OS. (and therefore may differ)
