### ISSUE TITLE
Is start 0 or 1 based?

### ISSUE THREAD

**Issue by AceHack** [dotnet/dotnet-api-docs#953]
so is start 1 equal to array[1] or array[0]?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12542bab-90d5-ee4f-fe42-3ad37dd133a1
* Version Independent ID: 1265f19b-bf12-ea32-0b5a-1bfae94b1be4
* Content: [Span&lt;T&gt; Constructor (System)](https://docs.microsoft.com/en-us/dotnet/api/system.span-1.-ctor?view=netcore-2.1#System_Span_1__ctor__0___System_Int32_System_Int32_)
* Content Source: [xml/System/Span`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Span`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by carlossanlop** [comment]
@Thraka I'm closing this issue (for reals now 😄), since you gave an answer.
