### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by MariusMyburg** [dotnet/dotnet-api-docs#954]
Hi. I have a .NET 4.5 project user System.IO.Ports.SerialPort, that I am converting to .NET Core.  However I do not see a Nuget package for System.IO.Ports that targets .NET Core 2.1 (or 2.0 for that matter). How do I add the proper references to my .NET Core 2.1 app to be able to use these calsses? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa765d00-19f8-74e4-4be1-1d7f1e7dc6ce
* Version Independent ID: 260749e3-69c6-a370-89b0-4f90d944fac7
* Content: [SerialPort Class (System.IO.Ports)](https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport?view=netcore-2.0)
* Content Source: [xml/System.IO.Ports/SerialPort.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Ports/SerialPort.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@MariusMyburg Please let me know if this is working for you?

**Comment by MariusMyburg** [comment]
Hi @Thraka , sorry for not letting you know, I did get it to work a while ago already. The mistake was mine, it was a silly mistake but unfortunately I cannot quite remember what I did wrong. Sorry I can not remember details - but I do know when I found the solution I wanted to kick myself.

**Comment by Thraka** [comment]
No worries! 😄
