### ISSUE TITLE
4.6.1 ReadLine example is for WriteLine 

### ISSUE THREAD

**Issue by APP-OYTEC** [dotnet/dotnet-api-docs#9628]
ReadLine example is for WriteLine
api/system.io.streamreader.readline
![image](https://github.com/dotnet/dotnet-api-docs/assets/96483364/97966026-187a-4f2e-9ba9-7cf5b07916fc)

**Comment by MihaZupan** [comment]
The sample shows how the `ReadLine` API can be used to read from a file.
The demo file happens to be generated via `WriteLine`, but that is not the focus of the sample.

```c#
using (StreamReader sr = new StreamReader(path))
{
    while (sr.Peek() >= 0)
    {
        Console.WriteLine(sr.ReadLine());
    }
}
```

**Comment by APP-OYTEC** [comment]
The current example don't do anything as it first deletes the file to be read. My suggestion is to remove the File.Delete and the  StreamWriter part of the example.

**Comment by APP-OYTEC** [comment]
Thanks MihaZupan, now I can see your point. Although the example is a bit confusing it's correct eventually.
Closing the issue
