### ISSUE TITLE
Questions about the definition of annotated frame

### ISSUE THREAD

**Issue by GameGameNoGG** [dotnet/dotnet-api-docs#9633]
From the doc,  If the stack frame has no instruction address (annotated frame) or the instruction address has no associated DkmModule, then GetInstructionSymbol will return null (S_FALSE in native code). Is that mean  `annotated frame ` == `the stack frame has no instruction address` ?
Doc: https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger.callstack.dkmstackwalkframe.getinstructionsymbol?view=visualstudiosdk-2022#microsoft-visualstudio-debugger-callstack-dkmstackwalkframe-getinstructionsymbol
Thanks in advance.

**Comment by gregg-miskelly** [comment]
> Is that mean annotated frame  == the stack frame has no instruction address?

Yes

**Comment by buyaa-n** [comment]
Looks answered. closing
