### ISSUE TITLE
There is an "Effect" property, but not an "Effects" property

### ISSUE THREAD

**Issue by spongyryno** [dotnet/dotnet-api-docs#9642]
DragEventArgs has an "Effect" property, but no "Effects" property. This web page shows the wrong one.

**Comment by MihaZupan** [comment]
Are you sure you are looking at the correct documentation page? There are multiple classes named `DragEventArg`:
- [`DragEventArgs.Effect` from `System.Windows.Forms.dll`](https://learn.microsoft.com/dotnet/api/system.windows.forms.drageventargs.effect)
- [`DragEventArgs.Effects` from `PresentationCore.dll`](https://learn.microsoft.com/dotnet/api/system.windows.drageventargs.effects)
