### ISSUE TITLE
HttpRequest.ContentLength should be of type long instead of int

### ISSUE THREAD

**Issue by alexis35115** [dotnet/dotnet-api-docs#9643]
Am i wrong but the documentation of `HttpRequest.ContentLength` should be of type `long` instead of type `int`?

https://learn.microsoft.com/en-us/dotnet/api/system.web.httprequest.contentlength?view=netframework-4.8.1&viewFallbackFrom=net-7.0

**Comment by MihaZupan** [comment]
The page you linked to is the `HttpRequest` class from `System.Web`. The [`ContentLength`](https://referencesource.microsoft.com/#System.Web/HttpRequest.cs,1280) there is indeed `int`.

Were you looking for [ASP.NET Core's `HttpRequest`](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.http.httprequest.contentlength#microsoft-aspnetcore-http-httprequest-contentlength)?

**Comment by alexis35115** [comment]
You are 100% right, i was wrong!
