### ISSUE TITLE
Method names are translated in menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/dotnet-api-docs#9655]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Method-names-are-translated-in-menu/10582201)._

---
https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.interlocked.increment?view=net-7.0

![image](https://github.com/dotnet/dotnet-api-docs/assets/45579687/0ec01524-2bda-4c83-9013-96881c44ca0a)

Estimated behaviour: Method names written in english always, independent of content language.

---
#### Feedback Bot on 2/11/2024, 01:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by gewarren** [comment]
[Internal work item](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/910837)

**Comment by gewarren** [comment]
Related to #9774, #8814.

**Comment by gewarren** [comment]
Thank you. This is a known issue and I hope it gets fixed soon. Closing as duplicate of #8814.
