### ISSUE TITLE
X509Certificate2.GetCertContentType can thow CryptographicException (undocumented)

### ISSUE THREAD

**Issue by dorssel** [dotnet/dotnet-api-docs#9669]
https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2.getcertcontenttype?view=net-8.0

This function throws `CryptographicException` (undocumented) when the input isn't parsable as any of the supported cryptographic input types.

**Comment by vcsjones** [comment]
This was fixed by https://github.com/dotnet/dotnet-api-docs/pull/10122, so I am going to mark this one as complete. Feel free to re-open the issue if you believe there are other issues or unaddressed concerns.
