### ISSUE TITLE
KeyNotFoundException not specified In Exceptions section in Dictionary<TKey,TValue>.IDictionary.Item[Object] Property

### ISSUE THREAD

**Issue by gejojimenez** [dotnet/dotnet-api-docs#9683]
In the Exceptions section of Dictionary<TKey,TValue>.IDictionary.Item[Object] Property, for .Net Framework versions, there should be KeyNotFoundException, that is thrown when specified Key is not a key of the dictionary.
Reading these page, it looks like there won't be any Exception when retrieving a value from dictionary if specified Key does not exist

**Comment by buyaa-n** [comment]
Looks the .NET Framework implementation https://referencesource.microsoft.com/#mscorlib/system/collections/generic/dictionary.cs,616 same as the .NET Core https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs,1249, both doesn't throw and returns null if key is not found, closing as won't fix
