### ISSUE TITLE
Misleading supported product version information

### ISSUE THREAD

**Issue by reyang** [dotnet/dotnet-api-docs#9771]
Take this document for example https://learn.microsoft.com/dotnet/api/system.diagnostics.activitysource#applies-to, it says the class applies to the following .NET versions which confused the users, because `ActivitySource` is also supported for .NET Framework 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, and 4.8.1.

![image](https://github.com/dotnet/dotnet-api-docs/assets/17327289/b21b5fce-5ced-4e32-adcf-87e25ada4139)

The expectation is that the doc lists out all the supported .NET (framework and core) runtime versions.

https://github.com/dotnet/dotnet-api-docs/blob/a31d8084d48828316dc6d0073de08e7562454bf3/xml/System.Diagnostics/ActivitySource.xml#L121-L125

This issue is specific to ActivitySource, but there seems to be a wider problem across the entire .NET docs.

**Comment by reyang** [comment]
@noahfalk @samsp-msft @tarekgh FYI.

**Comment by tarekgh** [comment]
@gewarren do you know who can help with this issue?

**Comment by gewarren** [comment]
@tarekgh In what way is `ActivitySource` also supported for .NET Framework 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, and 4.8.1?

**Comment by tarekgh** [comment]
@gewarren `ActivitySource` is a type defined in the library `System.Diagnostics.DiagnosticSource`. This library is targeting netcore, netstandard2.0, and netfx min supported versions (4.6.2). https://github.com/dotnet/runtime/blob/1fa699e9e82e96a7f4f1928f258984ce1cc38471/src/libraries/System.Diagnostics.DiagnosticSource/src/System.Diagnostics.DiagnosticSource.csproj#L4. 

Please look at https://apisof.net/catalog/c6b65dab-dea1-d234-e1b4-20597c5cbfae to see the supported platforms for this API.

**Comment by gewarren** [comment]
@tarekgh Ah, so this assembly is more like an extension? I agree that this is a confusing experience, and is tracked here: https://github.com/dotnet/dotnet-api-docs/issues/8405 (although there hasn't been any traction).

**Comment by tarekgh** [comment]
Is there any chance we get some traction on that? Users looks are complaining and think the APIs are not supported on netfx.

**Comment by gewarren** [comment]
I will push on it again. How common is it for core .NET libraries to also be available as NuGet packages that are supported on .NET Framework?

**Comment by tarekgh** [comment]
> I will push on it again. How common is it for core .NET libraries to also be available as NuGet packages that are supported on .NET Framework?

Thanks for helping with that. We have many libraries like that, a good example is `Microsoft.Extensions.x` libraries.

**Comment by gewarren** [comment]
This has been fixed now - see https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource?view=net-8.0#applies-to. LMK if you have any further suggestions about how the info is shown.

**Comment by tarekgh** [comment]
fantastic work @gewarren. Thanks a lot for taking care with that!
