### ISSUE TITLE
Colors by name

### ISSUE THREAD

**Issue by SlideRuleWes** [dotnet/dotnet-api-docs#9779]
The documentation links to a list of colors by name, but the names in that list do not match the names in the Color struct. Where can I see a palette of the colors in the struct? Why not add a thumbnail to each of the colors in the table?

---
[Associated WorkItem - 240289](https://dev.azure.com/msft-skilling/Content/_workitems/edit/240289)

**Comment by gewarren** [comment]
@SlideRuleWes Which API were you looking at? Is this table helpful? https://learn.microsoft.com/en-us/uwp/api/windows.ui.colors?view=winrt-22621#remarks

**Comment by SlideRuleWes** [comment]
@gewarren Yes, thank you! That is what I wanted. There ought to be a link to that table in the documentation for the Color struct (https://learn.microsoft.com/en-us/dotnet/api/system.drawing.color?view=net-8.0 ) instead of the link that is there now. At the end of the Remarks section ("For more information about these colors, see [List of colors by name](https://www.colorhexa.com/color-names)." points to a different table with different color names that is completely useless if a user is attempting to use the Color struct. Thank you!

**Comment by SlideRuleWes** [comment]
@gewarren , thank you!
