### ISSUE TITLE
IOException is not thrown if the directory exists

### ISSUE THREAD

**Issue by InteXX** [dotnet/dotnet-api-docs#9792]
If the directory exists, this function returns a `DirectoryInfo` instance for the directory. An `IOException` is not thrown in this case.

The documentation does not align with the behavior, for both online and offline versions.

**Comment by colejohnson66** [comment]
What method are you referencing? A few methods of `DirectoryInfo` claim to throw `IOException`.

**Comment by InteXX** [comment]
It looks like something went haywire during topic linking, and the reference to the actual online doc was lost when I created this issue. It appears that the GitHub issue creation page is ignoring the query string. This might be a bug of its own.

In any case, I got here by first viewing this topic:

https://learn.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.createsubdirectory

...and then by clicking the [Open a documentation issue](https://github.com/dotnet/dotnet-api-docs/issues/new?&pageUrl=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fapi%2Fsystem.io.directoryinfo.createsubdirectory%3Fview%3Dnet-8.0&pageQueryParams=%3Fview%3Dnet-8.0&contentSourceUrl=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdotnet-api-docs%2Fblob%2Fmain%2Fxml%2FSystem.IO%2FDirectoryInfo.xml&documentVersionIndependentId=d22917ff-d777-8c62-4c69-49720b856091&feedback=%0A%0A%5BEnter+feedback+here%5D%0A&author=%40dotnet-bot&metadata=*+ID%3A+b47a618c-acf6-33c9-01b6-348b4d577d7e+%0A*+Service%3A+**dotnet-api**%0A*+Sub-service%3A+**system.io**) link at the bottom of the page.

It's this method that I'm referring to. If the directory to be created already exists, an `IOException` isn't thrown as otherwise advertised in both the online and offline documentation.

**Comment by colejohnson66** [comment]
You're reading the documentation wrong. You are correct that `CreateSubdirectory("X")` does not throw if `X` already exists. However, the documentation says `IOException` will be thrown if (emphasis mine) "a _file_ already has the name specified by path." It throws if a _file_ with that name exists because you can't have a file and a directory with the same name.

For example, if a file with the name `temp` exists, `CreateSubdirectory("temp")` will throw.

**Comment by InteXX** [comment]
Oops, you are correct! I missed that little detail.

OK, thanks for your time.
