### ISSUE TITLE
ConnectionRefused	1006: El host remoto rechaza activamente una conexión.

### ISSUE THREAD

**Issue by EmmanuelNuvigant** [dotnet/dotnet-api-docs#9821]
Trabajo en un backend local y al hacer una peticion rechaza el localhost que quiero iniciar:
System.Net.Http.HttpRequestException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión. (localhost:5051)
 ---> System.Net.Sockets.SocketException (10061): No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

**Comment by wfurt** [comment]
that means you are connecting to something that does not run. e.g. there is no service listening on port 5051 or they access is blocked by firewall.
