### ISSUE TITLE
Help and support

### ISSUE THREAD

**Issue by daemi1212** [dotnet/dotnet-api-docs#9857]
while I am using different FRP bypass tools my PC showing me the message "system.security.cryptography.x509certificatecollection system.net.http.httpclienthandler.getclientcertificate" what can I do? I installed dot.net full version but not working. my OS is Windows 10 64 bit

**Comment by ManickaP** [comment]
Could you share more details? Repro code? What is showing the message? What steps have you done? What version of .NET are you using?

**Comment by vcsjones** [comment]
I am going to close this as there no additional information provided. Please feel free to re-open this issue, or create a new issue with the additionally provided information.
