### ISSUE TITLE
Incomplete statement "If the source sequence contains only values that are null."

### ISSUE THREAD

**Issue by ClaudioFriederich** [dotnet/dotnet-api-docs#9858]
The statement "If the source sequence contains only values that are null." is incomplete.  If the source sequence contains only values that are null then what happens?

---
[Associated WorkItem - 261122](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261122)

**Comment by MichaelDeutschCoding** [comment]
@ClaudioFriederich , do you recall what pages you noticed this on? I opened an issue #9881 for `Enumerable.MinBy` and `Enumerable.MaxBy` -- but I don't know if you had seen this on any other pages (as well)?

**Comment by gewarren** [comment]
Oops, looks like it happened here: https://github.com/dotnet/dotnet-api-docs/commit/8d6482e5f19402e7e6ec7062bb7173a2dee1f8a8.
