### ISSUE TITLE
TimeZone used in example while Visual Studio C# .NET 8.0 indicates its obsolete?

### ISSUE THREAD

**Issue by stickneyar** [dotnet/dotnet-api-docs#9861]
[Edit by gewarren] Doc in question: https://learn.microsoft.com/en-us/dotnet/api/system.timezone.currenttimezone?view=net-8.0#examples

**Comment by ManickaP** [comment]
Which example? Can you share the code?

**Comment by stickneyar** [comment]
This is the link to the Microsoft documentation 

TimeZone.CurrentTimeZone Property (System)

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
TimeZone.CurrentTimeZone Property (System)

Gets the time zone of the current computer.
 |

 |

 |


If you copy the code and try to run it in Visual Studio C# WPF, the obsolete error occurs. Thanks


    On Monday, April 29, 2024 at 03:13:57 a.m. EDT, dotnet-policy-service[bot] ***@***.***> wrote:  
 
 


Tagging subscribers to this area: @dotnet/area-system-runtime

**Comment by gewarren** [comment]
This is confusing because the TimeZone type is marked obsolete in source code, but not its members, so they don't automatically get the obsolete note block. There's an internal work item tracking this.
