### ISSUE TITLE
Misleading "Applies to" Section for Json Serialization

### ISSUE THREAD

**Issue by mariesophie** [dotnet/dotnet-api-docs#9868]
I wanted to use the [JsonDerivedType](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonderivedtypeattribute?view=net-6.0) or [JsonPolymorphic](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonpolymorphicattribute?view=net-6.0) attribute in a .NET 6 project. So I looked it up at the docs (see links) and was happy, because they are listed as available since .NET 6.
I tried, but couldn't even get the code to compile. Finally, I found the [Learn .NET section](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-6-0) about json serialization again, where both of them seem to be available only in .NET 7 or later.

Is there a way to get the attributes working in .NET 6, is my understanding of the "applies to" section skewed or is it a mishap in the documentation?

**Comment by gewarren** [comment]
@mariesophie For .NET 6, the APIs are available through the following package: https://www.nuget.org/packages/System.Text.Json/8.0.3.

**Comment by gewarren** [comment]
Related to #8405, #9771.

**Comment by mariesophie** [comment]
Oh, thanks, that's good to know. I like your [proposal](https://github.com/dotnet/dotnet-api-docs/issues/8405#issuecomment-1769514798), which clarifies whether the attribute (in this case) or whatever function is builtin or package-provided.
One of the referenced links also guided me to the [APIs of .net catalog](https://apisof.net/catalog/aa534942df66ac16a22702b93272eacb), which is another help.

**Comment by gewarren** [comment]
@mariesophie Thanks for reminding me that there's still some work needed in the Applies to section. I've logged an [internal work item](https://dev.azure.com/ceapex/Engineering/_queries/edit/969126) for that.

**Comment by carlossanlop** [comment]
Since we have an internal work item, I think it's safe to close this issue. @mariesophie thanks for reporting the issue, please open a new one if you have additional questions.
