### ISSUE TITLE
What?

### ISSUE THREAD

**Issue by b9chris** [dotnet/dotnet-api-docs#987]
This is not documentation. What does this page add that I couldn't glean from the method name and param types?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc360a3c-2d36-b46e-2ac4-07627f090026
* Version Independent ID: 622c3dbd-df0f-f443-a43f-8c4ae674180d
* Content: [MemoryExtensions.SequenceCompareTo Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.memoryextensions.sequencecompareto?view=netcore-2.1)
* Content Source: [xml/System/MemoryExtensions.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/MemoryExtensions.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This has been fixed since then.
