### ISSUE TITLE
GitHub bug report link does not work

### ISSUE THREAD

**Issue by rklec** [dotnet/dotnet-api-docs#9886]
## STR

1. Go to https://learn.microsoft.com/de-de/dotnet/api/system.directoryservices.searchscope?view=dotnet-plat-ext-8.0#gilt-f-r-
2. Click on "Problem in der Dokumentation öffnen" (aka "Open issue in documentation" at the bottom of the page that explains .NET is open-source:
   ![grafik](https://github.com/dotnet/dotnet-api-docs/assets/71322635/37ef7d46-32ea-4b8f-afa8-459c8a86fdff)
3. The link is https://github.com/dotnet/dotnet-api-docs/issues/new?&pageUrl=https%3A%2F%2Flearn.microsoft.com%2Fde-de%2Fdotnet%2Fapi%2Fsystem.directoryservices.searchscope%3Fview%3Ddotnet-plat-ext-8.0&pageQueryParams=%3Fview%3Ddotnet-plat-ext-8.0&contentSourceUrl=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdotnet-api-docs%2Fblob%2Fmain%2Fxml%2FSystem.DirectoryServices%2FSearchScope.xml&documentVersionIndependentId=4b28885c-3c58-200b-7183-672a67d173e2&feedback=%0A%0A%5BHier+Feedback+eingeben%5D%0A&author=%40dotnet-bot&metadata=*+ID%3A+342e2666-9bf7-f7e9-aae8-e400e62bd958+%0A*+Service%3A+**dotnet-api**%0A*+Sub-service%3A+**system.directoryservices**, which opens a new GitHub issue form.

**Edit:** Same/also reproducible [on English page](https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.searchscope?view=net-8.0&viewFallbackFrom=dotnet-plat-ext-8.0#felder) [with this link](https://github.com/dotnet/dotnet-api-docs/issues/new?&pageUrl=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fapi%2Fsystem.directoryservices.searchscope%3Fview%3Dnet-8.0%26viewFallbackFrom%3Ddotnet-plat-ext-8.0%23felder&pageQueryParams=%3Fview%3Dnet-8.0%26viewFallbackFrom%3Ddotnet-plat-ext-8.0&contentSourceUrl=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdotnet-api-docs%2Fblob%2Fmain%2Fxml%2FSystem.DirectoryServices%2FSearchScope.xml&documentVersionIndependentId=4b28885c-3c58-200b-7183-672a67d173e2&feedback=%0A%0A%5BEnter+feedback+here%5D%0A&author=%40dotnet-bot&metadata=*+ID%3A+342e2666-9bf7-f7e9-aae8-e400e62bd958+%0A*+Service%3A+**dotnet-api**%0A*+Sub-service%3A+**system.directoryservices**).

### What happens
However, that form is empty.

### What should happen
As I suspect from that URL, it should contain some pre-filled information to ease reporting.

## System

Firefox 125.0.3
Windows 10

**Comment by gewarren** [comment]
This has been fixed, and the article info is prepopulated now. Thanks for reporting.
