### ISSUE TITLE
Behavior of '?' Wildcard in Directory.GetFiles

### ISSUE THREAD

**Issue by trevwilson16** [dotnet/dotnet-api-docs#989]
For .NET Core 2.1, the '?' wildcard is documented as matching "Zero or one character in that position", but it seems to actually be matching "Exactly one character in that position". Given the typical behavior of '?' in regex and wildcard searches, this feels like it could be an issue with the implementation rather than the documentation, so I wanted to check before requesting a docs change.

Output of sample program showing the issue:
```
# dotnet run
Search pattern 'file?name.txt' returned 1 results:
        C:\Test\file_name.txt

Search pattern 'file*name.txt' returned 3 results:
        C:\Test\filename.txt
        C:\Test\file_name.txt
        C:\Test\file__name.txt
```

.NET Core Info:
```
# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

And for the record the dir command behaves the same way, so maybe this is expected behavior:
```
# dir /B
filename.txt
file_name.txt
file__name.txt

# dir /B file?name.txt
file_name.txt

# dir /B file*name.txt
filename.txt
file_name.txt
file__name.txt
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be5663f7-3d2a-e997-7b92-be71df72f101
* Version Independent ID: 111b99c7-202a-c2ec-9a88-ae3cf4836309
* Content: [Directory.GetFiles Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=netcore-2.1)
* Content Source: [xml/System.IO/Directory.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Directory.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LanceUMatthews** [comment]
This puzzled me as well why that description doesn't match the behavior, at least on Windows.  Following the chain of calls I find...

1. [`Directory.GetFiles(string)`](https://github.com/dotnet/runtime/blob/87919a0462bc2ebd5c256e5ad7649ff98c858e2c/src/libraries/System.IO.FileSystem/src/System/IO/Directory.cs#L139)
2. [`Directory.GetFiles(string, string, EnumerationOptions)`](https://github.com/dotnet/runtime/blob/87919a0462bc2ebd5c256e5ad7649ff98c858e2c/src/libraries/System.IO.FileSystem/src/System/IO/Directory.cs#L146)
3. [`Directory.InternalEnumeratePaths(string, string, SearchTarget, EnumerationOptions)`](https://github.com/dotnet/runtime/blob/87919a0462bc2ebd5c256e5ad7649ff98c858e2c/src/libraries/System.IO.FileSystem/src/System/IO/Directory.cs#L169)
4. [`FileSystemEnumerableFactory.UserFiles(string, string, EnumerationOptions)`](https://github.com/dotnet/runtime/blob/87919a0462bc2ebd5c256e5ad7649ff98c858e2c/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerableFactory.cs#L121)
5. [`FileSystemEnumerableFactory.MatchesPattern(string, ReadOnlySpan<char>, EnumerationOptions)`](https://github.com/dotnet/runtime/blob/87919a0462bc2ebd5c256e5ad7649ff98c858e2c/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerableFactory.cs#L108)
6. [`FileSystemName.MatchesWin32Expression(ReadOnlySpan<char>, ReadOnlySpan<char>, bool)`](https://github.com/dotnet/runtime/blob/87919a0462bc2ebd5c256e5ad7649ff98c858e2c/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemName.cs#L90)
7. [`FileSystemName.MatchPattern(ReadOnlySpan<char>, ReadOnlySpan<char>, bool, bool)`](https://github.com/dotnet/runtime/blob/87919a0462bc2ebd5c256e5ad7649ff98c858e2c/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemName.cs#L159)

...the last of which is [commented as such](https://github.com/dotnet/runtime/blob/96d9a47228b0412945d151a79af7bf66463b053a/src/libraries/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemName.cs#L149)...
```
//   In words:
//
//       * matches 0 or more characters.
//       ? matches exactly 1 character.
```
Note that this same "Zero or one character in that position." (or, alternatively, "Exactly zero or one character.") language is used to describe the question mark wildcard character in all `Directory*.Get*s()` and `Directory*.Enumerate*s()` method overloads that take a `searchPattern` parameter...

1. [`Directory.EnumerateDirectories(...)`](https://docs.microsoft.com/dotnet/api/system.io.directory.enumeratedirectories)
2. [`Directory.EnumerateFiles(...)`](https://docs.microsoft.com/dotnet/api/system.io.directory.enumeratefiles)
3. [`Directory.EnumerateFileSystemEntriess(...)`](https://docs.microsoft.com/dotnet/api/system.io.directory.enumeratefilesystementries)
4. [`Directory.GetDirectories(...)`](https://docs.microsoft.com/dotnet/api/system.io.directory.getdirectories)
5. [`Directory.GetFiles(...)`](https://docs.microsoft.com/dotnet/api/system.io.directory.getfiles)
6. [`Directory.GetFileSystemEntries(...)`](https://docs.microsoft.com/dotnet/api/system.io.directory.getfilesystementries)
7. [`DirectoryInfo.EnumerateDirectories(...)`](https://docs.microsoft.com/dotnet/api/system.io.directoryinfo.enumeratedirectories)
8. [`DirectoryInfo.EnumerateFiles(...)`](https://docs.microsoft.com/dotnet/api/system.io.directoryinfo.enumeratefiles)
9. [`DirectoryInfo.EnumerateFileSystemInfos(...)`](https://docs.microsoft.com/dotnet/api/system.io.directoryinfo.enumeratefilesysteminfos)
10. [`DirectoryInfo.GetDirectories(...)`](https://docs.microsoft.com/dotnet/api/system.io.directoryinfo.getdirectories)
11. [`DirectoryInfo.GetFiles(...)`](https://docs.microsoft.com/dotnet/api/system.io.directoryinfo.getfiles)
12. [`DirectoryInfo.GetFileSystemInfos(...)`](https://docs.microsoft.com/dotnet/api/system.io.directoryinfo.getfilesysteminfos)

At 3 such overloads for each of the above methods, that makes for **36 method overloads** documented this way.

**Comment by danmoseley** [comment]
Docs are wrong. thanks for fixing them.
