### ISSUE TITLE
Drake Accounting issue

### ISSUE THREAD

**Issue by IffayOlaniyi** [dotnet/dotnet-api-docs#9949]
i was working on Drake accounting to restore a client file but i receivedan error message saying "Unhandled exception has occured. if you click continue, the application will ignore the error and attempt to continue. if you click quit, the application will close immediately. I have the details below also. I have also tried using visual code to debug but i still couldnt get the application to open. is there anything else i can do. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Data.SqlServerCe.SqlCeException (0x80004005): The specified table already exists. [ ActTransHistory ]
   at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.AsNoTracking()
   at System.Data.Entity.Infrastructure.DbQuery`1.AsNoTracking()
   at DrakeAccounting.ORM.ClientFileEF.ClientInfoCache.get_ClientInfo()
   at DrakeAccounting.frmMainTree.setNodes()
   at DrakeAccounting.frmMainTree.SetupUser()
   at DrakeAccounting.frmMainTree.frmMainTree_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DrakeAccounting2022
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/DrakeAccounting2022.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9220.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DrakeAccountingORM2022
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingORM2022.DLL
----------------------------------------
DrakeAccountingCommon
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingCommon.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/DrakeAccounting2022/dll/System.Resources.Extensions.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/DrakeAccounting2022/dll/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/DrakeAccounting2022/dll/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/DrakeAccounting2022/dll/System.Numerics.Vectors.DLL
----------------------------------------
EntityFramework
    Assembly Version: 6.0.0.0
    Win32 Version: 6.400.420.21404
    CodeBase: file:///C:/DrakeAccounting2022/dll/EntityFramework.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DrakeAccountingBooks2022
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingBooks2022.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
EntityFramework.SqlServerCompact
    Assembly Version: 6.0.0.0
    Win32 Version: 6.400.420.21404
    CodeBase: file:///C:/DrakeAccounting2022/dll/EntityFramework.SqlServerCompact.DLL
----------------------------------------
EntityFramework.SqlServer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.400.420.21404
    CodeBase: file:///C:/DrakeAccounting2022/dll/EntityFramework.SqlServer.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.OracleClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data.OracleClient/v4.0_4.0.0.0__b77a5c561934e089/System.Data.OracleClient.dll
----------------------------------------
System.Data.SqlServerCe
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.8876.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Data.SqlServerCe/4.0.0.0__89845dcd8080cc91/System.Data.SqlServerCe.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
EntityFrameworkDynamicProxies-DrakeAccountingORM2022
    Assembly Version: 1.0.0.0
    Win32 Version: 6.400.420.21404
    CodeBase: file:///C:/DrakeAccounting2022/dll/EntityFramework.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DevExpress.Utils.v21.1
    Assembly Version: 21.1.6.0
    Win32 Version: 21.1.6.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DevExpress.Utils.v21.1.DLL
----------------------------------------
DevExpress.Data.v21.1
    Assembly Version: 21.1.6.0
    Win32 Version: 21.1.6.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DevExpress.Data.v21.1.DLL
----------------------------------------
DevExpress.XtraEditors.v21.1
    Assembly Version: 21.1.6.0
    Win32 Version: 21.1.6.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DevExpress.XtraEditors.v21.1.DLL
----------------------------------------
DevExpress.Data.Desktop.v21.1
    Assembly Version: 21.1.6.0
    Win32 Version: 21.1.6.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DevExpress.Data.Desktop.v21.1.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/DrakeAccounting2022/dll/Newtonsoft.Json.DLL
----------------------------------------
DrakeAccountingPortalSync
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingPortalSync.DLL
----------------------------------------
Patagames.Pdf
    Assembly Version: 9.66.36.48
    Win32 Version: 9.66.36.48
    CodeBase: file:///C:/DrakeAccounting2022/dll/Patagames.Pdf.DLL
----------------------------------------
DrakeAccountingFormsCore
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingFormsCore.DLL
----------------------------------------
DrakeAccountingPortalsProxy
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingPortalsProxy.DLL
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DrakeAccountingReportsCore
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingReportsCore.DLL
----------------------------------------
DrakeAccountingFinancial
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingFinancial.DLL
----------------------------------------
DrakeAccountingFinancialCommon
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingFinancialCommon.DLL
----------------------------------------
DrakeAccountingDASMapping2022
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingDASMapping2022.DLL
----------------------------------------
DrakeAccountingEmployee
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingEmployee.DLL
----------------------------------------
DrakeAccountingPayroll
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingPayroll.DLL
----------------------------------------
DrakeAccountingTaxDeposit
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingTaxDeposit.DLL
----------------------------------------
DrakeAccountingBookkeeping
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingBookkeeping.DLL
----------------------------------------
DrakeAccountingAP
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingAP.DLL
----------------------------------------
DrakeAccountingAR
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingAR.DLL
----------------------------------------
DrakeAccountingEFilings
    Assembly Version: 2.38.0.0
    Win32 Version: 2.38.0.0
    CodeBase: file:///C:/DrakeAccounting2022/dll/DrakeAccountingEFilings.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by colejohnson66** [comment]
This is a bug in Drake Accounting, not dotnet. You need to contact them for assistance.

**Comment by antonfirsov** [comment]
Based on the callstack, this is not a .NET issue.
